### PR TITLE
Atlassian Jira v3 that supports mirroring

### PR DESCRIPTION
**Pull request by aburt-demisto**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
New integration for Atlassian Jira v3 that provides support for mirroring and also brings the code up to current specifications.

## Screenshots
N/A

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by reutshal** [comment]
Hi @aburt-demisto, Thanks for contributing this.
This is not exactly the way to add mirroring to integration, you can take a look at this documentation: https://github.com/demisto/content-docs/pull/211/files (it was not published yet).
Also, please share your availability for a demo with @roysagi and me. Thanks!

**Comment by reutshal** [comment]
Hi @aburt-demisto, Thanks for contributing this.
This is not exactly the way to add mirroring to integration, you can take a look at this documentation: https://github.com/demisto/content-docs/pull/211/files (it was not published yet).
Also, please share your availability for a demo with @roysagi and me. Thanks!

**Comment by aburt-demisto** [comment]
When will the official document be released?

Regards

Adam




Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by anara123** [comment]
@aburt-demisto it is almost ready. It should be merged this week. @ronykoz FYI

**Comment by aburt-demisto** [comment]
Could you let me know when it is and I can make the code changes please?


Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by ronykoz** [comment]
@aburt-demisto please note that you've created a new pack while you can just add the integration to an existing pack.
Shared the mirroring doc with you, let me know if you need help there.

**Comment by aburt-demisto** [comment]
Rony, please could you move it to the relevant pack. I will look at the
code again sometime this week.

Regards

Adam




Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by reutshal** [comment]
@aburt-demisto Actually, why do we need a new version for this integration?
Why not just add the mirroring to the current one? (the v2 integration)

**Comment by aburt-demisto** [comment]
Happy for it to be moved. Could you move it to the right location? I can
then make code adjustments as necessary.

Regards

Adam



Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by aburt-demisto** [comment]
> @aburt-demisto Actually, why do we need a new version for this integration?
> Why not just add the mirroring to the current one? (the v2 integration)

I think it is a breaking change. Mirroring is only support in server versions 6.0.0 upwards. The original integration is supported all the way back to version 4.5.

**Comment by aburt-demisto** [comment]
@ronykoz How are we looking with this?

**Comment by reutshal** [comment]
> > @aburt-demisto Actually, why do we need a new version for this integration?
> > Why not just add the mirroring to the current one? (the v2 integration)
> 
> I think it is a breaking change. Mirroring is only support in server versions 6.0.0 upwards. The original integration is supported all the way back to version 4.5.

@aburt-demisto Actually I don't think so, you only added the mirroring commands which will not be called in versions lower than 6.0.

It has been decided to wait with this PR until we know whether this issue is in the roadmap -  https://github.com/demisto/etc/issues/16193

**Comment by aburt-demisto** [comment]
@reutshal I have moved this PR into a change in the existing Jirav2. There is no need for a version 3

**Comment by reutshal** [comment]
Closing as this will be a part of the roadmap and will be taken care of next quarter.

**Comment by aburt-demisto** [comment]
Why has this been closed?

**Comment by reutshal** [comment]
@aburt-demisto As this is a part of our roadmap, one of the developers will take over the enhancement

**Pull request closed without merging**
