### PR TITLE
Microsoft-ATP documentation

### PR DESCRIPTION
**Pull request by barchen1**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/23864

## Description
Add README.md to Microsoft-ATP integration folder

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ronykoz** [comment]
@barchen1 keep the pack readme empty for now

**Comment by ronykoz** [comment]
@barchen1 Alex went over this, right? if not then let's have him review it

**Comment by barchen1** [comment]
@kirbles19 Could you please go over the readme file?

**Comment by ronykoz** [comment]
@kirbles19 could you check it out, i don't think that you have

**Comment by kirbles19** [comment]
@barchen1 Done.

**Pull request merged**
