### PR TITLE
Orca memory optimization

### PR DESCRIPTION
**Pull request by viktor-orca**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by edik24** [comment]
Hi @viktor-orca 
why the PR is in draft?
is it ready for review or there are still some actions that need to be done?

**Comment by viktor-orca** [comment]
> Hi @viktor-orca why the PR is in draft? is it ready for review or there are still some actions that need to be done?

Hi, there are some actions should be done, then i will make PR ready for review.

**Comment by edik24** [comment]
@dorschw the PR is no longer a draft and can be reviewed now

**Comment by dorschw** [comment]
(please ignore the bot)

**Review by dorschw — APPROVED** [review]

**Pull request merged**
