### PR TITLE
S/MIME Messaging Integration fix

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
Ready

## Description
Added a new command - sign and encrypt
Added a new param - recipient_key

## Does it break backward compatibility?
   - No

## Must have
- [ ] Documentation (with link to it)
- [ ] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by Itay4** [comment]
@kirbles19 please review:
https://github.com/demisto/content/blob/bbe127624380406c57ce75ab69c04c2c174fe8e9/Integrations/SMIME_Messaging/CHANGELOG.md
https://github.com/demisto/content/blob/bbe127624380406c57ce75ab69c04c2c174fe8e9/Integrations/SMIME_Messaging/SMIME_Messaging.yml

**Comment by kirbles19** [comment]
@Shellyber Done.

**Comment by Itay4** [comment]
@kirbles19 added additional changes, please review [changelog](https://github.com/demisto/content/blob/c5a6f5bbf71a46296e3fa4470c835da395b98d49/Integrations/MailSenderNew/CHANGELOG.md) and [yaml](https://github.com/demisto/content/blob/c5a6f5bbf71a46296e3fa4470c835da395b98d49/Integrations/MailSenderNew/MailSenderNew.yml)
Note that to the yaml, only `raw_message` argument was added

**Comment by kirbles19** [comment]
@Shellyber Done.

**Comment by Itay4** [comment]
> why did you removed the headers from context? please revert

@yaakovi done

**Pull request merged**
