### PR TITLE
Fixed DT syntax error

### PR DESCRIPTION
**Pull request by aburt-demisto**
## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/26310

## Description
DT Syntax modified in NetOps playbook that is causing failure of status ID captures.

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by liorblob** [comment]
@aburt-demisto Why make all of the operators `!=` rather than `!==`?

**Comment by aburt-demisto** [comment]
Because != works and is 1 character less. It also follows Python Syntax,
making it easier to remember.

Regards

Adam


Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by liorblob** [comment]
1. DT is in javascript
2. `!==` is more strict than `!=` and should work. See https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons
3. if it does not work and `!=` works please try to understand why.

**Comment by aburt-demisto** [comment]
You can keep it however you like. The issue is not the !== or !=. It is the
incorrect enclosure of the second parameters that makes my DT fail. The
last 3 calls to GenericPolling have the second parameter enclosed in a
bracket that I can't replicate on my keyboard. I suspect that is why it is
failing and have tested the DT copying and pasting with a manual DT command
and it fails. I then change the quotation marks to single ' and all is fine.

Dealers choice on the != vs !== however it would be nice if it was
consistent.

Regards

Adam




Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by liorblob** [comment]
Can you please change it to be `!==`. And add release notes as well.

**Comment by aburt-demisto** [comment]
I think I have done it correctly. Just pushed changes now..


Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by liorblob** [comment]
Thanks.
One last thing, can you run `demisto-sdk update-release-notes -p PAN-OS -u revision` to update the release notes for the pack? 
make sure to update the added file under the `ReleaseNotes` directory inside the pack.

**Comment by aburt-demisto** [comment]
:o(  .....

File "/usr/local/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/home/adam/.local/lib/python3.7/site-packages/click/core.py", line
764, in __call__
    return self.main(*args, **kwargs)
  File "/home/adam/.local/lib/python3.7/site-packages/click/core.py", line
717, in main
    rv = self.invoke(ctx)
  File "/home/adam/.local/lib/python3.7/site-packages/click/core.py", line
1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adam/.local/lib/python3.7/site-packages/click/core.py", line
956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adam/.local/lib/python3.7/site-packages/click/core.py", line
555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/demisto_sdk/__main__.py",
line 811, in update_pack_releasenotes
    update_pack_rn.execute_update()
  File
"/usr/local/lib/python3.7/dist-packages/demisto_sdk/commands/update_release_notes/update_rn.py",
line 62, in execute_update
    rn_string = self.build_rn_template(changed_files)
  File
"/usr/local/lib/python3.7/dist-packages/demisto_sdk/commands/update_release_notes/update_rn.py",
line 258, in build_rn_template
    for k, v in sorted(changed_items.items(), key=lambda x: x[1]):
TypeError: '<' not supported between instances of 'str' and 'NoneType'


demisto-sdk threw an error.


Adam Burt  |  Mgr, Solutions Architecture • EMEA

Mobile: +44(0) 7713 363155 | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

Email: adam@paloaltonetworks.com


<https://www.paloaltonetworks.com/cortex>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by liorblob** [comment]
I guess that's on us. I'll take care of it

**Pull request merged**
