### PR TITLE
Fixed description for ir-get-alarm command - LogRhythm

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/20409

## Description
Fixed description for ir-get-alarm command

## Does it break backward compatibility?
   - No

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file

### CODE REVIEW

**Comment by Shellyber** [comment]
@kirbles19 Please review the description change in ir-get-alarm command

**Comment by yardensade** [comment]
Just to be sure, either one of the arguments is required, not both in the same time, right?

**Comment by Shellyber** [comment]
@yardensade According to the issue, you can filter this command only by status and not by entity.
So fixed the description according to that

**Comment by kirbles19** [comment]
@Shellyber Done.

**Pull request merged**
