### PR TITLE
don't delete the incidents after test'

### PR DESCRIPTION
**Pull request by anara123**
## Status
Ready

## Description
We should keep the incidents even after test done.
For debugging purposes it is better to keep those incidents in Demisto
## Does it break backward compatibility?
No

## Must have
- [ ] Code Review

### CODE REVIEW

**Comment by anara123** [comment]
@ronykoz There should be. I think it just updating the status or something

**Comment by ronykoz** [comment]
@anara123 saw that you've failed on some PEP8 errors, i'll add the flake8 checks to the pre-commit in the support packages PR, and will try to look for auto formatting for simple problems like the one you had

**Comment by ronykoz** [comment]
Looks good to me, just not sure what are all the `Tag1` or `Tag2` incidents there

**Comment by ronykoz** [comment]
@anara123 do we want this?

**Comment by anara123** [comment]
yes

**Comment by yardensade** [comment]
What are we waiting for here?

**Comment by anara123** [comment]
it is not working properly. So I am closing for now

**Pull request closed without merging**
