### PR TITLE
Bug fix to QRadar Integration

### PR DESCRIPTION
**Pull request by prod-anas**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: QRadar fetch performance and logic issues

## Description
Fix logic and performance of fetching offenses from QRadar.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by prod-anas** [comment]
The registration form url is broken.

**Comment by prod-anas** [comment]
forgot to fix the confusing variables names.
I could change the variables and function names and related comments if it's ok.
The change will be either by changing the function logic to meet the function name or by changing the function name.

**Comment by prod-anas** [comment]
by the way, the failed validation tests are broken

**Review by tkatzir — APPROVED** [review]
Good! Need to be teste4d with a real instance.

**Comment by ostolero** [comment]
Hi @prod-anas  sorry for the delay with the review, and thank you for your patience! I'll get to this soon and update here after I test the code with qradar.

**Comment by ostolero** [comment]
Hi @prod-anas , the change itself makes sense, and the fetch worked for me in our instance. But I couldn't recreate the scenario where this is needed. Would be helpful to go over this together so I can understand the full scenario. contacted you through slack.

**Comment by prod-anas** [comment]
replied in slack

**Pull request merged**
