### PR TITLE
Added fields for Sentinel and JIRA integration. Check also request in description

### PR DESCRIPTION
**Pull request by tavogus55**
1. added "security" and "components" field for JIRA
2. added "owner" and "labels" fields for Sentinel
REQUEST: please add "environment" for JIRA

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
When updating jira and sentinel tickets/incidents using the commands, we noticed some fields were missing. With these changes (plus the one I requested), we should be able to add the changes we need when using the update command for both integrations.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by reutshal** [comment]
@tavogus55 Thanks for the contribution! Since this PR including arguments addition which will require further investigation and documentation, it should be taken care of as part of an enhancement for the integrations mentioned.  
I will open an issue for it with this PR as a reference.

**Comment by reutshal** [comment]
@tavogus55 Can you please provide your company's information?

**Comment by Kate-Pang** [comment]
Hi @reutshal , that will be Rakuten Inc

**Comment by sakiyanagi** [comment]
Hi, the customer wish to be solved this. could you

**Comment by sakiyanagi** [comment]
hi, this needed to be solved it. please take a look and if needed customer side action, please let me know.

**Comment by sakiyanagi** [comment]
the above X ci/circleci validations, 3X, please notice us what customer action needed it.

**Pull request closed without merging**
