### PR TITLE
Filter packs by minServerVersion upload flow

### PR DESCRIPTION
**Pull request by GuyAfik**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2626)

## Description
Added support for `minServerVersion` so that packs will be installed only on the server version in which they are supported.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by GuyAfik** [comment]
[successful pipeline](https://code.pan.run/xsoar/content/-/pipelines/3175553). 
See `install-packs-in-server_6.2 skipping` the minServerVersion which are `6.5.0`

**Review by daryakoval — APPROVED** [review]
Looks good

**Review by Noy-Maimon — APPROVED** [review]
Nice work

**Review by JudahSchwartz — APPROVED** [review]
nice

**Pull request merged**
