### PR TITLE
Jira improved auth support

### PR DESCRIPTION
**Pull request by orenzohar**
## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/18394

## Description
Jira improved auth support (updated docker image)

## Required version of Demisto
5.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [x] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by orenzohar** [comment]
@kirbles19 this is only a minor change, had to split the integration to two pakages because of the image update. please only check the [changelog](https://github.com/demisto/content/pull/4709/files#diff-17aa18a63448172755f3952632a4219f), and the [yml](https://github.com/demisto/content/pull/4709/files#diff-3c675a74a3281363e2e0f40c34bdd83c)

**Comment by orenzohar** [comment]
@yuvalbenshalom yes we do

**Comment by yaron-libman** [comment]
Reviewed the texts.

**Comment by ronykoz** [comment]
@orenzohar any reason we are not merging this?

**Comment by orenzohar** [comment]
@ronykoz yes, wanted to run few more tests before merging, will probably change it a bit.

**Comment by ronykoz** [comment]
Are you on this? Because it seem stale for the past 2 weeks

**Comment by orenzohar** [comment]
@ronykoz yes

**Comment by orenzohar** [comment]
@omercnet Just an FYI, the old OAuth didn't have any signature method (RSA-SHA1 here) and it seems like it never really worked. we're pretty sure this was the reason for it to fail, but there's a small chance that some client with an old version of Jira (on perm) will not need this, and it'll lead to breaking BC. still, a very small chance, but we wanted to make sure you know.

**Comment by orenzohar** [comment]
@anara123 we need your force-merge powers here

**Comment by ronykoz** [comment]
@orenzohar trigger a build with no BC checks please, no need to force merge

**Comment by yuvalbenshalom** [comment]
triggered no-BC build and it passed. but it dose not change the PR status. 
force merging.
https://circleci.com/gh/demisto/content/35062

**Pull request merged**
