### PR TITLE
[analyst-platform-591] illuminate Apply fix for malicious indicators without data

### PR DESCRIPTION
**Pull request by runt9**
- Ensure no return from API is "not malicious"
- Add benign to output table for clarity and informational purposes
- Add unit tests to cover 3 cases

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Email came in from Francesco Vega

## Description
Add a simple fix + unit tests when the illuminate API returns no entry for the "benign" value to ensure malicious is false under this case

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ x] Tests
- [ ] Documentation 

## Demisto Partner?
- [x ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by yaakovi** [comment]
fixes: https://github.com/demisto/etc/issues/22670

**Comment by runt9** [comment]
Sorry for just getting back to this to add a single line to the CHANGELOG.md, it's been a crazy week. Let me know if this update is sufficient or more details are needed in the changelog.

**Comment by anara123** [comment]
@kirbles19 please review

**Comment by kirbles19** [comment]
@yaakovi Done.

**Comment by yaakovi** [comment]
@anara123 after merging the PR to master, make sure to close the related issue: https://github.com/demisto/etc/issues/22670

**Pull request merged**
