### PR TITLE
SymantecEndpointProtection test playbook fix

### PR DESCRIPTION
**Pull request by roysagi**
## Status
Ready

## Description
Test playbook for SymantecEndpointProtection searched for 192.168.1.17 while it got 192.168.1.12 in the response - failing the playbook

### CODE REVIEW

**Comment by Itay4** [comment]
do we know what wrong with the mocks that this change is needed?

**Comment by roysagi** [comment]
> do we know what wrong with the mocks that this change is needed?

It seems the mock failed on the same error:
image

**Comment by Itay4** [comment]
we need to investigate this further to understand why the mock recorded this in the first place
this is exactly what the mocks are for

**Comment by roysagi** [comment]
Me and @yaakovi reviewed the several nightly runs back - we saw this happened about a week ago as well (same exact issue), while the mock was disabled then.

Because this has not happened since then until today and it did pass every time in between - we decided to wait till tomorrow to see if this issue returns before we change anything.

**Comment by roysagi** [comment]
It seems it worked today using the mock:
image

Thus this correction might not be necessary - we should monitor it or consider altering the playbook to match spheroidic failure reason.

**Comment by Itay4** [comment]
@yaakovi @roysagi lets discuss this

**Comment by roysagi** [comment]
Update: Circle started to rerun today (with no changes in the build) and the error has returned (both in mock and actual run).

**Comment by yaakovi** [comment]
closing for now, we will revisit this once the test fails again.

**Pull request closed without merging**
