### PR TITLE
SentinelOne bug fixes

### PR DESCRIPTION
**Pull request by noaco**
fixes: [etc/issue#10484](https://github.com/demisto/etc/issues/10484)
fixes: [etc/issue#10481](https://github.com/demisto/etc/issues/10481)

### CODE REVIEW

**Comment by anara123** [comment]
@noaco you missing releaseNotes. Are there are changes too or just this?

**Comment by noaco** [comment]
@anara123 just this

**Comment by anara123** [comment]
the build is red, merge from master and add release notes

**Comment by noaco** [comment]
@anara123 realeseNote is not missing, see end of file.

**Pull request merged**
