### PR TITLE
SafeNet Trusted Access - Updated guide link.

### PR DESCRIPTION
**Pull request by ujji8055**
## Description
The pack allows Cortex XSOAR to interact with SafeNet Trusted Access(STA) and applies security remediation actions on SafeNet Trusted Access alerts through Cortex XSOAR Security Orchestration Playbooks.

**Flow**
1. Cortex XSOAR listen to SafeNet Trusted Access Alert using Mail Listerner.
2. Cortex XSOAR creates an incident and invokes a playbook that executes the security remediation steps.
3. Playbook adds the user to a group for a configured amount of time on which STA policies with stronger authentication requirements are imposed.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: Updated Guide Link.

## Description
Updated configuration guide staging link to production link.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by ujji8055** [comment]
@kgal-pan
I have filled the contribution form. Please do the needful.

**Comment by abaumgarten** [comment]
@ujji8055 looks good, but you should sign on the license/cla before we merge it. 
https://cla-assistant.io/demisto/content?pullRequest=15026
Thanks.

**Review by abaumgarten — APPROVED** [review]
@ujji8055 looks good

**Comment by ujji8055** [comment]
@abaumgarten Thanks
I am unable to fill the license. The option is disabled for me. Please find the screenshot below. 
Please suggest the needful.

image

image

**Comment by abaumgarten** [comment]
@ShahafBenYakir @kgal-pan what should we do in such a case? when filling the cla is disabled.

**Comment by ShahafBenYakir** [comment]
https://xsoar.pan.dev/docs/concepts/faq#cla-is-pending-even-though-i-signed-the-agreement


On Mon, 27 Sep 2021 at 11:08 Aviya Baumgarten ***@***.***>
wrote:

> @ShahafBenYakir
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ShahafBenYakir&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=vgh0J2cb-74hOu0au-mZx-178cmjBaq0HDK1R8Drm38&e=>
> @kgal-pan
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kgal-2Dpan&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=88G_xinKsehmc8bOe5ycq_UtRfbnsX9KOuuBZnaJUrM&e=>
> what should we do in such a case? when filling the cla is disabled.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_15026-23issuecomment-2D927631123&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=QbRm3hF97iVD33vWnPdEFt6VYg5-RwnQAJjuwJXM7Mo&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKUY5SDPHAHJNMZJ4QLNY2DUEAQ7DANCNFSM5EWKH76Q&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=zHAS9p5MEJq63BUoGiCklZ-VnNC3j2obsCeZelLYvWQ&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=0ecPBhXh0uXRgFOTnOsOPZ3yBj9Ryzers_aXqoCPJ5c&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=31t0g9I_kswksJDPyZuMQC2jImFW_dOWBr7z1x9J7VE&m=pl2ypklaFJ5dXV810-YJ73dvJflNMlgzDouHkly_TRM&s=rHw4yqFy_uOaXroz-Ey2D7wwJ8Pcnf3Y-eLkQ8ZkDLI&e=>.
>
>
-- 


Shahaf Ben Yakir |  Partner Success Technical Manager

Cortex XSOAR, Palo Alto Networks ®

94a Yigal Alon St.  | Tel Aviv-Yafo 6789155 | Israel

E-Mail: ***@***.***

**Comment by abaumgarten** [comment]
will be handled in this PR: 
https://github.com/demisto/content/pull/15061

**Pull request closed without merging**
