### PR TITLE
[RiskIQ-127] RiskIQ Digital Footprint Merging premium to non premium pack 

### PR DESCRIPTION
**Pull request by crestdatasystems**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Merging premium pack content to non premium pack.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by crestdatasystems** [comment]
cc: @mchasepan @guykeller @anara123

**Comment by 9b** [comment]
Is there a merge timeline on this?

**Comment by roysagi** [comment]
@9b - Hi!
Sorry for the delay.

The script to move content from private to premium should be done today and we will expedite the merge here after that is done.

**Review by roysagi — APPROVED** [review]
Looks good - waiting for a green light from @adi88d

**Comment by ShahafBenYakir** [comment]
@roysagi @adi88d can we merge this?

**Pull request merged**
