### PR TITLE
[ASM] - Expander - Organizational scope searching for EC2

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-5778

## Description
The recommended way to search for an EC2 instance by public IP is called IPAM Public IP Insights (https://aws.amazon.com/about-aws/whats-new/2023/07/aws-public-ip-insights-vpc-ip-address-manager/) and it just got API to access data (commands added in https://github.com/demisto/content/pull/31165). This PR increases the abilities of the AWS - Enrichment playbook to use the AWS IPAM Public IP Insights API to search for an IP address on of an EC2 instance in the organization scope and to pull additional information on it.

This PR specifically adds the *AWSAssumeRoleName* optional input in the case of assuming roles for AWS.

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@ShirleyDenkberg , please review when possible

**Comment by johnnywilkes** [comment]
@capanw , if you have time, please review, blocked by https://github.com/demisto/content/pull/31849

**Comment by ShirleyDenkberg** [comment]
@melamedbn @yucohen Doc review completed.

**Comment by johnnywilkes** [comment]
@capanw / @BigEasyJ , please look over, still blocked by https://github.com/demisto/content/pull/31958

**Review by capanw — APPROVED** [review]
LGTM

**Review by BigEasyJ — APPROVED** [review]
Good job!

**Comment by yucohen** [comment]
@johnnywilkes @BigEasyJ On it :)

**Review by yucohen — APPROVED** [review]

**Pull request merged**
