### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rosenbet**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by edik24** [comment]
Hi @rosenbet,
since the adoption process is about to end, you should update additional information besides the readme.md that you updated.
https://xsoar.pan.dev/docs/partners/adopt#process
follow step 5 - since I think this is where you are.

you need to increment version, update the support in pack_metadata.json (change support from xsoar to partner, add support email and other fields in this file).

please do those changes in current PR.

let us know if there are any questions.

Edi

**Comment by rosenbet** [comment]
Thanks Edi.  I am unfortunately a novice with Github.  I have modified the
pack_metadata.json file and I will look into how to add the changes to the
existing PR.  If that is something you can quickly explain, I'd appreciate
it.

Todd

**Comment by edik24** [comment]
Hi @rosenbet  it looks like you pushed an update. 
Is there something else you want to add or can we review and approve it?

**Comment by merit-maita** [comment]
Hello @rosenbet 
i see that you updated the pack's current version in the pack_metadata, please add a release note file stating the change you made. One more thing, address the validation check that's failing over the author image please.
thanks!

**Review by merit-maita — CHANGES_REQUESTED** [review]
the previous comment.

**Comment by merit-maita** [comment]
@rosenbet any update?

**Comment by rosenbet** [comment]
I am waiting for my Marketing department to supply me with an
Author_image.png.  Thanks for checking in.

**Comment by rosenbet** [comment]
I believe I have added the Author_image to the correct PR.  I was asked to
add Release Notes. Should the new Release notes simply say "Pack has been
adopted by Attivo Networks"?

**Comment by merit-maita** [comment]
@rosenbet "Moved pack support to partner." should be good enough.
thanks!

**Comment by rosenbet** [comment]
Done!

**Review by merit-maita — APPROVED** [review]

**Pull request merged**
