### PR TITLE
Adding BERT features to DBotMLFetchData

### PR DESCRIPTION
**Pull request by lperryp**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by erezh31 — COMMENTED** [review]
Looks good,
let's test performance + time for 500 emails before approval

**Comment by lperryp** [comment]
> Looks good,
> let's test performance + time for 500 emails before approval

In my tests average time per incident increased from 0.1s to 0.8s.
If that's too much we can eliminate the BERT call for the email subject solely (and have just one call for subject + body)
also decreased the limit to 300 incidents

**Review by erezh31 — APPROVED** [review]

**Comment by yaron-libman** [comment]
@lperryp Can you please elaborate what is needed from the doc team here?

**Comment by lperryp** [comment]
> @lperryp Can you please elaborate what is needed from the doc team here?

Checking the release notes, let me know if it should be done differently

**Comment by ShirleyDenkberg** [comment]
@erezh31 Release Notes updated.  Doc review completed.

**Pull request merged**
