### PR TITLE
Aws api module

### PR DESCRIPTION
**Pull request by mrcoggsworth**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: N/A

## Description
My goal is to help open up the AWSApiModule to be able to use session tokens as part of the class build.
The reason for this is due to using third-party authenticators such as Hashicorp vault sends back the end-user the 
group of credentials in AWS. Adding the session token option directly to the helper class would ease additional repeated code inside each new integration submitted. This also allows for more control over client sessions for Cortex Xsoar servers not hosted on AWS infrastructure.

## Screenshots
N/A

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by mrcoggsworth** [comment]
The tests that failed are not linked to anything in my commit. I havn't modified the files in question that failed in circleci.

**Comment by ilaner** [comment]
> The tests that failed are not linked to anything in my commit. I havn't modified the files in question that failed in circleci.

The build fails because of missing release notes for the packs that using the AWS module.
Can you please run:
```
demisto-sdk update-release-notes -i Packs/ApiModules/Scripts/AWSApiModule -u revision
```

And can you please add a test for the added feature?

**Comment by mrcoggsworth** [comment]
> > The tests that failed are not linked to anything in my commit. I havn't modified the files in question that failed in circleci.
> 
> The build fails because of missing release notes for the packs that using the AWS module. Can you please run:
> 
> ```
> demisto-sdk update-release-notes -i Packs/ApiModules/Scripts/AWSApiModule -u revision
> ```
> 
> And can you please add a test for the added feature?

Absolutley, I can do these items. Thank you for the assistance.

**Review by mrcoggsworth — COMMENTED** [review]
Added trelease notes for each module that was affected, added tests for AWSApiModule.py on AWSApiModule_test.py

**Comment by mrcoggsworth** [comment]
Closing pull request due to inconsistency between branches causing tests to fail. Pulling updated code to fork then resubmit in new pull-request.

**Pull request closed without merging**
