### PR TITLE
Fix phishing ML predict label

### PR DESCRIPTION
**Pull request by erezh31**
fixes https://github.com/demisto/etc/issues/18349

### CODE REVIEW

**Comment by erezh31** [comment]
@glicht plz approve and merge, it's failing on "I get this message: Possible backwards compatibility break, You've changed the docker for the file Scripts/DBotPredictPhishingLabel/DBotPredictPhishingLabel.yml this is not allowed." which is not true

**Comment by glicht** [comment]
@yaakovi please check if we can fix the backwards compatibility verification

**Comment by glicht** [comment]
@yaakovi backwards compatibility check is still failing on the build. Can you take a look. See: https://circleci.com/gh/demisto/content/27576

**Comment by glicht** [comment]
@kirbles19 please review release notes: https://github.com/demisto/content/edit/fix_phishing_ml_test/Scripts/DBotPredictPhishingLabel/CHANGELOG.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F4043

**Comment by kirbles19** [comment]
@glicht is this for today's release?

**Comment by glicht** [comment]
Not for today

**Comment by kirbles19** [comment]
@glicht All done.

**Pull request merged**
