### PR TITLE
MATI - Supporting multiple inputs for generic enrichment commands

### PR DESCRIPTION
**Pull request by chrishultin**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Properly supports multiple inputs to generic reputation commands.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by MLainer1** [comment]
Hi @chrishultin, thank you for your contribution.
If you want to add a List capability for the reputation commands, make sure to create a CommandResults entry for each one and return a List of CommandResults, and not return all of the indicators in one entry.
A good example for the intended implementation can be found in the integration IPinfo v2.
Make sure to adjust the yml file as seen here: https://xsoar.pan.dev/docs/integrations/generic-commands-reputation

Feel free to contact me if you have any questions

**Comment by chrishultin** [comment]
> Hi @chrishultin, thank you for your contribution. If you want to add a List capability for the reputation commands, make sure to create a CommandResults entry for each one and return a List of CommandResults, and not return all of the indicators in one entry. A good example for the intended implementation can be found in the integration `IPinfo v2`. Make sure to adjust the yml file as seen here: https://xsoar.pan.dev/docs/integrations/generic-commands-reputation
> 
> Feel free to contact me if you have any questions

@MLainer1 When I originally proposed this fix in PR #30758, I was told by ilappe that I should create one CommandResults object and include all the indicators in `outputs`, and to use the DHS_Feed integration as an example.  Can you verify which approach is the correct one?

**Comment by MLainer1** [comment]
> > Hi @chrishultin, thank you for your contribution. If you want to add a List capability for the reputation commands, make sure to create a CommandResults entry for each one and return a List of CommandResults, and not return all of the indicators in one entry. A good example for the intended implementation can be found in the integration `IPinfo v2`. Make sure to adjust the yml file as seen here: https://xsoar.pan.dev/docs/integrations/generic-commands-reputation
> > Feel free to contact me if you have any questions
> 
> @MLainer1 When I originally proposed this fix in PR #30758, I was told by ilappe that I should create one CommandResults object and include all the indicators in `outputs`, and to use the DHS_Feed integration as an example. Can you verify which approach is the correct one?

Please implement the solution as I explained it, as @ilappe solution is suitable for Feed integrations, and not for Enrichers (as this integration).

**Comment by MLainer1** [comment]
@chrishultin Nice work! let's schedule a quick demo to see the changes

**Comment by chrishultin** [comment]
@MLainer1 It's ready to go :) Thanks for the help re: the context info

**Review by MLainer1 — APPROVED** [review]

**Pull request merged**
