### PR TITLE
deprecate pcapminer

### PR DESCRIPTION
**Pull request by jochman**
## Status
Ready

## Related Issues
https://github.com/demisto/etc/issues/17691
https://github.com/demisto/etc/issues/12845
https://github.com/demisto/etc/issues/14971

## Description
After a discussion with @JonathanMeler, we decided to deprecate the current script until a new one is built. The current one is barely usable.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
@glicht ok with you?

**Comment by glicht** [comment]
@yaakovi see this build: https://circleci.com/gh/demisto/content/27261?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link that ran all tests

**Comment by yaakovi** [comment]
@jochman add:
```
Tests: 
 - No test
```

**Comment by yaakovi** [comment]
@glicht 
should we force-merge this?
i don't think the docker image is an issue here if we are deprecating the script anyway.
as for the lint errors, that's an easier fix (however also not relevant).

**Comment by glicht** [comment]
@yaakovi see my comment here: https://github.com/demisto/etc/issues/17691#issuecomment-521449690 (we can continue the discussion on that thread)

**Comment by Itay4** [comment]
closing for now (based on the discussion in the issue)

**Pull request closed without merging**
