### PR TITLE
ExtraHop: Update alert rule command names

### PR DESCRIPTION
**Pull request by Dan-at-Extrahop**
@neela-j @reutshal following up on our email - Update alert rule command names to clarify that they are only for managing alert rules and not for fetching alert events. 

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/23140

## Description
Update alert rule command names to clarify that they are only for managing alert rules and not for fetching alert events.

## Screenshots
N/A

## Minimum version of Demisto
- [x] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details: Update alert rule command names to clarify that they are only for managing alert rules and not for fetching alert events. Causing customer confusion.
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by anara123** [comment]
@kirbles19 please review

**Comment by reutshal** [comment]
@Dan-at-Extrahop Thanks for your contribution!
@neela-j has also mentioned we have a customer requesting to add a command that returns all the detections from extraHop: https://github.com/demisto/etc/issues/23140. 
Do you think it will be possible to add this command as a part of this PR? Thanks!

**Comment by kirbles19** [comment]
@anara123 Done.

**Comment by Dan-at-Extrahop** [comment]
@anara123 - thanks, changes incorporated.
@reutshal - can you share the details of demisto/etc#23140 with me privately? I'm curious if they can use the current implemented approach to push incidents in via the REST API instead of a fetch: https://www.extrahop.com/customers/community/bundles/extrahop/demisto-integration/.

**Pull request merged**
