### PR TITLE
Implement the auto comment feature and update the fetch credential implementation

### PR DESCRIPTION
**Pull request by suhasini-b**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Suha1995** [comment]
@DeanArbel @merit-maita Though I have signed the Contributor License Agreement, still I can see check for "license/cla" is in pending state. Could you please help me with this.

cc - @edik24

**Comment by merit-maita** [comment]
@Suha1995 first of all thank you for you Contribution!
its weird that its now showing that you did, for the CLA its [this form](https://cla-assistant.io/demisto/content?pullRequest=26619), you might have filled the contribution registration form which is different.
please take a look if this's the same one you did fill it or not, if it is the same let me know.
sorry for the disconvenience

**Comment by Suha1995** [comment]
@merit-maita This the same one which I filled. Even if I clicked on CLA it shows me already filled form.

**Comment by edik24** [comment]
Hi @Suha1995, you are commenting with one user, but all commits were done with @githubsuha user. are you sure you're signing the CLA with the githubsuha user?

**Comment by Suha1995** [comment]
@edik24 I have signed the certificate with @Suha1995 with this user.

**Pull request closed without merging**
