### PR TITLE
upload flow - check_if_need_to_upload did not support only private packs

### PR DESCRIPTION
**Pull request by abaumgarten**
## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

fixes: https://github.com/demisto/etc/issues/33849

## Description
Fixed an issue where only private packs should be uploaded but check_if_need_to_upload checked only content packs.
Till this change, when upload flow included only private pack changes, the actual upload was skipped. 

trigger upload packs with private packs changes and no changes of content packs:

trigger upload packs with no private packs changes and no changes of content packs:
https://app.circleci.com/pipelines/github/demisto/content/68420/workflows/8a316b52-936b-4061-ad63-0683b0feb828

trigger upload packs with private packs changes and with changes of content packs:

### CODE REVIEW

**Review by guykeller — APPROVED** [review]
Looks good. Did you run upload flow with this branch?

**Review by guyfreund — CHANGES_REQUESTED** [review]
Looks good, please trigger an upload for each one of the following scenarios and attach the successful runs:
1. No public packs to upload and private packs that were changed - to make sure the index is being updated with the changed private packs
2. No private packs that were changed and public packs that need to be changed - not supposed to change, but better to trigger here too
3. No public packs to upload and no private packs that changed - to make sure that the upload is skipped

**Comment by abaumgarten** [comment]
> Looks good, please trigger an upload for each one of the following scenarios and attach the successful runs:
> 
> 1. No public packs to upload and private packs that were changed - to make sure the index is being updated with the changed private packs
> 2. No private packs that were changed and public packs that need to upload - not supposed to change, but better to trigger here too
> 3. No public packs to upload and no private packs that changed - to make sure that the upload is skipped

How can I ignore packs that are already recognized as packs that should be uploaded?

**Comment by guyfreund** [comment]
> > Looks good, please trigger an upload for each one of the following scenarios and attach the successful runs:
> > 
> > 1. No public packs to upload and private packs that were changed - to make sure the index is being updated with the changed private packs
> > 2. No private packs that were changed and public packs that need to upload - not supposed to change, but better to trigger here too
> > 3. No public packs to upload and no private packs that changed - to make sure that the upload is skipped
> 
> How can I ignore packs that are already recognized as packs that should be uploaded?

Create a new patch that ignores the detection of pack changes and returns False at all times, something like that

**Review by guyfreund — CHANGES_REQUESTED** [review]
As discussed, need also to add handling for the mentioned cases in `upload_packs.py`.

**Comment by abaumgarten** [comment]
Will open a new PR after re-designing as discussed.

**Pull request closed without merging**
