### PR TITLE
Joe security

### PR DESCRIPTION
**Pull request by yaakovi**
resolves https://github.com/demisto/etc/issues/10483
resolves https://github.com/demisto/etc/issues/10979
resolves https://github.com/demisto/etc/issues/11644
resolves https://github.com/demisto/etc/issues/12139

### CODE REVIEW

**Comment by anara123** [comment]
@JonathanMeler FYI

**Comment by anara123** [comment]
@yaakovi please merge from master, make sure the build is green so @Jonathan could work with it

**Comment by jonathan** [comment]
yeah, you aren't looking for me.

**Comment by anara123** [comment]
@jonathan  sorry 
@JonathanMeler FYI

**Comment by JonathanMeler** [comment]
@yaakovi @michalgold Joe security integration is not implementing full detonate use-case. it's not synchronic.

Cannot use it as is in playbooks

**Comment by JonathanMeler** [comment]
@yaakovi Is the result, please document all of the different formats for the report:
image

**Comment by anara123** [comment]
@yaakovi you have conflict

**Comment by anara123** [comment]
@JonathanMeler FYI detonate-file and detonate-url implemented

**Pull request merged**
