### PR TITLE
Extract domain from url format enhancement

### PR DESCRIPTION
**Pull request by yaakovi**
## Status
Ready

## Description
the script pulls the domain of the email, which may include mulitple 'subdomains'.
evaluating only the full email domain may result in inconclusive enrichments when also pulling the parent domain and enriching that domain will enhance results. This tends to be evident in spam campaigns, marketing or any other type of 'campaign' tracked email delivery.

the parentDomain add enrichment capability.

example:

email: alias@uniqueId.subdomain.domain.tld
uniqueId.subdomain.domain.tld may not provide valid enrichment
domain.tld may provide better.

## Related PRs
external PR: https://github.com/demisto/content/pull/2512

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [x] Code Review

## Additional changes
Describe additional changes done, for example adding a function to common server.

### CODE REVIEW

**Comment by yaakovi** [comment]
checked performance for the new version:
image



[ExtractDomainFromUrlAndEmail_PerformanceTest.yml.zip](https://github.com/demisto/content/files/2740800/ExtractDomainFromUrlAndEmail_PerformanceTest.yml.zip)

**Comment by Itay4** [comment]
@yaakovi did you also test performance impact in incident fetching and auto extract ?

**Comment by yaakovi** [comment]
@Itay4 no,
but since the diff is a millisecond for the entire command per execution we can see that the impact is insignificant to every operation running it.
assume we are not fetching thousands of incidents each time, this is less than a second delay.

**Comment by Itay4** [comment]
@yaakovi what's the status here?

**Comment by glicht** [comment]
There is another PR on this here: https://github.com/demisto/content/pull/3182

**Comment by yaakovi** [comment]
included as part of another PR: https://github.com/demisto/content/pull/3182

**Pull request closed without merging**
