### PR TITLE
add remote docker to nightly run

### PR DESCRIPTION
**Pull request by orhovy**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
added remote docker to sdk run. until now lint did not run on sdk nightly as it needs docker for all runs.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by orhovy** [comment]
failures arent caused by this pr.

**Review by yaakovi — APPROVED** [review]
trigger the workflow on this branch and attach a link to the build.

**Comment by orhovy** [comment]
https://app.circleci.com/pipelines/github/demisto/content/29945/workflows/dd08074d-a78a-4bdf-8a4c-2b7659f647b4

**Comment by yaakovi** [comment]
> https://app.circleci.com/pipelines/github/demisto/content/29945/workflows/dd08074d-a78a-4bdf-8a4c-2b7659f647b4
> 
> lint runs as needed
> @yaakovi FYI

looks good, you can merge

**Pull request merged**
