### PR TITLE
InstancesHealth - table and ratio - add scripts and widgets

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/15778

## Description
add the scripts and the widgets as specified in the issue

## Screenshots
instanceshealth2

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests - no
- [x] Documentation - we don't document scripts
- [ ] Code Review

### CODE REVIEW

**Comment by bakatzir** [comment]
my widgets sjon's are lacking the
```

  "params": {
    "currencySign": "%",
    "signAlignment": "right",
    "colors": {
      "isEnabled": true,
      "items": {
        "#00CD33": {
          "value": -1
        }
      },
      "type": "above"
    }
  }
}
```
could use some help with that

**Comment by yardensade** [comment]
What's the status here?

**Comment by bakatzir** [comment]
@sade see git issue

**Comment by bakatzir** [comment]
Closing the PR, issue will be handled in a different one.

**Pull request closed without merging**
