### PR TITLE
Cortex Data Lake Enhancements

### PR DESCRIPTION
**Pull request by darkushin**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/39740

## Description
- Support fetching from more log tables.
- Support custom queries for fetching.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by tschanfeld** [comment]
@darkushin For the readme and the yaml, do you want a full review of the files or only what was changed?

**Comment by darkushin** [comment]
Hi @tschanfeld please review only the new changes

**Review by DeanArbel — APPROVED** [review]
Good job.

**Comment by tschanfeld** [comment]
@darkushin Reviewed only the changes, done.

**Pull request merged**
