### PR TITLE
RemedyOnDemand fix

### PR DESCRIPTION
**Pull request by hod-alpert**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/23489

## Description
Fixing wrong endpoints

### CODE REVIEW

**Comment by hod-alpert** [comment]
@Itay4 This seems to be working for other customers as well
I think this can be merged

**Comment by Itay4** [comment]
@roysagi please review rn

**Comment by Itay4** [comment]
@kirbles19 please review yml and release notes

**Comment by kirbles19** [comment]
@hod-alpert Done.

**Pull request merged**
