### PR TITLE
[ASM] - ASM ServiceNow ITSM Enrichment & Service ID Fix

### PR DESCRIPTION
**Pull request by BigEasyJ**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Updated the playbook to make the input `search_terms` optional.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by capanw — APPROVED** [review]
LGTM

**Review by johnnywilkes — APPROVED** [review]
I approve of changes @BigEasyJ made

**Comment by ilappe** [comment]
@johnnywilkes 
is this are ready for review by XSOAR team?

**Comment by melamedbn** [comment]
> @johnnywilkes is this are ready for review by XSOAR team?

@ilappe 
Xpanse team do their own review for content within the Xpanse content pack

**Comment by johnnywilkes** [comment]
@ilappe , This has been approved from the Xpanse side.  
please merge as soon as possible.

**Review by ilappe — APPROVED** [review]

**Pull request merged**
