### PR TITLE
Add support for providerIncidentUrl field

### PR DESCRIPTION
**Pull request by Clemv95**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Adding support for the "providerIncidentUrl" field 
This field can be very useful when using Sentinel as a SIEM and when you want to grab the original incident URL
For exemple when you have a sentinel incident leading to a Microsoft Defender incident, getting this URL is practical

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by MLainer1** [comment]
Hi @Clemv95, thank you for your contribution.
Make sure to add a release note, and increase the pack version accordingly.

**Comment by Clemv95** [comment]
> Hi @Clemv95, thank you for your contribution. Make sure to add a release note, and increase the pack version accordingly.

Done !

**Comment by MLainer1** [comment]
@Clemv95 Hi, can you provide a short video showing your addition for the pack works as expected?
Afterwards we will continue with the merge of the PR.
Make sure to fix the pre-commit errors as well.

**Review by MLainer1 — COMMENTED** [review]
Great! make sure to fix the pre-commit errors.

**Comment by Clemv95** [comment]
> @Clemv95 Hi, can you provide a short video showing your addition for the pack works as expected? Afterwards we will continue with the merge of the PR. Make sure to fix the pre-commit errors as well.

I will fix pre-commit errors
How could i test in real conditions and make you a vidéo ?

**Comment by MLainer1** [comment]
@Clemv95 If you prefer, we can do a quick zoom call

**Comment by Clemv95** [comment]
> @Clemv95 If you prefer, we can do a quick zoom call

A video is ok, my question is about the content of it
You want to see a unit test ?

**Comment by MLainer1** [comment]
@Clemv95 I want to see the mirrored field you added (providerIncidentUrl) contain the intended data from Azure Sentinel:
You can create an incident in Azure Sentinel to mirror in to XSOAR that has the data

**Comment by Clemv95** [comment]
> @Clemv95 I want to see the mirrored field you added (providerIncidentUrl) contain the intended data from Azure Sentinel: You can create an incident in Azure Sentinel to mirror in to XSOAR that has the data

How can i test my addition in XSOAR ?
Is there a guide or something ?

**Comment by MLainer1** [comment]
@Clemv95 Have a look in this guide https://xsoar.pan.dev/docs/contributing/demo-prep

**Comment by Clemv95** [comment]
> @Clemv95 Have a look in this guide https://xsoar.pan.dev/docs/contributing/demo-prep

OKay thanks, can i send you in private the video ?

**Comment by ShirleyDenkberg** [comment]
@MLainer1 Doc review completed.

**Comment by Clemv95** [comment]
I see that there was another PR that impact my changes
I will update my branch and merge my changes with the new ones, i keep the .52 release ? Or making a .53 ?

**Comment by MLainer1** [comment]
> I see that there was another PR that impact my changes I will update my branch and merge my changes with the new ones, i keep the .52 release ? Or making a .53 ?

need to upgrade your version to 53

**Comment by Clemv95** [comment]
> > I see that there was another PR that impact my changes I will update my branch and merge my changes with the new ones, i keep the .52 release ? Or making a .53 ?
> 
> need to upgrade your version to 53

I think the merge with the contrib branch is bad, i will try to report the changes manually

**Comment by Clemv95** [comment]
Okay everything's good

**Comment by Clemv95** [comment]
@ShirleyDenkberg Is it normal that my PR hasn't been merged on the main branch ? 
I can see that MLainer1 account has dissappear, and the internal PR too https://github.com/demisto/content/pull/37433/files/aa1b465ae2491992fd5a0af5a3362fcead9c7748..097676bbe46c18e68103ac56599f256c6b452c45

**Comment by RotemAmit** [comment]
Hi @Clemv95,
The internal PR should be merged up to 3 days after the merge of the external PR, as written [here](https://github.com/demisto/content/pull/37288#issuecomment-2500078480).
Currently we have an open issue in the content repo that we are working to solve. We will reopen the internal PR after the issue is fixed.

**Comment by RotemAmit** [comment]
Hi @Clemv95,
I opened a new internal PR with your changes, you can see it [here](https://github.com/demisto/content/pull/37460).

**Pull request merged**
