### PR TITLE
integration-EWSv2 fix for query string efficiency;

### PR DESCRIPTION
**Pull request by aaronjonen**
## Status
Ready/In Progress/In Hold(Reason for hold)

## Related Issues
fixes: link to the issue

## Description
WSv2 fix for query string efficiency; some mailboxes were not retrieving items as well.

## Does it break backward compatibility?

   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Additional changes
Describe additional changes done, for example adding a function to common server.

### CODE REVIEW

**Comment by glicht** [comment]
Thanks for submitting this pr. I've rebased so we can review now. We will review and get back to you.

**Comment by aaronjonen** [comment]
The not found text should probably be an argument instead of a static list.

Aaron Jonen
IT Web Developer, working on behalf of NextEra Energy Inc.
414 840 0102

**Comment by BenJoParadise** [comment]
> The not found text should probably be an argument instead of a static list.

I didn't quite understand to which part of the code you are referring to.

**Comment by BenJoParadise** [comment]
duplicate of https://github.com/demisto/content/pull/2600
tracking through https://github.com/demisto/content/pull/2641

**Pull request closed without merging**
