### PR TITLE
Bitglass

### PR DESCRIPTION
**Pull request by asingh-bitglass**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by marcellarichmond** [comment]
@asingh-bitglass Can you share what the best email address to reach you at is?

**Comment by asingh-bitglass** [comment]
***@***.*** ***@***.***>* as mentioned, thanks

**Comment by kgal-pan** [comment]
Hey @asingh-bitglass! Great job overall!

Please see the comments below:

- Remove the file `Packs/Bitglass/Integrations/Bitglass/version.txt` as it should not be part of the Pack contents. See [Content Pack Structure](https://xsoar.pan.dev/docs/packs/packs-format) for the expected contents.
- Add `Packs/Bitglass/README.md`. See https://xsoar.pan.dev/docs/documentation/pack-docs for more information.
- Add content to `Packs/Bitglass/Integrations/Bitglass/Bitglass_description.md`. See https://xsoar.pan.dev/docs/documentation/integration-description for more information.
- Since this Pack is new, no need for release notes. Please remove `Packs/Bitglass/ReleaseNotes` folder.
- Add Bitglass support email to `.email` path in `pack_metadata.json`. I believe it's support@bitglass.com according to https://www.bitglass.com/support.
- Please remove the folder `Packs/Bitglass/TestPlaybooks/` and revert changes to `Tests/conf.json`. This is not needed in our case and is causing a merge confilict.
- Secrets were found in the Pack contents. Please remove them or add them to `.secrets-ignore`. See the list of secrets in the [build failure log](https://app.circleci.com/pipelines/github/demisto/content/135873/workflows/2c7f1e3f-6f1c-4ee5-8203-f006fbade270/jobs/464743?invite=true#step-105-9).
- Remove comment from `.pack-ignore` and leave the file empty.
- Change `.version` in `pack_metadata.json` to `1.0.0` as this is the first version of this Pack.
- Looks like the unit tests are using https://portal.us.bitglass.net/api/bitglassapi/logs/ as the base URL for the client. You should change these to a mock address, e.g. `mock://...`. In addition, seems like the [unit tests coverage is quite low (44%)](https://app.circleci.com/pipelines/github/demisto/content/135873/workflows/2c7f1e3f-6f1c-4ee5-8203-f006fbade270/jobs/464742?invite=true#step-108-21. Check out https://devguide.python.org/coverage/ how to increase and check your coverage.
- Instead of using `OAuth 2 Authentication Token` parameter for the integration configuration (in `Packs/Bitglass/Integrations/Bitglass/Bitglass.yml`), you should try to use the [XSOAR vault credentials](https://xsoar.pan.dev/docs/integrations/code-conventions#credentials).
- There are many additional classes inside of `Packs/Bitglass/Integrations/Bitglass/Bitglass.py` which are out of the scope of the integration code and have some implementations that are unnecessary. For example, `Logger`, `App`, `Secret`, etc. There should only be one class which inherits from `BaseClient` (which you already have), helper functions and command functions (such as `create_update_group_command`). Please see review [Python Code Conventions](https://xsoar.pan.dev/docs/integrations/code-conventions).


Please let me know if you have any questions and/or if you want to have a short call to review this together.

**Comment by kgal-pan** [comment]
@asingh-bitglass - [Build failure here](https://app.circleci.com/pipelines/github/demisto/content/137778/workflows/7045adc3-160a-4117-960e-a271aa78a4e7/jobs/468341?invite=true#step-109-110) caused by the fact that we have a [unified YAML](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/unify/README.md#unify). 

Run the following command to unified YAML into the integration YAML and the Python code:

```bash
demisto-sdk split -i Packs/Bitglass/Integrations/Bitglass/Bitglass.yml -o /tmp/
```

Running this will result in two separate files: `/tmp/Bitglass.yml` and `/tmp/Bitglass.py`. Replace `/tmp/Bitglass.yml` with the unified YAML (`Packs/Bitglass/Integrations/Bitglass/Bitglass.yml`).

**Comment by asingh-bitglass** [comment]
Hi Kobbi,

Replace* /tmp/Bitglass.yml* with the unified YAML (
*Packs/Bitglass/Integrations/Bitglass/Bitglass.yml*).
You probably meant the other way around like 'cp /tmp/tmp.yml
Packs/Bitglass/Integrations/Bitglass/Bitglass.yml'?

I think this error started happening after the validate command asked me to
update Docker image from 3.9.9.25564 to 3.10.1.25933 in the yml file.

That was probably triggered by the git pull command I did earlier.

Now, whether using *either* the old yml with the Docker image version
updated *or* the one generated by the split command, there are the same
errors output by the lint command (I think some older/wrong version is
being used as *the code hasn't changed* and it complains about Python
version 3.1 (the correct one is *3.10*)):

mypy: error: argument --python-version: Python 3.1 is not supported (must
be 3.4 or higher)
and
/devwork/Bitglass.py:1577:19: E1136 SyslogUDPHandler.handle: Value
'self.kwargs' is unsubscriptable

The split command itself outputs an error as well (although the files in
/tmp do get generated):

An unexpected error has occurred while trying to install the requirements
in pipenv.
Please try installing manually after extract ends.

Thanks,
Alexei

**Comment by kgal-pan** [comment]
@asingh-bitglass -  This error is actually a bug we have internally. I'll update when it'll be fixed (we're seeing this in all PRs right now)

```
> mypy: error: argument --python-version: Python 3.1 is not supported (must be 3.4 or higher) and /devwork/Bitglass.py:1577:19: E1136 SyslogUDPHandler.handle: Value 'self.kwargs' is unsubscriptable
```

Regarding this:

> Replace* `/tmp/Bitglass.yml` with the unified YAML (
`Packs/Bitglass/Integrations/Bitglass/Bitglass.yml`).
You probably meant the other way around like `cp /tmp/tmp.yml
Packs/Bitglass/Integrations/Bitglass/Bitglass.yml`?

Correct.

**Comment by kgal-pan** [comment]
@asingh-bitglass - As discussed on our call:

- We'll generate a new Docker image using documentation in our [`dockerfiles` repo](https://github.com/demisto/dockerfiles#demistos-dockerfiles-and-image-build-management) to include all custom code and remove them from `Bitglass.py`. This will ensure that the UT coverage increases and passes validation.
- Once the Docker image is ready, we'll update the `.script.dockerimage` key in `Bitglass.yml` with the name of the new Docker image.

As discussed, we will keep this PR open until the Docker image is ready.

FYI - @merit-maita

**Comment by kgal-pan** [comment]
> @asingh-bitglass - As discussed on our call:
> 
> * We'll generate a new Docker image using documentation in our [`dockerfiles` repo](https://github.com/demisto/dockerfiles#demistos-dockerfiles-and-image-build-management) to include all custom code and remove them from `Bitglass.py`. This will ensure that the UT coverage increases and passes validation.
> * Once the Docker image is ready, we'll update the `.script.dockerimage` key in `Bitglass.yml` with the name of the new Docker image.


I am closing this PR for now until we've finished generating the Docker image. Feel free to reopen after the integration code was migrated to the Docker image and when the image is ready.

**Pull request closed without merging**
