### PR TITLE
Introducing metrics api header

### PR DESCRIPTION
**Pull request by LHousehold**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Introducing a new header to help measure usage

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by kgal-pan** [comment]
@LHousehold - Please run the following to bump the version to fix [validation error](https://app.circleci.com/pipelines/github/demisto/content/152344/workflows/cf8a86f1-af91-4f81-b238-b5cdb5e92181/jobs/496566?invite=true#step-108-105):

```bash
demisto-sdk update-release-notes -i Packs/SecurityScorecard -u revision
```

See https://xsoar.pan.dev/docs/documentation/release-notes#format.

**Comment by yucohen** [comment]
@LHousehold 
Please also sign the [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18259) and fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**Comment by LHousehold** [comment]
I did fill in both of these. The agreement may have been signed under my github email, Luke.household@gmail.com

**Comment by yucohen** [comment]
> I had made a mistake for the contribution form, so I've resubmitted it correctly. I'm trying to re-sign the CLA but no content loads under "version". I can check off the "I accept" checkbox but there is no submit button.

it takes some time to load.. can you try again now?

**Comment by LHousehold** [comment]
Hello, thanks for the tip. It's definitely signed now.

**Review by yucohen — APPROVED** [review]

**Pull request merged**
