### PR TITLE
[Fix] Human readable ^^^ in tableToMarkdown

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19114

## Description
Upon executing certain commands ^^^ string is added to some parts of the output (can be seen next to indicators that are auto extrracted such as email).
This happens because autoextract doesn't (and shouldn't) ignore `|` characters, so the entire string is extracted - across several cells.

Adding spaces before and after a cell entry in `tableToMarkdown` solves this issue.

## Does it break backward compatibility?
No - Markdown is used primarily to generate HTML, and HTML collapses white spaces by default. as such white spaces in MD table are not taken into account when creating the UI table display, so this change should not affect existing integrations.

For examples see: 
- https://github.github.com/gfm/#tables-extension-
- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

## Must have
- [x] Tests
- [ ] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
@DeanArbel can you post screenshots of tables from 4.1, 4.5 and 5.0 ?

**Comment by DeanArbel** [comment]
## 4.1 - Doesn't reproduce
### Before + After
image

## 4.5 self service build failed, rebuilding now

## 5.0
### Before:
image

### After:
image

**Comment by DeanArbel** [comment]
> @DeanArbel can you post screenshots of tables from 4.1, 4.5 and 5.0 ?
@Itay4 see comment above

**Comment by DeanArbel** [comment]
@kirbles19 please review Scripts/CommonServerPython/CHANGELOG.md

**Comment by kirbles19** [comment]
@DeanArbel Done.

**Comment by DeanArbel** [comment]
> Following unit tests are failing:
> 
> Integrations/GoogleCloudStorage
> Scripts/HTMLDocsAutomation
> Scripts/ParseCSV
> 
> Following playbook tests are failing:
> TestCommonPython
> FormattingPerformance - Test
> 
> Please review and fix

- **Integrations/GoogleCloudStorage** - Fixed test
- Scripts/HTMLDocsAutomation - Doesn't reproduce locally, but shouldn't fail either way - the changes are unrelated.
- **Scripts/ParseCSV** - Fixed test
- **TestCommonPython** - Fixed related script
- **FormattingPerformance - Test** - Doesn't reproduce locally, but shouldn't fail either way as tblToMd isn't called in any form.

**Comment by DeanArbel** [comment]
CircleCi is a bit problematic, as the system shut down in `One Before GA` prior to finishing tests on all versions, however this change is the same for all versions, and shouldn't affect other versions differently.

I have reran the build, but in case we won't get a better result, here are the failed tests for latest GA.

image

@glicht @anara123 None of the the failing tests are failing due to the changes introduced to `tableToMarkdown`. Please see the full details below.

- SNDBOX - Quota reached (SNDBOX integration: Your request failed with the following error: Too Many Requests.
You have reached your plans daily quota of sample downloads)
- Shodan - Failed on integration was not found (seems it's true there's no playbook like that - maybe it was deleted?)
- wisdom-domain-flags - Fails due to a context path not existing, generated in a command that doesn't use tableToMarkdown
- PAN OS - Configuration Test - Failed due to error in file permissions: `Error [rename /var/lib/demisto/temp/script236764890/c8092abd8d581750c0530fa1fc8d8318.rl /var/lib/demisto/temp/script159290846/c8092abd8d581750c0530fa1fc8d8318.rl: permission denied]`
- Palo Alto Networks Cortex Test - Failed because it was unable to create an instance (failed on `Test`).
- FormattingPerformance  - Doesn't reproduce locally, but shouldn't fail either way as tblToMd isn't called in any form.

**Comment by yuvalbenshalom** [comment]
@anara123 @glicht, please see dean’s last post and consider force merge. I think that it is ready an I want to add it to the release bench too.

**Pull request merged**
