### PR TITLE
New LDAP integration that uses the Python ldap3 library

### PR DESCRIPTION
**Pull request by aburt-demisto**
## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
NA

## Description
New LDAP integration that uses the Python ldap3 library.

## Screenshots
NA

## Minimum version of Demisto
- [x] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
NA

### CODE REVIEW

**Comment by ronykoz** [comment]
@aburt-demisto thanks for the contribution, adding @IkaDemisto as a reviewer as he wrote the beta openLdap integration so he is more familiar with the library.

**Comment by ronykoz** [comment]
FYI we might push little fixes directly to your branch to avoid unnecessary work from your side.

**Comment by aburt-demisto** [comment]
No worries at all.

I will check out the failures too.

Regards

Adam

On Mon, Feb 10, 2020 at 2:02 PM Rony Kozakish <notifications@github.com>
wrote:

> FYI we might push little fixes directly to your branch to avoid
> unnecessary work from your side.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_5696-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAMYYDQMNG7IN6KS2MVALYQLRCFM4VA5CNFSM4KSNSZD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELITNYI-23issuecomment-2D584136417&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=SfBamao7x1OJ-Jmqv1HgHELJJWxQc4P2RW91K_ljPZE&m=vtrrAvZwZ0YJyj9txqOEaz2y-Q2tlCYmDkmTakYJw9w&s=jtaJpOw6s8cBxngAeYlwF82zf1LUjtK_rsAIaT-Wr6U&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMYYDQP5OF4PDTXDZDBILITRCFM4VANCNFSM4KSNSZDQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=SfBamao7x1OJ-Jmqv1HgHELJJWxQc4P2RW91K_ljPZE&m=vtrrAvZwZ0YJyj9txqOEaz2y-Q2tlCYmDkmTakYJw9w&s=vk85VbV6lAS2z2VPcdhIcTdQ-i2sMrKr3lIqvh1uqz0&e=>
> .
>


-- 
Adam Burt | Solutions Architect, EMEA
Mobile: +44(0) 7713 363155
Email: adam@paloaltonetworks.com <amir@paloaltonetworks.com>

**Comment by glicht** [comment]
See discussion at: https://github.com/demisto/etc/issues/21631

**Comment by aburt-demisto** [comment]
Last I heard was that this would be rolled into the Active Directory
integration.

Speak with Guy..

Regards

Adam

**Comment by ronykoz** [comment]
@aburt-demisto you can ignore messages from content-bot in the meantime, we are waiting to have people to assign for this migration into the active directory integration

**Comment by aburt-demisto** [comment]
Ok, thank you.

Regards

Adam

**Comment by yaakovi** [comment]
@ronykoz move this to a new PR

**Pull request closed without merging**
