### PR TITLE
fix return_error use of demisto.results when fetching

### PR DESCRIPTION
**Pull request by orenzohar**
## Status
Ready

## Before
image

## After
image

## Description
fixes return_error use of demisto.results when fetching, as it causes weird errors messages.

*new* added exception handling and traceback printing

### CODE REVIEW

**Comment by orenzohar** [comment]
@anar return_error uses sys.exit

**Comment by Itay4** [comment]
@orenzohar what is the status here?

**Comment by anara123** [comment]
@ronykoz can we close this PR, because your PR should include these changes?

**Comment by ronykoz** [comment]
@anara123 i will close it once the code is migrated to the second PR, not done yet

**Comment by yardensade** [comment]
Does the second PR exist atm?

**Comment by ronykoz** [comment]
@yardensade forgot about that, relates to https://github.com/demisto/content/pull/3298

**Comment by orenzohar** [comment]
@ronykoz I don't think you updated `return_error` in https://github.com/demisto/content/pull/3298

**Comment by ronykoz** [comment]
@orenzohar you are right, please update this PR to fix it.

**Comment by ronykoz** [comment]
Updated it to be in the CommonServerPython package

**Pull request closed without merging**
