### PR TITLE
Fix ASI branding to Attack Surface Intelligence

### PR DESCRIPTION
**Pull request by northcott-j**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
After publishing and seeing how copy was shown in the marketplace, we received some feedback to update the use of ASI to Attack Surface Intelligence.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by YuvHayun** [comment]
Hey @northcott-j 
Seems like there're some problems running the instance tests..
Can you please try to pull from master and push to the pr?

**Comment by YuvHayun** [comment]
Hey @northcott-j, can you please give me permission to edit this branch?
[here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) is a quick guide how to do that.

**Comment by YuvHayun** [comment]
> Hey @northcott-j, can you please give me permission to edit this branch? [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) is a quick guide how to do that.


@northcott-j this is still relevant, please let me know if you have trouble updating it.

**Comment by northcott-j** [comment]
@YuvHayun - working on getting permission in our org to add collaborators. 

What instance tests are failing? 

The branch should be pretty up-to-date with master. What other commits should I merge in?

**Comment by YuvHayun** [comment]
> @YuvHayun - working on getting permission in our org to add collaborators.
> 
> What instance tests are failing?
> 
> The branch should be pretty up-to-date with master. What other commits should I merge in?

It seems like some random problematic commit was merged in and therefore the instance tests are failing..
I just tried to retrigger it after you pulled from master again.

**Comment by YuvHayun** [comment]
should be fixed by now, try to re-pull for master, please.
Sorry for the inconvenience!

**Comment by northcott-j** [comment]
Sorry for all the sync issues. Tried to use Github UI for to sync branches and it did some things I didn't expect. Should be up-to-date now

**Comment by YuvHayun** [comment]
@northcott-j for some reason it keeps failing.
I want to merge the external pr and try to run the instance tests on the internal pr.
Can you please fill in the CLA?

**Comment by northcott-j** [comment]
Done

**Review by YuvHayun — APPROVED** [review]
@northcott-j thx, merging in.

**Pull request merged**
