### PR TITLE
fix reputation cmds issue

### PR DESCRIPTION
**Pull request by chloerongier**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
The reputation commands **ip**, **url**, **domain**, **file** and **email** are currently not able to handle an array as arguments which is an issue.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by rshunim** [comment]
Hi @chloerongier
Thanks a lot for your contribution, starting review this pr
I pushed a small fix for the UT according to the code changes

**Comment by kgal-pan** [comment]
@chloerongier - Thanks for the contribution! Since this is a Partner-supported Pack, we require that the Partner review the changes and approves them. We're contacting them now for approval.

**Comment by kgal-pan** [comment]
@sangeetha-sacumen @raghavendra-sacumen @himynamesdave  - Can you please review the changes here and let us know if you approve of them? Thanks!

**Comment by rshunim** [comment]
@sangeetha-sacumen @raghavendra-sacumen @himynamesdave
Any updates?

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
