### PR TITLE
urlscan_malicious_Test failure

### PR DESCRIPTION
**Pull request by ChanochShayner**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/20111

## Description
Change the condition of the URL test, since it is no longer malicious.
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ChanochShayner** [comment]
@ronykoz 
After I got a list of URLs that are supposed to be malicious - I checked a lot of them (about thirty) and in the urlscan system, they are not considered suspicious.
So, is the change I made okay?

**Review by ronykoz — APPROVED** [review]

**Review by ronykoz — CHANGES_REQUESTED** [review]
Just so your comment, lets find a suspicious one please.

**Comment by ChanochShayner** [comment]
@orlichter1 removed from TPB the failed mission, because "one of the two sites it checked to be malicious was removed so when you ran urlscan on it, it returned blank. As we were looking at 2 sites for maliciousness I just removed one"
@ronykoz FYI

**Comment by guykeller** [comment]
@ChanochShayner Did not understand your last comment

**Comment by orlichter1** [comment]
@guykeller The test playbook failed because it searched for a specific malicious site on urlscan.io but the site has been removed (from the internet) so urlscan returned a blank report which isn't malicious. As the test playbook looks at 2 malicious sites I just removed that one from the playbook.

**Review by ronykoz — APPROVED** [review]

**Pull request merged**
