### PR TITLE
Sample Incident Generator (Deprecated) - deprecate

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
- [x] Ready

## Related Issues
fixes: https://panw-global.slack.com/archives/C011E5T5K17/p1615462034207600

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Comment by Itay4** [comment]
dont think this should be deprecated, lets discuss

**Comment by ShahafBenYakir** [comment]
What was decided here?

**Comment by bakatzir** [comment]
> What was decided here?

I think we can deprecate, see:
https://github.com/demisto/etc/issues/34673#issuecomment-796857457

**Comment by bakatzir** [comment]
Decide not to deprecate for now, per the issue. closing.

**Pull request closed without merging**
