### PR TITLE
Calculate Severity - Standard

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19004

## Description
- Added the playbook `Calculate Severity - Standard`
- Added the playbook `Calculate Severity By Highest DBotScore`
- Added the test playbook `Calculate Severity - Standard - Test`

## Screenshots
image

image

image

## Related PRs
@mayagoldb pls post ur PR here

## Required version of Demisto
4.5.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation
- [ ] Code Review

### CODE REVIEW

**Comment by idovandijk** [comment]
@kirbles19 when you review, please feel free to suggest different names for the playbooks as well

**Comment by idovandijk** [comment]
@michalgold build now fails due to a problem with Minemeld (the test is using Minemeld)
@yardensade I know you contacted someone about it. When can we expect it to be fixed?

**Comment by yardensade** [comment]
I'm not the relevant person to give answer about that, reported it to lab yesterday.

**Comment by kirbles19** [comment]
@idovandijk Done.

**Pull request merged**
