### PR TITLE
Threat connect - bug

### PR DESCRIPTION
**Pull request by moishce**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/25808

## Description
 Fixed syntax error in **tc_indicators** command that not filtering based on the "owner" value.

### CODE REVIEW

**Comment by kirbles19** [comment]
@moishce Done.

**Comment by ShahafBenYakir** [comment]
@moishce test?

**Comment by moishce** [comment]
@ShahafBenYakir It looks like the license expired

**Comment by ShahafBenYakir** [comment]
@moishce I meant unit test.

**Comment by Itay4** [comment]
@moishce @ShahafBenYakir can we merge this ?

**Pull request merged**
