### PR TITLE
Add markdown images support in sanePdfReport

### PR DESCRIPTION
**Pull request by davidbinyamin**
## Status
- [x] Ready

## Related Issues
Related: https://github.com/demisto/etc/issues/40210

## Related PRs
branch | PR
------ | ------
Sane-reports PR | https://github.com/demisto/sane-reports/pull/183
Server MR |  https://code.pan.run/xsoar/server/-/merge_requests/16194

## Description
Full solution is described in the related issue.
in `SanePdfReport.py`, i added the ability to listen to markdown images requests (from `reportServer`) and fetch the requested image from demisto.

## Minimum version of Cortex XSOAR
Relevant server changes will be present only in 6.5 but this change is BC

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Comment by davidbinyamin** [comment]
@aviadl @dorsha FYI last piece of the puzzle

**Review by glicht — CHANGES_REQUESTED** [review]
We should add logic to disable the image server if running on Server version below 6.5.

**Comment by aviadl** [comment]
@glicht why not have 2 scripts with from -to version on them ?

**Comment by davidbinyamin** [comment]
@glicht @aviadl what is the verdict regarding version control?

**Comment by glicht** [comment]
> @glicht why not have 2 scripts with from -to version on them ?

It's an option. We can do that too. But from previous experience this introduces extra work as you need to fix things in 2 places when dealing with bugs. From what I see the logic changes are minimal (but I may be wrong), so I think 1 script with a version check will be easier to maintain. Anyway @davidbinyamin we can do a short call to discuss if needed.

**Comment by davidbinyamin** [comment]
Adding the ver check is pretty straight forward, ill do it

**Review by glicht — APPROVED** [review]

**Pull request merged**
