### PR TITLE
Microsoft Graph Generic Integration

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Description
A generic MS graph integration to execute any API.
Currently supports only Application permission type as Delegated is a bit more tricky - can add later if we see need.

## Minimum version of Demisto
- [x] 5.0.0

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by kirbles19** [comment]
@Itay4 Done

**Comment by glicht** [comment]
Looks interesting. Let's schedule a short demo to further review.

**Comment by Itay4** [comment]
@glicht @anara123 renamed `Generic` to `API` and improved the integration description to elaborate on the usage

@kirbles19 please review again the following:
https://github.com/demisto/content/blob/d8a69cfc1cb511077c2fe052e1faccaec3e1bf8e/Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
https://github.com/demisto/content/blob/d8a69cfc1cb511077c2fe052e1faccaec3e1bf8e/Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI_description.md
https://github.com/demisto/content/blob/d8a69cfc1cb511077c2fe052e1faccaec3e1bf8e/Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md

**Comment by glicht** [comment]
@Itay4 why are we releasing a new version of all the graph api packs?

**Comment by Itay4** [comment]
> @Itay4 why are we releasing a new version of all the graph api packs?

because the api module was modified

**Review by glicht — APPROVED** [review]

**Comment by kirbles19** [comment]
@Itay4 Done.

**Pull request merged**
