### PR TITLE
Whatismybrowser fix

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/20468

## Description
Fixed the command outputs to support extend-context

## Does it break backward compatibility?
   - No

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by Shellyber** [comment]
@kirbles19 Please review the changelog file.

**Comment by yardensade** [comment]
- Fix build errors
- Were we able to simulate the problem? Needs tests to show the problem/solution

**Comment by kirbles19** [comment]
@Shellyber Done

**Comment by Shellyber** [comment]
@yardensade Done. Please review

**Pull request merged**
