### PR TITLE
urlencode transformer

### PR DESCRIPTION
**Pull request by omercnet**
Signed-off-by: Omer Cohen <omer@paloaltonetworks.com>

## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/20353

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - Yes
       - Further details:
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](https://github.com/demisto/content/blob/feature/urlencode/Scripts/URLEncode/URLEncode.yml)
- [ ] [CHANGELOG](https://github.com/demisto/content/blob/feature/urlencode/Scripts/URLEncode/CHANGELOG.md)

### CODE REVIEW

**Comment by Itay4** [comment]
@omercnet whats our status here?

**Comment by Itay4** [comment]
@omercnet ?

**Comment by jochman** [comment]
@omercnet ??

**Comment by Itay4** [comment]
Closing this due to changes done in `master` branch.
Please reopen in a new branch.

**Pull request closed without merging**
