### PR TITLE
Update sane doc reports automation

### PR DESCRIPTION
**Pull request by agamm**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19058
fixes: https://github.com/demisto/etc/issues/18556

## Description
Updates the sane-doc-reports image tag.

## Note
It will fail because we are changing the docker tag.

### CODE REVIEW

**Comment by agamm** [comment]
@anara123 / @ronykoz ready.

**Comment by ronykoz** [comment]
@anara123 we need force merge due to BC break(but this is from 5.0, so no biggie)

**Comment by anara123** [comment]
@ronykoz dont he missing CHANGELOG?

**Comment by ronykoz** [comment]
@anara123 he has a Changelog file there, but i don't see the need in updating it for this change as customers still don't use this

**Comment by ronykoz** [comment]
@anara123 ?

**Pull request merged**
