### PR TITLE
Packagified Tanium integration

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
Ready

## Description
Packagified Tanium integration

## Does it break backward compatibility?
   - No

## Screenshots:
Test is skipped, so here is a screenshot of it running:
image

## Must have
- [X] Tests
- [X] Documentation
- [ ] Code Review

### CODE REVIEW

**Comment by yuvalbenshalom** [comment]
@glicht mypy has issues with pytan docker fetch.
 do you think? can we force merge?

**Comment by glicht** [comment]
@DeanArbel build is failing. Probably best to merge from master.

**Comment by glicht** [comment]
@DeanArbel build is still failing on validate files. @yaakovi maybe you can help here.

**Comment by yaakovi** [comment]
secret file was missing a comma so the `json.loads` failed to parse the file.
see line 1033
image

**Comment by yaakovi** [comment]
build run while AMI was recreated, re-run should fix it.

**Pull request merged**
