### PR TITLE
Fix IPv4 modeling rule for Office 365

### PR DESCRIPTION
**Pull request by screencoffee**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue
N/A

## Description
The company i work for has recently acquired XSIAM, and after connecting the Office 365 data source I noticed that some IPv4 modeling was not accounting for certain edge cases.

In particular the modeling rule for setting `xdm.source.ipv4` in `msft_o365_exchange_online_raw`, would sometimes contain a port number as well.
This would result in a source IP in the format "127.0.0.1:6473".

A similar problem occured when `xdm.source.ipv4` was set in `msft_o365_general_raw`, where the IPv6 subnet prefix `::ffff:` was present in IPv4 that was extracted.
This would result in a source IP in the format "::ffff:127.0.0.1".

This pull request aims to fix the above edge cases, resulting in a more coherent data model for Office 365.

I have tested the changes in the XQL Query builder, but cannot provide any logs or similar due to the sensitivity of the data.

I would like to point out that I am not the most proficient in XQL yet, so if there is a better way to handle these issues please let me know and I'll make sure to incorporate these changes.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kobymeir** [comment]
Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @amshamah419 will know the proposed changes are ready to be reviewed.
For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

**Comment by kobymeir** [comment]
Hi @screencoffee, thanks for contributing to the XSOAR marketplace. To receive credit for your generous contribution please follow this [link](https://xsoar.pan.dev/docs/packs/packs-format#contributorsjson).

**Comment by screencoffee** [comment]
For any questions feel free to reach out to the email i provided in the Contribution registration :)

**Comment by amshamah419** [comment]
Hi @screencoffee just as an update, we have the security team running some tests. When they report back to me, we can move this along.

**Comment by screencoffee** [comment]
Sounds good!

**Comment by amshamah419** [comment]
Hi @screencoffee I spoke with the security team and they wanted me to let you know that they are already in the process "and it includes various improvements and updates for extracting both IPv4/6 and port and interface value from the IP addresses values". They will be handling it in this PR - https://github.com/demisto/content/pull/37814.

Thank you again for your contribution!

**Pull request closed without merging**
