### PR TITLE
Update script-GetTime.yml

### PR DESCRIPTION
**Pull request by omercnet**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16846

## Description
Allow time manipulation with transformers

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - Yes
       - Further details:
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

### CODE REVIEW

**Comment by meirwah** [comment]
@omercnet this is not really a transformer.. 
It doesn't change a value , it just gives current time

**Comment by asafshen** [comment]
@omercnet note that transformer should get `value` argument to trasform, and this one does not

for me its feels a bit hacky

**Comment by omercnet** [comment]
the `date` parameter is the input here, how about it'll accept input parameter if it exists?

`date = args.input || args.date`

or a separate automation running GetTime with input, wdyt?
would like to avoid creating a duplicate

**Comment by Itay4** [comment]
@omercnet closing due to non activity

**Pull request closed without merging**
