### PR TITLE
tableToMarkdown support array of strings

### PR DESCRIPTION
**Pull request by anara123**

### CODE REVIEW

**Comment by dorsha** [comment]
Do the same also for the JS implementation, they should be aligned, otherwise users will not trust the content

**Comment by anara123** [comment]
@dorsha sure will do. @liorblob was working on that change, that is why I assigned him to review

**Comment by dorsha** [comment]
👍

**Comment by liorblob** [comment]
@anara123 @dorsha https://github.com/demisto/content/pull/1658 should solve the issue in JS

**Comment by anara123** [comment]
@liorblob sure. But you can review this PR and approve in the mean time

**Comment by anara123** [comment]
@liorblob that is how I check if the header is string, if yes then it single string, otherwise it should be list

**Comment by anara123** [comment]
closing for now. DON'T DELETE THE BRANCH

**Pull request closed without merging**
