### PR TITLE
Fix random filename variable

### PR DESCRIPTION
**Pull request by slavikm**

### CODE REVIEW

**Comment by gshriki** [comment]
It's deprecated...

**Comment by slavikm** [comment]
Yup, it's deprecated in favor of this one.

**Comment by dorsha** [comment]
Still it has a bug.... but ok

**Comment by dorsha** [comment]
And other people can copy this bug to other scripts (like slavik did)

**Comment by slavikm** [comment]
@dorsha I deprecated it and started with the code from there - don't think anyone else will do it.

**Comment by dorsha** [comment]
ok, lets leave it to the fate 🤞

**Pull request merged**
