### PR TITLE
name -> indicatorName

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22945

## Description
`name` cliname is a system name, changed to indicatorName

## Minimum version of Demisto
- [x] 4.5.0

## Does it break backward compatibility?
   - [x] No
This field was never in Demisto (XSOAR)

### CODE REVIEW

**Comment by Itay4** [comment]
lets change also file name
are there other content entities that use that field ? if so, we need to update them as well

**Comment by jochman** [comment]
> lets change also file name
> are there other content entities that use that field ? if so, we need to update them as well

I was unable to find any entities using it. Care to have a look?

**Comment by Itay4** [comment]
also change the `name` and `prevName` to `Indicator Name`

**Comment by avidan-H** [comment]
@jochman It looks like you already did something with name related indicator field... ?
image

**Comment by jochman** [comment]
Field, not name.

**Comment by avidan-H** [comment]
> Field, not name.

I don't understand what this means.

**Pull request closed without merging**
