### PR TITLE
AWS CloudWatchLogs - test fix

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/29828

## Description
changed the string `test` used for resources in the test to be random uuid to avoid conflicts on resources creation/deletion

### CODE REVIEW

**Comment by Itay4** [comment]
@ShahafBenYakir are you interested in reviewing this ?

**Comment by ShahafBenYakir** [comment]
🙅

**Comment by ShahafBenYakir** [comment]
you have removed the integration from unmockable but this issue was not fixed https://github.com/demisto/etc/issues/20958

**Comment by ShahafBenYakir** [comment]
?

**Comment by Itay4** [comment]
@ShahafBenYakir done

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
