### PR TITLE
[ASM] EXPANDR-3686 - Added sleep and retry changes

### PR DESCRIPTION
**Pull request by capanw**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3686

## Description
Adding a sleep task to accommodate for delayed service information.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Review by johnnywilkes — APPROVED** [review]
@capanw , looks good to me.

Need to figure out what we will do with versioning

**Comment by capanw** [comment]
@johnnywilkes, updated the version number and its good to go.

**Comment by johnnywilkes** [comment]
@thefrieddan1, this is an ASM only change and we have approved internally, please merge when possible.

**Comment by johnnywilkes** [comment]
@thefrieddan1 , we fixed the validation error. Can you please merge today?  This is holding up another PR: https://github.com/demisto/content/pull/26444

**Comment by johnnywilkes** [comment]
@thefrieddan1 after talking to @ShacharKidor , this is not a blocker for https://github.com/demisto/content/pull/26444, however, if this is merged 2nd, the release number will have to change

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
