### PR TITLE
demistoUrls better docstring

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/14900

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
why is this `docs-approved` ?

**Comment by bakatzir** [comment]
@Itay4 I took what @ShirleyDenkberg commented in the referenced issue.

**Comment by Itay4** [comment]
what referenced issue ?

**Review by Itay4 — APPROVED** [review]
please track the content-docs deployment build to make sure this is formatted well on the docs site

**Pull request merged**
