### PR TITLE
delete .replace from all fetch incidents

### PR DESCRIPTION
**Pull request by anara123**
fixes https://github.com/demisto/etc/issues/10431

### CODE REVIEW

**Comment by Spivaka** [comment]
we added it on purpose AFAIR cause otherwise we had parsing errors... did you check it still work with those integrations?

**Comment by liorkol** [comment]
Here is the json field that broke classification
 (only some incidents had quotes in the value so at first there seemed to
be no pattern.. Some incidents just weren't being classified)

"u_soc_custom_string_2": "\u003cResource URI=" / All Rules / Real - time
Rules / Redacted / Corporate / Security Domains / Insider Threat / MyDetec
","

**Comment by liorkol** [comment]
@anar if you want to add a content test and you need the full json for this
please ping me, I will get it

**Comment by anara123** [comment]
@Spivaka This is what I thought. But later I noticed that without replace it works fine. Didn't tested the fetch on all the integrations. But will check on few of them, just to make sure.
@liorkol Removing the `.replace` fixed the fetch problem in servicenow, right?

**Pull request merged**
