### PR TITLE
Created README file for MS graph mail

### PR DESCRIPTION
**Pull request by reutshal**
## Status
- [] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Description
Created a README file for MS graph mail.
Fixed a bug in the "delete" commands

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation 
- [X] Code Review

### CODE REVIEW

**Comment by reutshal** [comment]
@kirbles19 Can you please go over the README file:
https://github.com/demisto/content/blob/MS_graph_mail-readme/Integrations/MicrosoftGraphMail/README.md
Ther is also the command examples file if relevant: 
https://github.com/demisto/content/blob/MS_graph_mail-readme/Integrations/MicrosoftGraphMail/commands.txt
Thanks!

**Comment by kirbles19** [comment]
@reutshal Done, ready to publish

**Comment by reutshal** [comment]
@kirbles19 Why do we need the `<span>` addition?
image
 it causes an error in the validation stage.

**Comment by ronykoz** [comment]
@reutshal try to do `<span/>`

**Comment by ronykoz** [comment]
merging due to not related issue

**Pull request merged**
