### PR TITLE
Created new script for changing packs integration url in metadata

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold 

## Related Issues
related to: https://github.com/demisto/content/pull/6603

## Description
When master bucket is copied to test bucket, integration images URLs are not updated. 
Created new script that downloads `index`, iterates over pack's sub-folders and fixes the integration images.

### CODE REVIEW

**Comment by yuvalbenshalom** [comment]
@IkaDemisto can we close this?

**Comment by IkaDemisto** [comment]
@yuvalbenshalom not yet, need to add additional fix for author images

**Comment by IkaDemisto** [comment]
Added handling also for author image.
Once new version is tested and copied, we can close.

**Comment by IkaDemisto** [comment]
Closing.
Was included in https://github.com/demisto/content/pull/6603

**Pull request closed without merging**
