### PR TITLE
[Axonius Content Pack 1.2.0] Bumping Dockerfile

### PR DESCRIPTION
**Pull request by bryce-ax**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/dockerfiles/pull/19635

## Description
Updating the Axonius integration with our latest Dockerfile. This Dockerfile change bumps the version of the axonius-api-client python package.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by bryce-ax** [comment]
The image is currently `devdemisto/axonius:1.1.0.72791` but how will this be updated accordingly once the dockerfiles pr is merged? @RotemAmit @RosenbergYehuda

**Comment by RotemAmit** [comment]
> The image is currently `devdemisto/axonius:1.1.0.72791` but how will this be updated accordingly once the dockerfiles pr is merged? @RotemAmit @RosenbergYehuda

You will have to update it manually after the merge.

**Review by RosenbergYehuda — COMMENTED** [review]
Hello @bryce-ax, great job!

I wanted to provide you with an update as we enter the holiday season here in Israel. Please expect some potential delays from our end during this time.

I'm looking forward to reviewing this next week.

Wishing you a fantastic weekend!

**Comment by bryce-ax** [comment]
Thanks, Rosen! Enjoy the holiday :D

**Pull request merged**
