### PR TITLE
completing the adoption process

### PR DESCRIPTION
**Pull request by munna-metron**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShacharKidor** [comment]
Hi @munna-metron, 
Thank you for your contribution!
Due to a problem in our infra, the automation that should add your PR to the contributions queue failed. 
We fixed it now, so please merge the content master into your branch so we could re-trigger the automation and start the review process of your PR. 
Please let me know once you merge master. 

Thanks in advance, 
Available here or on slack (DFIR) for any questions :)

**Comment by munna-metron** [comment]
Hi @ShacharKidor, merged the content master into my branch, can you please review it again. Thanks!

**Comment by daryakoval** [comment]
@munna-metron Thanks for your fast response. 
Can you please close this PR and open a new one? 
Due to a problem in our infra, that @ShacharKidor mentioned before, only merging from master didn't help, but it should be solved for new incoming PRs. 
The flow will automatically re-trigger the automation and start the review process of your PR.

**Comment by munna-metron** [comment]
@daryakoval i think @kgal-pan closed this PR. BTW i created the new PR here is the link https://github.com/demisto/content/pull/25470

**Pull request closed without merging**
