### PR TITLE
Virus total value unpack fix

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/40362

## Description
Fixed an error where reserved WHOIS string caused an error to be thrown

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by tomneeman151293** [comment]
test failure to indicate error
https://app.circleci.com/pipelines/github/demisto/content/107446/workflows/91dffa20-196a-4c18-9ffa-ddcf337dec3d/jobs/411484

**Review by jochman — APPROVED** [review]
👍

**Comment by tomneeman151293** [comment]
can we force merge this? test failure is not related, it is a test failing in the nightly (not relevant to virus total)
@dantavori @Itay4

**Comment by Itay4** [comment]
merging due to the comment above

**Pull request merged**
