### PR TITLE
AlienVault OTX V2 - Design

### PR DESCRIPTION
**Pull request by GalRabinDemisto**
Hi,
there was some errors with git hook in the last branch, I fixed it here.
Can you please review this pull request and not the other one?

Thanks

### CODE REVIEW

**Comment by yaakovi** [comment]
recommit the files without the windows line-ending (no `\r` or as appears here `^M`)

**Comment by GalRabinDemisto** [comment]
@Arsenikr 
Hi,
Do you have a design for DBot score as we discussed?

Thanks!

**Comment by Arsenikr** [comment]
yes we are going with pulses 

not found - unknown
pulses = 0 - good
pulses > 0 - suspicious
pulses > <threshold> [default will be 1] - bad

**Comment by GalRabinDemisto** [comment]
@Arsenikr 
Hi,
I would appreciate if can clarify the following commands:
1. alienvault-get-related-urls-by-indicator.
2. alienvault-get-related-hashes-by-indicator.
3. alienvault-get-passive-dns-data-by-indicator.

From my understanding, the user should give indicator in the 3 commands, but to which path in the API should I send a request, I didn't found one that the indicator id.
An example will be helpful 

Thanks

**Comment by Arsenikr** [comment]
alienvault-get-related-hashes-by-indicator.

**Pull request closed without merging**
