### PR TITLE
Fixed an issue where it doesn't return any errors when failed to pars…

### PR DESCRIPTION
**Pull request by spearmin10**
…e a pcap.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
PcapConvert and PcapExtractStreams are transformer that `return_error` return successful results.
They have to raise exceptions instead of `return_error` in transformer.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by spearmin10** [comment]
@JasBeilin There were some regressions by someone modified the scripts in the reviewing process. https://github.com/demisto/content/pull/19150

**Review by JudahSchwartz — COMMENTED** [review]
According to our [code conventions](https://xsoar.pan.dev/docs/integrations/code-conventions), best practice is to catch exceptions in the main function and return errors using the `return_error` function
Why are we removing the try catch block here? Is there a specific flow where the error is not being returned properly?

**Comment by spearmin10** [comment]
@JudahSchwartz The coding conventios that it returns errors with `return_error` is geenrally true, but transformer is an exception. In transfomer, returning an error must be raised by an exception. Because results returned with `return_error` from an transformer are handled as success. That comes from the design of XSOAR.
This is a simple test playbook that branches to an error path from a task which runs PcapConvert fails. The current script (try-except-return_error) runs on the successful path even in causing an error, but the fixed code branches expectedlly to the error path.
[Test_Error_Path.zip](https://github.com/demisto/content/files/9080463/Test_Error_Path.zip)

**Comment by JudahSchwartz** [comment]
Youre right, thanks for the explanation! Merging it in

**Pull request merged**
