### PR TITLE
Deprecate Cymon

### PR DESCRIPTION
**Pull request by amshamah419**
## Status
Ready

## Description
Packaging Cymon so we can perform bug fixes at a later PR

### CODE REVIEW

**Comment by amshamah419** [comment]
I don't believe we have a working instance because yes, it's completely shut down

**Comment by Itay4** [comment]
Why are we still supporting this if it’s being deprecated?

**Comment by amshamah419** [comment]
In my opinion, we really should just remove it.

**Comment by Itay4** [comment]
Let’s start with deprecating the commands and add (Deprecated) to the display name

**Comment by yuvalbenshalom** [comment]
I think that the whole integration should be replaced with a code that return the same error entry that say that this service dose not exist any more.
and also to mark every command as deprecated.

**Comment by amshamah419** [comment]
Test button now returns an error indicating service is discontinued.
Screen Shot 2019-06-05 at 11 24 16

Deprecated is now part of the display name.
Screen Shot 2019-06-05 at 11 24 23

For commands, it now returns an error indicating the service is discontinued.
Screen Shot 2019-06-05 at 11 24 39

**Comment by Itay4** [comment]
Let’s discuss before merging

**Comment by gshriki** [comment]
What happens today, before this change, for customers who have Cymon configured?

Think we should say: `Cymon service discontinued. Please disable or delete the integration instannce`.
We also need to have proper documentation in the release notes.

**Comment by amshamah419** [comment]
As of right now, customers get an error message indicating that the http handler failed to connect. This is technically correct, since the endpoint has simply vanished, however most customers would see it as a failure on our end as opposed to Cymon being defunct.

**Pull request merged**
