### PR TITLE
skip failing tests

### PR DESCRIPTION
**Pull request by asafshen**
related to https://github.com/demisto/server/issues/9985
related to https://github.com/demisto/server/issues/9984

Also fixed issue in `AssignAnalystToIncident` (fallback to roles)

### CODE REVIEW

**Comment by asafshen** [comment]
after consulting with @aviadl, the `AssignAnalistToIncident` issue was probably caused due to a problem in our server
reverted it

**Comment by dorsha** [comment]
@asafshen ?

**Comment by asafshen** [comment]
@dorsha 
image
this playbook fails due to a regression in the server

I can make a patch in `AssignAnalistToIncident` script that will fix this. But after consulting with @aviadl - we decided not to do so.

cannot merge until this fix (because merge is block until build passes)
do you think we should handle it in other way?

**Comment by dorsha** [comment]
No, need to fix the problem.. just make sure we have issue for this.

**Comment by dorsha** [comment]
@asafshen still failing

**Comment by asafshen** [comment]
@dorsha?

**Pull request merged**
