### PR TITLE
New mutex indicator type and layout (description and StixID fields associate to all)

### PR DESCRIPTION
**Pull request by Ni-Knight**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2732

## Description
New Indicator type and layout - Mutex
Associated the indicator fields "Description" and "StixID" to all types.

## Screenshots
image

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by Ni-Knight** [comment]
cc - @DanilVil

**Comment by Ni-Knight** [comment]
cc - @altmannyarden, when you get a sec

**Comment by altmannyarden** [comment]
Dont we need to add some mutex related fields?

**Comment by altmannyarden** [comment]
I think we can close the PR since all the changes are in another PR (with the ASN)
https://github.com/demisto/content/pull/20447

**Comment by Ni-Knight** [comment]
@altmannyarden - there are no mutex fields except a value, relationships and description.

**Review by altmannyarden — APPROVED** [review]

**Comment by altmannyarden** [comment]
before merging, lets pull from master since its been a while

**Pull request merged**
