### PR TITLE
Palo alto networks wild fire v2

### PR DESCRIPTION
**Pull request by cx-jp**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fixed an issue that it is unable to create reports when no report is found for any of file hashes.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by yaakovi — APPROVED** [review]
I'll handle the fixes in the internal PR

**Comment by yaakovi** [comment]
@cx-jp please update your branch with master. I tried to but I don't have permission to push the update.

**Comment by yaakovi** [comment]
> @cx-jp please update your branch with master. I tried to but I don't have permission to push the update.
> also, please fill in the contribution registration form: [here](https://forms.gle/XDfxU4E61ZwEESSMA)

@cx-jp @spearmin10 
any updates here?

**Comment by spearmin10** [comment]
I will re-create a PR for this.

**Comment by spearmin10** [comment]
Please close this PR. New PR is below.
https://github.com/demisto/content/pull/11893

**Pull request closed without merging**
