### PR TITLE
Phishing - Core + test

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
In Progress:
- Simplifying further
- Adding `Process Email - Core`

## Related Issues
fixes: https://github.com/demisto/etc/issues/17398

## Description
- Added `Phishing - Core` playbook
- Added a `Phishing - Core - Test` - test playbook

## Screenshots
image

## Required version of Demisto
4.1.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] [Documentation](https://github.com/demisto/etc/issues/17565)
- [ ] Code Review

### CODE REVIEW

**Comment by idovandijk** [comment]
The new field for phishing category won't be added in this PR as we are waiting for incident sub-types to be released for that purpose. FYI @erezh31

**Comment by kirbles19** [comment]
Done reviewing .yml file.

I still have concern about using the words Basic or Simple for the playbook. As a user, it automatically makes me think I'm not getting the full service and there is something better out there.

**Comment by Itay4** [comment]
@idovandijk whats our status here ?

**Comment by idovandijk** [comment]
New PR here: https://github.com/demisto/content/pull/3718

**Pull request closed without merging**
