### PR TITLE
Qualys_Add_New_Commands

### PR DESCRIPTION
**Pull request by DaniSalcedoGFT**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
We have created two new commands that:
- Deletes assets and actives when you give a host id (qualys-host-asset-delete)
image

- Obtain a list of host ids when you give an asset id (qualys-asset-host-list)
image

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by thefrieddan1** [comment]
Hi @DaniSalcedoGFT,
Thank you for your contribution.
You are enhancing an existing integration which is an XSOAR support level integration.
XSOAR support level means the contribution requires you to add a unit test per each command you have added.
Also there is a need to add the commands to the yml file with input params and output context params. 
Also there is a need to add the commands to the README and update the pack version. 
I suggest working with demisto-sdk to ease the process of adding these requirements.
Thanks

**Comment by thefrieddan1** [comment]
Hi @DaniSalcedoGFT,
Please let me know if you have any questions about my previous comment.

**Comment by thefrieddan1** [comment]
> Hi @thefrieddan1, sorry for the delay, yes I will try to add the things you are asking me, in case I need help I will reach you

@DaniSalcedoGFT 
What is the addition in the command qualys-asset-host-list you added to the existing qualys-host-list?

**Comment by DaniSalcedoGFT** [comment]
The addition o difference is that qualys host list doesn't accept asset like an argument,
And our new method qualys-asset-host-list yes

**Comment by thefrieddan1** [comment]
Hi @DaniSalcedoGFT 
First let me start with apologizing on the delay here.
Technical product manager got back to me and approved these additions.
I will merge these with minor naming change to:
```
qualys-host-asset-delete
qualys-host-asset-list
```

Thank you again for the contribution.

**Review by thefrieddan1 — CHANGES_REQUESTED** [review]
Missing required files. yml RN pack metadata

**Comment by thefrieddan1** [comment]
Hi @DaniSalcedoGFT, 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

**Pull request closed without merging**
