### PR TITLE
Fixed "index out of range" exception in RedCanary integration

### PR DESCRIPTION
**Pull request by vector-sec**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Fixed "index out of range" exception when username does not contain a backslash because the user is not an active directory user.

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

### CODE REVIEW

**Comment by Itay4** [comment]
Looks good !
Let's refactor a bit to:
```
for endpoint_user in res:
    username = endpoint_user.get('attributes', {}).get('username', '')
    if '\\'' in username:
	hostname, parsed_username = username.split('\\')
	user = {
	    'Username': parsed_username,
	    'Hostname': hostname
	}
    else:
        user = {
            'Username' : username
        }
    endpoint_users.append(user)
return endpoint_users
```

**Comment by Itay4** [comment]
@vector-sec Any update on this? Do you need our help to get this done?

**Comment by ronykoz** [comment]
@vector-sec any update here? If you need our help please let me know

**Comment by vector-sec** [comment]
Hey sorry for the delay, I just assumed you could take the refactor here https://github.com/demisto/content/pull/3787#issuecomment-507012357 without anything else from me.

**Comment by ronykoz** [comment]
@vector-sec it seems that you've deleted the branch/fork, we've tried to resolve the conflict or to merge it to an inner branch within Demisto but with no luck there.
So i was thinking of two options:
1. You can create a new PR which we will be able to merge with the correct coding from Itay.
2. We can create a PR for that by ourselves in our repo.

Please let us know what you think

**Comment by vector-sec** [comment]
@ronykoz since you all have the change here in the PR you can just close this PR and make the change in your own branch and merge if that's easier.

**Comment by yaakovi** [comment]
closing, opened a new PR with the updated code.

**Pull request closed without merging**
