### PR TITLE
[ASM] - EXPANDR-1614 - Servicenow pack asm integration

### PR DESCRIPTION
**Pull request by capanw**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-1614

## Description
Integrating ServiceNow changes into main ASM playbook.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by BigEasyJ** [comment]
@capanw It looks good to me, you'll need to merge with master and resolve conflicts.

@yucohen this PR should be merged after #25036, since it has an earlier release number.

**Review by BigEasyJ — APPROVED** [review]

**Comment by johnnywilkes** [comment]
related to https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3057

**Comment by johnnywilkes** [comment]
@BigEasyJ , please add closeReasons to known_words file:
https://github.com/demisto/content/actions/runs/4358998329/jobs/7620281416

**Comment by johnnywilkes** [comment]
once https://github.com/demisto/content/pull/25115 is merged, we will need to pull in the changed to the parent playbook

**Comment by yucohen** [comment]
@capanw @BigEasyJ @johnnywilkes can we merge? :)

**Review by BigEasyJ — APPROVED** [review]

**Comment by BigEasyJ** [comment]
Yes @yucohen , please merge :relaxed:

**Review by yucohen — APPROVED** [review]

**Pull request merged**
