### PR TITLE
Ping via cmdline

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
fixes: demisto/etc#15014

## Description
Move to use builtin ping cmd line

## Required version of Demisto
All

## Does it break backward compatibility?
      - No

## Must have
- [x] Tests
- [x] Documentation: Description remains as before
- [ ] Code Review

## Dependencies
- [ ] McAfee ePO Endpoint Connectivity Diagnostics Playbook: this playbook uses ping

### CODE REVIEW

**Comment by anara123** [comment]
@glicht fix the test
```
 ------ Test playbook: Ping Test Playbook start ------
Failed to create incident. Possible reasons are:
Mismatch between playbookID in conf.json and the id of the real playbook you were trying to use, or schema problems in the TestPlaybook.
```

**Comment by glicht** [comment]
@anara123 I saw this. Wanted your help with this when you have time.

**Comment by anara123** [comment]
ok

**Comment by Itay4** [comment]
Try adding to the integration yml:
```
tests:
 - Ping Test Playbook
```

**Pull request merged**
