### PR TITLE
FortiMail (Alpha)

### PR DESCRIPTION
**Pull request by Aceilies**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
New Integration

## Description
Integration to Take Action Fortinet FortiMail, Under Development will be updated regularly with tests, Currently Working Functions, Display/List mails in Quarantine, Block/Unblock Sender/Recipient Addresses 

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by Aceilies** [comment]
ReUploaded for better Fork Management

**Comment by MLainer1** [comment]
Hi @Aceilies, thank you for your contribution.
Make sure to add a metadata file, along with tests to the PR.

**Comment by Aceilies** [comment]
@MLainer1 I've added the metadata file please review and let me know

**Comment by Aceilies** [comment]
@MLainer1 test screenshots will be attached soon

**Comment by omerKarkKatz** [comment]
@Aceilies Thank you for this great contribution and for the hard work you put into it.
In the next 1-2 weeks we are going to publish a large xsoar-supported pack for FortiGate and Fortimail, Before merging this contribution we will first publish the xsoar-supported packs to see if it fits your use cases. 
If the new packs won't be sufficient I will be in touch with you regarding this contribution.

**Comment by Aceilies** [comment]
@omerKarkKatz Great in case anything is needed just let me know

**Comment by Aceilies** [comment]
@omerKarkKatz I've just read the other contributor work, which is excellent but we are tackling almost completely different endpoints and usecases.

**Comment by omerKarkKatz** [comment]
@Aceilies Hey, thanks for your hard work and dedication. 
Since we already published an Xsoar support integration for Fortimail, If you want to add more commands and functionality it will need to be an enhancement to the existing integration. Following the Xsoar support standards of the pack.
If you decide to go ahead with the contribution process a developer from Xsoar will be assigned to help you with questions and further help.  
In that case please open a new PR. If you have any further questions or need further help please feel free to contact @AradCarmi via Slack DFIR or email. 
Thanks @omerKarkKatz

**Pull request closed without merging**
