### PR TITLE
[ASM] EXPANDR-6261

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6261

## Description
Bug fix for GCP Enrichment/remediation

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@capanw / @BigEasyJ , please review and approve.  See testing in ticket under `End to End testing:` section.

**Review by BigEasyJ — APPROVED** [review]
LGTM. Updated `view` keys to unescaped values.

**Comment by johnnywilkes** [comment]
@ShirleyDenkberg , please review

**Comment by johnnywilkes** [comment]
@melamedbn / @MosheEichler , this is approved from Xpanse-side.  Please merge when possible

**Comment by MosheEichler** [comment]
@ShirleyDenkberg
Can you please reveiew the docs?

**Review by MosheEichler — APPROVED** [review]

**Pull request merged**
