### PR TITLE
Add entitlement changes

### PR DESCRIPTION
**Pull request by Nitzperetz**
Deprecate `addOneTimeEntitlement` command, Use `addEntitlement` instead.
`addEntitlement` Receives a boolean argument - `persistent`.

### CODE REVIEW

**Comment by Nitzperetz** [comment]
@gshriki , updated.

**Comment by gshriki** [comment]
I thought we agreed we are not going to release the EmailAskUser3.5.yml, no?
We should have only one file, and it should have the fromVersion.
And it all should be merged AFTER we have 3.5 out

**Comment by Nitzperetz** [comment]
@gshriki , but then when upgrading content on v3.1.0, the scripts would not work. Let's discuss.

**Comment by Nitzperetz** [comment]
@asafshen , @aviadl , please approve and merge.

**Comment by Nitzperetz** [comment]
@aviadl , fixed.
I think we can consider removing the persistent parameter (meaning all entitlements would be persistent). It was used in order to add `one-time` entitlement as `assOnetimeEntitlement` command is now deprecated.
Any objections?

**Comment by aviadl** [comment]
@Nitzperetz the persistent parameter should be an argument.
That has a default.
Default should actually be `false` to support backward compatibility

**Comment by Nitzperetz** [comment]
Updated.

**Comment by Nitzperetz** [comment]
@aviadl  please review and merge.

**Pull request merged**
