### PR TITLE
[Enhancement] PagerDuty-get-users-on-call-now

### PR DESCRIPTION
**Pull request by gal-berger**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18842

## Description
  - added new arguments to ***PagerDuty-get-users-on-call-now*** command:
    - escalation_policy_ids: Filters the results, showing only on-calls for the specified escalation
        policy IDs.
    - schedule_ids: Filters the results, showing only on-calls for the specified schedule
        IDs. If null is provided, it includes permanent on-calls due to direct user
        escalation targets.

## Screenshots
image

## Does it break backward compatibility?
  - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] PagerDutyAssignOnCallUser.yml

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](https://github.com/demisto/content/edit/pagerduty-enhance/Integrations/PagerDuty/PagerDuty.yml?pr=%2Fdemisto%2Fcontent%2Fpull%2F4441)
- [ ] [CHANGELOG](https://github.com/demisto/content/edit/pagerduty-enhance/Integrations/PagerDuty/CHANGELOG.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F4441)

### CODE REVIEW

**Comment by gal-berger** [comment]
@kirbles19 Added a new enhancement to PagerDuty integration. can you please review my RN? 
https://github.com/demisto/content/blob/005127796c7e3fce0f9caa2ab8a97b4bc0538cce/Integrations/PagerDuty/CHANGELOG.md

https://github.com/demisto/content/blob/005127796c7e3fce0f9caa2ab8a97b4bc0538cce/Scripts/script-PagerDutyAssignOnCallUser.yml

**Comment by richardbluestone** [comment]
> @kirbles19 Added a new enhancement to PagerDuty integration. can you please review my RN?
> https://github.com/demisto/content/blob/005127796c7e3fce0f9caa2ab8a97b4bc0538cce/Integrations/PagerDuty/CHANGELOG.md
> 
> https://github.com/demisto/content/blob/005127796c7e3fce0f9caa2ab8a97b4bc0538cce/Scripts/script-PagerDutyAssignOnCallUser.yml

I've made changes to the files. I reviewed the script file but I saw there are changes to the integrations yml file. Do you want me to review the integrations file as well?

**Comment by gal-berger** [comment]
RN - release notes
Can you please go over this files as well? 
https://github.com/demisto/content/blob/277ac024511774f7f8506073d64b0d328f11fbbc/Scripts/script-PagerDutyAssignOnCallUser_CHANGELOG.md

https://github.com/demisto/content/edit/pagerduty-enhance/Integrations/PagerDuty/PagerDuty.py?pr=%2Fdemisto%2Fcontent%2Fpull%2F4441
I forgot to mention it before.

**Comment by richardbluestone** [comment]
I've reviewed and updated all the files.

**Pull request merged**
