### PR TITLE
Reduce images 01

### PR DESCRIPTION
**Pull request by agamm**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related:  demisto/etc#44196

Related: https://github.com/demisto/content/pull/16958

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by yuvalbenshalom — APPROVED** [review]

**Review by yuvalbenshalom — CHANGES_REQUESTED** [review]
please generate the missing release notes

**Comment by agamm** [comment]
> please generate the missing release notes

Maybe there is a bug in the checks?
I didn't change those Packs, you can check with the changed files here. @yuvalbenshalom

**Comment by yuvalbenshalom** [comment]
please update from master and see if the issue persists, and then check the test playbooks runs and see if they they are relevant to the changed images, and make a summary.

**Comment by agamm** [comment]
Currently done at: https://github.com/demisto/content/pull/17031
(Without CommonScripts)

**Pull request closed without merging**
