### PR TITLE
TIM \ REGEX \ URLFormatter \ Allow parenthesis in the query part of the URL

### PR DESCRIPTION
**Pull request by Ni-Knight**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44562

## Description
The old URL regex did not allow parenthesis in the query part of the URL.

Tests:
https://regex101.com/r/3IsAyU/1

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
@DeanArbel Doc review completed.

**Comment by kobymeir** [comment]
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12222018616)
- **CommonScripts** pack version was bumped to **1.17.3**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

**Comment by kobymeir** [comment]
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12232346213)
- **CommonScripts** pack version was bumped to **1.17.4**.
- **ApiModules** pack version was bumped to **2.2.32**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

**Comment by kobymeir** [comment]
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12238829646)
- **CommonScripts** pack version was bumped to **1.17.5**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

**Review by DeanArbel — APPROVED** [review]
LGTM

**Pull request merged**
