### PR TITLE
Change Version Number in IAM Test Playbook

### PR DESCRIPTION
**Pull request by amshamah419**
## Status
Ready

## Related Issues
fixes: master

## Description
Old AWS playbooks were using hardcoded version. Switched IAM test playbook to -1

### CODE REVIEW

**Comment by ronykoz** [comment]
Why did you change the ID back to uuid

**Comment by amshamah419** [comment]
@ronykoz it failed again when we changed just the version number

**Comment by yardensade** [comment]
So is it going to stay like that for eternity?

**Comment by ShahafBenYakir** [comment]
@yardensade Or until we will figure out how to change playbook ID without breaking content

**Comment by amshamah419** [comment]
@yardensade so essentially yes

**Pull request merged**
