### PR TITLE
[ASM] EXPANDR-9427 fix email issue

### PR DESCRIPTION
**Pull request by capanw**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9427

## Description
Fixing tag email issue

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by capanw** [comment]
@johnnywilkes @BigEasyJ Please review when you can. Thank you.

**Comment by johnnywilkes** [comment]
> @johnnywilkes @BigEasyJ Please review when you can. Thank you.

@capanw , making comments in https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9427

**Review by johnnywilkes — CHANGES_REQUESTED** [review]
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9427 Let me know when you have made changes that I recommend in the ticket, please

**Review by johnnywilkes — APPROVED** [review]
@capanw , thanks for those changes

**Comment by capanw** [comment]
@maimorag, this is approved from our side

**Review by maimorag — APPROVED** [review]
Hey @capanw,
great work!

**Pull request merged**
