### PR TITLE
New SplunkPy command !splunk-job-status

### PR DESCRIPTION
**Pull request by moishce**
replacing: https://github.com/demisto/content/pull/6104

## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/22345

## Description
Add a new command to SplunkPy integration for checking the status of a job in Splunk

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Comment by moishce** [comment]
I added a test in the test playbook

**Comment by Itay4** [comment]
cant see the test playbooks in the changed files

**Comment by moishce** [comment]
and the readme i updated  in the PR https://github.com/demisto/content/pull/6225

**Comment by moishce** [comment]
I forgot to pass it on to the new brunch, I added it now

**Pull request merged**
