### PR TITLE
SpyCloud Enterprise Protection initial commit

### PR DESCRIPTION
**Pull request by loginsoft-integrations**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by loginsoft-integrations** [comment]
Ref: The old pull request number is #29034

**Comment by omerKarkKatz** [comment]
@loginsoft-integrations Please remove the package-lock.json file it's not supposed to be related to your PR.

**Comment by amshamah419** [comment]
Hi @loginsoft-integrations. Thanks for the contribution, let's setup a demo call to review the PR and figure out next steps.

**Comment by melamedbn** [comment]
Dear @loginsoft-integrations,

I've been reviewing the SpyCloud Protection content you've submitted and I'd like to share some feedback to ensure we maximize its effectiveness and user-friendliness.

### **Incident Fields**:
Some fields you've added already exist in common types. To avoid redundancy, I'd recommend using these pre-existing fields. If there's a specific reason for the unique fields, it'd be great to understand your perspective.

- `domain` can replace `SpyCloudDomain`
- `email` can replace `SpyCloudEmail`
- `fullname` can replace `SpyCloudFullName`
- `filepath` or `processpath` can replace `SpyCloudInfectedPath`
- `occurred` or `detectiontime` can replace `SpyCloudInfectedTime`
- `severity` can replace `SpyCloudSeverity`
- `detectionurl`, `URLs`, or `externallink` can replace `SpyCloudTargetURL`
- `sourceid` can replace `SpyCloudSourceID`
- `username` can replace `SpyCloudUserName`
- `deviceosname` or `deviceosversion` can replace `SpyCloudUserOS`

### **Playbooks**:
#### **Breach Investigation-SpyCloud**:
1. Enhancing task titles (e.g., 2, 3, 5, 10) will assist users in navigation.
2. Could you provide insights into the logic for conditional tasks, specifically IDs 2, 3 and 4?
3. Consider making the password length check in task 9 adjustable through playbook input for flexibility.
4. For consistency, I'd suggest aligning the names of 'End' and 'Exit Playbook' headers.
5. Expanding on the technical flow in the playbook's description could be beneficial.
6. In which part the password is being reset? It seems that there's no use in password reset capabilities.
6. Should this playbook include outputs?

#### **Malware Investigation-SpyCloud**:
1. Descriptive titles for tasks, especially 1 and 2, would enhance clarity.
2. For better versatility, think about adding 'infected_machine_id' as a playbook input.
3. Should this playbook include outputs?

### **Incident Types**:
I observed that only 'SpyCloud Informative Data' doesn't have a default playbook. Is this by design?

### **Layouts**:
Across **SpyCloud Breach**, **Informative**, and **Malware Layouts**:
1. Re-arranging the grid to optimize visual space (as highlighted in the attached screenshot) would enhance the user interface.
2. Current indicator sections don't seem to have a filter, which might display benign and unknown statuses. Please verify if this aligns with your intent.
3. Grouping SpyCloud fields into thematic sections, like "SpyCloud Identity" or "SpyCloud Network," could offer a more intuitive incident overview.

image

Your attention to these details will not only enhance the quality of the content but also improve its usability. Thanks for your ongoing efforts in refining these tools. If you have any questions or need further clarification on the feedback, please feel free to reach out.

Looking forward to the updated versions!

Best regards,
Ben

**Comment by loginsoft-integrations** [comment]
Hi @melamedbn,
We have implemented all the suggestion except for the playbooks, we would like to get on a call to discuss on Playbooks. Please schedule a call based on your availability.

**Comment by amshamah419** [comment]
@loginsoft-integrations Hi, I'm trying to get the commits sorted out for y'all on this PR so we won't need to open another one, but looks like I don't have enough permissions in your repo.

Can you either add me as a contributor, or follow this quick guide so we can get this merged. Code wise, I think we are ready, just need to sort these last little build issues.

---
- Save all of your changes locally or in a new branch.
- Enter your forked repository page in GitHub.
- At the top of the page, you will probably see something like this, please ensure you are in the master branch. 
Screenshot 2024-01-10 at 11 46 23

- Click on “Sync fork” button on the top right side of the page.
- The following message will appear (This branch has conflicts that must be resolved).

Screenshot 2024-01-10 at 11 47 04

- Click on the button “Discard commits”. Note that for this action to work, you should have permission to do a force push in the forked repo. If you don’t have one, ask the forked repo Owner to do that.
- Enter your branch and repeat the same steps (4-6).
- Check your PR, and see if your changes have been saved. If yes - you finished the update process.
- If your PR does not show your changes, open a new PR with the changes that you saved at the beginning of the process.
- In case you opened a new PR please close the old one, and update your reviewer with the new PR link.
- Please paste on the new open PR the URL to your previous PR so our team member can continue the review from the same place.

**Comment by amshamah419** [comment]
This PR was closed automatically for some reason - New PR is here and it's already internal - https://github.com/demisto/content/pull/32732

**Pull request merged**
