### PR TITLE
Pack metadata fixes

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
We should never add empty string as tag in `pack_metadata.json`. Need to add validation for it in later step, it causes the server to display empty data as tags in UI.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by liorblob** [comment]
@IkaDemisto this comes from the SDK, need to fix it there.

**Comment by amshamah419** [comment]
Nice

**Comment by amshamah419** [comment]
Guardrails is down? Really?

**Comment by IkaDemisto** [comment]
yes  👎

**Comment by liorblob** [comment]
This corona virus man...

**Comment by amshamah419** [comment]
Next we will have to quarantine the build...

**Pull request merged**
