### PR TITLE
fixing pack image size - cortex 911

### PR DESCRIPTION
**Pull request by roysagi**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
fixing the pack image size for cortex 911
this should let us get the fix to the author image validation in https://github.com/demisto/demisto-sdk/pull/1549

### CODE REVIEW

**Comment by Itay4** [comment]
is version bump required?

**Comment by roysagi** [comment]
> is version bump required?

SDK asked me to do it - @guyfreund @ShahafBenYakir  is that wrong?

**Review by yaakovi — APPROVED** [review]
revert the version bump (if needed, we will force-push).
this change should not require a version bump.

**Comment by guyfreund** [comment]
No need for version bump, we detect changes in author images and upload them.

@Noy-Maimon FYI

**Pull request merged**
