### PR TITLE
Slack - document direct messages and name change

### PR DESCRIPTION
**Pull request by liorblob**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/24578

### CODE REVIEW

**Comment by kirbles19** [comment]
@liorblob Done.

**Comment by liorblob** [comment]
@kirbles19 I added documentation for changing the app name, please review.

**Comment by Itay4** [comment]
i think the images are uploaded wrong, have a look at https://xsoar.pan.dev/docs/integrations/integration-docs#images

**Comment by liorblob** [comment]
@Itay4 done

**Comment by kirbles19** [comment]
@liorblob Done

**Pull request merged**
