### PR TITLE
fixed printed bucket path when printing summary table

### PR DESCRIPTION
**Pull request by guykeller**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fixed printed bucket path when printing summary table, that used to be hard coded until now.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by anara123 — APPROVED** [review]

**Comment by anara123** [comment]
@guykeller 
image
The bucket URL printed as None

**Comment by anara123** [comment]
@guykeller I think you need to merge from master.

**Comment by anara123** [comment]
still None
image

**Comment by anara123** [comment]
@guykeller what is the status here?

**Comment by guykeller** [comment]
Closing this PR due to master changes, opened a new one [here](https://github.com/demisto/content/pull/9923).

**Pull request closed without merging**
