### PR TITLE
Bug fix/data message

### PR DESCRIPTION
**Pull request by cyble-dev**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
NA

## Description
Sometimes fetched alerts do not have data message field which results in app throwing an error and getting stuck. This PR is to fix this issue.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kobymeir** [comment]
Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @amshamah419 will know the proposed changes are ready to be reviewed.
For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

**Comment by kobymeir** [comment]
Hi @cyble-dev, thanks for contributing to the XSOAR marketplace. To receive credit for your generous contribution please follow this [link](https://xsoar.pan.dev/docs/packs/packs-format#contributorsjson).

**Review by amshamah419 — APPROVED** [review]
Hi @cyble-dev! PR looks good. Just need to bump the docker image, but I can take care of that for you.

**Comment by cyble-dev** [comment]
Sure @amshamah419,
Please go ahead.
Thanks.

**Comment by amshamah419** [comment]
@cyble-dev Have you signed the CLA? We've had some troubles with the bot lately so it's possible you may need to sign again. https://cla-assistant.io/check/demisto/content?pullRequest=37582

**Pull request merged**
