### PR TITLE
Wildfire dbot score

### PR DESCRIPTION
**Pull request by Shellyber**
Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/26901

## Description
Added a dbot score of 0 where no report was found using !file command.

## Screenshots
image
image

## Minimum version of Demisto
- [x] 4.0.0

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Comment by Itay4** [comment]
please add test

**Comment by Shellyber** [comment]
@Itay4 added to the test playbook

**Review by Itay4 — APPROVED** [review]
cool

**Comment by kirbles19** [comment]
@Shellyber Done.

**Pull request merged**
