### PR TITLE
Remove unnecessary keys from fields

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Remove all unneeded keys as described [here](https://github.com/demisto/content/pull/6320#issuecomment-606575040).
Also, it changed all "content" flags to true.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

### CODE REVIEW

**Comment by Itay4** [comment]
why is this needed?

**Comment by jochman** [comment]
> why is this needed?

@sagylell  pls answer

**Comment by sagylell** [comment]
Not a "must" to fix this backward.
Just make sure "prevName" is either empty/removed or is equal to "Name". Preferably removed.
A problem occurs when they doesn't match - the version control will try to rename the items.

**Comment by Itay4** [comment]
@jochman lets close this one and open issue to add the verification @sagylell mentioned to the sdk

**Pull request closed without merging**
