### PR TITLE
ATDDetonate - Poll through ATD detonate process, URL and Files

### PR DESCRIPTION
**Pull request by JonathanMeler**
input: `atd-file-upload` input and `atd-get-report` reportType input

### CODE REVIEW

**Comment by Spivaka** [comment]
@JonathanMeler either fix and merge or delete

**Comment by JonathanMeler** [comment]
@Spivaka @aviadl In my opinion we can merge (I need someone to approve)
regarding aviad questions:
1. why playbook - this should be callable from the CLI as well
2. The context exists, it's created from the base-api calls
3. should I just copy the context/important fields from the base-api call?

**Comment by aviadl** [comment]
if you call an api call from a script nothing is being placed into the context, it is the script responsibility to place it.
So you should declare it and handle it in the script (getting the data as is form the api call and forwarding it is good enough, but still needs to be done.

**Comment by JonathanMeler** [comment]
I'm returning the result of the api as is:
' demisto.results(demisto.executeCommand('atd-get-report',{'taskId':taskID, 'type' : reportType}))'
The api call is from the integration, it contains human-readable and context.

I'll add declarations to the script

**Comment by Spivaka** [comment]
@JonathanMeler add and I'll approve and merge

**Comment by Spivaka** [comment]
@JonathanMeler ???

**Comment by JonathanMeler** [comment]
@Spivaka sorry for the delay. please review the changes (the output was copied from the original integration api-command)

**Pull request merged**
