### PR TITLE
Code42: Mirror of external contributor PR 

### PR DESCRIPTION
**Pull request by ilappe**
Link to original contribution PR: https://github.com/demisto/content/pull/19418
this PR was stock on the Contributor License Agreement (CLA) due to it contained commits from old user which not sign the agreement but leave the contributor company 
so we close the original PR and reflect the changes here

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Adds support for API Client auth and deprecates Username/Password auth
- Adds commands to interact with Code42 Watchlists, and deprecates the High Risk Employee and Departing Employee commands (which Watchlists has replaced)
- Adds Code42 Alert Incident Mapping for version 6.0+
- Updated to use latest py42 docker image

## Screenshots
Screen Shot 2022-06-06 at 3 34 26 PM
Screen Shot 2022-06-06 at 3 38 05 PM

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [X] Yes
       - Username/password authentication has been replaced with API Client authentication to better apply principles of least privilege for integration authorizations.
   - [ ] No

## Must have
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by timabrmsn** [comment]
@ilappe what's the process for this getting to the marketplace? Is it once this is approved/merged it goes live right away?

**Comment by ilappe** [comment]
@timabrmsn 
yes - once it's approved/merged it will be available in marketplace ~ in a few hours (our upload task will upload it's from maser to marketplace)
i work on this PR as it contains some errors
may be we will need your help here :)

**Comment by timabrmsn** [comment]
@ilappe I don't think this PR has all of the commits from my branch, the `demisto.log` usages that lint is failing were removed in my branch.

**Comment by timabrmsn** [comment]
@ilappe anything I can help with to keep this moving forward?

**Comment by ilappe** [comment]
@timabrmsn 
very sorry for that 
i was busy with other tasks
i hope to handle it in this week ASAP

**Comment by ilappe** [comment]
@timabrmsn 
[the validation error ](https://app.circleci.com/pipelines/github/demisto/content/180770/workflows/498fb287-abbd-4fde-b537-362008101876/jobs/550072?invite=true#step-108-230)
mentioned that the deprecated commands are used in some playbook in the pack Code42InsiderThreatRemediation
can you please update them and push it to the original PR ?

**Comment by timabrmsn** [comment]
@ilappe I have pushed new changes to the original PR to support the updates to the paid pack (to maintain the same functionality in the playbook, I needed to add another command `code42-user-update-risk-profile` to the main PR. 

The paid pack update PR here: https://github.com/code42/xsoar-paid-packs/pull/20

The build is failing for some reason, but linting/formatting passed locally. Looking at the github action it seems like it's a basic template that should be customized to our pack, but previous CI runs in this repo worked, and it doesn't seem like the file has changed at all. So I'm not sure what needs to be done there.

**Comment by timabrmsn** [comment]
@ilappe I got the paid pack CI running, but now the linting is failing: 

```
Error: : Packs/Code42InsiderThreatRemediation/Playbooks/playbook-Code42_Suspicious_Activity_Action.yml: [PB107] - in task ordereddict([('id', '4ba7f898-da96-4b17-8978-16a24f80f628'), ('version', -1), ('name', 'Add User to Watchlist'), ('description', 'Add a user to a watchlist.'), ('script', '|||code42-watchlists-add-user'), ('type', 'regular'), ('iscommand', True), ('brand', '')]) the script |||code42-watchlists-add-user was not found in the id_set.json file. Please make sure:
[93](https://github.com/code42/xsoar-paid-packs/runs/7773738103?check_suite_focus=true#step:12:94)
1 - The right script id is set and the spelling is correct.
[94](https://github.com/code42/xsoar-paid-packs/runs/7773738103?check_suite_focus=true#step:12:95)
2 - The id_set.json file is up to date. Delete the file by running: rm -rf Tests/id_set.json and rerun the command.
```

I'm not sure what it expects here, is it because the new core Code42 pack with the watchlist commands hasn't been released yet? If so, it seems we're in a dependency loop, where we can't release Code42 3.0 because the paid pack uses deprecated methods, but we can't update the paid pack because the core integration hasn't been updated...

**Comment by ilappe** [comment]
@timabrmsn 
ok i will accept your changes here 
and we will see the results, if is due to dependency loop may be we will force merge it
thanks

**Review by yaakovi — APPROVED** [review]

**Comment by timabrmsn** [comment]
@ilappe is this waiting on anything on my end?

**Comment by ilappe** [comment]
@timabrmsn 
sorry for that - again i was busy  with other tasks and there was a credentials problem in the build system 
i fixed the credentials issue
will try to merge it ASAP

**Comment by ilappe** [comment]
@timabrmsn 
done!
thanks for your efforts!
so i think you should be able to merge your paid pack

**Comment by timabrmsn** [comment]
@ilappe was there a problem discovered after the merge?

**Comment by ilappe** [comment]
Hi @timabrmsn 
yes, due to the paid pack - our build is failed 

we will need do the following:

1. rolled bace the command deprecation in Code42
2. merged this (including the new commands)
3. you should be able to merged the change in the paid pack 
4. open new pr for deprecate the commands in Code42

make sense ?

**Comment by timabrmsn** [comment]
Yeah, that makes sense. Is that a change you're making or should I make?

**Comment by ilappe** [comment]
@timabrmsn 
you - please remove the deprecation (make them not deprecated)
i will merge them
you - to merge the paid pack & after that re deprecate the commands
please do it via the https://github.com/demisto/content/pull/19418 original pr

**Pull request merged**
