### PR TITLE
Get User Manager Details - Fixed input check + error handling

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/23164

## Description
Improved error handling for the playbook and fixed an issue where it failed if no inputs existed (no username nor email)

## Screenshots
image

## Minimum version of Demisto
4.5.0

## Does it break backward compatibility?
No

## Must have
- [x] Tests
- [ ] Code Review

### CODE REVIEW

**Comment by kirbles19** [comment]
@idovandijk Done.

**Comment by idovandijk** [comment]
Build will keep failing until this is fixed https://github.com/demisto/etc/issues/21383

**Comment by idovandijk** [comment]
Fails due to ExtraHop test that failed. Our license expired. Now waiting to see if we can get a new license, otherwise I will skip their test.

**Comment by idovandijk** [comment]
Skipped ExtraHop-Test for now

**Pull request merged**
