### PR TITLE
Updates accommodating for Critical Assets field in Phishing

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19297

## Description
- Added a Critical Assets field of type "grid". The field will display critical assets that were involved in the incident
- Added a script to populate grid of `Critical Assets` with data (thanks @orenzohar)
- Updated `Calculate Severity - Critical Assets v2` to use the new script
- Updated the test playbook `Calculate Severity - Generic v2 - Test` to include data for critical assets
- Added the field to the layout of phishing incidents for version 4.5
- Added a fix for the hooks

## Screenshots
image

## Required version of Demisto
4.5

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation (with link to it)
- [x] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [x] [YAML file](https://github.com/demisto/content/blob/92391d2dcfca43151d47079c5d06073ea767033f/IncidentFields/incidentfield-criticalassets.json) line 8
- [x] [YAML file](https://github.com/demisto/content/blob/92391d2dcfca43151d47079c5d06073ea767033f/Scripts/PopulateCriticalAssets/PopulateCriticalAssets.yml) lines 5 and 14-15
- [x] [JSON file](https://github.com/demisto/content/blob/92391d2dcfca43151d47079c5d06073ea767033f/Layouts/layout-details-Phishing_4_5_0.json) line 99
- [x] [CHANGELOG](https://github.com/demisto/content/blob/92391d2dcfca43151d47079c5d06073ea767033f/Layouts/layout-details-Phishing_4_5_0_CHANGELOG.md)
- [x] [CHANGELOG](https://github.com/demisto/content/blob/92391d2dcfca43151d47079c5d06073ea767033f/Playbooks/playbook-Calculate_Severity_-_Critical_Assets_v2_CHANGELOG.md)

### CODE REVIEW

**Comment by idovandijk** [comment]
@yuvalbenshalom I set you as a reviewer for the script only. The reason for this is because @orenzohar helped with this script so it wouldn't make sense for him to review it.

**Comment by idovandijk** [comment]
@yaakovi reviewed instead of @yuvalbenshalom. Disregard my previous comment

**Comment by yaron-libman** [comment]
TW review complete.

**Comment by idovandijk** [comment]
Build is failing because master is broken

**Pull request merged**
