### PR TITLE
Json generic readme

### PR DESCRIPTION
**Pull request by teizenman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

### CODE REVIEW

**Comment by teizenman** [comment]
@kirbles19 Can you please go over the ReadMe file?

**Comment by teizenman** [comment]
@kirbles19 Can you please go over the ReadMe file?

**Comment by kirbles19** [comment]
@teizenman Done, ready to publish

**Comment by glicht** [comment]
@teizenman I've update the doc to use video. You can see a preview at: https://deploy-preview-94--demisto-content-docs.netlify.com/docs/reference/integrations/json-feed

Still working on documenting the process in our content-docs repo.

**Pull request merged**
