### PR TITLE
fixes for Cymulate integration. Since I am uploading from private rep…

### PR DESCRIPTION
**Pull request by micioffe**
…o you are welcome to contact me at michaeli@cymulate.com to verify my identity. Regards, Michael

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by mmhw** [comment]
> [CLA assistant check](https://cla-assistant.io/demisto/content?pullRequest=27910) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=27910) before we can accept your contribution.
> 
> **michael** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=27910) it.

Hi @micioffe,
Thank you for your contribution we appreciate your effort.
In order for me to start review your PR please fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA).

**Comment by mmhw** [comment]
Hi @micioffe,
Thank you for your contribution!
Good work :)

Note that the arguments you added to the commands in the Python file must also be added in the YML file.

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by micioffe** [comment]
Hi
Added yaml file.
The form I recall filling up a couple of days ago, do you need me to fill it again?
#copied response to email as well

**Comment by mmhw** [comment]
> Hi Added yaml file. The form I recall filling up a couple of days ago, do you need me to fill it again? #copied response to email as well

Hi @micioffe ,
The form is fine. You just have to sign the [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=27910).

**Comment by mmhw** [comment]
Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes -i Packs/Cymulate` command - for more information please see `[here](https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes)`.

**Comment by micioffe** [comment]
> > Hi Added yaml file. The form I recall filling up a couple of days ago, do you need me to fill it again? #copied response to email as well
> 
> Hi @micioffe , The form is fine. You just have to sign the [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=27910).

Hello guys. Answered to you by mail, provided screenshots. I really can't understand what exactly is the problem with cla, since I see it as signed, as shown on screenshots.
Tried to re-login from different machine as well-same result.
Could we may be schedule a video conversation/phone call?
Meanwhile, since this week I am on vacation, please refer your answer to Yahav Levin: yahavl@cymulate.com

**Comment by mmhw** [comment]
Hi @micioffe,

I replied to you on Slack, are you available there?

**Comment by micioffe** [comment]
Hi.
I am but I haven't seen your reply.
Anyhow-I am on vacation this week, so contact Yahav Levin instead. yahavl@
cymulate.com

**Comment by mmhw** [comment]
Hi @micioffe,
Note that the signature on your [commits](https://github.com/demisto/content/pull/27910/commits) is `michael`, but the username you opened the PR with is `micioffe`, and this is what causes the problem with the `CLA`.
Please open a new PR.

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Pull request closed without merging**
