### PR TITLE
doc-howto - Moving docs to Base pack

### PR DESCRIPTION
**Pull request by reutshal**
## Status
- [X] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
relates: https://github.com/demisto/etc/issues/25169
relates: https://github.com/demisto/demisto-sdk/pull/518

## Description
Moved the Documentation dir under Base pack so it will be detected and upload to the bucket

** Didn't test yet since sdk is currently breaking content so linking to the sdk change is breaking the build

### CODE REVIEW

**Comment by anara123** [comment]
@reutshal make sure that all the scripts are not in the Base.zip pack artifact in marketplace 
image

**Comment by reutshal** [comment]
> @reutshal make sure that all the scripts are not in the Base.zip pack artifact in marketplace
> image

@anara123 Yes, I'm deleting them in the sdk PR

**Comment by anara123** [comment]
@reutshal what is the status here?

**Comment by reutshal** [comment]
@anara123 this fix did not work as it turns out the problem was related to the `collect_tests_and_content_packs` scripts.
Closing as another PR is open https://github.com/demisto/content/pull/7477

**Pull request closed without merging**
