### PR TITLE
EWS - Security&Compliance - Search Action Limit Fix

### PR DESCRIPTION
**Pull request by darkushin**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34416

## Description
Fixed an issue where using the `limit` parameter with value -1 in the `O365-sc-get-search-action` command resulted in an error.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by darkushin** [comment]
@GalRabin @yaakovi As can be seen in the screenshot, when the user asks to export the results file to the war room, we create a file containing all the results even if the user has set a limit. Is this on purpose or should I change it to the limit set by the user?
Same applies also to the `GetSearchActionCommand` function.
image

**Review by yuvalbenshalom — COMMENTED** [review]
looks ok for me
@yaakovi please take a look too

**Comment by GalRabin** [comment]
> @GalRabin @yaakovi As can be seen in the screenshot, when the user asks to export the results file to the war room, we create a file containing all the results even if the user has set a limit. Is this on purpose or should I change it to the limit set by the user?
> Same applies also to the `GetSearchActionCommand` function.
> image

Its not in purpose its a bug , You right.
Thanks!

**Review by GalRabin — COMMENTED** [review]
Its not in purpose its a bug , You right.
Thanks!

**Review by yaakovi — APPROVED** [review]
validate is failing on an SDK issue, @yuvalbenshalom force-merge when ready.

**Pull request merged**
