### PR TITLE
Cybereason v2.1.13

### PR DESCRIPTION
**Pull request by shabina-metron**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added a new command fetch-machine-details. 

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by sapirshuker** [comment]
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @sapirshuker will know the proposed changes are ready to be reviewed. For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

Hi @shabina-metron ,
Thank you for your contribution. 
I will review your PR soon.
In the meantime, please fill in the following registration form: [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA).
and sign on the the contributions SLAs document(https://xsoar.pan.dev/docs/contributing/sla).
I'm available for any of your questions here or on slack.
Thanks again.

**Comment by shabina-metron** [comment]
Hi @sapirshuker,

Thank you for getting back to me.
I have filled out the contribution registration form and signed the contributions SLAs document.

Please let me know if there are any questions.

Thanks.

**Comment by shabina-metron** [comment]
Hi @sapirshuker,
Thank you for your comments.
We are working on it and we shall update you once done.

Thanks

**Comment by sapirshuker** [comment]
Hey, @shabina-metron 
Thank you, I am waiting for your update.
Please note that I sent you a mail regarding to this PR.
Thanks

**Comment by shabina-metron** [comment]
Created a new PR. Closing this one.

**Pull request closed without merging**
