### PR TITLE
[greynoise-266] Update dockerfile to support latest GreyNoise SDK

### PR DESCRIPTION
**Pull request by bradchiappetta**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: N/A

## Description
A few sentences describing the overall goals of the pull request's commits.

This is update the Pack to use an updated docker image, which includes an update to the GreyNoise SDK.

## Screenshots
Paste here any images that will help the reviewer

The SDK now prevents non-routable IPs from being sent to the GreyNoise API and reports the error to the client:

image

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ostolero** [comment]
Hi Brad, I see this is still marked as a draft, is it ready for review?

**Comment by bradchiappetta** [comment]
I am currently waiting for the dockerfile update that is associated with
this to be approved and merged, then I will be able to update this and it
will be ready.

**Comment by bradchiappetta** [comment]
@ostolero : not sure if you can help push through https://github.com/demisto/dockerfiles/pull/6725, that's the gating factor for getting this finished.  Thanks.

**Comment by ostolero** [comment]
Hey Brad, Yes I'll review the SDK pr as well, will update soon.

**Comment by ostolero** [comment]
Hey Brad, I see the pr was just merged! so you can add any final changes you need.
Also please make sure the integrations affected by the new docker work as expected, as the versions of the upgraded packages may change functionality for some actions.

**Comment by bradchiappetta** [comment]
@ostolero : PR has been updated and changes verified.  The big change here is the SDK now prevents non-routable IPs from being sent to our API and just returns an error instead.  I've included a screenshot example of what an invalid lookup looks like, which appears consistent with some of the other packs.  Please let me know if you see any issues or need any other changes.

**Review by ostolero — APPROVED** [review]
All looks good!

**Pull request merged**
