### PR TITLE
Change widgets to list like in the default dashboard

### PR DESCRIPTION
**Pull request by orius123**
Changed late incidents and unassigned incidents to list widget like they are in the default dashboard instead of table widgets

### CODE REVIEW

**Comment by orius123** [comment]
@Bars92 please review default dashboard

**Comment by Bars92** [comment]
@orius123 you are missing a few things.. few seconds i will upload and let me know what you think

**Comment by Bars92** [comment]
[Incidents (3).json.txt](https://github.com/demisto/content/files/1685405/Incidents.3.json.txt)
Try this @orius123

**Comment by Bars92** [comment]
image

**Comment by meirwah** [comment]
@orius123 can we merge thiS?

**Comment by orius123** [comment]
@Bars92 I think it is better if each number is above it's list (unassigned incidents, late incidents, late tasks). WDYT?

**Comment by orius123** [comment]
Maybe this?
image

**Comment by orius123** [comment]
@Bars92 pushed my version, please merge unless you have objections

**Comment by meirwah** [comment]
@Bars92 @orius123 merging, plz revert if you think any issue

**Pull request merged**
