### PR TITLE
Add REN-ISAC Integration

### PR DESCRIPTION
**Pull request by PaulBartruff**
## REN-ISAC
PR to add a REN-ISAC Integration

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Details
REN-ISAC provides a curated intel feed for the Research and Engineering ISAC (Higher Ed).  

## Minimum version of Cortex XSOAR
- [X] 6.8.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by michal-dagan — COMMENTED** [review]
Hi @PaulBartruff, Thanks for the contribution! Great work!
Before I begin reviewing the code, please address my comments:
1. please delete these files:
Packs/REN-ISAC/Integrations/Cifv3/integration-Cifv3.yml
Packs/REN-ISAC/Integrations/Cifv3/test_data/baseintegration-dummy.json
Packs/REN-ISAC/Integrations/Cifv3/Pipfile.lock
Packs/REN-ISAC/Integrations/Cifv3/Pipfile

2. please update the image:`Packs/REN-ISAC/Author_image.png` failed on `Unable to render rich display
Invalid image source.`
maybe use this picture : Packs/REN-ISAC/Integrations/Cifv3/Cifv3_image.png
as the the Packs/REN-ISAC/Author_image.png

3. Please update the **CIFv3** integration to match our standard of feed integrations: https://xsoar.pan.dev/docs/integrations/feeds

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by PaulBartruff** [comment]
Completed Step 3
Regarding PR #27150 Step 3:
 
- Added 'fromversion'
- Appended 'feed' to id, name, and display
- Modified Indicator Reputation to list only 4 options
- Changed 'display' to be the head of a yaml, list instead of the alphabetically first value
- Ensured required parameters are accurate
- Validated required command names
- Validated use of 'demisto.createIndicators' command
- Validated indicator object contains all 'Required' elements

**Review by michal-dagan — CHANGES_REQUESTED** [review]
Hi @PaulBartruff ,
Great work!!!
First of all, sorry for the extra commits, @ilaner  ooked into why one step failed on the PR.
Please see my comments:
1. The pack name should also start with `FeedCifv3`
2. If you don't want to add unit tests - please delete the file Packs/REN-ISAC/Integrations/Cifv3/Cifv3_test.py
3. please generate the README file from your integration YML file using the `demisto-sdk generate-docs` command. See - https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_docs/README.md

4. the secrets step failed on https://app.circleci.com/pipelines/github/demisto/content/267952/workflows/a144acdc-9fa9-44d6-9137-13059d55e825/jobs/703951/parallel-runs/0/steps/0-118
As this is not a secret, please add this to the packs's .secrets-ignore file. See - https://xsoar.pan.dev/docs/concepts/demisto-sdk#ignoring-secrets

5. please update the docker image:  `demisto-sdk format -ud -i Packs/REN-ISAC/Integrations/Cifv3/Cifv3.yml`

6. please resize the image dimensions, failed on: `[ERROR][INFO] : Packs/REN-ISAC/Integrations/Cifv3/Cifv3_image.png: [IM111] - The image dimensions are 120x33. The requirements are 120x50.`

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by michal-dagan** [comment]
Hi @PaulBartruff,
Haven’t heard from you since I published my review.
Do you need any help with something?
Please don’t hesitate to reach out to me here or on Slack.
Thanks again.

**Comment by michal-dagan** [comment]
Hi @PaulBartruff,
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

**Pull request closed without merging**
