### PR TITLE
add to context outputs of get-issue and get-issue-evidence

### PR DESCRIPTION
**Pull request by fjfernandezj-san**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by israelpoli — COMMENTED** [review]
Hi @fjfernandezj-san thank you for your contribution
see below comments

**Comment by fjfernandezj-san** [comment]
Hi Israel, i made the changes that you say me. Tell me if i have any error. The output of the commands are this and inside it, all content:
image

**Comment by kgal-pan** [comment]
@fjfernandezj-san - Since this is a Partner-supported Pack, we'll need the Wiz team to review it and approve the changes.

@solalraveh @ariel-wiz @yanivblumWiz  - Can you please review this contribution and add the `Partner-Approved` label if you approve of it?

**Comment by yanivblumWiz** [comment]
Hi @kgal-pan, we do not approve contributions to our code that are not done by Wiz developers. So please close this PR

@fjfernandezj-san Thanks for all the effort. We will definitely add your comments to our next version

Thank you all for all the help

**Pull request closed without merging**
