### PR TITLE
Add section_start and section_end helper functions

### PR DESCRIPTION
**Pull request by avidan-H**
## Status
- [x] Ready

## Description
Enables the use of `section_start` and `section_end` bash functions for collapsible sections in GitLab job logs as detailed [here](https://docs.gitlab.com/ee/ci/jobs/index.html#custom-collapsible-sections).

## Screenshots
image

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by avidan-H** [comment]
Adding the `docs-approved` label since there is no documentation that requires review.

**Comment by hod-alpert** [comment]
Noice

**Review by hod-alpert — APPROVED** [review]

**Review by DinaMeylakh — APPROVED** [review]
Cool stuff

**Comment by avidan-H** [comment]
Merging despite the GitLab run being red because it fails on artifactory-related issues.

**Pull request merged**
