### PR TITLE
detection source for fetch incident

### PR DESCRIPTION
**Pull request by ckaadic**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added fetch incidents filter by detection source.

## Screenshots
grafik

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by esharf** [comment]
Hey @ckaadic.
First thing, thanks for your contribution. we appreciate your effort.
Second thing, it seems that you changed the file `Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.yml` unintentionally, can you please fix it so i will be able to review your PR?

**Comment by ckaadic** [comment]
hi @esharf demisto-sdk validate returned an error for the file and asked me to run the format with -ud flag to push the dockes version. I can revert the change but the pipeline will show the error here afterwards. What do you want me to do?

**Comment by esharf** [comment]
@ckaadic let’s revert this change and i will handle the validation error

**Comment by ckaadic** [comment]
@esharf reverted changes to said file

**Comment by esharf** [comment]
@ckaadic looks good.
please add unit tests (example [here](https://github.com/demisto/content/blob/master/Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py#L1340)).
and let’s schedule a demo in [DFIR](https://dfircommunity.slack.com/team/UQWL4FQJ0).

**Comment by ckaadic** [comment]
@esharf Tried to contact you in DFIR, but got no response so far

**Review by esharf — APPROVED** [review]

**Pull request merged**
