### PR TITLE
EWS O365 body logic

### PR DESCRIPTION
**Pull request by teizenman**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29622

## Description
According to the standard of `send-mail` when`htmlBody` is provided, the `body` arg is disregarded.
Tested as many integrations with `send-mail` that I could, and went over the logic of the rest and they look fine.

### CODE REVIEW

**Review by ronykoz — APPROVED** [review]
@anara123 what do you think, will it break BC?

**Comment by anara123** [comment]
in this case body contains the extra stuff at the top of the mail that causes the issue?

**Comment by teizenman** [comment]
@anara123 
Yes, this should be ignored as the rest of the send-mail commands.

**Comment by anara123** [comment]
@teizenman ok, lets merge

**Pull request merged**
