### PR TITLE
Update MicrosoftTeams_description.md

### PR DESCRIPTION
**Pull request by tschanfeld**
changed link url from support.demisto.com page to  https://xsoar.pan.dev/docs/reference/integrations/microsoft-teams

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by Bharathwaj-Murali — APPROVED** [review]

**Review by reutshal — APPROVED** [review]
Please run `demisto-sdk update-release-notes -i Packs/MicrosoftTeams -u (major|minor|revision|documentation)` to generate release notes.

**Review by tschanfeld — COMMENTED** [review]
rewrite

**Review by tschanfeld — COMMENTED** [review]
deleted sentence

**Review by reutshal — APPROVED** [review]

**Comment by tschanfeld** [comment]
@reutshal 'ci/gitlab/code.pan.run — Pipeline failed on GitLab' ??

**Pull request merged**
