### PR TITLE
AWS Api Module - Change parameter name

### PR DESCRIPTION
**Pull request by mmhw**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
No changes were made to the code, except for changing the **name** of the function and the parameters

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by bziser — COMMENTED** [review]
Looks good
Let's add RN to all the packs that need:
`Fixed a typo in **AWSApiModule**.`

**Review by jieliau — COMMENTED** [review]
Am I eligible to review and approve it?

**Comment by bziser** [comment]
@jieliau It's a minor change, you are welcome to review it

**Review by jieliau — COMMENTED** [review]
I have no concern with the changes.

**Review by bziser — APPROVED** [review]

**Pull request merged**
