### PR TITLE
Modified README.md for well-formatted style.

### PR DESCRIPTION
**Pull request by spearmin10**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Modified README.md for well-formatted style.

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by abaumgarten** [comment]
@spearmin10 Hi! I think that your new readme is not in the correct place. It should be in `Packs/MapPattern/Scripts/MapPattern/README.md` and not in `Packs/MapPattern/README.md`. 
Please change it and then it will be ready for merge.

**Comment by spearmin10** [comment]
@abaumgarten The details view of `MapPattern` is currently like this:
image

I would like to make it change like this. Could you let me know where and how can I modify the README?
image

**Comment by abaumgarten** [comment]
@spearmin10 Ok got you, so please read this https://xsoar.pan.dev/docs/documentation/pack-docs#pack-readme and update your pack readme file to include the content that should appear in such a file (under `Each pack readme should contain` in the above link). thanks.

**Comment by spearmin10** [comment]
@abaumgarten Sorry, I'm not sure how I modify the Scripts/MapPattern/README.md for the pack summary shown in XSOAR.
As far as I've looked over other packs, it looks ./README.md has the pack summary, not Scripts/xxx/README.md.
There doesn't seem to have the instructions at https://xsoar.pan.dev/docs/documentation/pack-docs#pack-readme.
Please let me know how to make README for the summary page.

**Comment by spearmin10** [comment]
@abaumgarten  I've added `What does this pack do?`

**Review by abaumgarten — APPROVED** [review]

**Pull request merged**
