### PR TITLE
EXPANDR-7735 - add EV2 core packs

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-7735

## Description
Adding Xpanse core packs that have been delayed since: https://jira-dc.paloaltonetworks.com/browse/CRTX-101923

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@anas-yousef , we need to be really careful for this PR because it caused a p1 before.  Any ideas why the `Setup Environment` build stage is failing?  Seeing same failure on another [PR](https://github.com/demisto/content/pull/34121)

**Comment by anas-yousef** [comment]
@johnnywilkes
Concerning the **Setup Environment** step, run the script [./Utils/git_pull_master_into_fork.sh](https://github.com/demisto/content/blob/master/Utils/git_pull_master_into_fork.sh) in your repo, and push the changes to.

**Comment by johnnywilkes** [comment]
> ./Utils/git_pull_master_into_fork.sh

This is what I get:
`Switched to branch 'master'
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Successfully rebased and updated refs/heads/master.
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/PaloAltoNetworks/xpanse-content.git
   15f513c075..b1b4abf247  master -> master
Switched to branch 'CORE-PACKS-EXPANDR-7735'
Your branch is up to date with 'origin/CORE-PACKS-EXPANDR-7735'.
From https://github.com/PaloAltoNetworks/xpanse-content
 * branch                  master     -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.`

**Comment by johnnywilkes** [comment]
@ShahafBenYakir , you mentioned in https://jira-dc.paloaltonetworks.com/browse/CRTX-101923 that we could get a custom marketplace from build.  That is form internal PR, right?

@anas-yousef , please continue merge but let us test before you merge the internal PR

**Comment by ShahafBenYakir** [comment]
@anas-yousef please help @johnnywilkes get the relevant bucket URL from Gitlab for them to test

**Review by anas-yousef — APPROVED** [review]

**Pull request merged**
