### PR TITLE
Maintain "New" tag in packs

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/27133

will merge after: https://github.com/demisto/content/pull/11302 is merged

## Description
Maintain "New" tag in packs. 

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests

### CODE REVIEW

**Comment by ohaim1008** [comment]
@guyfreund @bakatzir fixed and ready, please review.

**Comment by bakatzir** [comment]
@ohaim1008 So it will be added/removed in the `upload_packs.py` process and will be invisible to the dev, correct?

@glicht -  Do we want it all on packs? or only on XSOAR and Partner?

Also - please try to attach a video or let's set a short demo, I would like to see the updated pack_metadata in the bucket.

**Review by guyfreund — COMMENTED** [review]
@ohaim1008 please attach a successful upload run

**Comment by glicht** [comment]
> @glicht - Do we want it all on packs? or only on XSOAR and Partner?

All packs.

**Comment by ohaim1008** [comment]
Test upload in - 
https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/upload-metadata/262156

In this test you can see that a new pack's metadata of a recently created pack will have the `New` tag:
image
- it doesn't exists in other packs that their creation time in longer than 30 days ago.

I added "New" to the valid approved tags.
@guyfreund @bakatzir

**Review by guyfreund — APPROVED** [review]
Nice 👏

**Review by guyfreund — COMMENTED** [review]
I'd add a ut for the case of a pack that has the `New` tag and is < 30 days old.

**Comment by ohaim1008** [comment]
@guyfreund @yuvalbenshalom @glicht After fixing the dates, the new test bucket index is in the issue, it looks ok now.

**Review by yuvalbenshalom — APPROVED** [review]

**Pull request merged**
