### PR TITLE
Add support for marking emails as read

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
CIAC-4097 (partially)

## Description
Add the following to the Microsoft Graph Mail integration:
- Boolean parameter to optionally mark fetched emails as read
- Command `msgraph-mail-mark-as-read` to mark an email as read or unread

## Screenshots
Screen Shot 2022-10-18 at 8 24 45 PM

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by bakatzir** [comment]
Thanks Ali,
I think we still need to have the boolean parameter to mark emails as read when fetched which I do not se in the `yml` in the latest commit, not sure if this is by intent or not.
in any case, @dorschw is aware of this PR and will expedite this.

**Comment by moishce** [comment]
@ali-sawyer It looks great
However, you are probably not up-to-date with Master
It seems that there are changes that are not yours in the PR, and the build also fails for this.

**Comment by ali-sawyer** [comment]
@moishce got it, that makes sense, I made this change a few weeks ago so it was based on a slightly older version of the integration. I probably won't get a chance to fix this until next week.

**Comment by moishce** [comment]
Hi, @ali-sawyer,
Haven’t heard from you,
Do you need any help?
Please don’t hesitate to reach out to me here or on Slack.
Thanks again.

**Comment by moishce** [comment]
Hi @ali-sawyer, 
Thank you for your contribution. 
I have not received a response from you, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

**Pull request closed without merging**
