### PR TITLE
Updated file reputations and added indicator fields

### PR DESCRIPTION
**Pull request by hirshbergshachar**
## Status
Ready

## Related Issues
https://github.com/demisto/etc/issues/16089

## Description
Added the unified file reputation and several indicator fields

branch | PR
------ | ------
https://github.com/demisto/server/pull/12930
https://github.com/demisto/web-client/pull/5002

## Does it break backward compatibility?
   - Yes
       - Further details: in the issue - https://github.com/demisto/etc/issues/16089

### CODE REVIEW

**Comment by yaakovi** [comment]
@kirbles19 
need to go over the RN only (end of each file).
@hirshbergshachar will supply more details on the changes.

**Comment by hirshbergshachar** [comment]
@kirbles19 please add your comments here

**Comment by kirbles19** [comment]
@hirshbergshachar I can't tell just from looking at the JSON files what was added/changed, so not sure what to add to release notes. What exactly was done?

**Comment by hirshbergshachar** [comment]
@kirbles19 I added four new fields for indicators and added a new indicator type.

**Comment by kirbles19** [comment]
Which ones....

**Comment by hirshbergshachar** [comment]
@kirbles19

**Comment by kirbles19** [comment]
All RN descriptions updated.

**Pull request merged**
