### PR TITLE
Adds appNovi content pack

### PR DESCRIPTION
**Pull request by kfreezen**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
This submits appNovi's first content pack and integration for Cortex XSOAR. Includes one playbook and one integration.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ShacharKidor** [comment]
Hi @kfreezen, 
Thank you for your contribution!

Please fill in the following registration form so @yaakovi could start the review: 

> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @YuvHayun will know he can start review the proposed changes.

You can also try to solve the errors in the [573401](https://app.circleci.com/pipelines/github/demisto/content/193291/workflows/5b774b77-c8d1-4057-85d3-6be2638144e6/jobs/573401).

Thanks again.

**Comment by kfreezen** [comment]
Hi @ShacharKidor, we're working on some stuff we had missing, like a README for the pack. Will also try to get that contribution form filled out today!

**Comment by ShacharKidor** [comment]
> Hi @ShacharKidor, we're working on some stuff we had missing, like a README for the pack. Will also try to get that contribution form filled out today!

@kfreezen - OK great! please let us know when the PR is ready for review :)

**Comment by ShacharKidor** [comment]
Hi @kfreezen, 
We haven't heard from you for a while... Can we help you with something? 
 Is the PR ready for review? 

I also would like to remind you to fill in the above registration form.

Thank you.

FYI - @marcellarichmond.

**Comment by kfreezen** [comment]
Hi @ShacharKidor this PR is ready for review.

**Comment by ShacharKidor** [comment]
Hi @kfreezen, 
Thanks for the update - our team will start the review in the next few days.

Thanks again.

**Review by DeanArbel — CHANGES_REQUESTED** [review]
Thank you very much for your contribution. The PR looks great, I have a few comments below. Please review them.

I'd like to set up a demo meeting with you and @idovandijk next week.
When would be an appropriate time for you?

**Comment by kfreezen** [comment]
> Thank you very much for your contribution. The PR looks great, I have a few comments below. Please review them.
> 
> I'd like to set up a demo meeting with you and @idovandijk next week. When would be an appropriate time for you?

Pretty flexible. Just send me an email at kent@appnovi.net and I'll add the relevant people from my side.

**Comment by dorschw** [comment]
hi, please merge from demiso/origin/master so the CI can run, thanks

**Review by idovandijk — DISMISSED** [review]
Hi @kfreezen, I reviewed your fixes. Looks good but there's still one part that's missing.
Task 1 expects a mandatory input which is not satisfied:
image

What is the expected input for that task?

**Comment by dorschw** [comment]
Hi, please check the [CI error](https://app.circleci.com/pipelines/github/demisto/content/206789/workflows/42151642-8f64-481b-8a99-b07072725e79/jobs/597592?invite=true#step-103-57) and merge from content `origin/master` so we can approve it.

**Comment by dorschw** [comment]
Hi, please fix the issue mentioned in CircleCI (change the docker version, under the integration's yaml, to `3.10.8.37233`), and answer @idovandijk's comment above so we can proceed. Let us know if you have any questions, we're available over DFIR

**Comment by kfreezen** [comment]
@idovandijk The expected input is an 'identity' object created with the MAC Address in the incident.

**Comment by idovandijk** [comment]
> @idovandijk The expected input is an 'identity' object created with the MAC Address in the incident.

@kfreezen can you please fill in that data in the task?

**Comment by kfreezen** [comment]
@idovandijk is this the information that needs to be filled out?
image

**Comment by idovandijk** [comment]
> @idovandijk is this the information that needs to be filled out? image

Yes. I've verified and the playbook YML is correct. I see that it works on XSOAR but there's an issue in XSIAM which I'm going to check internally.

@dorschw @DeanArbel please see this as approved from my side, if there are no code change requirements - feel free to approve.
Thanks again @kfreezen for the clarification here.

**Review by dorschw — APPROVED** [review]

**Pull request merged**
