### PR TITLE
Fixing adding indicators to the context data

### PR DESCRIPTION
**Pull request by hod-alpert**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/24849

## Description
Indicator has no ID attribute, the actual value comes in `Value` field which should be the unique field.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Documentation

### CODE REVIEW

**Comment by dantavori** [comment]
what if you have two indicators, say a URL with the value `https://www.google.com` and a string with the same value? @Arsenikr can you confirm/deny this case is extreme?

**Comment by Arsenikr** [comment]
> what if you have two indicators, say a URL with the value `https://www.google.com` and a string with the same value? @Arsenikr can you confirm/deny this case is extreme?

if the value is the same it is the same indicator i guess.. am i missing something here?

**Comment by hod-alpert** [comment]
He meant if there are two indicators with the same value but with different types
Anyways we agreed that there is no issue here since id the indicator has an ID it will be added to the context, and if it does not- then it's probably the same indicator.

**Comment by kirbles19** [comment]
@hod-alpert @Itay4 Done.

**Pull request merged**
