### PR TITLE
delete old XFE pack and fix test playbook

### PR DESCRIPTION
**Pull request by anara123**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22715

## Description
Deletes old XFE pack. There were 2 XFE packs with the same name.
Now there is one. Deprecated the old XFE integration. Deleted it's test playbook.
Updated the new Test_XFE_v2 playbook.

## Screenshots
Test_XFE_v2_Wed_Jul_08_2020

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
- Let's remove the test from conf entirely (from skip and this entry: https://github.com/demisto/content/blob/1e41f0dd6232721473669eeae74c06ea74bd49f1/Tests/conf.json#L1690) 
- How did you manage to fix and run the test for XFE v2? I thought we don't have an instance

**Comment by Itay4** [comment]
@anara123 what is the status here?

**Comment by anara123** [comment]
@Itay4 don't remember why I didn't merged. Will try to push it again

**Comment by anara123** [comment]
closing - opened new PR https://github.com/demisto/content/pull/9025

**Pull request closed without merging**
