### PR TITLE
Wiz v1.1.0

### PR DESCRIPTION
**Pull request by solalraveh**
~~DRAFT. IN PROGRESS. PANW team, please don't review yet, we'll update via CS and Slack once ready.~~
We're PR-ing it, so the unit testing report os generated again (previous one expired). We're now working on it.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

#### Commands
- Added `wiz-issue-in-progress` command. See docs for usage.
- Added `wiz-reopen-issue` command. See docs for usage.
- Added `wiz-reject-issue` command. See docs for usage.
- Added `wiz-set-issue-note` command. See docs for usage.
- Added `wiz-clear-issue-note` command. See docs for usage.
- Added `wiz-get-issue-evidence` command. See docs for usage.
- Added `wiz-rescan-machine-disk` command. See docs for usage.
- Added `wiz-set-issue-due-date` command. See docs for usage.
- Added `wiz-clear-issue-due-date` command. See docs for usage.
- Added `wiz-get-project-team` command. See docs for usage.

##### Wiz Mapper
- Add new Incident Field "Wiz Resource Cloud ID" which has the Cloud Provider ID, whereas Wiz Resource ID has the Wiz unique ID.
- Add new Incident Field "Wiz Issue URL" with URL to Wiz Issue.
- Add new Incident Field "Wiz Projects". This value can be empty if no Projects apply.
- Add new Incident Field "Wiz Projects Owners". This value can be empty if no Projects apply or if no Owners were assigned.
- Add new Incident Field "Wiz Projects Security Champions". This value can be empty if no Projects apply or if no Security Champions were assigned.

##### Wiz Mapper Webhook
- Add new Incident Field "Wiz Resource Cloud ID" which has the Cloud Provider ID, whereas Wiz Resource ID has the Wiz unique ID.
- Changed the transformation of INFORMATIONAL incidents from 0 to 0.5
- Add new Incident Field "Wiz Issue URL" with URL to Wiz Issue.
- Add new Incident Field "Wiz Projects". This value can be empty if no Projects apply.
- Add new Incident Field "Wiz Projects Owners". This value can be empty if no Projects apply or if no Owners were assigned.
- Add new Incident Field "Wiz Projects Security Champions". This value can be empty if no Projects apply or if no Security Champions were assigned.

##### Wiz
- Changed Demisto info logging to error in several output fields.
- Better error handling for VM disk rescan if VM isn't found.
- Better JSON parsing handling.

#### Incident Types
- **Wiz Issue**
- Fix for choosing the right pre-built Wiz Layout.

#### Incident Fields
- **Wiz Issue URL**
- **Wiz Resource Cloud ID**
- **Wiz Resource ID**
- Add new Incident Field "Wiz Resource Cloud ID" which has the Cloud Provider ID, whereas Wiz Resource ID has the Wiz unique ID.

##### Wiz Layout
- Added "Wiz Resource Cloud ID" to the Wiz Layout.
- Added "Wiz Issue URL" to the Wiz Layout.
- Added "Wiz Projects" to the Wiz Layout. This value can be empty if no Projects apply.
- Added "Wiz Projects Owners" to the Wiz Layout. This value can be empty if no Projects apply or if no Owners were assigned.
- Added "Wiz Projects Security Champions" to the Wiz Layout. This value can be empty if no Projects apply or if no Security Champions were assigned.

##### New: Assess Wiz Issues
- Example basic Playbook to assess Wiz Issues
- Added "Assess_Wiz_Issues" Playbook to be automatically mapped to Wiz Incident types, but not run automatically.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by solalraveh** [comment]
@kgal-pan hi! 👋 
While I did request not to review yet, since we need the PR for the coverage report, to do the unittesting, it won't get to that point, since there are some basic conflicts that we need to update, but need your permission. Can you kindly help there?

**Comment by solalraveh** [comment]
@ariel-wiz FYI

**Comment by kgal-pan** [comment]
> there are some basic conflicts that we need to update, but need your permission. Can you kindly help there?

Hey @solalraveh! From what I can tell, you need to sync your fork and feature branch with content `master`. Can you do so?

**Comment by kgal-pan** [comment]
@solalraveh @ariel-wiz - Any update on this? Is it ready to be removed from Draft and reviewed?

**Comment by ariel-wiz** [comment]
@kgal-pan - We are still working on this. We'll update the repo by the end of the week.

**Comment by ariel-wiz** [comment]
Hi @kgal-pan 
We've noticed that the coverage is not correct for long strings.
For example, when running [this part of code](https://github.com/wiz-sec/content/blob/wiz-v1.1.0/Packs/Wiz/Integrations/Wiz/Wiz.py#L115-L216), we get that only the first line (115) has been executed, and all the other no.
This occurs in several other parts of our code, and significantly reduce our code coverage.
What can we do to overcome this?
Thanks,
Ariel

**Comment by kgal-pan** [comment]
> We've noticed that the coverage is not correct for long strings. For example, when running [this part of code](https://github.com/wiz-sec/content/blob/wiz-v1.1.0/Packs/Wiz/Integrations/Wiz/Wiz.py?rgh-link-date=2022-07-07T12%3A59%3A06Z#L115-L216), we get that only the first line (115) has been executed, and all the other no. This occurs in several other parts of our code, and significantly reduce our code coverage. What can we do to overcome this? 

Hey @ariel-wiz  - From what I can tell, the query `tuple` is not being hit at all:
image

This is because there's no UT for `fetch_issues` method in `Wiz_test.py`.

In general, to exclude lines/logic from coverage, you can add `  # pragma: no cover` to the end of the statement. A good example would be to use in `main` as such:

```python
def main():  # pragma: no cover
    global URL
    params = demisto.params()
```

As we're not attempting to cover `main` logic, only helper and command functions.

**Comment by ariel-wiz** [comment]
Hi @kgal-pan 

> Hey @ariel-wiz - From what I can tell, the query `tuple` is not being hit at all

I can confirm that the behaviors it the same for `strings` that are longer than one line.
They also are not being hit.

As I can't use `# pragma: no cover` for strings (otherwise it becomes part of the string), and as I don't want to use it for all the functions, what is your suggestion to overcome this?
image

**Comment by kgal-pan** [comment]
As I can't use `# pragma: no cover` for strings (otherwise it becomes part of the string), and as I don't want to use it for all the functions, what is your suggestion to overcome this? image


@ariel-wiz - Can you have the multiline string start in the next line, as so:

```python
query = (  # pragma: no cover
	"""
	graphql query...
	"""
)
```

**Comment by ariel-wiz** [comment]
Hi Gal, 
The commit is ready, however it seems I require additional permissions:
```
remote: Permission to demisto/content.git denied to ariel-wiz.
fatal: unable to access 'https://github.com/demisto/content.git/': The requested URL returned error: 403

```Please let me know when I can push again.
Thanks,
Ariel

**Comment by kgal-pan** [comment]
@solalraveh  - Thanks for the update.

The conflicts occurred because the `master` branch in your fork is outdated compared to https://github.com/demisto/content. 

image

Can you sync the fork with https://github.com/demisto/content, pull those changes into your working branch and push them upstream?

**Comment by solalraveh** [comment]
@kgal-pan for the record that's a method I enjoyed doing, since we have a ton more commits and reviewers after this sync. If you have another idea, or you want to undo this sync and ~200 commits that show many other contributors, then I'd prefer if we do so...

**Comment by solalraveh** [comment]
Marking as draft until this is fixed...

**Comment by solalraveh** [comment]
OK. Shall I run a new PR? This became too messy..

**Pull request closed without merging**
