### PR TITLE
Added support for retry mechanism on rate limit

### PR DESCRIPTION
**Pull request by mmhw**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4303)

## Description
Add support for retry on requests where 429 Rate limit error is recieved

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by bziser — APPROVED** [review]
Great work!

Let's wait for @ostolero to review it too :)

**Review by ostolero — CHANGES_REQUESTED** [review]
Hi @mmhw nice work!
Please note that `_parse_email_as_incident` function under `fetch_incidents` also makes http requests, and needs to have the `overwrite_rate_limit_retry` flag as well. you can see the bug fix where I added it for ms graph mail [here](https://github.com/demisto/content/pull/22120/files#diff-d5de86a338e406b9f295037099570f915d5ef97629346782bd7840583894ff6f) (look for the changes to MicrosoftGraphMail.py)

**Review by ostolero — APPROVED** [review]
Looks great! just make sure to test the `fetch incidents` in xsoar to make sure it works as expected.

**Comment by mmhw** [comment]
> Looks great! just make sure to test the `fetch incidents` in xsoar to make sure it works as expected.

Thanks,
I tested it with @yucohen and it seems to work

**Pull request merged**
