### PR TITLE
Do not escape dot on table to markdown

### PR DESCRIPTION
**Pull request by Nitzperetz**

### CODE REVIEW

**Comment by dorsha** [comment]
@slavikm you added it, so you should give the answers :)

**Comment by slavikm** [comment]
Hmmm... If I added it, it means we needed this for something. So, I'm afraid this will break other stuff.

**Comment by aviadl** [comment]
@dorsha isn't this related to the fix we did, where we saw all the chars that needs to be escaped in MD?

**Comment by dorsha** [comment]
A different one

**Comment by meirwah** [comment]
@Nitzperetz what is this pending on?

**Pull request merged**
