### PR TITLE
WF - wildfire-report failed when specifying verbose=true

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18904

## Description
see in referenced issue

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - no change
- [x] Code Review

### CODE REVIEW

**Comment by bakatzir** [comment]
@kirbles19 
bug fix, only RN changes:
https://github.com/demisto/content/blob/45da3664f8ba49cb78858ab8d8d4bf9fa42f9c0e/Integrations/Palo_Alto_Networks_WildFire_v2/CHANGELOG.md

**Comment by yuvalbenshalom** [comment]
@bakatzir tests are failing

**Comment by bakatzir** [comment]
@yuvalbenshalom hashes are not auto extracted because the file indicator type does not hold any regex.
it happens only in 4.0.
did you guys chagnes the reputations for 4.0? @DeanArbel @hirshbergshachar 

Screen Shot 2019-08-29 at 17 50 55

**Comment by hirshbergshachar** [comment]
@bakatzir I don't think so

**Pull request merged**
