### PR TITLE
McAfee Esm "watchlist" commands addition

### PR DESCRIPTION
**Pull request by apekarovsky**
Added the following commands:

"get-watchlsists"
"esm-add-vatchlist-value"
"esm-remove-watchlist-value"

Also added latest versions 11 to the versions check

* Updated the documentation in README.md
* Added the test in test playbook.
* fixed test playbook failing with wrong transformer in alerts check.

Please assign @dantavori to this PR as he reviewed the original PR and ask me to delete is and create this one as the previous was outdated.

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
McAfee Esm "watchlist" commands addition in order to add/remove values to/from watchlists.

## Screenshots

image

image

image

## Minimum version of Demisto
- [x] 5.0.0
- [x] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by apekarovsky** [comment]
@dantavori Please take this :-)

**Comment by kirbles19** [comment]
@dantavori Done.

**Review by dantavori — APPROVED** [review]

**Comment by ShahafBenYakir** [comment]
@esharf @yaakovi Please go over this PR and see if we already cover this use cases in our open PR, if not let's consider adding them.

**Comment by dantavori** [comment]
@esharf closing this PR, use the content of the branch if you need

**Pull request closed without merging**
