### PR TITLE
Added new transformers which are MakePair, SortBy and DedupBy

### PR DESCRIPTION
**Pull request by spearmin10**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Added new transformers which are `MakePair`, `SortBy` and `DedupBy`.
On `DedupBy`, there is a similer script which is `DeduplicateValuesbyKey`, but it cannot be used on the classifier or mappers since it's not a transformer, and also `DedupBy` can be used no matter what data types are.

## Screenshots
[https://paloaltonetworks.zoom.us/rec/share/62h7KHcAOcLzFcaiH0M7N4VUqtMMJZV0kFOL-5PXgbfawp1TuQK4pGsy82ZVrV9E.sKHPVZtpqJeaZbFN](https://urldefense.proofpoint.com/v2/url?u=https-3A__paloaltonetworks.zoom.us_rec_share_62h7KHcAOcLzFcaiH0M7N4VUqtMMJZV0kFOL-2D5PXgbfawp1TuQK4pGsy82ZVrV9E.sKHPVZtpqJeaZbFN&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=Ofm-xnwIyR-wX5Qd5Wta5yebOWzrIzmkRd55xrRodnY&m=q-1fXCjoKtA5n3L9RtL5eqhzkfHRJDacj3g8AVg0eNUNoUvdx0TOgklbxZKxrFC6&s=37EQz8jJB10B5EnaTMKSK1bYWT9T1Y9O0Z8T2CqbkeA&e=)
PassCode: %D&%L.y4jM

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by samuelFain** [comment]
Hi @spearmin10, and thank you for your contribution!
Your PR will PR review shortly.
In the meanwhile, feel free to contact me for any questions/clarifications.
Thank you!

**Review by samuelFain — COMMENTED** [review]
Hi @spearmin10, thank you for your patience!
please see my comments, I tried to make code suggestions wherever I could.
I am adding @ShirleyDenkberg from the technical writers team as a reviewer as well.

**Comment by spearmin10** [comment]
@samuelFain  Thank you for the review! I've fixed them following to your comments. Please review again.

**Comment by ShirleyDenkberg** [comment]
@samuelFain Doc review completed.

**Review by samuelFain — APPROVED** [review]

**Pull request merged**
