### PR TITLE
Update sane-doc-reports tag

### PR DESCRIPTION
**Pull request by agamm**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19986
https://github.com/demisto/dockerfiles/pull/1256
https://github.com/demisto/sane-doc-reports/pull/61

## Description
Fixes an edge case in the old transformation of the old JSON format.

## Required version of Demisto
5.0.0

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [x] Documentation (with link to it)
- [X] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [CHANGELOG](Scripts/SaneDocReport/CHANGELOG.md)

### CODE REVIEW

**Comment by meirwah** [comment]
@agamm you need to add python type:
image

**Comment by agamm** [comment]
> @agamm you need to add python type:
> image

Good catch, it usually doesn't pass until there is the docs approved tag, so I thought that is the only problem.

**Comment by meirwah** [comment]
@kirbles19 can you approve here ?

**Comment by kirbles19** [comment]
@agamm Done. please check the changes for technical accuracy.

**Comment by agamm** [comment]
> @agamm Done. please check the changes for technical accuracy.

@kirbles19 Seems good, thanks!

**Pull request merged**
