### PR TITLE
Panorama - added 2 commands by Alex

### PR DESCRIPTION
**Pull request by abaumgarten**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: https://github.com/demisto/content/pull/10879
related: https://github.com/demisto/content/pull/9150

## Description
@apekarovsky's pack description: This content pack is set to be a "toolbox" for organisations with "Air Gap" networks. There are currently two use-cases in this "toolbox".
One is indicators "reputation" query from internal , air gapped network. This is done by getting the indicators across the "Air Gap" by using unidirectional diode that can pass UDP traffic. The answer will return as a JSON Feed file and will be transferred back in via another unidirectional diode that can pass files.
The second use-case is automating "Offline Panorama content updates" like AV, Apps and threats or even Wildfire content updates. External network Panorama will pull the content updates forward them to XSOAR. Then they will be checked for threats and moved by a unidirectional diode into the internal network where they will be automatically installed on the Panorama server and pushed to the firewalls.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by abaumgarten** [comment]
@guykeller  we have talked about this PR related to hackathons PR was written by @apekarovsky, as this contribution level is xsoar, should I assign you as a reviewer?

**Comment by guykeller** [comment]
@abaumgarten Review it, once you merge it to the midway branch assign me as well

**Review by bakatzir — COMMENTED** [review]
Please remember to update the readme after @kirbles19 reviews the PR.

**Comment by abaumgarten** [comment]
status - I have reviewed all files, I will test all commands with @apekarovsky soon. After that, the PR with be ready to @guykeller's review.

**Pull request closed without merging**
