### PR TITLE
Update integration-OpenPhish.yml

### PR DESCRIPTION
**Pull request by EdenOhana**
## Status
Ready

## Related Issues
ZD Issue: 2801

## Description
Added an option to use "Trust any certificate (unsecure)", customers with SSL Inspections fails to send a request to the site.

## Screenshots - Error message
*** openphish fails 
Running the integartion test yields this error => "Get https://openphish.com/feed.txt: x509: certificate signed by unknown authority" 
Debug logs show => "Unable to do Http req to url : https://openphish.com/feed.txt (error: Get https://openphish.com/feed.txt: x509: certificate signed by unknown authority)"

## Does it break backward compatibility?
   - No

## Must have
- [V ] Tests - customer tested copy of the integration with the changes and it solved the issue

### CODE REVIEW

**Comment by EdenOhana** [comment]
Done, installed content_new.zip from circle on 4.0 build 31883 and test was successful.

**Comment by anara123** [comment]
@EdenOhana Good work!

**Comment by anara123** [comment]
@EdenOhana is there an open issue related to this fix?

**Comment by EdenOhana** [comment]
@anara123 No, I faced it with a customer and fixed it for him with a copy but we might face more customers who need it in the future and it's a small change so I figured I can do it myself.

Do we have to open issue before pull request?

**Pull request merged**
