### PR TITLE
Email thread

### PR DESCRIPTION
**Pull request by hiep4hiep**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

### CODE REVIEW

**Comment by altmannyarden** [comment]
Hi @hiep4hiep ,
My first question before reviewing your PR is - why you opened a new pack? Why didn't you add these improvements / enhancements to the existing email communication pack?

**Comment by hiep4hiep** [comment]
> Hi @hiep4hiep ,
> My first question before reviewing your PR is - why you opened a new pack? Why didn't you add these improvements / enhancements to the existing email communication pack?

Yes, that's what I'm not sure and need your suggestion here. The idea is quite the same as the updated Email Communication pack to support send/receive emails in multiple threads with some enhancements. 
My version is based on a request from customer to have a friendlier UI that looks like other email client that the users are more familiar with. And it supports managing email from EmailAskUser or send email from playbook tasks.
Those enhancements come along with some new scripts, also modified scripts of the original pack, new incident fields. Please help suggest what should be the best way to update the original pack? Kind of version 2 of the same packs or something?
If that's possible, pls cancel this PR and I'll build and submit a new one. Thank you.

**Comment by hiep4hiep** [comment]
> @hiep4hiep I see. Can you schedule a meeting for us to discuss it? I think it will be the best and the fastest :)

Sure, thank you. Can we have a call at 9AM TLV time tomorrow (Friday)? Else pls suggest other slot. I'm in AEDT timezone so it's a bit late now.

**Comment by hiep4hiep** [comment]
> We are not working on Friday's in Israel, and we have a Holiday Sunday-Monday next week.
> We can schedule for Tuesday at 9AM (Israel time)?

Yes, I've scheduled the discussion here https://calendar.google.com/event?action=TEMPLATE&tmeid=MTM5bTNmaXUxbml1ZXBtOGk2ZmoydXFhc2YgaG5ndXllbkBwYWxvYWx0b25ldHdvcmtzLmNvbQ&tmsrc=hnguyen%40paloaltonetworks.com

**Comment by altmannyarden** [comment]
@hiep4hiep In the meeting you added, I don't see any zoom link or the other participants. Please send a DM in our DFIR channel - https://dfircommunity.slack.com/archives/DURQWAE7K

**Comment by hiep4hiep** [comment]
> @hiep4hiep In the meeting you added, I don't see any zoom link or the other participants. Please send a DM in our DFIR channel - https://dfircommunity.slack.com/archives/DURQWAE7K

Sorry don't know why but I cannot access the DIFR slack link.
Can you join the call here https://paloaltonetworks.zoom.us/my/hnguyen?pwd=L3QvT1JROHRUUTRFT1hmLzNtWFZxQT09
My Palo Alto Networks ID is hnguyen@paloaltonetworks.com

**Comment by hiep4hiep** [comment]
Please ping me on Slack next time when you are available. Thank you.

**Pull request closed without merging**
