### PR TITLE
Ews mem fix

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
related: https://github.com/demisto/etc/issues/17486

## Description
Fix for mem issue in EWS. Logging streamio object was left active.

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by glicht** [comment]
Yes. I was waiting for the old release notes to be cleared.

**Comment by meirwah** [comment]
@IkaDemisto are you reviewing this?

**Comment by glicht** [comment]
@kirbles19 release notes are at: 
https://github.com/demisto/content/edit/ews-mem-fx/Releases/LatestRelease/EWSv2.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F3922

**Comment by kirbles19** [comment]
@glicht Release notes reviewed, no changes needed, all done.

**Pull request merged**
