### PR TITLE
fix health dashboard

### PR DESCRIPTION
**Pull request by Spivaka**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18218

## Description
Fix default health dashboard to support disk partitions

## Screenshots
Paste here any images that will help the reviewer
image

## Required version of Demisto
5.0.0

## Does it break backward compatibility?
Not that I know of, as the content is overriden in the new version

### CODE REVIEW

**Comment by Bars92** [comment]
can we automaticlly do in server `disk.usedPercent` match `disk.usedPercent./` in 5.0.0? that should save the need for old yaml

**Comment by Spivaka** [comment]
we can, but I think adding patches in the server is less preferred than changing the content...

**Comment by idobloch** [comment]
isn't it already fixed in: https://github.com/demisto/server/pull/13214 ?

**Comment by Itay4** [comment]
@Spivaka whats our status here?

**Pull request closed without merging**
