### PR TITLE
added Vertica integration + tests and removed from beta integration

### PR DESCRIPTION
**Pull request by yardensade**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16270

## Description
Vertica DB Integration

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation (https://github.com/demisto/etc/issues/16274)
- [x] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
Please post playbook screenshot

**Comment by yardensade** [comment]
image

**Comment by Itay4** [comment]
can we also verify that expected values exist ? what about testing errors ?

**Comment by yardensade** [comment]
the verify does test for value exist

**Comment by Itay4** [comment]
pending @kirbles19 review

**Pull request merged**
