### PR TITLE
AccessData API Update (New Branch)

### PR DESCRIPTION
**Pull request by ThomasVieth**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Rewrite the current integration to provide interaction the new FTK API.

## Screenshots
AccessData__Process_Evidence_and_Export_Wed_Dec_29_2021
AccessData__Job_Polling_Tue_Jan_11_2022
image

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by ThomasVieth** [comment]
Please note this is a new PR entry to combat the branch issue explained here https://github.com/demisto/content/pull/16390

**Comment by ThomasVieth** [comment]
Still need to resolve the unique ID issue standing in the old PR.

**Comment by eyalpalo** [comment]
Hi @ThomasVieth, Please note that this V2 integration does not have tests and ReadMe. Please add those, as it cannot be merged without. 
You can see [ReadMe explained](https://xsoar.pan.dev/docs/documentation/readme_file) and [Unit tests explained](https://xsoar.pan.dev/docs/integrations/unit-testing).

**Comment by ThomasVieth** [comment]
@eyalpalo The REST API exposed by our product is a privately sold service and cannot be publicly exposed to the web so writing unit-tests for the functionality is not possible. I understand that we wish to verify that the context is being correctly generated but how can we go about this?

I will update the V2 integration to contain a new README though.

**Comment by kgal-pan** [comment]
> @eyalpalo The REST API exposed by our product is a privately sold service and cannot be publicly exposed to the web so writing unit-tests for the functionality is not possible. I understand that we wish to verify that the context is being correctly generated but how can we go about this?
> 
> I will update the V2 integration to contain a new README though.

@ThomasVieth - The unit tests will use a mocker and not actual calls to the product REST API. Please refer to [Write Your Unit Tests](https://xsoar.pan.dev/docs/integrations/unit-testing#write-your-unit-tests) for more information. 
Let me know if you have any questions.

**Comment by kgal-pan** [comment]
Closing as no work has been committed since the day the PR was reopened.

**Pull request closed without merging**
