### PR TITLE
add-FiltersAndTransformers

### PR DESCRIPTION
**Pull request by bakatzir**
Adding the base/core pack of Filters and transformers to Expanse MP.

## Status
- [x] Ready

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/EXPANDR-2297

### CODE REVIEW

**Comment by bakatzir** [comment]
@yaakovpraisler @daryakoval should I ask review from someone else?

**Comment by ShahafBenYakir** [comment]
Adding a core pack is risky and not enough to run the build. Have we checked about dependencies?

**Comment by bakatzir** [comment]
> Adding a core pack is risky and not enough to run the build. Have we checked about dependencies?

If you'll instruct me what to do - I'll do that. Bare in mind that this is already a core pack for XSOAR and XSIAM MP.

**Comment by ShahafBenYakir** [comment]
Good point regarding it being a core pack.
We need to verify all dependencies are from within this close core packs group. The best will be to run the find dependencies SDK command on the filtersAndTransformers pack to validate that all required dependencies are in this list.

**Comment by bakatzir** [comment]
> Good point regarding it being a core pack. We need to verify all dependencies are from within this close core packs group. The best will be to run the find dependencies SDK command on the filtersAndTransformers pack to validate that all required dependencies are in this list.

@ShahafBenYakir 
```
Found dependencies result for FiltersAndTransformers pack:
{}
```

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
