### PR TITLE
Onion URL Reputation Script

### PR DESCRIPTION
**Pull request by Bargenish**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: demisto/etc/issues/28934

## Description
Onion url reputation script

## Screenshots
Screen Shot 2020-10-14 at 13 30 00

### CODE REVIEW

**Review by yaakovi — COMMENTED** [review]
where is the `Onion URL`. indicator type defined? couldn't find it in the repo/platform

**Comment by Bargenish** [comment]
@yaakovi @EliorKedar is responsible for the indicator types PRs (for both `Cryptocurrency` and `Onion URL`).
attached is the `Onion URL`  indicator type as defined by Elior.

[Indicatortype-Onion URL.json.zip](https://github.com/demisto/content/files/5397143/Indicatortype-Onion.URL.json.zip)

**Review by yaakovi — APPROVED** [review]
make sure to update the indicator type to use this script.

**Comment by ShirleyDenkberg** [comment]
@yaakovi Doc review is done.

**Pull request merged**
