### PR TITLE
Update layout and fields for records

### PR DESCRIPTION
**Pull request by yleiferman**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Updated the format of the records, from a raw string to json, associated with a signal for better functionality.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by mmhw — COMMENTED** [review]
Hi @yleiferman,
Thank you for your contribution!
Good work :)

@melamedbn If you could please look at it.

General Comment:
Note please the errors in [Validate](https://app.circleci.com/pipelines/github/demisto/content/354756/workflows/f7d2d294-180c-4ae5-bcb3-0028e6d35874/jobs/745094).


Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by melamedbn** [comment]
Hi @yleiferman,

Can you please explain the changes made to the incident field and classifier?
Additionally, these changes need to be mentioned in the RN as well.

Best regards,
Ben

**Comment by yleiferman** [comment]
Hi @melamedbn ,

I've update the RN. Basically I'm changing how the records fields is being displayed. Previously it was shown as raw text. Now, the mapper converts the JSON text so it can be formatted appropriately and then displayed in a more useful manner. That way customers can use the data easily.

Please let me know if you have any other questions. I appreciate all your help as this is my first PR.

**Review by melamedbn — APPROVED** [review]

**Comment by mmhw** [comment]
Hi @yleiferman,
Thanks for the RN update.

Note the following error [here](https://app.circleci.com/pipelines/github/demisto/content/355565/workflows/e888d8f3-5bf6-4d90-b663-8532692d5a55/jobs/745612?invite=true#step-119-10127_186):
```
[ERROR] Packs/SumoLogic_Cloud_SIEM/IncidentFields/incidentfield-Sumo_Logic_Cloud_SIEM_Record_Fields.json: [IF111] - Changing incident field type is not allowed.
```
It looks like you will have to create a new incident type so that it is of markdown type.

**Comment by yleiferman** [comment]
Hi @mmhw , thank you for your reply. Is there a reason why I can't change the incident type? The previous version had bad formatting type so it wasn't very helpful. What would happen if it changes for customers?

**Comment by mmhw** [comment]
Hi @yleiferman,
The server prevents from changing the type of the incident field, if you change anyway, the change will not happen to customers who already have the pack installed, only customers who will install the pack for the first time.

**Comment by yleiferman** [comment]
Hi @mmhw , thank you for your comment. Do you have any documentation I can look at to learn how to deprecate an incident field?

**Comment by kgal-pan** [comment]
> Do you have any documentation I can look at to learn how to deprecate an incident field?

Change the `description` field of the incident field to:

```json
{
"description": "Deprecated. Please use $NAME_OF_REPLACEMENT_FIELD instead",
}
```

**Comment by mmhw** [comment]
Hi @yleiferman,
Also note [this error](https://app.circleci.com/pipelines/github/demisto/content/357380/workflows/bccdec73-42ba-4326-9521-dc75fce26dc4/jobs/746479?invite=true#step-119-10761_85):
`
[ERROR] /home/circleci/project/Packs/SumoLogic_Cloud_SIEM/Classifiers/classifier-mapper-incoming-Sumo_Logic_Cloud_SIEM.json: [GR103] - Content item 'Sumo Logic Insight - Mapper' using content items: 'Record Event Product', 'Record Event Vendor', 'Record Count', 'Record Message ID', 'Record Device Event ID', 'Confidence Score', 'Record Source Category' which cannot be found in the repository.
`
It doesn't seem related to the current PR, but it seems that the mapper is really using Incident Fields that don't exist, could you please check it?

Thanks again!

**Comment by yleiferman** [comment]
Hi, I've updated the content according to your recommendations. Please let me know if you have any comments.

**Comment by mmhw** [comment]
Hi @yleiferman, It seems that there was some confusion here, actually you need to restore the file `incidentfield-Sumo_Logic_Cloud_SIEM_Record_Fields.json` to the way it was, except for the change in the description, and in the new incident field update the description accordingly.
And also in the Layout you will probably want to use the new incident field.

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by mmhw** [comment]
Hi @yleiferman,
Could you please update your branch from master?
Thanks again

**Comment by yleiferman** [comment]
@mmhw , I did update my branch from master here https://github.com/demisto/content/pull/33635/commits/bc8f059a7a846fe732a97dfe9e8441710ce3eb05. Is there something else that you need from me? Thank you again for all your help.

**Comment by mmhw** [comment]
@yleiferman I need you to update once again from master following a fix entered there in the circleci files

**Comment by yleiferman** [comment]
@mmhw , please let me know if you need anything else.

**Review by mmhw — APPROVED** [review]

**Pull request merged**
