### PR TITLE
Adding GCP Enrichment and Remediation playbooks

### PR DESCRIPTION
**Pull request by capanw**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[Expander-88](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-88)

## Description
Adding GCP enrichment and remediation playbooks to GCP Enrichment and Remediation pack.
Given the IP address the enrichment playbook enriches GCP and Firewall information. And Remediation playbook replaces current firewall rules with limited access firewall rules.

## Screenshots
Provided if necessary

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by capanw** [comment]
Hello @omerKarkKatz,

I submitted the Contribution form twice and for some reason it's still throwing an error asking me to submit the form. Any suggestions on why this is happening?

Thanks

**Comment by efelmandar** [comment]
Hi @capanw and thank for your contribution, the content looks very good!
Please consider giving a more descriptive name since there is already a playbook in this pack called `Cloud_Response_-_GCP` which might be confusing with `GCP-Firewall remediation`.
in addition would appreciate if you could add a detailed playbook/task description so the purpose and use of this playbook would be clearer to the user. currently the description only show that the playbook is changing firewall rules but not explaining very well that it creates the firewall rules to isolate the instance from public traffic and allows internal traffic only.

besides that great work!

@omerKarkKatz, once the description is added we can merge this PR

**Comment by capanw** [comment]
Hello @efelmandar, Thank you so much for reviewing and providing feedback and happy new year.

I agree with your suggestion on description of the playbook. I modified and added more informative description with an example that clearly explains what does the playbook perform. However, for playbook nam, we are currently using the same format for AWS playbooks too and I think it would be better if we can keep the current playbook name as is. 

Let me know if that looks good. 

Thank you
Chait

**Comment by omerKarkKatz** [comment]
@efelmandar please give me your OK to merge this contribution.

**Comment by efelmandar** [comment]
@capanw Thank you for adding the description for the playbook, @omerKarkKatz we can go ahead and merge the PR

**Review by omerKarkKatz — APPROVED** [review]

**Pull request merged**
