### PR TITLE
Kaspersky Security Center

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/17699

## Minimum version of Demisto
- [x] 5.5.0

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
@hod-alpert please review the changes in CommonServerPython

**Comment by hod-alpert** [comment]
@Itay4 Seems OK

**Review by anara123 — APPROVED** [review]

**Review by yaakovi — APPROVED** [review]
very nice

**Comment by ShirleyDenkberg** [comment]
@anara123 @yaakovi @hod-alpert  Submitted. In order to meet the requirements of completing all PRs within a week, there was not enough time to review the descriptions of the arguments. If required, we can revisit this at a later time.

**Pull request merged**
