### PR TITLE
fixed clickable links

### PR DESCRIPTION
**Pull request by ronykoz**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/17812

## Description
Hiding links

### CODE REVIEW

**Comment by ronykoz** [comment]
@yaakovi i don't see the need in UT for simple replace.
And thats the fix:
image

**Comment by yaakovi** [comment]
@ronykoz please fix the change log before merging to master (after the the last commit the format is not correct)

**Comment by ronykoz** [comment]
@yaakovi not sure what do you mean by wrong format here, seems ok to me

**Comment by yaakovi** [comment]
```
## [Unreleased]
Removed the hyperlink from links.

## [19.9.0] - 2019-09-04
  - Improved EML file type detection.
  - Added the *Email.AttachmentNames* output, which contains a list of the names of all email attachments.
```

**Pull request merged**
