### PR TITLE
URLScan.io Adoption

### PR DESCRIPTION
**Pull request by heipei**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Readme for pack adoption

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
Hi @heipei can you add also a new version and a corresponding release note? See number 3 [here](https://xsoar.pan.dev/docs/partners/adopt#process)

**Comment by heipei** [comment]
> Hi @heipei can you also bump the pack version and add a corresponding release note? See number 3 [here](https://xsoar.pan.dev/docs/partners/adopt#process)

Hello @ShahafBenYakir I only changed the README so the demisto-sdk update-release-notes command is telling me that there weren't any changes.

**Comment by ShahafBenYakir** [comment]
Hi @heipei you are right. Do the following:
1. In your `pack_metadata.json` file set the `currentVersion` key to 1.1.7 (instead of 1.1.6)
2. Inside the `ReleaseNotes` folder create a new md file called `1_1_7.md` with the following text inside:
```
### Pack Support
Support for this pack will be moving to the partner around September 1, 2021.
```

**Comment by heipei** [comment]
@ShahafBenYakir Thanks for the guidance, I've amended the commit and force-pushed the branch, I hope this was OK. Anything else I need to do?

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
