### PR TITLE
[DomaintoolsIris] Release v2.0.0 (after sync with master)

### PR DESCRIPTION
**Pull request by wesleya**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Attempting to re-create the PR for version 2.0 of the DomainTools Iris pack: https://github.com/demisto/content/pull/29474

This release includes:

New commands for Iris Enrich, Whois History, Hosting History, Reverse Whois, Domain Profile, Whois, Reverse IP, Reverse Name Server.
New Scripts for Extract and Enrich, and Extract and Investigate.
New Playbooks for checking domains by High Risk Score, Tags, and Search Hash
Bug fixes and improvements

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by melamedbn — APPROVED** [review]

**Review by MichaelYochpaz — APPROVED** [review]
@wesleya Looks like the `.secrets-ignore` file from the previous PR is missing, causing secrets to be detected. And there's a Docker version bump needed.
https://app.circleci.com/pipelines/github/demisto/content/335924/workflows/66d96c25-851d-4205-9edd-dade6491ceeb/jobs/736700

Other than that, assuming you've re-tested everything following the changes, PR looks good to me for a merge :)

**Comment by wesleya** [comment]
@MichaelYochpaz Thank you for the review! I've re-added the missing `.secrets-ignore` file and bumped the docker version. 

Do you need anything else from us or can you merge our PR? Once merged, does that mean the release is public in the cortex marketplace? Thank you!

**Comment by MichaelYochpaz** [comment]
@wesleya Nothing is needed from your side, I'll merge it :)
Once this PR is merged, it's merged to an internal branch on our repo that runs our full build. Once the second PR is merged (to `master`), it should take a few hours for our scheduled upload process to upload the updated pack onto the marketplaces.

It should take 1-3 days for the whole process to complete (if there are no unexpected issues) and for the update to be available on the marketplace for customers.

**Comment by wesleya** [comment]
@MichaelYochpaz Just wanted to confirm that the release was completed, and if there is any follow up you need from our side? Thank you!

**Comment by MichaelYochpaz** [comment]
@wesleya Release was completed, and the new version is already available for customers on the marketplace :)
https://cortex.marketplace.pan.dev/marketplace/details/DomainTools_Iris/

**Comment by wesleya** [comment]
@MichaelYochpaz thank you! Appreciate you and your team's guidance and patience with this!

**Pull request merged**
