### PR TITLE
Create incident field for cve list

### PR DESCRIPTION
**Pull request by sebadoh**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Take a list of CVEs from the user and check whether a there is a coverage in the firewall for each cve

## Screenshots
CVE Input

CVE Output1

## Minimum version of Demisto
- [ x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by moishce** [comment]
@sebadoh Thanks for your contribution.
Can you please share your availability for a demo to better understand the use case here.

**Comment by sebadoh** [comment]
Sure,

Your morning, my night would work best. I'm on Mountain Time, my midnight,
your 9am would work

Etay

**Comment by moishce** [comment]
@sebadoh How is it for you Wednesday at 9 am
And if you can share your email address

**Comment by moishce** [comment]
This pr is in halt at @sebadoh request

**Comment by sebadoh** [comment]
Keep it open please, I’ll set up time for a demo.

**Comment by adi88d** [comment]
Hi @ sebadoh
We want to schedule a demo for your contribution, please share with us your availability for this week,
Thanks

**Review by adi88d — APPROVED** [review]
Nice feature!

**Pull request merged**
