### PR TITLE
Fix incorrect parsing of severity level

### PR DESCRIPTION
**Pull request by mixmind**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling out the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
The severity mapping was not working correctly, and were sent key instead of a value. Also, there was an additional separator in query params that was braking filters

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by thefrieddan1** [comment]
Hi @mixmind,
Thank you for your contribution, we appreciate your time and effort.
Just keeping you in the loop that because this is a Claroty partner pack.
We are notifying them of this PR and wait for their input as well.

Thanks,

**Comment by mixmind** [comment]
> Hi @mixmind, Thank you for your contribution, we appreciate your time and effort. Just keeping you in the loop that because this is a Claroty partner pack. We are notifying them of this PR and wait for their input as well.
> 
> Thanks,

Hi, thanks.
Who is your contact in Claroty? I can speed up things from inside🙂

**Comment by thefrieddan1** [comment]
@mixmind Im checking. :)

**Comment by thefrieddan1** [comment]
@mixmind This is our contact in Claroty:
Stephan Goldberg

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
