### PR TITLE
Update pack README.md and pack_metada.json

### PR DESCRIPTION
**Pull request by PankajKCohesity**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Only app store meta-data changes: Pack README.md and pack_metadata.json

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kgal-pan** [comment]
@PankajKCohesity - Looks like your fork is not synced with `content` `master` branch:

image


This is causing conflicts and adding a lot of files to the PR which do not not actually have diffs. For example, according to the title of the PR, you're attempting to update the `README` and `pack_metadata` but there are 31 changed files in the PR (we should only have 2).

Please sync your fork to `content` `master` - see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork.

**Comment by kgal-pan** [comment]
@PankajKCohesity - Please create a new PR with the synced `master` and close this one as we now have authors in this PR that need to sign the CLA but who are unrelated to this Pack:

image

**Comment by PankajKCohesity** [comment]
Abandoning this PR and creating a new one due to above reasons.

**Comment by kgal-pan** [comment]
New PR => https://github.com/demisto/content/pull/16990

**Pull request closed without merging**
