### PR TITLE
Removed custom fields

### PR DESCRIPTION
**Pull request by ShahafBenYakir**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/24730

## Description
Removed custom fields from layouts to prevent customer warnings

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
@Itay4 @idovandijk review pls

**Comment by ShahafBenYakir** [comment]
@idovandijk Yes it is, it will keep happening in playbooks until this is fixed https://github.com/demisto/etc/issues/24731. Therefore it will be taken care of as part of this issue.

**Comment by idovandijk** [comment]
@ShahafBenYakir Is this related? Getting this error when installing Impossible Traveler pack:
image

**Comment by kirbles19** [comment]
@ShahafBenYakir @Itay4 Done.

**Pull request merged**
