### PR TITLE
FileCreateAndUpload enhancement 

### PR DESCRIPTION
**Pull request by gshriki**
Converted to JS. 
Added the ability to intake entry ID instead of data

### CODE REVIEW

**Comment by gshriki** [comment]
done. please have a look.

**Comment by meirwah** [comment]
to make it run in CI, need to add some stuff : https://github.com/demisto/server/wiki/Content-Tests

**Comment by asafshen** [comment]
@gshriki We can run playbook without integration
in `Tests/conf.json` just mention `playbookId` and don't mark `name` field

**Comment by meirwah** [comment]
@gshriki you want to merge this?

**Pull request merged**
