### PR TITLE
IntSights Get alert's CSV file command 

### PR DESCRIPTION
**Pull request by orenzohar**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/15753

## Description
added a command to get alert's CSV file in case of credentials leakage or leaked credit cards alerts

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by orenzohar** [comment]
we have two accounts for IntSights, the mssp one expired so the build is failing. (https://github.com/demisto/etc/issues/16351).

**Comment by JonathanMeler** [comment]
@orenzohar what's the gap here?

**Comment by orenzohar** [comment]
@JonathanMeler no BD require anymore https://github.com/demisto/etc/issues/15753#issuecomment-523609118 I can finish it now

**Comment by orenzohar** [comment]
*UPDATE*: The MSSP account still doesn't work. @JonathanMeler

**Comment by Itay4** [comment]
closing pr and keeping branch alive

**Comment by yardensade** [comment]
What's the status on this, can we delete the branch?

**Pull request closed without merging**
