### PR TITLE
Add copy command to Google Cloud Storage integration

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Contributing on behalf of a customer who needs this functionality. Adds a copy command to the Google Cloud Storage integration to copy an object from one storage bucket to another.

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ali-sawyer** [comment]
@moishce It seems the README for this integration is in a nonstandard format (it is HTML instead of MD). How should I add the new command to the README? Should it first be converted to MD?

**Comment by ali-sawyer** [comment]
@moishce Sounds good, I just added the new command to the HTML. This is ready for review.

**Comment by moishce** [comment]
@ali-sawyer Looks great, good job
Only if you can fix the lint errors

**Comment by ali-sawyer** [comment]
@moishce I think I fixed most of the errors except the last one, regarding a newline at the end of the file – I got errors both with and without a blank line at the end of the file. Can you please assist?

**Review by moishce — APPROVED** [review]

**Pull request merged**
