### PR TITLE
Parse url sneaky chr

### PR DESCRIPTION
**Pull request by roysagi**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [ ] Ready
- [x] In Hold - waiting for decisions as to how should this character should be handled.

## Related Issues
fixes: https://github.com/demisto/etc/issues/29136

## Description
1. Improved regex for both URL and Domain.
2. Improved parsing scripts for both URLs and Domains.

### CODE REVIEW

**Review by ronykoz — COMMENTED** [review]
didn't we say we want to create two indicators one with the sneaky char and one without it

**Review by ronykoz — APPROVED** [review]

**Comment by ronykoz** [comment]
@roysagi what's the status on this one?

**Comment by roysagi** [comment]
@ronykoz - on hold until we get further information about how should this situation be approached: https://github.com/demisto/etc/issues/29136#issuecomment-717944409

**Comment by glicht** [comment]
@roysagi status?

**Comment by roysagi** [comment]
@glicht - I'll close this PR, it should be handled by anyone who retakes this: https://github.com/demisto/etc/issues/29136 as the design changed from when I created this.

**Pull request closed without merging**
