### PR TITLE
remove empty options from selectValue

### PR DESCRIPTION
**Pull request by MosheEichler**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/43200, fixes: https://github.com/demisto/etc/issues/42886

## Description
Remove empty strings from selectValue in incident/indicator fields

## Screenshots
Screen Shot 2021-11-11 at 17 26 49

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by MosheEichler** [comment]
@tomneeman151293 You may want to consider adding verification in `demisto-sdk` to avoid such issues

**Comment by tomneeman151293** [comment]
@MosheEichler Are you able to open an issue for such validation? and tag the bugs in the issue in the newly created ticket?

**Comment by MosheEichler** [comment]
@tomneeman151293 https://github.com/demisto/etc/issues/43692

**Review by reutshal — APPROVED** [review]
Looks good.
Please upload one of the fixed fields to the system and make sure the bug resolves.

**Comment by MosheEichler** [comment]
> Looks good. Please upload one of the fixed fields to the system and make sure the bug resolves.
Screen Shot 2021-11-16 at 10 04 16

**Pull request merged**
