### PR TITLE
Fix YML bugs that caused inputs to not work correctly

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Fix 2 malformed YML bugs that caused inputs to not work as expected:
1. Value `inputs.O365AllowNotFoundExchangeLocations`, passed in as `allow_not_found_exchange_locations` input to subplaybook `O365 - Security And Compliance - Search And Delete` (extra `|` char and newline) – This caused this input to get passed in as the empty string even if a value was actually passed.
2.  Playbook input `inputs.O365DeleteType` (was "simple", needs to be "complex") – This caused this input to get passed in as the literal string "inputs.O365DeleteType" rather than the actual value.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by idovandijk — COMMENTED** [review]
@ali-sawyer Can you show an occasion where the `O365AllowNotFoundExchangeLocations` input was passed as an empty string?
On my system it looks correct
image

and when I export the YML it exports it with `|`
image

as for the `inputs.O365DeleteType` - indeed a bug, but users would probably overwrite that input anyway when it's a subplaybook. Nonetheless these fixes are more than welcome, thanks!

@shaniacht1 Can you help shed light why the server is sometimes exporting with the `|` character? If it's causing content to break we may need to open a platform bug and handle it in the SDK meanwhile.

**Comment by ali-sawyer** [comment]
@idovandijk I see the exact same thing as you – in the UI it looks completely normal, but in the YML export there is a `|` char and newline. I first saw this issue working with a customer and I am able to reproduce. I will send you a video.

**Review by idovandijk — APPROVED** [review]
@ali-sawyer thanks, these fixes can be merged. Still expecting answer from the platform team as to why this happens

**Comment by JasBeilin** [comment]
@ali-sawyer Please note that your build is failing, let me know if you need help in fixing the errors.

**Pull request merged**
