### PR TITLE
Changing the indicators search in relevant integrations - part 2

### PR DESCRIPTION
**Pull request by OrelHaim**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: https://github.com/demisto/etc/issues/33050

## Description
Searching indicators by demisto version,
if the version is 6.2 or higher we will use the searchAfter param, otherwise, we will use paging.

**Workday_IAMXDR_iocs**

1. ExportIndicators
2. CyrenThreatInDepthRenderRelated
3. FeedMitreAttack
4. Workday_IAM
5. XDR_iocs

**and scripts:**

1. FeedRelatedIndicatorsWidget
2. MITREIndicatorsByOpenIncidents

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by OrelHaim** [comment]
@bakatzir Those are all the places that are using searchIndicators, looks like all of those are relevant,
should it separate it to couple PR's?

**Comment by ShahafBenYakir** [comment]
@bakatzir @OrelHaim This feature is supported from 6.1 no? you have here integration that have lower support than this

**Comment by OrelHaim** [comment]
> @bakatzir @OrelHaim This feature is supported from 6.1 no? you have here integration that have lower support than this

@ShahafBenYakir It supported both of the options, searching indicators using the new feature and the "older" version with paging, you can see the implementation in common server python.

**Comment by ShahafBenYakir** [comment]
@OrelHaim Missed it thanks.

**Comment by OrelHaim** [comment]
@dantavori please take a look at the changes I made in Workday.

**Review by bakatzir — APPROVED** [review]

**Pull request merged**
