### PR TITLE
Proofpoint TRAP improvements

### PR DESCRIPTION
**Pull request by reutshal**
## Status
- [] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/14821

## Description
* Improved the description of the 'expiration' argument
* Change the 'blacklist_ip/url/domain/hash' to be commands arguments rather than integration parameters since their only use is in the commands.

## Does it break backward compatibility?
   - [X] Yes
       - Removed integration parameters
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 
- [X] Code Review

### CODE REVIEW

**Comment by reutshal** [comment]
@ronykoz going to need force merge for this one

**Comment by reutshal** [comment]
@kirbles19 Can you please go over the following files:
YML - https://github.com/demisto/content/blob/proofpointTRAP-improvements/Beta_Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
CHANGELOG - https://github.com/demisto/content/blob/proofpointTRAP-improvements/Beta_Integrations/ProofpointThreatResponse/ProofpointThreatResponse_CHANGELOG.md

Thanks!

**Comment by kirbles19** [comment]
@reutshal Done.

**Comment by ronykoz** [comment]
@anara123 FYI this beta will break BC

**Comment by jochman** [comment]
@reutshal what is the status here?

**Comment by reutshal** [comment]
> @reutshal what is the status here?

Took this as a part of https://github.com/demisto/content/pull/5961, will be merged tomorrow.

**Pull request closed without merging**
