### PR TITLE
Align find email campaign script to native image

### PR DESCRIPTION
**Pull request by GuyAfik**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5249

## Description
This PR aligns the find email campaign to be able to use the native image as well

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JudahSchwartz** [comment]
please explain the change

**Review by JudahSchwartz — APPROVED** [review]

**Comment by GuyAfik** [comment]
> please explain the change

there is a very clear explanation in the issue so you can take a look :)

**Comment by JudahSchwartz** [comment]
@GuyAfik yeah i saw, I mean 
the method was renamed? at what version?

**Comment by GuyAfik** [comment]
> https://jira-hq.paloaltonetworks.local/browse/CIAC-5249

yeah looks like it was done here in 1.2.0 - https://github.com/scikit-learn/scikit-learn/pull/24395

**Pull request merged**
