### PR TITLE
[sixgill-195] darkfeed pack 13 7 2020

### PR DESCRIPTION
**Pull request by BenSterenson**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Sixgill Pack - includes dashboard, widgets, playbook.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [x] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [x] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by guykeller** [comment]
As far as I'm concerned the changes can be approved, pending a quick demo of the script and changes to the integration.
Reaching out on Slack to schedule a demo.
@michalgold - any notes from your side?

**Comment by guykeller** [comment]
Approving the changes from my side, but agreed with @BenSterenson to wait for the review of @michalgold before merging.

**Comment by michalgold** [comment]
@BenSterenson please change playbooks to be fromversion 5.5.0. 
Otherwise, looks good.

**Comment by fvigo** [comment]
@guykeller is it ready to merge?

**Pull request merged**
