### PR TITLE
Wf handle file type error gracefully and detonate playbook xml --> ooxml

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/17497
fixes: https://github.com/demisto/etc/issues/17107

## Description
please see related issue for docs reference.

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - soon
- [x] Code Review

### CODE REVIEW

**Comment by bakatzir** [comment]
@kirbles19 
Added a parameter to suppress file type errors that come from WF.
yml:
https://github.com/demisto/content/blob/7847bf391692a3f26c825ba87b7f5576d0d70d37/Playbooks/playbook-Detonate_File_-_WildFire.yml

**Comment by kirbles19** [comment]
I don't have edit permissions, please add me to the branch.

Does the entire playbook need to be reviewed, or only the new parameter and
RN?

*Alex Fiedler* | Manager, Technical Documentation | Demisto
Palo Alto Networks
Cell: +972-52-4474126
Email: afiedler@paloaltonetworks.com

**Comment by bakatzir** [comment]
@kirbles19 only the new parameter and the RN.

**Comment by bakatzir** [comment]
If you can't edit, just comment on the pr itself and I'll fix.

**Comment by bakatzir** [comment]
@yuvalbenshalom changed param desc and RN according to alex.

**Pull request merged**
