### PR TITLE
Add Xpanse MP to Jira Pack

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3213

## Description
Need to get Jira in Xpanse marketplace for testing before content release

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@anas-yousef , not sure what these validation error are about.  Can you help please?

Do I need release notes for this change or no?

**Comment by anas-yousef** [comment]
Hey @johnnywilkes,
Thank you for your contribution!
Of course, I'll take a look at the failing build steps and check what needs to be done to fix them.
I'll update you

**Comment by anas-yousef** [comment]
Hello @johnnywilkes,
I have noticed that the following content items are only for the XSOAR marketplace:
1. The two [layouts](https://github.com/demisto/content/tree/master/Packs/Jira/Layouts)
2. The [Jira Created Time](https://github.com/demisto/content/blob/master/Packs/Jira/IncidentFields/Jira_created_time.json) incident field
Do you also want them?

**Comment by johnnywilkes** [comment]
> Hello @johnnywilkes, I have noticed that the following content items are only for the XSOAR marketplace:
> 
> 1. The two [layouts](https://github.com/demisto/content/tree/master/Packs/Jira/Layouts)
> 2. The [Jira Created Time](https://github.com/demisto/content/blob/master/Packs/Jira/IncidentFields/Jira_created_time.json) incident field
>    Do you also want them?

Neither of these are important at this time

**Pull request merged**
