### PR TITLE
splunk fetch configure time zone support

### PR DESCRIPTION
**Pull request by meirwah**

### CODE REVIEW

**Comment by orius123** [comment]
why +180 and not +3 and we will multiply by 60?
and you should validate so we wouldn't get exceptions IMHO

**Comment by aviadl** [comment]
Because there are time zones in half hours as well

**Comment by orius123** [comment]
Than you can treat it as a float. it will work with 180 it's just less clear

**Comment by aviadl** [comment]
This is how our system works in all places

**Comment by Spivaka** [comment]
@meirwah are you going to merge this?

**Pull request merged**
