### PR TITLE
Test playbooks format fixes

### PR DESCRIPTION
**Pull request by roysagi**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related : https://github.com/demisto/etc/issues/23712

Fixing format for all test playbooks

### CODE REVIEW

**Comment by hod-alpert** [comment]
I believe we decided to remove the validation for test playbooks so fixing test playbooks for validation is nice to have but not a must, right @anara123 ?

**Comment by ronykoz** [comment]
@hod-alpert @anara123 checking the scheme should be important, not a must but important IMO

**Comment by anara123** [comment]
@ronykoz right now schema of test playbook fails on non existing descriptions. There is no need to  require description for test playbooks. If we create separate schema for test playbooks, then it is ok. But if not, lets remove validation for test playbooks

**Comment by roysagi** [comment]
ok closing this PR and I'll add a schema for test playbooks to my validation improvements

**Pull request closed without merging**
