### PR TITLE
test playbook fix

### PR DESCRIPTION
**Pull request by adiozer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29087

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [X ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X ] No

## Must have
- [ X] Tests
- [X ] Documentation

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
@adiozer Please up the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**Comment by orhovy** [comment]
Please make sure to register your contribution by filling the contribution registration form [.](https://forms.gle/XDfxU4E61ZwEESSMA)
Only after filling it we can proceed the review process.

**Review by orhovy — APPROVED** [review]

**Comment by ShahafBenYakir** [comment]
Hi there @adiozer Seems like there is a bug in the way the token is passed in the integration.
If I give: `mytoken123` the integration fails however if I pass `Basic mytoken123:` it succeeds... Let's just change it like this:
This:
Settings 2020-10-08 19-11-51

Should change to this:
Settings 2020-10-08 19-13-00

**Comment by adiozer** [comment]
@ShahafBenYakir 
The token contains the work "Basic". the right way is to pass "Basic mytoken123" as you did.

**Comment by ShahafBenYakir** [comment]
Hi @adiozer, It is a bit weird but I understand what you are saying, thanks.

**Pull request merged**
