### PR TITLE
Microsoft Graph - improved authentication flow

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

## Description
Improved OAUTH2 authentication flow.

## Required version of Demisto
Any

## Does it break backward compatibility?
   - Yes - @gshriki FYI
       - Further details: Remove a parameter and added required parameter
                                     This is a must, in order to make this process to be right.

## Must have
- [x] Tests
- [ ] Documentation - will work with @kirbles19 to update documentation ASAP
- [ ] Code Review

## Dependencies
None

## Additional changes
Removed a command which is no longer necessary.

### CODE REVIEW

**Comment by gshriki** [comment]
@Itay4  - what will be the experience of a customer with this integration enabled once this is updated on his system?

**Comment by Itay4** [comment]
@gshriki similar to Slack integration, with the exception that the user will have to login with his Microsoft account and authorise Demisto app to access the security data (i.e. microsoft graph alerts)

**Comment by gshriki** [comment]
Need to make sure this is clearly identified as breaking change in the release notes.

**Comment by gshriki** [comment]
including - what changed, what will be the experience and what customers need to do to resolve
@anara123 @Itay4

**Pull request merged**
