### PR TITLE
added new widget for showing new incidents per week

### PR DESCRIPTION
**Pull request by ronykoz**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18865

## Description
New widget for showing new incidents per week

### CODE REVIEW

**Comment by ronykoz** [comment]
@kirbles19 could you please go over everything but the .py file please?
BTW the empty changelog is meant to be this way, because it is used only for the widget itself

**Comment by aviadl** [comment]
@ronykoz this is not the correct way to do this (I think) 
You can come over an i will show you what i did in some other places

**Comment by kirbles19** [comment]
Done.

**Comment by yaakovi** [comment]
@ronykoz any updates here?

**Comment by Itay4** [comment]
@ronykoz ?

**Comment by yaakovi** [comment]
@ronykoz stale?

**Pull request closed without merging**
