### PR TITLE
packs/Reco: add change alert status command

### PR DESCRIPTION
**Pull request by GalNakash-RecoLabs**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by mmhw — COMMENTED** [review]
Hi @GalNakash-RecoLabs,
Thank you for your contribution!
Good work :)

**Comment by mmhw** [comment]
Please add a unit test for your new command.

**Comment by GalNakash-RecoLabs** [comment]
> Please add a unit test for your new command.

DONE

**Review by mmhw — APPROVED** [review]
Nice!

**Pull request merged**
