### PR TITLE
Include hrefs provided by API in formatted results

### PR DESCRIPTION
**Pull request by luis261**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Make the URLScan Integration add the content of hrefs in the HTML of the scanned site to the playbook context when running the "url" automation

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by luis261** [comment]
Signed the CLA and filled out the contribution registration. @omerKarkKatz let me know if you need anything else

**Comment by heipei** [comment]
Looks good, fine to be merged from our end.

**Review by omerKarkKatz — COMMENTED** [review]
Hey @luis261, 
Thanks a lot for your contribution looks great. 
There are a few suggestions and files that need to be added, in order for this PR to be approved. 
1. Bump the version by a revision in the metadata.json file of the pack (1.2.4). 
2. Add in the ReleaseNotes folder of the pack a new file 1_2_4.md and specify your changes for other users to be aware of. please look here for extra data on release notes in XSOAR content. https://xsoar.pan.dev/docs/documentation/release-notes
3. Add a unit test checking and validating your addition to the original code. 
If you have any questions or need any help please feel free to reach out here or via slack.
Thanks again @omerKarkKatz

**Comment by luis261** [comment]
@omerKarkKatz
  
I just bumped the version and added release notes as specified. Regarding the unit tests: I could not find any existing tests for the `format_results` function other than the one that tries to cover endless loops.
  
Since I don't see any tests for the general output/behavior of the function adding a test for my change would mean having to completely set up that sort of testing including any mocking etc. that might be necessary, which is out of scope for me rn
  
If someone more involved with demisto and the URLScan integration wants to tackle that, I'd try to contribute as well, otherwise I think the coverage of the function will remain nonexistent ...

**Comment by luis261** [comment]
There seems to be a problem regarding the docker image tag in `UrlScan.yml`. I guess I should just update it to `3.10.8.39276`?

**Comment by omerKarkKatz** [comment]
Hey @luis261, 
I made you a test template that you can use in order to check your code. Please add under the test_data folder relevant mocked data for the links, and check in the template that the response retunes accordingly. 
About the docker yes please bump the version. 
If you need any help please reach out here or via slack. 
Thanks again! 

Template code to add to UrlScan_test.py
def test_format_results_check_lists(mocker): 
    from UrlScan import format_results, Client
    client = Client()

    with open('./test_data/capitalne.json', 'r') as f:
        response_data = json.loads(f.read())
    
    mocker.patch('UrlScan.urlscan_submit_request', return_value=(response_data,'',''))
    mocker.patch.object(demisto, 'results', return_value='')
    command_results_inputs = mocker.patch('UrlScan.CommandResults')

    format_results(client, 'uuid', '')
    outputs = command_results_inputs.call_args[1]['outputs']['URLScan(val.URL && val.URL == obj.URL)']
    assert outputs.get('links') == {}

**Comment by luis261** [comment]
Hi @omerKarkKatz,

thanks for your template, appreciate it! I added a test case for my code and it seems like it succeeded. Only problem now is Flake8 whining bc of missing whitespace, I'll go ahead and fix that and also bump the docker tag and we should be good to go I think

**Comment by omerKarkKatz** [comment]
@luis261 thank you for the modifications!

**Review by omerKarkKatz — APPROVED** [review]

**Pull request merged**
