### PR TITLE
change query cmd to mimecast-query cmd

### PR DESCRIPTION
**Pull request by meirwah**
change query cmd to mimecast-query cmd

### CODE REVIEW

**Comment by meirwah** [comment]
@JonathanMeler plz review

**Comment by meirwah** [comment]
@JonathanMeler don't forget this PR...

**Comment by JonathanMeler** [comment]
@meirwah iv'e merged the pr. and updated the scripts.
anything else?

**Comment by meirwah** [comment]
just verify that the scripts work now...

**Comment by JonathanMeler** [comment]
they're working just fine :)

**Pull request merged**
