### PR TITLE
Remove default value from long running port parameters

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/23744

## Description
Removed default values from long-running port parameters

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by DeanArbel** [comment]
@kirbles19 all the files of this PR require technical writer review

**Comment by kirbles19** [comment]
@DeanArbel Done.

**Comment by DeanArbel** [comment]
> Might break BC won't it?

Not really, since instances that were already created with that value should retain it.
Only newly created instances will have their value changed.

**Comment by ronykoz** [comment]
@yaakovi is this right? Not too sure about this one

**Pull request merged**
