### PR TITLE
added servicenow test playbook

### PR DESCRIPTION
**Pull request by yardensade**

### CODE REVIEW

**Comment by anara123** [comment]
@yardensade add here screenshot of the test playbook

**Comment by yardensade** [comment]
@anara123 
Here we go, ain't much to it :)
image

**Comment by anara123** [comment]
add verifycontext task, which should verify if the command exports the
correct output

**Comment by yardensade** [comment]
Current PR is closed until further advance with issue:
https://github.com/demisto/etc/issues/12678

**Pull request closed without merging**
