### PR TITLE
[tufin-3] Added six new actions to Tufin integration

### PR DESCRIPTION
**Pull request by jtmoran**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Six new actions added to the Tufin integration

## Minimum version of Demisto
- [ ] 4.5.0
- [x] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [x] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by jtmoran** [comment]
I have been working with Francesco on the back end and he told me not to 
worry about that error.

**Comment by jtmoran** [comment]
> The CircleCI build failed again. @jtmoran take a look at the build details [here](https://circleci.com/gh/demisto/content/51265?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) - and try and fix the issues so that we can merge your proposed changes as soon as possible.
> 
> #### Failed Build Steps
> * Store Artifacts to GCS

Working with Francesco V on this integration on the backend.  Francesco advised not to worry about this error and the integration could be submitted without resolving.

**Comment by fvigo** [comment]
@guykeller are we ready to merge this on Sunday for the 5/12 content release?

**Comment by guykeller** [comment]
@fvigo As far as I'm concerned we are ready to merge.
I'm not sure what is the Circle step that is failing here, will verify

**Pull request merged**
