### PR TITLE
MS Graph Mail - Headers Missing Bug

### PR DESCRIPTION
**Pull request by ChanochShayner**
…mage.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29404

## Description
Fixed an issue where the mail headers is empty.
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ChanochShayner** [comment]
@Itay4 before you changed the timestamp filter in fetch incidents there was no '$' before the filter - 'select'
And for some reason it made headers come back from API empty -

With `$` - empty headers - 
image
image


Same mail without `$` - 
image
image

**Comment by Itay4** [comment]
@ChanochShayner according to [microsoft docs](https://docs.microsoft.com/en-us/graph/query-parameters#select-parameter) it should be with `$`
what i think happens is that with `$` is actually beahves as intended and it outputs only the key fields, while the way it was before and now with the change in this PR, without `$`, it just ignores the `select` param
lets verify that with removing the `select` param and see what's returned and if it can be removed completely

**Comment by ChanochShayner** [comment]
@Itay4 If you remove the 'select' filter completely, the headers return empty, really weird.
image
image

**Comment by Itay4** [comment]
seems like a bug on graph api
lets add a comment in the code to clarify what we want to achieve by setting `select: *`

**Comment by ChanochShayner** [comment]
> seems like a bug in graph api
> lets add a comment in the code to clarify what we want to achieve by setting `select: *`

@Itay4 Done

**Review by ronykoz — APPROVED** [review]

**Pull request merged**
