### PR TITLE
CS falconhost threatgraph API support

### PR DESCRIPTION
**Pull request by bakatzir**
- ***cs-threatgraph-summary***
  - ***cs-threatgraph-processes***
  - ***cs-threatgraph-detections***

## Status
- [x] In Progress - customer validation

## Related Issues
fixes: https://github.com/demisto/etc/issues/10477

## Minimum version of Demisto
- [x] 2.5.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests - no
- [x] Documentation - not yet

### CODE REVIEW

**Comment by bakatzir** [comment]
@yuvalbenshalom 
Tended to the tables, outputs and DT merging in the commands.
Will add readme and rn in the new format after the review.

**Comment by bakatzir** [comment]
@kirbles19 :
[yml](https://github.com/demisto/content/blob/48f6c462851d278ecac7f78879b148348c465eee/Packs/CrowdStrikeHost/Integrations/integration-CrowdStrikeHost.yml)
[changelog](https://github.com/demisto/content/blob/48f6c462851d278ecac7f78879b148348c465eee/Packs/CrowdStrikeHost/ReleaseNotes/1_1_0.md)

**Comment by kirbles19** [comment]
@bakatzir Done

**Comment by bakatzir** [comment]
@yuvalbenshalom The marketplace build is failing, can't find dependencies. not sure if related to the PR or not.
```
The request to install packs has failed. Reason:
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Set-Cookie': 'S=EAYXcxOfQR0N5w6QhZyV0v8sTPsRZfqg+rL/30daUhb1VJHBNI/lhLT+0goc3HMAb318HBhnIAvhTuCDyh0C3kbfxbOYo6026KlktS3M/xGGZz89ip5bYFgjPR8pybDRG63QVZhl9dyCS87nivMV1exnMYgVY8hXawzlV9MQkvfeB1eYq9/9EF9BRrlcQvSKeVFdd0h/S2XsiApOzEx5; Path=/; Expires=Sat, 06 Jun 2020 10:35:55 GMT; Max-Age=3600; HttpOnly; Secure; SameSite=Lax, S-Expiration=MDYgSnVuIDIwIDEwOjM1ICswMDAw; Path=/; Expires=Sat, 06 Jun 2020 10:35:55 GMT; Max-Age=3600; Secure; SameSite=Lax', 'Strict-Transport-Security': 'max-age=10886400000000000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Xss-Protection': '1; mode=block', 'Date': 'Sat, 06 Jun 2020 09:35:55 GMT', 'Content-Length': '233'})
HTTP response body: {"id":"errInstallContentPack","status":400,"title":"Could not install content pack","detail":"Could not install content pack","error":"the following required dependencies are missing 'ProtectWise'","encrypted":false,"multires":null}
```

**Pull request merged**
