### PR TITLE
Sane-pdf-reports log command arguments 

### PR DESCRIPTION
**Pull request by ShahafBenYakir**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Comment by agamm** [comment]
@Bars92 @ShahafBenYakir I fixed the Verbosity, added a legacy argument and this should also fix the logos. Please check that this indeed works (It doesn't just debug now).

**Comment by ShahafBenYakir** [comment]
@agamm can I close this?

**Comment by agamm** [comment]
> @agamm can I close this?

What is this exactly? It seems to be conflicting too.

**Comment by ShahafBenYakir** [comment]
@agamm The branch I created for you to debug

**Comment by agamm** [comment]
> @agamm The branch I created for you to debug

Ohhh I see, no need then from my side :)

**Comment by ShahafBenYakir** [comment]
Closing

**Pull request closed without merging**
