### PR TITLE
Find similar incidents search v2

### PR DESCRIPTION
**Pull request by erezh31**
## Status
Ready

### CODE REVIEW

**Comment by meirwah** [comment]
@erezh31 this still fails

**Comment by erezh31** [comment]
@meirwah now it should be fine

**Comment by bakatzir** [comment]
@erezh31 only @kirbles19 edits the CHANGELOG. are you synced with him?

**Comment by erezh31** [comment]
@bakatzir yes he already review and edit that, you can see in the last commits

**Comment by erezh31** [comment]
@meirwah we can merge now

**Comment by yaakovi** [comment]
@meirwah @erezh31 
have you noticed your tests fails in circle?
please don't force-merge anything without informing content leaders
image
image

**Comment by meirwah** [comment]
https://github.com/demisto/content/pull/5372#issuecomment-576235789

**Pull request merged**
