### PR TITLE
Delinea dsv

### PR DESCRIPTION
**Pull request by roshani-delinea-github**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ShacharKidor** [comment]
Hi @roshani-delinea-github, 
Thank you for your contribution!
I've just seen that you opened a new PR for the same pack - [20574](https://github.com/demisto/content/pull/20574), does it mean that this PR is redundant? 
Please let me know which of those PRs is relevant, if one of them is a duplication of the other we will close the duplicated one. 
Thanks in advance :)
FYI - @YuvHayun, @JasBeilin

**Comment by roshani-delinea-github** [comment]
> Hi @roshani-delinea-github, Thank you for your contribution! I've just seen that you opened a new PR for the same pack - [20574](https://github.com/demisto/content/pull/20574), does it mean that this PR is redundant? Please let me know which of those PRs is relevant, if one of them is a duplication of the other we will close the duplicated one. Thanks in advance :) FYI - @YuvHayun, @JasBeilin

This PR is for the Delinea DSV pack and the other one 20574 is for Delinea secret server pack. Both are different integrations. Please, don't close any of the PR. Thanks.

**Comment by edik24** [comment]
Hello @roshani-delinea-github,
We will get to review this PR as soon as possible.

A quick note,
we do not support changing paths in our repo, you so you cannot rename the file paths.

You should change the display name in the metadata and it will show this name in the marketplace.
please revert file paths to the original ones.

**Comment by roshani-delinea-github** [comment]
> Hello @roshani-delinea-github, We will get to review this PR as soon as possible.
> 
> A quick note, we do not support changing paths in our repo, you so you cannot rename the file paths.
> 
> You should change the display name in the metadata and it will show this name in the marketplace. please revert file paths to the original ones.

Updated file paths

**Comment by roshani-delinea-github** [comment]
It is not possible for us to keep the folder name as Thycotic and do changes in the file because the validations suggest backward changes which are not possible to do. so I want to abandon this Pull request.

**Pull request closed without merging**
