### PR TITLE
[Marketplace Contribution]Introduce AdvancedGenericPolling Pack

### PR DESCRIPTION
**Pull request by mdrobniu**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Description
This pack introduces an automation called AdvancedGenericPolling.
AdvancedGenericPolling is an ScheduleCommand based alternative to GenericPolling. 
It introduces the following features:
- polling on a second basis (not minutes)
- Works with context and incident fields OOB
- Ability to exercise your DT/XT directly on the main Context Data
- Ability to trigger side playbook branches ( with reopen task)

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by mdrobniu** [comment]
@tomer-pan  @yaakovpraisler I have not done it in a while, please let me know what is missing or what can I do better.

**Review by yaakovpraisler — COMMENTED** [review]
Hey @mdrobniu, Thank you for your contribution!

A few points:
- After consulting with @tomer-pan, the playbook looks more like an example of how to use the AdvanceGenericPoling script with SNOW, we don't think we need to push it but every user will have the option to use it in his playbook according to his needs.
- I don't think we need a new pack for this feature, please add the script to the CommunityCommonScripts pack, bump its version, and add release notes.
- Please add a README file for this script describing the advanced features in this script.

Thank you for your cooperation!

**Comment by yaakovpraisler** [comment]
Hey @mdrobniu, are there any updates?
If you need any help feel free to reach out.

**Comment by yaakovpraisler** [comment]
Hi @mdrobniu, 
I have not received a response from you here in the last two weeks, so I will close the PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

**Pull request closed without merging**
