### PR TITLE
support tags in threatconnect integration

### PR DESCRIPTION
**Pull request by meirwah**
support tags in threatconnect integration

### CODE REVIEW

**Comment by meirwah** [comment]
@Spivaka can u plz review?

**Comment by Spivaka** [comment]
the tag and get indicator doesn't seem to send anything. is that ok??

**Comment by meirwah** [comment]
where do you see that? point to code plz...

**Comment by meirwah** [comment]
@Spivaka ?

**Comment by Spivaka** [comment]
Maybe I am not following but does indicators.retrieve() sends something? if yes, than forget what I wrote. If not I don't understand in which line the message goes out

**Comment by meirwah** [comment]
indicators.retrieve()  sends an GET request, to get iindicators

**Pull request merged**
