### PR TITLE
New IPv4 filters / transformers

### PR DESCRIPTION
**Pull request by tundisto**
## Status
Ready

## Related Issues
N/A

## Description
Added transformer script **IPv4Whitelist** - takes one or more IPv4 addresses and one or more CIDR ranges, and returns the IP's that match against one or more of the CIDR ranges

Added transformer script **IPv4Blacklist** - takes one or more IPv4 addresses and one or more CIDR ranges, and returns the IP's that doesn't match against any of the CIDR ranges

Added filter script **IsInCidrRanges** - similar to IPv4Whitelist but is used as a filter rather than a transformer (returns bool)

Added filter script **IsNotInCidrRanges** - similar to IPv4Blacklist but is used as a filter rather than a transformer (returns bool)

Added filter script **IsRFC1918Address** - wrapper script around IsInCidrRanges which checks if an address is in RFC-1918 private address space -- 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
N/A

## Required version of Demisto
4.x / 5.x

## Does it break backward compatibility?
No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
None

### CODE REVIEW

**Comment by Itay4** [comment]
@tundisto please convert all scripts to directory package format

**Comment by tundisto** [comment]
Converted to package format.

**Comment by Itay4** [comment]
please review the following YAMLs
https://github.com/demisto/content/blob/dc7b5b8fc86f0f40eea8a5413d60b35cbfa49053/Scripts/IPv4Blacklist/IPv4Blacklist.yml
https://github.com/demisto/content/blob/dc7b5b8fc86f0f40eea8a5413d60b35cbfa49053/Scripts/IPv4Whitelist/IPv4Whitelist.yml
https://github.com/demisto/content/blob/dc7b5b8fc86f0f40eea8a5413d60b35cbfa49053/Scripts/IsInCidrRanges/IsInCidrRanges.yml
https://github.com/demisto/content/blob/dc7b5b8fc86f0f40eea8a5413d60b35cbfa49053/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.yml
https://github.com/demisto/content/blob/dc7b5b8fc86f0f40eea8a5413d60b35cbfa49053/Scripts/IsRFC1918Address/IsRFC1918Address.yml

**Comment by Itay4** [comment]
@tundisto please note [the build](https://circleci.com/gh/demisto/content/31328) fails

**Comment by tundisto** [comment]
I see that.  Please provide guidance on how to deal with it.

`You have failed to update id_set.json with the data of Scripts/IPv4Blacklist/IPv4Blacklist.yml please run `python Tests/scripts/update_id_set.py`
The ID IPv4Whitelist already exists, please update the file or update the id_set.json toversion field of this id to match the old occurrence of this id`

**Comment by Itay4** [comment]
> I see that. Please provide guidance on how to deal with it.
> 
> `You have failed to update id_set.json with the data of Scripts/IPv4Blacklist/IPv4Blacklist.yml please run `python Tests/scripts/update_id_set.py` The ID IPv4Whitelist already exists, please update the file or update the id_set.json toversion field of this id to match the old occurrence of this id`

Screen Shot 2019-10-22 at 13 28 00

**Comment by kirbles19** [comment]
@tundisto @Itay4 Done.

**Comment by tundisto** [comment]
@Itay4 CI tests finally succeeding.  Ready for your review

**Comment by tundisto** [comment]
@Itay4 did as you requested and build is now failing on content descriptor and content artifacts

**Pull request merged**
