### PR TITLE
powershell remoting

### PR DESCRIPTION
**Pull request by glicht**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Re-open of work done by @yardensade . Converted to Pack format.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [x] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by yardensade** [comment]
I will take it this weekend, might not be able to provide multiple sessions connection at first tho.

**Comment by vik-patel** [comment]
@yardensade any updates on ETA? ... thx Vik

**Comment by yardensade** [comment]
Not much to be honest, initially we planned to make it so we can remote into multiple machines at once, but it creates some complexity which requires more attention which I cannot give at the moment. So I will we will start with a release of a version that can remote into a single machine just so we release something useful and we can kind of take it form there and enhance it after once I get some time to sit on it.

That being said this is currently not a priority for me due to marketplace work.

**Comment by yardensade** [comment]
Move to https://github.com/demisto/content/pull/7028

**Pull request closed without merging**
