### PR TITLE
Darktrace: Patch post request

### PR DESCRIPTION
**Pull request by JustasZDT**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Fixing an issue where DarktraceMBs actions requiring HTTP POST would fail when the target instance is a Darktrace Unified View instance.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ilappe** [comment]
Hi @JustasZDT
thanks for contributing our repo!
please make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

**Comment by JustasZDT** [comment]
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @ilappe will know the proposed changes are ready to be reviewed. For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

Thanks, that's done now.

**Review by ilappe — APPROVED** [review]
Thanks @JustasZDT for the contribution!

**Comment by ilappe** [comment]
validation issues will be fixed in the internal PR

**Pull request merged**
