### PR TITLE
Critical high report bug fix

### PR DESCRIPTION
**Pull request by Bargenish**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22145

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by yaakovi** [comment]
Add screenshots/sample files of before and after the fix

**Comment by Bargenish** [comment]
Before:
Screen Shot 2020-03-22 at 14 24 39


After:
Screen Shot 2020-03-22 at 14 23 42

**Comment by kirbles19** [comment]
@Bargenish Done.

**Comment by agamm** [comment]
@Bargenish did you check other reports in `Reports/report-*.json` for the same problem?

**Comment by Bargenish** [comment]
yes, I've noticed that almost every PDF JSON report doesn't have the readableHeaders field (the docx reports are fine) but I don't know which reports are in use.
Would you like me to add the readable headers elsewhere?

**Comment by agamm** [comment]
@Bargenish I think that the default reports should all have them. @Bars92 what do you think? and where can he see all of the default used ones?

**Comment by Bars92** [comment]
yeah you are right @agamm it should be in all the pdf reports. @Bargenish mostly all the reports without the `old` suffix and all reports with `fromVersion: 3.5.0`

**Comment by yaakovi** [comment]
@Bargenish please open another PR for the rest of the reports.
@agamm @Bars92 thanks for catching that.

**Pull request merged**
