### PR TITLE
Added fix to cast NaN to None

### PR DESCRIPTION
**Pull request by ShahafBenYakir**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/25928

## Description
When not all values were present in context the script crashed.

### CODE REVIEW

**Comment by Itay4** [comment]
@roysagi please review rn

**Comment by Itay4** [comment]
@ShahafBenYakir can we a test here?

**Comment by ShahafBenYakir** [comment]
failing build due to UT 
https://circleci.com/gh/demisto/content/60248#queue-placeholder/containers/1

**Comment by ShahafBenYakir** [comment]
Build passed all validations and it is already passed all tests several times before, however, every time we come to merge this we have a conflict (people merge in between) therefore I am force merging this.

**Pull request merged**
