### PR TITLE
Hod/fix validations failures

### PR DESCRIPTION
**Pull request by hod-alpert**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
demisto/etc#23233

## Description
In this PR there are two main changes:
1. Changing yml files versions to -1
2. Renaming description file

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by Itay4** [comment]
rename `Cisco-umbrella-description.md` to `/Cisco-umbrella_description.md`

**Comment by Itay4** [comment]
@hod-alpert resolve conflicts please

**Comment by hod-alpert** [comment]
@Itay4 Resolved

**Comment by Itay4** [comment]
build failed due to non-related tests
merging

**Pull request merged**
