### PR TITLE
SpyCloud Enterprise Protection initial commit

### PR DESCRIPTION
**Pull request by amshamah419**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by amshamah419** [comment]
@loginsoft-integrations I got this PR setup since the other was getting messy. Please review the errors found in the validation. It looks like the mapper and layout are looking for a field which doesn't exist.

```bash
[2024-02-06 09:34:44,839] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Layouts/layoutscontainer-SpyCloudBreachLayout.json: [GR103] - Content item 'SpyCloud Breach Layout' using content items: 'spycoudseverity' which cannot be found in the repository.

[2024-02-06 09:34:44,840] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Layouts/layoutscontainer-SpyCloudMalwareLayout.json: [GR103] - Content item 'SpyCloud Malware Layout' using content items: 'spycoudseverity' which cannot be found in the repository.

[2024-02-06 09:34:44,840] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Classifiers/classifier-SpyCloud_Mapper.json: [GR103] - Content item 'SpyCloud - Incoming Mapper' using content items: 'SpyCloud User Hostname' which cannot be found in the repository.
```

Once we are passing, then the merge should be fairly straightforward

**Comment by loginsoft-integrations** [comment]
> @loginsoft-integrations I got this PR setup since the other was getting messy. Please review the errors found in the validation. It looks like the mapper and layout are looking for a field which doesn't exist.
> 
> ```shell
> [2024-02-06 09:34:44,839] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Layouts/layoutscontainer-SpyCloudBreachLayout.json: [GR103] - Content item 'SpyCloud Breach Layout' using content items: 'spycoudseverity' which cannot be found in the repository.
> 
> [2024-02-06 09:34:44,840] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Layouts/layoutscontainer-SpyCloudMalwareLayout.json: [GR103] - Content item 'SpyCloud Malware Layout' using content items: 'spycoudseverity' which cannot be found in the repository.
> 
> [2024-02-06 09:34:44,840] [ERROR] /home/circleci/project/Packs/SpyCloudEnterpriseProtection/Classifiers/classifier-SpyCloud_Mapper.json: [GR103] - Content item 'SpyCloud - Incoming Mapper' using content items: 'SpyCloud User Hostname' which cannot be found in the repository.
> ```
> 
> Once we are passing, then the merge should be fairly straightforward

Hi @amshamah419 
changes done

**Comment by amshamah419** [comment]
@loginsoft-integrations Since I pushed the commits, I need another dev to approve so I can continue. I've asked Yuval to help us out and afterwards I'll handle the internal PR

**Review by yuvalbenshalom — APPROVED** [review]

**Review by melamedbn — APPROVED** [review]

**Comment by amshamah419** [comment]
@loginsoft-integrations You guys have signed the CLA yes? Just trying to see if this will just require a force merge so we can progress it.

**Comment by RamboV** [comment]
> @loginsoft-integrations You guys have signed the CLA yes? Just trying to see if this will just require a force merge so we can progress it.

Hi @amshamah419 
For this new PR, we completed the signing of the CLA earlier today.

**Pull request merged**
