### PR TITLE
Mcafee TIE Documentation

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18151

## Description
Creating a documentation of McAfee-TIE

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by orlichter1** [comment]
@kirbles19 Hi Alex. [This](https://github.com/demisto/content/edit/mcafee-tie-documantation/Integrations/McAfee-TIE/McAfee-TIE.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F3994) is the link to the .md
[This](https://github.com/demisto/content/edit/mcafee-tie-documantation/Integrations/McAfee-TIE/McAfee-TIE.py?pr=%2Fdemisto%2Fcontent%2Fpull%2F3994) is the link to the .yml
Could you please review them?

**Comment by kirbles19** [comment]
@orlichter1 .yml and .md reviewed, all done.

**Comment by orlichter1** [comment]
This is only packaging. The issue was documentation

**Comment by orlichter1** [comment]
@yaakovi done with the changes

**Pull request merged**
