### PR TITLE
[code42-363] Add Else to Download File playbook and upgrade docker file

### PR DESCRIPTION
**Pull request by unparalleled-js**
## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [x] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Issue from slack partner channel.

## Description
Adds missing else case to the Code42 Download File Playbook, formats the playbook. These changes also update the py42 dockerfile and use the newly available constants.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by reutshal — COMMENTED** [review]
Hi @unparalleled-js!
Overall looking great.
When can we schedule a quick demo with you?
@mayagoldb FYI

**Comment by unparalleled-js** [comment]
> Hi @unparalleled-js!
> Overall looking great.
> When can we schedule a quick demo with you?
> @mayagoldb FYI

Early mornings my time is 3:00 pm - 5:00pm Israel time is good for me, any day.
Note that it will be a pretty simple demo. The other things that have really changed are bug fixes as as well adding a missing Else condition in one of the playbooks.

**Comment by mayagoldb** [comment]
@unparalleled-js 
Comments about the playbook:
1) The else case you should add is for the `Is Code42 Integration Active?`, so if the integration is not active it will finish the playbook's run. In the PR you added a link from the trigger to the end task which should be removed.

**Comment by unparalleled-js** [comment]
> @unparalleled-js
> Comments about the playbook:
> 
> 1. The else case you should add is for the `Is Code42 Integration Active?`, so if the integration is not active it will finish the playbook's run. In the PR you added a link from the trigger to the end task which should be removed.

Whoops!  Okay, it is correct now.

**Review by mayagoldb — APPROVED** [review]

**Review by reutshal — APPROVED** [review]

**Pull request merged**
