### PR TITLE
Use handle_proxy() in all requests in SplunkPy integration.

### PR DESCRIPTION
**Pull request by ag3ntsc4rn**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
It's a standard across integrations to use the common server method 'handle_proxy'. The SplunkPy integration has 3 requests.post call and it was relying on the older method of checking `if not proxy: then do this or that`. This PR sets a variable `PROXIES=handle_proxy()` in the beginning of the file and everywhere there is a requests call adds `proxies=PROXIES` to it.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by guykeller** [comment]
@ag3ntsc4rn 
Looks good, could you please fix flake8 errors?

**Comment by ag3ntsc4rn** [comment]
Thanks @guykeller, I have fixed the flake8 errors. There is however one error
`./Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py:236:5: F841 local variable 'response' is assigned to but never used`

This is something that was not introduced by this PR.

**Comment by ronykoz** [comment]
@ag3ntsc4rn seems that we are missing the CLA signing, we will be able to merge only after you sign that document(Allowing us to use your code)

**Comment by ag3ntsc4rn** [comment]
Hi @ronykoz , I have signed it, but I have no idea why it does not reflect in this PR.

**Comment by ronykoz** [comment]
@ag3ntsc4rn was it signed with the same mail of your github account?

**Comment by ag3ntsc4rn** [comment]
@ronykoz - Nope. It was signed with the same email. I do have email settings to private. Wonder if that has something to do with it.

**Comment by ronykoz** [comment]
@ag3ntsc4rn i can think of two options:
1. the commit was done from a different account - meaning the commit before github, which can hopefully get solved quickly 
2. there is a problem in github regarding the authentication than due to the small nature of the fix we might be able to open an internal PR if that's ok by you.

**Comment by ag3ntsc4rn** [comment]
Sounds good to me. Appreciate the help @ronykoz!

**Comment by guykeller** [comment]
Hi @ag3ntsc4rn ,
Same here - I'd be very happy to set up a call and help you generate the release notes for this PR and get this merged.
Just let me know which platform can we schedule on (email or Slack) and I'll love to help.

**Comment by guykeller** [comment]
If you'd like, you can simply update your demisto-sdk version and run the `update-release-notes` command which should solve the problem.
More information can be found [here](https://xsoar.pan.dev/docs/integrations/changelog)

**Comment by ag3ntsc4rn** [comment]
I have uploaded the RN. The CLA is still complaining. I give up. lol.

**Pull request merged**
