### PR TITLE
EWS get-items-from-folder support item attachment

### PR DESCRIPTION
**Pull request by erezh31**
Add flag to show attached item instead of the external item.
See doc issue demisto/etc#16594 for details

### CODE REVIEW

**Comment by erezh31** [comment]
I did manual test run, over "Inbox\test" folder in demisto lab account.
Documentation is same as the description:
If the email item contains another email as attachment - get the internal email attachment (common use in a phishing mailbox)

**Comment by BenJoParadise** [comment]
Anar did not approve it for this release, so it will be part of the next release. We will work on merging it regardless.

**Comment by erezh31** [comment]
ok, NP we can wait to the next release

**Comment by BenJoParadise** [comment]
Opened doc issue https://github.com/demisto/etc/issues/16594
@IkaDemisto will add a test case in the EWSv2 test playbook and test it manually.

**Comment by erezh31** [comment]
@BenJoParadise plz review

**Comment by yardensade** [comment]
What is the status here?

**Comment by IkaDemisto** [comment]
Looks abandon. @erezh31 is it still relevant to you?

**Comment by erezh31** [comment]
Yes

**Comment by erezh31** [comment]
Yes

**Comment by IkaDemisto** [comment]
@erezh31 if it's relevant for you, make sure to merge it.

**Comment by erezh31** [comment]
@IkaDemisto @BenJoParadise has conflicts ^, we need to fix and merge plz

**Comment by erezh31** [comment]
have new PR

**Pull request closed without merging**
