### PR TITLE
Added the instructions to connect to Microsoft Sentinel

### PR DESCRIPTION
**Pull request by spearmin10**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Added the instructions to connect to Microsoft Sentinel

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShacharKidor** [comment]
Hi @Ni-Knight,
As we discussed, please verify the instructions that were added to the README file.

**Review by ShacharKidor — COMMENTED** [review]
Hi @spearmin10, 
Thank you for your contribution!
Please fille in the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form.

**Comment by tschanfeld** [comment]
@ShacharKidor doc review is complete

**Comment by spearmin10** [comment]
@Ni-Knight Setting to **Collection JSON** has been removed by the review. I've re-added it.

**Pull request merged**
