### PR TITLE
QRadar - Limit the amount of data fetched in one call

### PR DESCRIPTION
**Pull request by Spivaka**

### CODE REVIEW

**Comment by Spivaka** [comment]
You are right about the test. will limit.
about the call - whoever calls it can limit. don't think we should hard-code limit it

**Comment by aviadl** [comment]
@Spivaka what about this pr ?

**Comment by aviadl** [comment]
@Spivaka what is this waiting for ?

**Comment by liorkol** [comment]
@Spivaka @aviadl Ping :)

**Pull request merged**
