### PR TITLE
[malwarebytes-254] Fixed an IndexError issue with ***!malwarebytes-list-endpoint-info*** command. GI-1278 

### PR DESCRIPTION
**Pull request by rskumar-mwb**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by RosenbergYehuda — COMMENTED** [review]
Hello @rskumar-mwb,

Great work on this bug fix! I added one minor comment - please take a look when you have a chance.

Since this was a bug fix, did you consider adding a unit test to ensure the issue does not reoccur if someone modifies the code in the future? Adding tests for fixes like this can help prevent potential regressions.

Please let me know if you have any other questions! I appreciate you contributing this fix to improve our content.

Regards, Yehuda

**Comment by rskumar-mwb** [comment]
@RosenbergYehuda The unit tests are already there for the function where the bug fix was made. So if anyone modifies the function in the future, the unit test will fail. Thanks. https://github.com/rskumar-mwb/content/blob/master/Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_test.py#L816 https://github.com/rskumar-mwb/content/blob/master/Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_test.py#L1201

**Comment by RosenbergYehuda** [comment]
Hello @rskumar-mwb,

Thank you for your response. I don't think I explained clearly enough - since you had a bug but all unit tests passed, that means the existing tests did not cover the case that caused the bug. Now that you've fixed the code but not added any new tests, if someone in the future removes the code you added, the tests won't fail to alert that the bug was reintroduced.

That's why I recommend in cases of a bug fix to add unit tests that 'lock in' the code changes. This helps prevent future regressions.

I want to mention that due to the holiday season in Israel, our team will be out of the office until next Tuesday the 26th. Please feel free to address that comment at your convenience, and I will review again when I'm back.

Thank you again for your contribution, I look forward to getting it merged once I return from the holiday break. Enjoy your weekend!

**Comment by rskumar-mwb** [comment]
@RosenbergYehuda Thanks for the explanation, I understand now. I have added the unit tests covering the new code changes for the bug. Please review and let me know.

**Review by RosenbergYehuda — APPROVED** [review]
Hello @rskumar-mwb, this PR is approved!

Last thing:
I would like to understand the bug fix better - could you please send a short video showing:

The version before your fix, demonstrating the bug
This fixed version, showing how the bug is now resolved

This will help me verify that the issue is fully addressed. 

Please let me know if you have any other questions!

**Comment by rskumar-mwb** [comment]
@RosenbergYehuda 

Please see the videos below before and after the fix,


https://github.com/demisto/content/assets/48316606/1c85bf57-a2e9-4411-9b41-7d46b67ae61f


https://github.com/demisto/content/assets/48316606/81a09db5-a04a-4f4f-92ed-2ae5bd92b3e0

Thanks.

**Pull request merged**
