### PR TITLE
Create Internal PR - add contribution label + contributor username to template

### PR DESCRIPTION
**Pull request by tallieber**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [37626](https://github.com/demisto/etc/issues/37626)
[38530](https://github.com/demisto/etc/issues/38530)

## Description
1. Added Contribution label to any open internal PR. 
2. Added Contributor section to internal PR body, if this section does not exist on the external PR. 

## Screenshots
Text organization when adding the contributor section.

Screen Shot 2021-07-28 at 10 19 36

### CODE REVIEW

**Review by ShahafBenYakir — COMMENTED** [review]
Looks ok on my end

**Comment by ShahafBenYakir** [comment]
FYI @Shellyber

**Comment by Shellyber** [comment]
Looks good!

**Review by bakatzir — APPROVED** [review]

**Comment by tallieber** [comment]
Added @ before the contributor user name. @Shellyber @ShahafBenYakir FYI

**Comment by Shellyber** [comment]
@tallieber even better!

**Pull request merged**
