### PR TITLE
FortiGuard Threat Intel & Enrichment

### PR DESCRIPTION
**Pull request by Aceilies**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
New Integration

## Description
Integration with FortiGuard Threat Intel to Fetch Indicators and Query URL Categories 

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by amshamah419** [comment]
@Aceilies Great work! Let's set up a demo call and we can go over the PR.

**Comment by Aceilies** [comment]
Sure, lets do it

**Comment by Aceilies** [comment]
@amshamah419 Yeah sure lets schedule a call

**Comment by amshamah419** [comment]
Hi @Aceilies,

Last Thursday, December 20th, there was an update in the content repo. This is why your PR looks like there were a lot of commits and files changed.
Please open a new PR to fix this issue.

Thank you very much for your contribution and your understanding of the situation.
Have a nice holiday season!

**Pull request merged**
