### PR TITLE
hiding d2

### PR DESCRIPTION
**Pull request by DinaMeylakh**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4637)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
Build is failing let's invastigate

**Review by ShahafBenYakir — COMMENTED** [review]
Looks good. 
Can we add some test cases?
Let's trigger a Nightly and Upload test build to validate this change (we are changing a core component)

**Comment by DinaMeylakh** [comment]
test upload flow - https://code.pan.run/xsoar/content/-/pipelines/4150906
nightly - https://code.pan.run/xsoar/content/-/pipelines/4150772

**Review by ShahafBenYakir — APPROVED** [review]

**Comment by DinaMeylakh** [comment]
@esharf This is the pr I run the Nightly that failed on
https://code.pan.run/xsoar/content/-/jobs/19344062

**Comment by DinaMeylakh** [comment]
yet another problematic nightly run can be found [here](https://code.pan.run/xsoar/content/-/pipelines/4196677)

**Pull request closed without merging**
