### PR TITLE
QRadar support 7.3.2 patch 3

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
In progress (Waiting @kirbles19 )

## Related Issues
fixes: https://github.com/demisto/etc/issues/18473

## Description
Removed SEC header if token was not provided. This should remediate issues encountered in version 7.3.2 patch 3.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Code Review

### CODE REVIEW

**Comment by DeanArbel** [comment]
This fix was tested to work and fix the issue on the reporting customer's instance (for more details please contact me privately).

**Comment by DeanArbel** [comment]
@kirbles19 please review https://github.com/demisto/content/edit/qradar-sec-header/Integrations/QRadar/CHANGELOG.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F4067

**Comment by DeanArbel** [comment]
> No sensitive data logged here?

The api token might be logged if it's used instead of a username/password - I'll address this

**Comment by kirbles19** [comment]
@DeanArbel Done. Please read my commit comments.

**Pull request merged**
