### PR TITLE
Fix tanium test error

### PR DESCRIPTION
**Pull request by shaniacht1**
## Status
ready

## Related Issues
fixes https://github.com/demisto/etc/issues/16202

## Description
Added log messages to all commands accessing Pytan
Removed "get all packages" test from the integration test. 

## Does it break backward compatibility?
   - No

## Must have
- [ ] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
Can we add to the test something instead, which does not require non-admin permissions?

**Comment by shaniacht1** [comment]
@Itay4 let me know what you think (I made it user configurable so we don't run into other unexpected permission issues

**Comment by Itay4** [comment]
@shaniacht1 dont really think we need a param just for the test, can't we just use the default one you added there?

**Comment by Itay4** [comment]
@shaniacht1 what do you say?

**Comment by shaniacht1** [comment]
@Itay4 done

**Pull request merged**
