### PR TITLE
Partner Armis adopt complete

### PR DESCRIPTION
**Pull request by crestdatasystems**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
PR for adoption process completion for Amris pack. Previously raised #20284 for starting adoption process.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by dorschw** [comment]
Hey @crestdatasystems, thank you for the contribution!

Reviewing this PR will be slightly delayed as we are in the midst of the local holiday season. We'll have a look as soon as we're back at work. 

PS - please use a 120x50 image with transparent background as author_image.png, per the [standards](https://xsoar.pan.dev/docs/integrations/integration-logo).

**Comment by crestdatasystems** [comment]
> Hey @crestdatasystems, thank you for the contribution!
> 
> Reviewing this PR will be slightly delayed as we are in the midst of the local holiday season. We'll have a look as soon as we're back at work.
> 
> PS - please use a 120x50 image with transparent background as author_image.png, per the [standards](https://xsoar.pan.dev/docs/integrations/integration-logo).

@dorschw this image is given by the client and already used in the integration logo. Also, changing the size to 120x50 distorts the image hence we kept it as is.

**Review by moishce — APPROVED** [review]
That's perfect.

**Comment by moishce** [comment]
We have ready the logo adapted to standards
And it is recommended to change to this or you want me to change it.
armis

**Comment by crestdatasystems** [comment]
> We have ready the logo adapted to standards And it is recommended to change to this or you want me to change it. armis

We have updated the Author logo as per the standard

**Pull request merged**
