### PR TITLE
[Fix] Using zscaler-category-add-url, undo-blacklist/whitelist, activate changes addition

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - Waiting customer verification

## Related Issues
fixes: https://github.com/demisto/etc/issues/21619
fixes: demisto/etc#21635
fixes: demisto/etc#19831

## Description
- Fixed an issue where the ***zscaler-category-add-url*** command failed when passing multiple URLs separated with spaces.
- Fixed an issue where the ***zscaler-undo-blacklist-url*** command always failed with an error "Given URL is not blacklisted".
- Fixed an issue where the ***zscaler-undo-blacklist-ip*** command always failed with an error "Given IP is not blacklisted".
- Fixed an issue where the ***zscaler-undo-whitelist-url*** command always failed with an error "Given host address is not whitelisted.".
- Fixed an issue where the ***zscaler-undo-whitelist-ip*** command always failed with an error "Given IP address is not whitelisted.".
- Updated command executions to always activate changes after API calls and close session. This fixes issues related to session not being authenticated or timing out.

Also, packified the integration.

## Does it break backward compatibility?
   - [ ] No

## Must have
- [x] ~Tests~ - No instance
- [x] ~Documentation~ - No instance

### CODE REVIEW

**Comment by kirbles19** [comment]
@DeanArbel Done.

**Comment by DeanArbel** [comment]
@kirbles19 we added some more release notes. Please rereview the release notes at your leisure.

**Comment by bakatzir** [comment]
fixes: https://github.com/demisto/etc/issues/21635
fixes: https://github.com/demisto/etc/issues/19831

**Comment by kirbles19** [comment]
@DeanArbel Done.

**Pull request merged**
