### PR TITLE
VMWare integration improvements

### PR DESCRIPTION
**Pull request by Itay4**
Improvements done in integration and test playbook according to requested changes in integration presentation

### CODE REVIEW

**Comment by Itay4** [comment]
By `mark commands as important` you mean `Potentially harmful`? If so, I did.
Will mark relevant commands as important.

**Comment by anara123** [comment]
@aviad what is the status of this PR?

**Comment by aviadl** [comment]
I still think that there are problems there, need to see how the `findings` section looks like

**Comment by anara123** [comment]
@aviadl can you elaborate, what exactly is missing so we can close this pr

**Comment by dorsha** [comment]
@aviadl / @anara123 please handle this PR.

**Pull request merged**
