### PR TITLE
new Pack integration from Ataya

### PR DESCRIPTION
**Pull request by tony19911010**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by efelmandar** [comment]
Hi @tony19911010,

Thank you for your contribution and your dedicated effort in the PR. I've conducted a comprehensive review and would like to share some feedback:

1. **Mapper:** Consider mapping to the "Ataya" incident type instead of "commonMappings."
2. **Event Type:** It would be beneficial to use the "Event Type" incident field from "commonTypes" to avoid creating unnecessary fields.
3. **Playbook Clarification:** Could you kindly provide more insight into the playbook's purpose? I observed that two tasks share the same title, one task seems disconnected from a path, and all tasks under "create," "modify," and "delete" exhibit similar inputs and actions. Understanding your intentions will help us determine the optimal approach.
4. **Enhanced Clarity:** By adding descriptions for the playbook, layout, and other content items, we can improve clarity and context, facilitating smoother user adoption.

Your contributions are highly valued! Please feel free to address these points. If you have any questions or concerns, don't hesitate to reach out here or on the DFIR workspace in Slack.
I am looking forward to your refinements.

**Comment by tony19911010** [comment]
Hi @efelmandar, Thanks for review,
1. **Event Type**, I've replace the original "Ataya_eventType" with the "Event Type" incident field from "commonTypes", and update the mapper and layout as well.
2. **About the Mapper**, I've not sure whether the change is correctly map to "Ataya" incident type, not "commonMappings", if this fix not correct, please guide me about this part.
3. **About the Playbook**, I've added the description on Playbook yml and fix the task which disconnected.

The purpose of Playbook is target to automatically login/logout user id on pan-os according to information (event type) which received by the webhook server (create, modify, delete), currently the type of create and modify do the same action.

**Comment by efelmandar** [comment]
@tony19911010 Thanks for the updates and information regarding the purpose of the playbook, now that I have a better understanding I would like to offer some additional things for refinement:

1. **Check 5G UE IMEI Value (Task 1):**
The task name `checkValue` seems misleading, as it merely prints the IMEI value. Consider renaming it to `Check 5G UE IMEI Value` for clarity. If the purpose is for analysts to manually verify it before proceeding, you can make it a manual or conditional-ask task to halt the playbook until confirmation.

2. **Event Type Inspection (Task 4):**
If the value's letter case may change, it's best to enable the ignore case option in the Equals condition. This will help avoid potential bugs down the line.

3. **Integration Availability Check:**
When utilizing commands from other integrations, it's a good practice to incorporate a task that ensures the integration is enabled and accessible before executing the pan-os commands. there is a command named `IsIntegrationAvailable` which you can use for that.

4. **Close Investigation (Task 2):**
I recommend adding a closing note or comment when closing investigations. This will help track the reason for the closure and the actions taken.

5. **Playbook Naming Convention:** 
Kindly modify the playbook name to adhere to the naming convention of `{Pack Name} - {Playbook Title}`, for example, `Ataya - Auto Login or Logout user in PAN-OS`. Correspondingly, the playbook file name would be `playbook_-_Ataya_-_Auto_Login_or_Logout_user_in_PAN-OS`.

**Comment by tony19911010** [comment]
Hi @efelmandar,
I've update the Playbook according to your comments.
and also update the corresponding change of incidenttype-Ataya.json file to map to the correct playbook name.

Please review it again to check if there has something need to be fix. Thanks a lot.

**Comment by efelmandar** [comment]
@tony19911010  I've reviewed the changes, and they look excellent. Could you please include a playbook image under the `doc_files` directory? Additionally, I noticed that secrets validation is failing on `https://www.ataya.io/`. If I'm correct and this isn't a secret, you can add it to the `.secrets-ignore` file to pass validation. 
Once that's done, I believe we can proceed with a quick demo (you can share a recorded demo if it's easier) to observe how everything works together.

**Comment by tony19911010** [comment]
@efelmandar Thanks again,
I've create a new commit which update playbook image and fix secrets validation problem, and I saw that it pass the validations, please check.

**Comment by efelmandar** [comment]
@tony19911010 Thanks for making all the necessary changes! all the validations are passing which is great! but, I see you changed the image but it needs to be the playbook screenshot image, You can generate it from the XSOAR UI by going to the `Playbooks` section and using the image button 
image

For a demo please let me know when would be best for you to schedule a meeting to present it live or you can just record a short video explaining and showing the workflow of the new content and that everything works when used with the Ataya product, whichever is more convenient for you

**Comment by mmhw** [comment]
Closed for now, since the partner still wants to work on it, before releasing it.

**Pull request closed without merging**
