### PR TITLE
ExtractDomainFromEmail - Changed script to properly extract domain

### PR DESCRIPTION
**Pull request by yardensade**
+ added tests

## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/15535

## Related PRs
https://github.com/demisto/content/pull/3170

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Code Review

### CODE REVIEW

**Comment by yardensade** [comment]
Are we going to push it before the content release? @yaakovi @glicht

**Comment by glicht** [comment]
Please run performance test as done here:

https://github.com/demisto/content/pull/2718#issuecomment-452675776 

Don't think there should be any issues with this.

**Comment by yardensade** [comment]
Seems to have the same performance.
image

**Comment by liorblob** [comment]
should resolve also https://github.com/demisto/etc/issues/16130

**Comment by yardensade** [comment]
It will.

**Pull request merged**
