### PR TITLE
Doc Review only XSOAR-supported Packs

### PR DESCRIPTION
**Pull request by kgal-pan**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - Waiting for changes made in https://github.com/demisto/demisto-sdk/pull/2660 to be released in next SDK version.

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4970

## Description
Adds the `--xsoar-only` flag to the `DocReviewer` constructor to skip checking of non-XSOAR supported Packs in the _Review Release Notes_ workflow.

### CODE REVIEW

**Review by ShacharKidor — APPROVED** [review]
@kgal-pan - good work!

Please edit the pyproject.toml file so this PR will 'look' at your SDK branch. 
That way we could run the GitHub action and verify that the change works as expected. 
Please let me know if you need any help with that.

**Review by DinaMeylakh — APPROVED** [review]
cool cool cool

**Comment by kgal-pan** [comment]
> Please edit the pyproject.toml file so this PR will 'look' at your SDK branch. That way we could run the GitHub action and verify that the change works as expected.

@ShacharKidor - 

Change made in [`b055bae` (#23791)](https://github.com/demisto/content/pull/23791/commits/b055bae243e12cb86af48e51ded521275019517c).

[Doc Review](https://github.com/demisto/content/actions/runs/3924140813/jobs/6708192771#step:7:16) completed without issues using the SDK dev branch.

**Comment by ShacharKidor** [comment]
> Change made in [`b055bae` (#23791)](https://github.com/demisto/content/pull/23791/commits/b055bae243e12cb86af48e51ded521275019517c).
> 
> [Doc Review](https://github.com/demisto/content/actions/runs/3924140813/jobs/6708192771#step:7:16) completed without issues using the SDK dev branch.
> 
> I also [committed changes to two Packs](https://github.com/demisto/content/pull/23791/commits/a45fd8971b4e8eaf1cbd3de8b9b84814598806db), SentinelOne (XSOAR-supported) and HelloWorld (community-supported) and found that [the doc review failed](https://github.com/demisto/content/actions/runs/3924196217/jobs/6708287716#step:7:22) as expected when checking the XSOAR-supported RN while skipping the community-supported RN.
> 
> We should be good to go here.

@kgal-pan - Amazing. 
Adding here a link to the Review Release Notes step run  - [link](https://github.com/demisto/content/actions/runs/3924196217/jobs/6708287716).
Let's revert the changes in the 2 packs, and merge the SDK PR. 

We could merge this one once the next SDK version will be released :)

Great Job!

**Comment by kgal-pan** [comment]
> Let's revert the changes in the 2 packs, and merge the SDK PR.

Done. Putting on-hold until SDK version is out.

**Pull request merged**
