### PR TITLE
Citrix Analytics - Initial version

### PR DESCRIPTION
**Pull request by jmuthuku**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kgal-pan** [comment]
@jmuthuku - As discussed in Slack, please sync fork with content master using:

```bash
./Utils/git_pull_master_into_fork.sh
```

This should resolve [`ReferenceError`](https://app.circleci.com/pipelines/github/demisto/content/164780/workflows/c444b917-74eb-4db2-b33e-20d88febf09b/jobs/520470?invite=true#step-108-90).

**Comment by ShacharKidor** [comment]
The PR is on hold - The review process will start when we get a green light from @marcellarichmond.

**Comment by jmuthuku** [comment]
> @jmuthuku - As discussed in Slack, please sync fork with content master using:
> 
> ```shell
> ./Utils/git_pull_master_into_fork.sh
> ```
> 
> This should resolve [`ReferenceError`](https://app.circleci.com/pipelines/github/demisto/content/164780/workflows/c444b917-74eb-4db2-b33e-20d88febf09b/jobs/520470?invite=true#step-108-90).

Thanks @kgal-pan. I was on PTO last week. Working on it this week.

**Comment by ShacharKidor** [comment]
Hi @jmuthuku, 
Thank you for your contribution!

I'm closing the PR for now, until you'll finish the process with @marcellarichmond.
You can reopen the PR as soon as you want to restart the review process.

I'm available for every question here or via slack :)

Thanks again, 
Shachar Kidor Marco

**Pull request closed without merging**
