### PR TITLE
Microsoft Teams enhancements

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

## Description
1. Added message to be sent on channel creation as part of mirror flow.
2. Fixed bug in which error returned from server are not sent in direct messages.

## Screenshots
image

Error returned from server when an external user tries to send `list my incidents` to the bot in direct message:

Screen Shot 2019-08-26 at 21 48 28

## Required version of Demisto
5.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Code Review

## Dependencies
- [x] MicrosoftTeamsAsk

### CODE REVIEW

**Comment by Itay4** [comment]
@kirbles19 please review the changelog

**Comment by yaakovi** [comment]
@kirbles19 please also review the messages presented to the user (see screenshots)

**Comment by Itay4** [comment]
@yaakovi he already reviewed the message sent on channel creation
the second one is a server side message, so we won't be able to change it here anyway

**Comment by kirbles19** [comment]
@Itay4 Done.

**Pull request merged**
