### PR TITLE
Detailed Malware Investigation Summary

### PR DESCRIPTION
**Pull request by dorschw**
closes: https://github.com/demisto/etc/issues/46842

### CODE REVIEW

**Review by DeanArbel — APPROVED** [review]
Impressive work.

**Comment by David-BMS** [comment]
@julieschwartz18 If possible please review today or we can just fix the descriptions after its merged

**Comment by julieschwartz18** [comment]
@David-BMS - doc review complete for the [InvestigationDetailedSummaryParse.yml](https://github.com/demisto/content/pull/19176/files?file-filters%5B%5D=.md&file-filters%5B%5D=.yml&show-viewed-files=true#diff-b937102d2108076445777f3e71981debfffabe2f7182fa4abf0be74c57f7a298) file (see the file with minor updates - I had to save it as a .md file to be able to copy it here). Please confirm:
- same description is used for the Privilege Escalation.Boot and the Persistence.Boot context paths, do you want to be more specific in the description?
[InvestigationDetailedSummaryParse.md](https://github.com/demisto/content/files/8796026/InvestigationDetailedSummaryParse.md)

**Comment by julieschwartz18** [comment]
@David-BMS - doc review complete for the 1_3_0.md file, minor updates.
[1_3_0.md](https://github.com/demisto/content/files/8796065/1_3_0.md)

**Comment by julieschwartz18** [comment]
@David-BMS - doc review complete for the InvestigationDetailedSummaryParse README file. (minor updates, aligned descriptions with the yaml file). Please confirm:
- same description is used for the Privilege Escalation.Boot and the Persistence.Boot context paths, do you want to be more specific in the description?
[InvestigationDetailedSummaryParse README.md](https://github.com/demisto/content/files/8796099/InvestigationDetailedSummaryParse.README.md)

**Comment by julieschwartz18** [comment]
@David-BMS - doc review complete for the InvestigationDetailedSummaryToTable.yml file, minor update to the description (saved as Markdown).
[InvestigationDetailedSummaryToTable.md](https://github.com/demisto/content/files/8796129/InvestigationDetailedSummaryToTable.md)

**Comment by julieschwartz18** [comment]
@David-BMS - doc review complete for the InvestigationDetailedSummaryToTable README file, minor update to the description.
[InvestigationDetailedSummaryToTable README.md](https://github.com/demisto/content/files/8796146/InvestigationDetailedSummaryToTable.README.md)

**Pull request merged**
