### PR TITLE
Upload xsiam

### PR DESCRIPTION
**Pull request by daryakoval**
Adding XSIAM instances testing to upload flow. 
The main changes: 
- Added support to install only new added packs, and its dependencies. (for xsoar and xsiam).
- Remained the same flow for XSOAR (install all content packs) if the flag: OVERRIDE_ALL_PACKS = TRUE.
- Not supported: XSIAM with OVERRIDE_ALL_PACKS = TRUE. Opened an issue to handle this. https://github.com/demisto/etc/issues/48159

fixes: https://github.com/demisto/etc/issues/47972

### CODE REVIEW

**Comment by daryakoval** [comment]
Changed Core Pack, and saw that the upload flow installed only Core Pack and its dependencies:  https://code.pan.run/xsoar/content/-/pipelines/2821602

**Review by dantavori — CHANGES_REQUESTED** [review]
partial review

**Comment by daryakoval** [comment]
@dorschw Please pay attention to `Tests/scripts/collect_tests_and_content_packs.py` changes I did for upload flow.

**Review by Noy-Maimon — APPROVED** [review]

**Review by dantavori — APPROVED** [review]
looks good, approving but suggested some minor changes, mainly in the error handling.

**Pull request merged**
