### PR TITLE
Prisma cloud dashboard

### PR DESCRIPTION
**Pull request by ayman-m**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added a new dashboard to report on prisma cloud incidents.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by ShacharKidor — CHANGES_REQUESTED** [review]
Hi @ayman-m, 
Thank you for contributing! 

I added a little change to the RN file - please commit it. 
Let's schedule a short demo :)

**Comment by ayman-m** [comment]
> Hi @ayman-m, Thank you for contributing!
> 
> I added a little change to the RN file - please commit it. Let's schedule a short demo :)

Hi @ShacharKidor , Thank you for reviewing my contribution :), sure I can be available for this demo this week.

**Comment by ShacharKidor** [comment]
@ayman-m, @idovandijk - Demo was scheduled for tomorrow (21.6) at 05:00 pm (Israel local time).

**Review by ShacharKidor — APPROVED** [review]

**Comment by ShirleyDenkberg** [comment]
@ShacharKidor @idovandijk Doc review completed.

**Pull request merged**
