### PR TITLE
remove PB110 ignore from several packs

### PR DESCRIPTION
**Pull request by dansterenson**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Should be merged after this fix: https://github.com/demisto/demisto-sdk/pull/1660

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by yaakovi** [comment]
@dansterenson what is the status here?

**Comment by dansterenson** [comment]
Can be merged, the SDK fix was merged in version 1.5.1. So unblock the merge and Ill merge it.

**Comment by tomneeman151293** [comment]
Lets merge content master to this branch and retrigger build just in case

**Review by yaakovi — APPROVED** [review]

**Comment by yaakovi** [comment]
branch build passed
nightly trigger failed and is blocking the merge.

**Pull request merged**
