### PR TITLE
Update CortexXDRIR.yml

### PR DESCRIPTION
**Pull request by ShirleyDenkberg**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
Following are several questions:
Line 48 - What integration doc are you referring to?  Perhaps there should be a link here.
Line 642 - Is the only valid value True?  What about False?
Line 1831 - what is the format of the date?
Line 2228 - Is this still true? Will this soon be deprecated?
Line 2277 -is this description correct
      PaloAltoNetworksXDR.ScriptResult.results.endpoint_name
      description: Number of successfully retrieved files.
Line 2412 - is this description correct
      PaloAltoNetworksXDR.ScriptResult.results.endpoint_name
      description: Number of successfully retrieved files.
Line 2851 - emitted or omitted?
 - contextPath: PaloAltoNetworksXDR.OriginalAlert.event.resource_type
      description: The normalized type of the service that emitted the log row.
Line 2854 - emitted or omitted?
- contextPath: PaloAltoNetworksXDR.OriginalAlert.event.resource_type_orig
      description: The type of the service that omitted the log as provided by the cloud provider.
Line 2862 - emitted or omitted?
   - contextPath: PaloAltoNetworksXDR.OriginalAlert.event.region
      description: The cloud region of the resource that emitted the log.
      type: String
    - contextPath: PaloAltoNetworksXDR.OriginalAlert.event.zone
      description: The availability zone of the resource that emitted the log.
Line 3419 - is there a period or underscore missing from the context path?
 - contextPath: PaloAltoNetworksXDR.RiskyHost.reasons.date created
      description: Date when the incident was created.

**Comment by ShirleyDenkberg** [comment]
Comments on the Description File:
After Step 3 - Need to add a step to select a role. How do they know what role to select?
Do they need to do anything in the Components section?
Step 4 - Copy and paste the key - Where should I copy the key to?

**Comment by ShirleyDenkberg** [comment]
@JasBeilin 
Regarding the Pack Readme - At one time we were told to include a screenshot of one of the playbooks in the pack.  Then that decision was reversed.  I am not sure if we should have the playbook screenshot in the pack readme.  Who makes this final decision?

**Review by thefrieddan1 — APPROVED** [review]

**Comment by maimorag** [comment]
Hey @ShirleyDenkberg

line 48- the reference is to the README file line 132
line 648- added false
line 1832 - ISO 8601, added to doc.
line 2228- not sure, will ask tpm( Natalya Dalid)/
line 2277- fixed description
line 2407 - fixed 
line 2851, 2854, 2854- emitted
line 3419- underscore, fixed

**Comment by maimorag** [comment]
Description File -
step 3- role according to your permissions.
step 4- after generating the key a window is opened with the key (I sent an example via Slack)

README- I asked TPM, and post here as soon as I'll get an answer.

Thanks!

**Comment by maimorag** [comment]
Update regarding the "Soon to be deprecated command" - TPM will open a ticket to deprecate it, thanks.

**Review by maimorag — APPROVED** [review]

**Comment by michal-dagan** [comment]
please next time add a comment for the force merge:)

**Pull request merged**
