### PR TITLE
Fix url enrichment test

### PR DESCRIPTION
**Pull request by liorblob**
Also changed the playbook, make sure to look at it in the review

### CODE REVIEW

**Comment by liorblob** [comment]
Should be more stable.

**Comment by liorblob** [comment]
Skipped for now, further investigation required

**Comment by dorsha** [comment]
@liorblob you referenced the PR to itself, I guess you wanted to reference to the issue..

And skipping is not the best solution for this problem.. we must make sure we enable it asap, so we won't have untested flows.

**Comment by liorblob** [comment]
Agreed, I'll look at it tomorrow.

**Pull request merged**
