### PR TITLE
CrowdStrikeFalcon: Fix cs-falcon-get-detections-for-incident by sending data as JSON

### PR DESCRIPTION
**Pull request by mluhta**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description

cs-falcon-get-detections-for-incident command uses get_detections_by_behaviors to find detections related to an incident, but it's trying to send the data as form data, not as JSON so it does not work. This PR fixes the problem by changing the data keyword parameter to json.

## Screenshots
Screenshot from CrowdStrike Falcon API docs:
CleanShot 2022-10-10 at 14 18 59@2x

CleanShot 2022-10-10 at 15 19 17@2x

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

### CODE REVIEW

**Comment by dorschw** [comment]
Hi @mluhta, thank you for your contribution!

Reviewing this PR will be slightly delayed as we are in the midst of the local holiday season. We'll have a look as soon as we're back at work.

**Comment by esharf** [comment]
@mluhta looks good.
can you just update the RN?
you should:
- rename your `Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_6.md` to `Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_7.md`
- update the version in the `pack_metadata.json` file

after resolving this issues we will be ready to merge.

**Comment by mluhta** [comment]
> @mluhta looks good. can you just update the RN? you should:
> 
> * rename your `Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_6.md` to `Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_7.md`
> * update the version in the `pack_metadata.json` file
> 
> after resolving this issues we will be ready to merge.

Thanks, I fixed these

**Comment by esharf** [comment]
@mluhta sorry for missing it in my first review but, can you add a little more info in the release notes?
it should be something like `Fixed an issue in **cs-falcon-get-detections-for-incident** command where command used to <describe the buggy behavior>`

there are also some failures in the validation but I can take care of them.
- mypy error
- docker image is not the latest updated version

**Comment by mluhta** [comment]
@esharf Fair point, I made the release notes more explanatory. Also upgraded the integration's Docker image to the latest version. Didn't know if I should do it for all of the scripts in the pack so I left them untouched. Mypy is not showing any problems for me

**Comment by mluhta** [comment]
@esharf Any updates here?

**Comment by esharf** [comment]
hey @mluhta sorry for the delay.
I’m a little-bit under pressure.
i will rerview it soon.
also can you give me collaborate permissions so i will be able to fix the conflicts here?

**Comment by mluhta** [comment]
No problem :+1:. I added you to the contributors @esharf

**Review by esharf — APPROVED** [review]

**Pull request merged**
