### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tschanfeld**
changed two urls to fix link to #configure-microsoft-teams-on-cortex-xsoar

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by Bharathwaj-Murali — COMMENTED** [review]
I just noticed the same changes needs to be made in #4-using-cloudflare and #prerequisites. Can those be added as well?

**Review by tschanfeld — COMMENTED** [review]
changed the two links

**Comment by tschanfeld** [comment]
changed the additional links

**Comment by reutshal** [comment]
Closing as this will get in as part of https://github.com/demisto/content/pull/13920

**Pull request closed without merging**
