### PR TITLE
Add sha512 support as per customer's requirement

### PR DESCRIPTION
**Pull request by jieliau**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by YuvHayun — CHANGES_REQUESTED** [review]
Hi @jieliau, thx for your contribution!
Small fixes are required:
- Please update the docker image: you can run: `demisto-sdk format -ud -i  Packs/CreateHash/Scripts/CreateHash/CreateHash.yml` to update it.
- Also, please add RN 1_0_2.md, run 'demisto-sdk update-release-notes -i Packs/CreateHash`: write about the added sha512 support and the update docker image.
You can use [this](https://xsoar.pan.dev/docs/documentation/release-notes) as a reference.


Let me know if you need any help.

**Comment by jieliau** [comment]
> 
Hi @YuvHayun , update the docker image to latest one and add release note. Thanks so much for the help .

**Comment by YuvHayun** [comment]
@jieliau thx!
I'll trigger the instance tests for now

**Review by YuvHayun — APPROVED** [review]
All tests passed, this pr is approved and merged.

**Pull request merged**
