### PR TITLE
Updated tests that use Minemeld

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/26878

## Description
Now creating indicators manually and not using minemeld. Also deprecated test for deprecated playbook.

### CODE REVIEW

**Comment by idovandijk** [comment]
@ShahafBenYakir do u know why this is happening?

image

image

**Comment by ShahafBenYakir** [comment]
@idovandijk `Playbooks - Missing sub-playbooks for following playbooks: Calculate Severity - Generic v2 - Test (96)`

**Comment by ShahafBenYakir** [comment]
@idovandijk is `createNewIndicator` supported in 4.1?

**Comment by idovandijk** [comment]
> @idovandijk is `createNewIndicator` supported in 4.1?

`createNewIndicator` is, but calc severity is actually from 4.5.. I see now.. `format` deleted the fromversion 4.5 part of the test

**Pull request merged**
