### PR TITLE
Recorded Future integration

### PR DESCRIPTION
**Pull request by Itay4**
Fixes https://github.com/demisto/etc/issues/6239
Test is in `nightly` cause of limited API quota.
In addition, added hash types to constant file path.

### CODE REVIEW

**Comment by Itay4** [comment]
Documentation: https://github.com/demisto/etc/issues/12317

**Comment by anara123** [comment]
@Itay4 DO NOT MERGE YET

**Comment by Itay4** [comment]
@JonathanMeler @erezh31 Please review and confirm it's ok with you to merge.

**Comment by Itay4** [comment]
@aviadl Yes, they are included in the last commit.

**Pull request merged**
