### PR TITLE
Generic Proxy URL feed with initial support for ProxySG

### PR DESCRIPTION
**Pull request by omercnet**
Signed-off-by: Omer Cohen <omer@paloaltonetworks.com>

## Status
In-Progress (awaiting customer test)

## Related Issues
fixes: https://github.com/demisto/etc/issues/19958

## Description
This integration will create an HTTP server that will provide a URL filter file to be fetched by proxy servers.
First implementation is designed for Symantec (BlueCoat) ProxySG

This integration is meant to be later expanded by other proxy products as needed

## Screenshots
Paste here any images that will help the reviewer

## Required version of Demisto
5.0.0

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](https://github.com/demisto/content/blob/feature/proxyfilterserver/Integrations/Proxy_URL_Filter_Server/Proxy_URL_Filter_Server.yml)
- [ ] [CHANGELOG](https://github.com/demisto/content/blob/feature/proxyfilterserver/Integrations/Proxy_URL_Filter_Server/CHANGELOG.md)

### CODE REVIEW

**Comment by anara123** [comment]
@omercnet it looks good. I will be happy to get test playbook next time, but here I will add one myself.

**Comment by Itay4** [comment]
@omercnet whats our status here?

**Comment by Itay4** [comment]
@anara123 ?

**Comment by anara123** [comment]
@Itay4 I think we can merge it

**Comment by anara123** [comment]
@omercnet you have failing unit tests
image

**Comment by omercnet** [comment]
handled via https://github.com/demisto/content/pull/5905

**Pull request closed without merging**
