### PR TITLE
skip lastline v2 test

### PR DESCRIPTION
**Pull request by guyfreund**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
moved into skipped tests because of https://github.com/demisto/etc/issues/26170

## Description
Unskipped integration, skipped test.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by bakatzir** [comment]
@ShahafBenYakir @guyfreund  Seems like a real bug in the integration, why skip and not tend to the bug?

**Comment by ShahafBenYakir** [comment]
@bakatzir There is a bug https://github.com/demisto/etc/issues/26170

**Comment by ShahafBenYakir** [comment]
@guyfreund What about this?

**Comment by guyfreund** [comment]
@ShahafBenYakir looks like only 6.0 build is failing due to unrelated issue (lastline test passes), we might need to consider force merging

**Comment by ShahafBenYakir** [comment]
@guyfreund Let's close or merge this

**Comment by guyfreund** [comment]
Closing due to https://github.com/demisto/etc/issues/27496

**Pull request closed without merging**
