### PR TITLE
Cyble vision v2

### PR DESCRIPTION
**Pull request by cyble-dev**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by cyble-dev** [comment]
@CLAassistant, @cyble-dev  is already Contributor, is it required to get for another user linked Rajesh Ramamoorthy

**Comment by GuyAfik** [comment]
> @GuyAfik , Kindly help me to fix incidenttype and palybook issue



> [cyble-dev](/cyble-dev)

are you able to speak with in DFIR slack? if yes please send me a message.

**Comment by cyble-dev** [comment]
New PR is created, Suggested by @RotemAmit

**Comment by RotemAmit** [comment]
Closed due to a problem in the CLA. A new PR was opened https://github.com/demisto/content/pull/26519

**Pull request closed without merging**
