### PR TITLE
[ASM] - EXPANDER 3741 - XSIAM Layout and Rule

### PR DESCRIPTION
**Pull request by BigEasyJ**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-3741](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-3741)

## Description
Adds a new layout and rule for the ASM alert source in XSIAM.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by BigEasyJ** [comment]
@RotemAmit @melamedbn I'm not sure about the validation errors I am seeing and what is required of them. `alert_sub_type` is something that exist in XSIAM and `ASM` is an alert type that exists in XSIAM also.

**Comment by melamedbn** [comment]
Hi @BigEasyJ,

Is the layout a generic ASM layout or Xpanse specific (ASM) layout?

Ben

**Comment by adi88d** [comment]
@BigEasyJ  also the `ASM Alert Layout` is using the `alert_sub_type` field which not exists, please add it to the PR

**Comment by BigEasyJ** [comment]
@adi88d the `alert_sub_type` field is a default out of the box field in XSIAM.

**Review by capanw — APPROVED** [review]
Reviewed the XSIAM alert and code changes. LGTM

**Comment by BigEasyJ** [comment]
@adi88d requested that I add `"alert_sub_type"` to `"IncidentField"` and add 

```
"IncidentType": [
        "ASM"
    ]
 ```
 
 to `Tests/Marketplace/server_content_items.json`

**Pull request merged**
