### PR TITLE
Crowdstrike FalconX Fix png Download

### PR DESCRIPTION
**Pull request by darkushin**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-16742

## Description
Fix an issue where IOC artifacts of png images weren't parsed correctly.

### CODE REVIEW

**Comment by darkushin** [comment]
Output example for an image IOC:
image

**Review by DeanArbel — APPROVED** [review]
Nice one

**Comment by asantamarina** [comment]
@DeanArbel @darkushin 
Hey team, has this been completed? It appears as though it was merged into master but it hasn't updated in the marketplace as of yet. 
Thank you.

**Comment by darkushin** [comment]
Hi @asantamarina,
The new version is now available in the marketplace.

**Pull request merged**
