### PR TITLE
Update CommonServerPython.py

### PR DESCRIPTION
**Pull request by ckaadic**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added the "Note" flag to the "CommandResults" class to use the conext transformation and be able to mark the entry as note.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by barchen1** [comment]
@ckaadic Can you please explain the use case here?
Also, please share your email address so we can schedule a zoom call.

**Comment by ckaadic** [comment]
@barchen1
Usecase: we would like to use the benefit of CommandResults output formating (to append data with the same key field in context) in integrations while being able to mark the result as note. Currently we either have to do the dt transformation ourselfs and create the dict manually afterwards or we copy the dt transformation from the CommandResults class as a helperfunction in all our integrations/automations where we need both features.

You can pm me in Slack "@cedric" and I will give you my mail work address to schedule the zoom call. I also already sent the Slack name and mail address in the contribution form.

**Review by barchen1 — APPROVED** [review]
Thanks a lot for your contribution!
You did a great job!

**Comment by barchen1** [comment]
@ckaadic Can you please sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=10873) ?

**Pull request merged**
