### PR TITLE
AD Query v2

### PR DESCRIPTION
**Pull request by dantavori**
## Status
Ready

## Related Issues
fixes: [https://github.com/demisto/etc/issues/18316](https://github.com/demisto/etc/issues/18316)

## Description
1. Fixed a bug in create-contact command
2. Added some detailed description for arguments in search and create commands.

## Does it break backward compatibility?
   - No (but users must be aware of the correct search filter syntax)

### CODE REVIEW

**Comment by kirbles19** [comment]
@dantavori Please only assign me, not as a reviewer.

**Comment by dantavori** [comment]
@ronykoz we can define another syntax that we decode and encode (with regex), but basically the search filter syntax defines a regular language with an infinite cardinality while our command receives in each execution a constant number of arguments (and lists won't help us much)

**Comment by ronykoz** [comment]
@dantavori yeah i know, but it feels strange to ask the user to fill in \\28 instead of brackets

**Comment by richardbluestone** [comment]
I've reviewed both the yml and md files.

**Pull request merged**
