### PR TITLE
Content legacy pack

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Moved all content items to legacy pack.

### CODE REVIEW

**Comment by IkaDemisto** [comment]
@anara123 @yuvalbenshalom @yaakovi what should we do with test playbooks? Move all to `TestPlaybooks` folder inside the new pack?

**Comment by anara123** [comment]
@IkaDemisto you can move them. But it makes more problems, they can stay where they are now

**Comment by IkaDemisto** [comment]
@anara123 @yaakovi fixed the release notes validation. 
Passing the secret detection is not realistic, each time it detects new secrets.
There are still a lot of validation errors, mostly on docker latest tag.

@yaakovi is it enough to force merge it? Additionally there are 2 unit tests that fail, fixed 2 others.

**Comment by anara123** [comment]
@IkaDemisto 
secrets are still failing
to fix this add to .secrets-ignore file
```
23.20.239.12
file:Scripts/ReadPDFFileV2/test_data/encrypted.pdf
file:Scripts/ReadPDFFileV2/test_data/Docker-Cookbook.pdf
``` 
```
Starting secrets detection
ERROR: Could not parse PDF file in path: Packs/Legacy/Scripts/ReadPDFFileV2/test_data/encrypted.pdf - ***Review Manually***
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
Secrets were found in the following files:

In File: Docker-Cookbook.pdf

The following expressions were marked as secrets: 
[
    "72.17.8.100",
    "72.17.8.104",
    "72.17.8.101"
]

In File: README.md

The following expressions were marked as secrets: 
[
    "23.20.239.12"
]

```

**Comment by IkaDemisto** [comment]
@anara123 it is not helping, already did it. It will detect new secrets in next stage

**Pull request merged**
