### PR TITLE
Remove default values from yml - phase 2

### PR DESCRIPTION
**Pull request by ilappe**
## Related Issues
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-4906

## Description
The following fields was deleted (field name: appearance counter)
`{'runonce':1671, 'required':1182, 'isArray':797, 'default':782, 'secret':773, 'deprecated':618, 'execution':569, 'longRunningPort':466, 'longRunning':459, 'isfetch':409, 'feed':352, 'hidden':286, 'system':257}`

### CODE REVIEW

**Comment by ilappe** [comment]
[content nightly](https://code.pan.run/xsoar/content/-/pipelines/5636493) to test the validation of the updated files
with SDK hot fix

**Comment by ilappe** [comment]
[nightly with sdk 1.17.1](https://code.pan.run/xsoar/content/-/pipelines/5677451)

**Review by dorschw — CHANGES_REQUESTED** [review]
Are the `poetry.lock` changes intentional? If not, undo them.

**Comment by ilappe** [comment]
[updated nightly](https://code.pan.run/xsoar/content/-/pipelines/5682940)

**Pull request merged**
