### PR TITLE
RTIR - Handle non ascii chars

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/30531

## Description
Encoded arguments to handle non ascii chars

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests

See failing test in https://app.circleci.com/pipelines/github/demisto/content/43013/workflows/4c0e6ed9-a3c6-40b1-b341-fe6fbb22831d/jobs/186056

### CODE REVIEW

**Review by ShahafBenYakir — COMMENTED** [review]
Don't we have unit tests to check this?

**Comment by Itay4** [comment]
> Don't we have unit tests to check this?

i dont see the added value in unit tests in this case since the test playbook covers

**Comment by ShahafBenYakir** [comment]
Looks like it fails

**Comment by Itay4** [comment]
> Looks like it fails

Failed on login for some reason, will check that

**Review by ronykoz — APPROVED** [review]

**Comment by kirbles19** [comment]
@Itay4 Done.

**Pull request merged**
