### PR TITLE
Adoption for pack

### PR DESCRIPTION
**Pull request by adit-ghildiyal**
We need to add an author image as well. 
We will be providing it shortly.

### CODE REVIEW

**Comment by maimorag** [comment]
Hey @adit-ghildiyal,
Thank you for your contribution!
Let me know when this PR is ready for review :)

**Review by maimorag — APPROVED** [review]

**Comment by maimorag** [comment]
Hi @adit-ghildiyal, we haven’t heard from you in a while.
Is the PR ready with the author's image?

Thanks again for contributing to our repo, hope to hear from you soon.

**Comment by adit-ghildiyal** [comment]
Hi @maimorag , Yes the image is ready, I will update the PR today.

**Comment by adit-ghildiyal** [comment]
Hi @maimorag I have added the author image.

**Pull request merged**
