### PR TITLE
fix field type for Kafka_v2.max_messages

### PR DESCRIPTION
**Pull request by yhager**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Type for `max_messages` is incorrect, looks like a typo

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by yhager** [comment]
not sure why the CLA assistant does not see it, but I have signed the CLA a couple of hours ago

**Comment by Itay4** [comment]
@yhager can you click on `recheck` please ?

**Comment by yhager** [comment]
> @yhager can you click on `recheck` please ?

Yeah, already done, multiple times. Just tried again. When I click the CLA link, it's already signed, so not sure what else I can do.

**Comment by glicht** [comment]
@yhager thanks for your contribution. 

You need to sign the cla with the user that performed the commit (@yhagerjs) in this case it seems to be different than the user that opened the PR.

**Comment by yhagerjs** [comment]
Done. Sorry about that (unfortunately I have multiple github identities)

**Comment by Itay4** [comment]
Please note the [Circle CI build](https://circleci.com/gh/demisto/content/31337) fails on missing [release notes](https://github.com/demisto/content/tree/master/docs/release_notes)
In this case, you can feel free to empty release notes, by typing in `-` in the changelog under `Unreleased`

**Comment by yhager** [comment]
What is missing to get this merged?

**Comment by Itay4** [comment]
@kirbles19 please review the changelog

**Pull request merged**
