### PR TITLE
New Script - S/MIME Encrypt

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/17269

## Description
Encrypt email body message using S/MIME

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by Shellyber** [comment]
@kirbles19 Please review YML file

**Comment by kirbles19** [comment]
@Shellyber Done reviewing the .yml.

**Comment by anara123** [comment]
@Shellyber @Itay4 what are we waiting for?

**Comment by Itay4** [comment]
@anara123 pending customer

**Comment by glicht** [comment]
@Shellyber build has flake8 errors

**Comment by Shellyber** [comment]
@glicht Will be fixed.

**Comment by Itay4** [comment]
will be implemented as integrations instead

**Pull request closed without merging**
