### PR TITLE
set to false field Threat Name

### PR DESCRIPTION
**Pull request by franciscojavierfernandezjim**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by franciscojavierfernandezjim** [comment]
Hi! We want to change this because we use automations to tracking the incident drops (preprocessing) and when our users use this field to do queries or preprocess, its not searchable.

**Review by melamedbn — APPROVED** [review]

**Comment by amshamah419** [comment]
Hi @franciscojavierfernandezjim thanks for the contribution! If you'd like, we have the ability to set this within your own specific environment. If not, we can go ahead and merge this change.

If you'd like to continue with contributing this change, please bump the pack version and we can proceed with a merge.

**Comment by franciscojavierfernandezjim** [comment]
Hi,
Release notes updated!
After consulting with my team, we prefer that the change be merged.

**Comment by franciscojavierfernandezjim** [comment]
I dont know whats wrong with Review Release Notes job, can u help me? ty

**Comment by amshamah419** [comment]
@franciscojavierfernandezjim I just pushed a commit which might help. I'll approve and merge.

**Pull request merged**
