### PR TITLE
Add QRadar v3 to the QRadar_hunting_v2 playbook

### PR DESCRIPTION
**Pull request by ShacharKidor**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added QRadar v3 to the QRadar_hunting_v2 playbook.
** I verified a successful running of the playbook on a QRadar v3 instance.  

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by David-BMS — COMMENTED** [review]
The last checkup we did for all the versions was for V2
Its worth to review all the non deprecated QRadar playbooks and make sure we have V3 for all of them.

**Comment by ShacharKidor** [comment]
> The last checkup we did for all the versions was for V2 Its worth to review all the non deprecated QRadar playbooks and make sure we have V3 for all of them.

@David-BMS - I opened a separate issue for that - [46262](https://github.com/demisto/etc/issues/46262).

**Comment by jrosenpanw** [comment]
@ShirleyDenkberg please could you take care of this and assign to another team member if necessary.

**Comment by ShirleyDenkberg** [comment]
@David-BMS Doc review completed.

**Review by David-BMS — APPROVED** [review]

**Pull request merged**
