### PR TITLE
Add additional arguments to authorize_security_group_ingress command AWS EC2

### PR DESCRIPTION
**Pull request by amshamah419**
## Status
Ready

## Description
Added arguments to the `authorize_security_group_ingress` command.

## Related Issues 
Fixes: demisto/etc#18395

## Screenshots
Paste here any images that will help the reviewer

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by yuvalbenshalom** [comment]
@amshamah419 there is no issue for this?

**Comment by amshamah419** [comment]
@yuvalbenshalom not that I'm aware.

**Comment by amshamah419** [comment]
@yuvalbenshalom as best as I can

**Comment by amshamah419** [comment]
https://github.com/demisto/content/blob/ec2-ingress/Integrations/AWS-EC2/AWS-EC2.yml#L3617

Just here @kirbles19 Line 3617 to 3734, not the whole thing.

**Comment by kirbles19** [comment]
@amshamah419 Done.

**Pull request merged**
