### PR TITLE
[195-sixgill] Adding the fetch_only_current_item to actionable alert content API

### PR DESCRIPTION
**Pull request by Umamahesh-Loginsoft**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by AradCarmi** [comment]
Hey @Umamahesh-Loginsoft ,
Thank you for your contribution!

In order to start my review, I will kindly ask you to fill out the [contribution form](https://docs.google.com/forms/d/e/1FAIpQLSd0V270r75tTy9YbT50irQBUpKK8Wfn1aCUihYNn2rc_LkPpA/viewform)

Please don't hesitate to contact me with any questions :)

**Comment by Umamahesh-Loginsoft** [comment]
@JudahSchwartz  Can you please let me know the exact issue why it was broken
for me all the unit test cased are passed. and I updated the version in pack_metadata.json to 1.1.2
but still it fails

**Comment by Umamahesh-Loginsoft** [comment]
Hey @JudahSchwartz 
Can you please help me with this
I'm getting this when try to update release notes using the command.
image

**Comment by JudahSchwartz** [comment]
@Umamahesh-Loginsoft 
That error looks like its coming from running the demisto-sdk in a windwos environment
You can look [here](https://xsoar.pan.dev/docs/contributing/contrib-requirements#windows-users) for our suggestions about how to configure the environment

**Comment by JudahSchwartz** [comment]
@Umamahesh-Loginsoft what is this pr trying to solve?
@meital-aizen FYI

**Comment by Umamahesh-Loginsoft** [comment]
> @Umamahesh-Loginsoft what is this pr trying to solve? @meital-aizen FYI

@JudahSchwartz In this pr we are adding the **fetch_only_current_item** filed to the Actionable alert content API.

**Review by JudahSchwartz — APPROVED** [review]

**Pull request merged**
