### PR TITLE
Integration proofpoint threatresponse

### PR DESCRIPTION
**Pull request by liorblob**

### CODE REVIEW

**Comment by liorblob** [comment]
@dorsha has been tested with mock instance, however I'm waiting for the client to fix their hardware issue to test with them, and according to those tests I will determine the use cases for the documentation and playbook test.

**Comment by dorsha** [comment]
👍

**Comment by anara123** [comment]
@liorblob what is the status of this PR?

**Comment by anara123** [comment]
it hasn't been test on test lab

**Pull request closed without merging**
