### PR TITLE
Feature/send teams notification using workflow

### PR DESCRIPTION
**Pull request by nikstuckenbrock**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
```
Action Required:
O365 connectors within Teams will be deprecated and notifications from this service will stop.
[Learn more](https://aka.ms/O365ConnectorDeprecation)
about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request.
[Set up workflow](https://teams.microsoft.com/l/task/c3a1996d-db0f-4857-a6ea-7aabf0266b00?url=https://make.powerautomate.com/teams/store/flowCreation?templateId=d271a6f01c2545a28348d8f2cddf4c8f)
```
## Description
Regarding to the issue printed by the Microsoft O365 Webhook you'll need to replace the current connector with a workflow webhook. This has some side effects, the specification of the `HTTP` `POST` format for the webhook changes. This PR adds a new flag which switches the content to the new specification. An example on how to create the specific worklfow can be found [here](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/).

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by samuelFain** [comment]
@nikstuckenbrock Thank you for your contribution!
We have started reviewing your PR and will update you as soon as its done. 
In the meantime, if you have any questions or additional information you’d like to provide, please feel free to reach out.

Thank you again for your effort and patience.

**Comment by samuelFain** [comment]
Hi @nikstuckenbrock, appreciate your patience on this one.
The PR itself looks great and all the checks have passed.
However, we will need to have a live call for the demo for this PR, together with @merit-maita , who is in charge of Microsoft Teams within our team. We aim to verify certain aspects of these changes to ensure that we do not break backward compatibility for other users.

Please reach out to me wherever convenient (mail, Slack DFIR, here in a comment) so we can schedule a call.
sfainberg@paloaltonetworks.com

Thanks again!

**Review by samuelFain — CHANGES_REQUESTED** [review]
Hi @nikstuckenbrock!

This is a kind reminder that I am still waiting for your response regarding scheduling a call about this contribution.

**Comment by samuelFain** [comment]
Schedualed a demo call in 22.08.2024 – 15:00 (UTC+3).

**Comment by nikstuckenbrock** [comment]
Sorry for the failed demo today. Unfortunately I didn't have the time to look at the changes again after my vacation and assumed that everything would work, I hope I didn't cause any trouble.

Anyway, now everything works and I have prepared a [demo video](https://drive.google.com/file/d/1zkIEecjMLAanZs54iXk5GdmW_Y8YCUBP/view?usp=sharing) for you.

Let me know what you think.

@samuelFain @merit-maita

**Comment by samuelFain** [comment]
@nikstuckenbrock, Apologies for our delay with this contribution, as I'm currently on PTO.
Me and @merit-maita will examine your demo video asap and update you on any progress.

Thank you for you penitence.

**Review by samuelFain — APPROVED** [review]

**Pull request merged**
