### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by asafshen**
Update version number in content release to 3.1.0
(this version will not be release. only for demisto 3.1.0 release)

@dorsha we need to make sure will take content for master please

### CODE REVIEW

**Comment by gshriki** [comment]
What will be the experience for customers with 3.0.1 or older versions?

**Comment by asafshen** [comment]
@gshriki nothing
They won't get any content update,  since we wont publish a release
(Only master version will be affected, this will be used when build 3.1.0)

**Comment by aviadl** [comment]
@asafshen but we will release in a week , what will you do then

**Comment by asafshen** [comment]
@aviadl we will update version number before
even if not - we will have the same problem we have today (costumers with 2.5/2.6 still have content update - isn't them?)

**Pull request merged**
