### PR TITLE
Open Source Vulnerabilities Integration

### PR DESCRIPTION
**Pull request by anilagr**
…ret ignore

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[fixes: Initial PR](https://github.com/demisto/content/pull/16992)

## Description
OSV is a vulnerability database and triage infrastructure for open source projects aimed at helping both open source maintainers and consumers of open source.

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by merit-maita — CHANGES_REQUESTED** [review]
Thank you for the hard work.
the integration image does not meet the required standards which are : 120x50 px PNG, transparent background, <10kB in Size

**Comment by merit-maita** [comment]
@anilagr one last thing, the picture should have a transparent background.
thanks.

**Comment by anilagr** [comment]
@merit-maita Removed the background. Please let me know if any other changes are needed. Thanks

**Comment by merit-maita** [comment]
@anilagr Thank you, all look good.
i'd like to schedule a demo, please let me know when does it suit you?

**Review by merit-maita — APPROVED** [review]

**Pull request merged**
