### PR TITLE
Ml playbook improved memory

### PR DESCRIPTION
**Pull request by lperryp**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/44775)

## Description
* Using populateFields argument also when training a phishing classifier from the playbook to improve memory usage
* Adding a helper script to extend query so only relevant incidents for phishing labels will be returned 

continuing this PR : https://github.com/demisto/content/pull/17416/files

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
@lperryp In Release Notes 1.4.0, it says (Available from Cortex XSOAR 0.0.0).  I think you need to add in the version of Cortex XSOAR or remove this.
@erezh31 Doc review completed.

**Comment by lperryp** [comment]
@ShirleyDenkberg Will fix this, thanks a lot!

**Review by yguezpa — APPROVED** [review]

**Comment by meirwah** [comment]
@lperryp whats the status here ?

**Comment by lperryp** [comment]
> 

The PR is ready, on fails on unrelated tests, asked to force-push this, will try to run this tests again

**Comment by lperryp** [comment]
@idovandijk hi what's up? I don't manage to complete this pr because Phishing `Investigation - Generic v2 - Campaign Test (Mock Disabled)` keeps failing, you know who can stabilize this test?

**Comment by idovandijk** [comment]
> @idovandijk hi what's up? I don't manage to complete this pr because Phishing `Investigation - Generic v2 - Campaign Test (Mock Disabled)` keeps failing, you know who can stabilize this test?

Yeah the test is failing intermittently in the build:
https://github.com/demisto/etc/issues/44740

I opened a server issue on that as there's a server error during the test and I can't figure why it's happening. I also am not able to reproduce it when I run the test myself:
https://github.com/demisto/etc/issues/46660

**Comment by lperryp** [comment]
image
this is the snapshot I managed to take if it's helpful, eventually managed to pass this pr

**Comment by idovandijk** [comment]
> image this is the snapshot I managed to take if it's helpful, eventually managed to pass this pr

thanks. same as the issue I opened

**Pull request merged**
