### PR TITLE
PANW Magnifier - naming and logo

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16583
fixes: https://github.com/demisto/etc/issues/16584

### CODE REVIEW

**Comment by Itay4** [comment]
@bakatzir why is the logo not 4kb?

**Comment by bakatzir** [comment]
@Itay4 I used the logo given in https://github.com/demisto/etc/issues/16583, see my comment.
maybe decided to do PANW logo in 8kb.

**Comment by bakatzir** [comment]
Although the cortex is 4kb, i'll check with eyanv.

**Comment by Itay4** [comment]
all logos should be 4kb, otherwise we might encounter performance issues

**Comment by bakatzir** [comment]
@Itay4 she said up to 10kb is fine.

**Pull request merged**
