### PR TITLE
Skipping Preparing Content Packs For Testing in nightly builds

### PR DESCRIPTION
**Pull request by hod-alpert**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30886

## Description
Nightly instances uses production bucket, there is no need to create a staging bucket in that flow.

## nightly build example:
https://app.circleci.com/pipelines/github/demisto/content/58364/workflows/1dd65370-dd64-4540-96ff-9fa9c26e791c

### CODE REVIEW

**Review by ShahafBenYakir — COMMENTED** [review]
Let's trigger new nightly build

**Comment by hod-alpert** [comment]
@ShahafBenYakir We have it here https://app.circleci.com/pipelines/github/demisto/content?branch=hod%2Fskip_preparing_content_in_nightly_test

**Review by ShahafBenYakir — APPROVED** [review]

**Review by guyfreund — CHANGES_REQUESTED** [review]
Please also delete the nightly configuration from `prepare_content_packs_for_testing.sh`

**Comment by hod-alpert** [comment]
@guyfreund Done, is this what you meant?
 A new nightly link with the changes is here - https://app.circleci.com/pipelines/github/demisto/content/58654/workflows/a5414ad6-087c-46f2-866c-57a60bf1e43c

**Review by guyfreund — APPROVED** [review]

**Comment by guyfreund** [comment]
successful upload run: https://app.circleci.com/pipelines/github/demisto/content/58711/workflows/cdd89bf6-5a1e-4b57-ad54-462fa12181e7

slack msg:
image

**Pull request merged**
