### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saassecuritywriter**
Added missing descriptions. Updated existing descriptions with more detail. Added some clarity to a Note that used the term "we", which is confusing. Added additional topic, which displays in Help tab but is best here--in one location. I still don't know what to write for Use system proxy settings, but will figure it out and update with next pull request.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by julieschwartz18** [comment]
Doc review complete for this file. @eyalpalo - there are extensive edits throughout the file, please review and confirm.

**Comment by eyalpalo** [comment]
@saassecuritywriter Please reflect the changes @julieschwartz18 made in the README.md file so they will show also in the yml file (mainly descriptions).

**Comment by saassecuritywriter** [comment]
> @saassecuritywriter Please reflect the changes @julieschwartz18 made in the README.md file so they will show also in the yml file (mainly descriptions).

**Comment by eyalpalo** [comment]
Hi @saassecuritywriter,  please see [this PR](https://github.com/demisto/content/pull/17100). There are changes made at the same places. Are you aware to this PR?

**Pull request closed without merging**
