### PR TITLE
CrowdStrike Falcon Intel Feed - map also non-STIX fields

### PR DESCRIPTION
**Pull request by ilappe**
## Status
- [x] In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/43493

## Description
Map also to non-STIX filed to align with servers >= 6.2.0 

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
   - [x] No

### CODE REVIEW

**Comment by ilappe** [comment]
@yaakovi need force merge due to [CJ105] (missing test playbook)

**Review by yaakovi — COMMENTED** [review]
looks ok to me
@ChanochShayner please review as well.

**Review by ChanochShayner — APPROVED** [review]

**Comment by ilappe** [comment]
@julieschwartz18
Hi 
any update for the doc review?
it's simple one line in the release notes 
Thanks a lot!

**Comment by julieschwartz18** [comment]
@ilappe - doc review complete.

**Comment by ilappe** [comment]
@yaakovi 
force merge is needed here due to CJ105 (missing test playbook)
thanks!

**Pull request merged**
