### PR TITLE
Improved FortiGate Integration:

### PR DESCRIPTION
**Pull request by ayman-m**
- Handling the login disclaimer (Issue https://github.com/demisto/etc/issues/21878)
- Two additional commands to Create and Delete IP Address Objects (Issue https://github.com/demisto/etc/issues/21877)

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: Issues #21877, #21878

## Description
- Handling the login disclaimer
- Two additional commands to Create and Delete IP Address Objects

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by bakatzir** [comment]
@ayman-m I believe that you've had the courtesy to do this as well.
fixes: https://github.com/demisto/etc/issues/21017

**Comment by ayman-m** [comment]
> @ayman-m I believe that you've had the courtesy to do this as well.
> fixes: [demisto/etc#21017](https://github.com/demisto/etc/issues/21017)

thanks @bakatzir, I believe it's the same issue as demisto/etc#21877, I had a call with Anar about the same issue around the same time 21017 was opened , so we can close one of them as duplicate

**Comment by anara123** [comment]
@ayman-m is the PR is ready?

**Comment by yuvalbenshalom** [comment]
I am planing to finish the tests today

**Comment by yuvalbenshalom** [comment]
Hi @ayman-m, I just managed to test your version, the log in and the new commands are working.
I wanted to ask, why did you make it a V2 integration? did this break any backward compatibility?

**Comment by ayman-m** [comment]
> Hi @ayman-m, I just managed to test your version, the log in and the new commands are working.
> I wanted to ask, why did you make it a V2 integration? did this break any backward compatibility?

Hi @yuvalbenshalom , I am closing this PR to submit a new Pack PR shortly as discussed last week

**Comment by ayman-m** [comment]
The new PR #6593

**Pull request closed without merging**
