### PR TITLE
Changed ML field associations to be associated with Phishing

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Description
Changed `DBotPrediction` and `DBotPredictionProbability` field associations to be associated only with Phishing incidents.

## Does it break backward compatibility?
   - Yes(?) - if the fields were utilized in other incident types, though they shouldn't have.

### CODE REVIEW

**Comment by idovandijk** [comment]
> why are we changing that?

The fields are currently only used in Phishing incidents as far as I know, and are displayed for any new incident type right now, which makes no sense. @meirwah @erezh31 is that the only reason?

**Comment by meirwah** [comment]
correct @idovandijk

**Comment by kirbles19** [comment]
@idovandijk Done.

**Comment by idovandijk** [comment]
@anara123 can we force merge?

**Pull request merged**
