### PR TITLE
Increasing timeout for inline and attachment phishing test playbooks

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
Ready

## Does it break backward compatibility?
   - No

### CODE REVIEW

**Comment by ronykoz** [comment]
Don't merge, the test is on skip, why?

**Comment by Shellyber** [comment]
This two tests are not in skipped. And I need to merge a fix for playbook and I can't because this two fails on timeout

**Comment by idovandijk** [comment]
Wait, @ShahafBenYakir already increased the timeout one time.
The reason it's failing on timeout is because it's stuck in a manual task. 
This PR should've fixed it https://github.com/demisto/content/pull/2907
We need to understand why the test is going in the "non-malicious" path again. The malicious URL "http://tpb.crushus.com/www.paperstreetcash.com" should be in the "Malicious" list of Palo Alto Minemeld

**Comment by ronykoz** [comment]
@idovandijk please try to create a build which runs these tests and monitor it while he is running the test, try to figure out what's happening here

**Pull request merged**
