### PR TITLE
"WIP - do not merge yet - CylancePROTECT - 

### PR DESCRIPTION
**Pull request by JonathanMeler**

### CODE REVIEW

**Comment by meirwah** [comment]
@JonathanMeler what's the status of this?

**Comment by JonathanMeler** [comment]
@meirwah having problem creating threats, pushed by priority

**Comment by meirwah** [comment]
@JonathanMeler status now?

**Comment by JonathanMeler** [comment]
@meirwah @Spivaka we have a problem with the instance. currently we can't create threats and work with them.
we're trying contacting cylance for assistance

**Comment by Spivaka** [comment]
@JonathanMeler resolve and merge. we will handle the fetch once we will get attention from Cylance

**Comment by JonathanMeler** [comment]
@Spivaka sounds good. i'll do it first thing next week after Wix/Citi/McAfee demos will be over
is this ok time-wise?

**Comment by Spivaka** [comment]
Yes. But please send yourself a reminder so You won't forget

**Pull request closed without merging**
