### PR TITLE
Mindmeld changes

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28023

## Description
Option of updating only the indicators mentioned and not all of them

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No (default of change is False)

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by yaakovi — APPROVED** [review]

**Comment by yaakovi** [comment]
bump pack revision

**Comment by orlichter1** [comment]
@yaakovi if I bump the version I'll have to add RN. Should I add them as well?

**Comment by orlichter1** [comment]
@kirbles19 could you please have a look at the release notes and the `stateless` parameter + arguments added?

**Comment by kirbles19** [comment]
@orlichter1 Done.

**Pull request merged**
