### PR TITLE
Add new Cybraics integration

### PR DESCRIPTION
**Pull request by NanoDano**
## Status
Ready

## Related Issues
Adds an integration for Cybraics service

## Description
This integration allows users to query Cybraics for case information

## Required version of Demisto
4.5-5.0

## Does it break backward compatibility?
 No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by yaakovi** [comment]
@NanoDano please resubmit the integration in the package format according to our standard:
https://demisto.pan.dev/docs/package-dir/

**Comment by anara123** [comment]
@NanoDano please delete all the files from the main directory. Github shows that you have 1571 new files.
Or just fork again

**Comment by NanoDano** [comment]
Thank you I will clean it up. I had committed some test files in to the same branch that I did not intend to be part of the PR. I will be fixing this PR. I am working on getting the Dockerfile submitted to our other repo to pass all the build steps.

**Comment by NanoDano** [comment]
Now that I know what I need to fix (directory structure and providing the docker file) and because this PR got messed up, I am going to close it out and make a fresh one that is more up to standard.

**Pull request closed without merging**
