### PR TITLE
Add double quotes around subject in KQL query

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Add double quotes around email subject in KQL query so that the query works correctly in the event the subject contains spaces or other special characters. Otherwise the subject query will not work as expected, leading to confusion.

## Screenshots
Current **Search And Delete Emails - Generic v2** `O365KQL` input value is missing double quotes around the email subject:

Screen Shot 2022-05-19 at 1 46 25 PM

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ilappe** [comment]
@ali-sawyer 
please dump the version in the pack_metadata.json

@idovandijk please take a look 
this is playbook changes

**Review by idovandijk — CHANGES_REQUESTED** [review]
Thanks for the fix. However I noticed that the correct phishing tests are not configured for this playbook. To ensure this fix doesn't break anything, please change the `tests` to have the following tests:

`Phishing v3 - Get Original Email + Search & Delete - Test`
`Phishing v3 - DomainSquatting+EML+MaliciousIndicators - Test`

@tomer-pan I think one of your fixes reverted the new tests. Though my request for https://github.com/demisto/etc/issues/45815 should prevent such cases in the future

**Comment by ilappe** [comment]
Hi @ali-sawyer 
Have you seen the comments above from @idovandijk ?

**Comment by ali-sawyer** [comment]
@ilappe yes I saw it. This PR just had bigger implications than I expected and I have not had time to fix the tests. I may have questions when I get to that step. I will try to get that done in the next couple days.

**Comment by ali-sawyer** [comment]
@ilappe I think I misunderstood Ido's comment when I first read it. I thought tests needed to be written, but it looks like the correct test playbooks exist, they were just not configured for the `Phishing - Generic v3` playbook. Let me know if we are good to go now!

**Review by idovandijk — APPROVED** [review]
Thanks @ali-sawyer, and yes I meant that we just had to update the YMLs with the already existing correct tests :)

**Comment by ilappe** [comment]
moved to doc review

**Comment by ShirleyDenkberg** [comment]
@ilappe @idovandijk Doc review completed.

**Pull request merged**
