### PR TITLE
Return GetTime test playbooks

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
@jochman What was fixed? 🤔

**Comment by jochman** [comment]
Nothing, it's working (this playbook is running script with no API calls.)

**Comment by ShahafBenYakir** [comment]
SO why did it fail? Plus, aren't these two TPB?

**Comment by jochman** [comment]
Two PB that are dependent on the same script.
Server issue most likely.

**Comment by ShahafBenYakir** [comment]
Add a `fixes: ...` for the two issues, otherwise, these issues will remain open

**Pull request merged**
