### PR TITLE
IsIPInRanges fix bug

### PR DESCRIPTION
**Pull request by JonathanMeler**
use new lib - `netaddr`

fixes: https://github.com/demisto/etc/issues/9988

### CODE REVIEW

**Comment by aviadl** [comment]
@JonathanMeler in commonServer we have the following function:
isIPInSubnet
I think it should do the work, and then we will have a consistent logic
Please check it, and change the script to call this function (JS)

**Comment by dorsha** [comment]
@JonathanMeler - please see @aviadl comment and close the PR.

**Comment by JonathanMeler** [comment]
@aviadl, changed to Javascript

**Comment by dorsha** [comment]
I improved the script syntax (and performance).

**Pull request merged**
