### PR TITLE
Q radar none type from events limit error

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/37633

## Description
Fixed an error where the new integration parameter 'events_limit' was interpreted as None.
Added a protection in code where it will handle such cases

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Documentation

### CODE REVIEW

**Review by ShahafBenYakir — COMMENTED** [review]
Bear in mind that this issue will happen for **every** param that doesn't have a default value and is not required.

**Comment by tomneeman151293** [comment]
@ShahafBenYakir Noted.

**Comment by tomneeman151293** [comment]
@ShahafBenYakir Forgot to approve this?

**Comment by tomneeman151293** [comment]
@dantavori @ShahafBenYakir Master 6.0.0 failure is due to QRadar v2 failure which is not related to the changes.

**Comment by tomneeman151293** [comment]
@dantavori @ShahafBenYakir PR passed

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
