### PR TITLE
PAN-OS - Fix incorrect parsing of Panorama High-Availability state XML

### PR DESCRIPTION
**Pull request by adambaumeister**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [] Ready
- [X] In Hold - Pending customer validation

## Description
This fixes a bug when the instance of panorama is configured in High-availaiblity. We correctly look for the panorama HA state, but the result XML was not being parsed correctly, which results in all commands failing as it cannot resolve which server is active.

@GuyAfik @jpeng19 

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Review by GuyAfik — APPROVED** [review]
Looks great, @adambaumeister can you please pull from master to re-trigger the build?

**Comment by adambaumeister** [comment]
Waiting on customer to confirm fix then will do!

**Comment by adambaumeister** [comment]
@GuyAfik we haven't heard back from the customer, might be a good sign that it's working. Your call whether to merge or keep waiting. I've updated the branch from upstream.

**Comment by GuyAfik** [comment]
> @GuyAfik we haven't heard back from the customer, might be a good sign that it's working. Your call whether to merge or keep waiting. I've updated the branch from upstream.

@adambaumeister lets wait, at the meantime please add release-note and bump the pack-metadata

**Comment by GuyAfik** [comment]
@adambaumeister please pull from master again, fixed an issue in the pan-os build.

**Comment by GuyAfik** [comment]
@adambaumeister lets push forward that one

**Comment by adambaumeister** [comment]
fyi -

The original fix is verified working from a seperate user, so that part is good. However, another user has reported that after fixing the HA component, now get-ha-status does not return the correct status and peer for Panorama specifically. This was due to the mishandling of the "state" field in the XML when referring specifically to Panorama. I've added this and also updated from master, so I would just wait on the confirmation of that fix before merging.

**Comment by adambaumeister** [comment]
I had to replicate the topology in the lab. The issue was due to an incorrect statement overriding the dictionary that stores the High-availability pairs. I added the following code;

```python
        # This is only true if Panorama is in HA mode as well.
        if self.ha_pair_serials:
            self.ha_pair_serials = {**self.ha_pair_serials, **ha_pair_dict}
        else:
            self.ha_pair_serials = ha_pair_dict
```

It's important to note that HA Panorama is still not fully supported, and it was never intended to be, as it is only possible to add one panorama IP into the integration at a time. This is a feature that could be added at another time if there is a reason for it.

**Review by GuyAfik — APPROVED** [review]
That is amazing!

**Pull request merged**
