### PR TITLE
Adding Armis logos for the XSIAM ingestion dashboard

### PR DESCRIPTION
**Pull request by paulusaltus**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Adds logo files for display on the XSIAM dashboard

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by paulusaltus** [comment]
Haven't tested this as it's for the XSIAM dashboard, but the Armis pack has 2 integrations...the "Armis" one works properly, so tracked down related pull https://github.com/demisto/content/pull/30931 that added the two files...for this one I copied the same two files to the "ArmisEventCollector" integration to push out and have on the XSIAM dashboard...let me know any questions, thanks!

**Review by maimorag — APPROVED** [review]
Hi @paulusaltus,
Thank you for your contribution!
Good work :)

Before merging, we'll need to confer with our partner, and we'll ensure to keep you informed along the way.

**Comment by maimorag** [comment]
Hey @paulusaltus,
we still haven't got a response from the partner.
In the meantime, can you please merge from master?
Thanks.

**Comment by paulusaltus** [comment]
Thanks @maimorag, merged in current master... fyi, I saw that PAN support submitted a related PR https://github.com/demisto/content/pull/34154, in case they end up conflicting versions depending on which one goes first... thanks for your support!

**Comment by maimorag** [comment]
Hey @paulusaltus,
I'll be on PTO from May 12th to May 19th. Apologies for any delay in advance.

**Review by hadar-kaplan-armis — APPROVED** [review]

**Pull request merged**
