### PR TITLE
New indicator layouts

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
On hold - layouts don't get updated properly in the content update - needs to be further investigated

## Description
Added new layouts and scripts that relate to the new layouts.

## Screenshots
image
image
image

## Required version of Demisto
5.0.0

## Does it break backward compatibility?
   - No

## Must have
- Tests - Can't be tested, must be tested manually.
- [ ] Code Review

## Additional details:
contains fix from https://github.com/demisto/content/pull/4113

### CODE REVIEW

**Comment by DeanArbel** [comment]
@JonathanMeler waiting for your (non-technical) approval, and then I'll assign technical reviewer

**Comment by DeanArbel** [comment]
After manual testing this feature, it would seem our server implementation is currently unable to install indicator layout content in the content update.

For this reason this PR is on hold until we can properly investigate the reason for this.

**Comment by Itay4** [comment]
Better to close pr and keep branch alive

**Comment by DeanArbel** [comment]
Server bug was fixed, the new layouts should now appear properly - will test this manually before merge

**Pull request merged**
