### PR TITLE
fix bug - process Email is extracting indicators twice on the same data

### PR DESCRIPTION
**Pull request by adi88d**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16186

## Description
The issue: 
tasks 'Add original email attachments to context' and 'Set incident with the Email object data' extract indicators on the same data.
The fix:
duplicate 'Set incident with the Email object data' task - one is extract indicators and the other not. 

## Screenshots
before:
image

after:
image

## Required version of Demisto
4.0.0

## Does it break backward compatibility?
   - No

### CODE REVIEW

**Comment by glicht** [comment]
@idovandijk fyi

**Comment by idovandijk** [comment]
1. Uploaded both to my dev environment and ran tests which I configured to run the new `Process Email - Generic`. **The playbook works fine.**
2. @glicht, I think that this is a workaround more than a fix, because autoextract should not even produce duplicate indicators.
3. @adi88d, please add descriptions to the tasks you touched. Also explain that one is with autoextract and one isn't (as we try to make it more clear to customers). I know they didn't have descriptions to begin with, but we try to add whenever we edit tasks.
image
Consult with @kirbles19 about the wording. Once that is done I'll approve :)

**Comment by glicht** [comment]
@idovandijk it is a performance improvement. There isn't an issue of duplicates.

**Comment by adi88d** [comment]
> 1. Uploaded both to my dev environment and ran tests which I configured to run the new `Process Email - Generic`. **The playbook works fine.**
> 2. @glicht, I think that this is a workaround more than a fix, because autoextract should not even produce duplicate indicators.
> 3. @adi88d, please add descriptions to the tasks you touched. Also explain that one is with autoextract and one isn't (as we try to make it more clear to customers). I know they didn't have descriptions to begin with, but we try to add whenever we edit tasks.
>    image
>    Consult with @kirbles19 about the wording. Once that is done I'll approve :)

I updated the tasks descriptions

**Comment by kirbles19** [comment]
> 1. Uploaded both to my dev environment and ran tests which I configured to run the new `Process Email - Generic`. **The playbook works fine.**
> 2. @glicht, I think that this is a workaround more than a fix, because autoextract should not even produce duplicate indicators.
> 3. @adi88d, please add descriptions to the tasks you touched. Also explain that one is with autoextract and one isn't (as we try to make it more clear to customers). I know they didn't have descriptions to begin with, but we try to add whenever we edit tasks.
>    image
>    Consult with @kirbles19 about the wording. Once that is done I'll approve :)

@idovandijk Which wording, specifically?

**Comment by idovandijk** [comment]
> > 1. Uploaded both to my dev environment and ran tests which I configured to run the new `Process Email - Generic`. **The playbook works fine.**
> > 2. @glicht, I think that this is a workaround more than a fix, because autoextract should not even produce duplicate indicators.
> > 3. @adi88d, please add descriptions to the tasks you touched. Also explain that one is with autoextract and one isn't (as we try to make it more clear to customers). I know they didn't have descriptions to begin with, but we try to add whenever we edit tasks.
> >    image
> >    Consult with @kirbles19 about the wording. Once that is done I'll approve :)
> 
> @idovandijk Which wording, specifically?

Task descriptions that @adi88d just added. Please check with him.

**Comment by adi88d** [comment]
> specifically

i added

**Pull request merged**
