### PR TITLE
[ASM] EXPANDR-5776: Add AWS Hierarchy Info to Main Playbook

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-5776

## Description
Add AWS Hierarchy Info to Main Playbook

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@ShirleyDenkberg , can you please review?

**Comment by johnnywilkes** [comment]
On hold until https://github.com/demisto/content/pull/31951 is complete

**Comment by johnnywilkes** [comment]
@capanw / @BigEasyJ , please review this is on hold until https://github.com/demisto/content/pull/32123 is merged

**Review by capanw — APPROVED** [review]

**Comment by johnnywilkes** [comment]
@ShirleyDenkberg , please review

**Comment by johnnywilkes** [comment]
@YuvHayun , this has been approved by Xpanse team.  Please merge when possible

**Comment by YuvHayun** [comment]
Merging to internal pr.

**Review by YuvHayun — APPROVED** [review]

**Pull request merged**
