### PR TITLE
hello world doc take 2

### PR DESCRIPTION
**Pull request by glicht**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Hello world doc

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by glicht** [comment]
@kirbles19 do you want to review?

**Comment by anara123** [comment]
The integration since then. There are new commands. I will open a new PR
for readme of Hello World

**Comment by kirbles19** [comment]
@glicht Done.

**Comment by glicht** [comment]
@anara123 should we close this or merge?

**Comment by anara123** [comment]
@fvigo will add a helloworld in this PR https://github.com/demisto/content/pull/6441

**Pull request closed without merging**
