### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonbreimer**
Updated Tanium documentation links. Thanks!

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Two documentation links for Tanium are fixed in this change. The current links are no longer valid.

### CODE REVIEW

**Review by YuvHayun — APPROVED** [review]

**Comment by YuvHayun** [comment]
Hey @jasonbreimer, thx for your contribution.. please make sure to sign the from above.

**Comment by YuvHayun** [comment]
@jasonbreimer still waiting for the CLA

**Comment by YuvHayun** [comment]
Hey @jasonbreimer, still waiting for you to sign the CLA.

**Comment by YuvHayun** [comment]
Closing the pr.
Please re-open when you are available to sign the CLA.

**Comment by jasonbreimer** [comment]
Hello, unfortunately I'm unable to sign the CLA. Since this is a URL link replacement is there any other way to get this change?

**Comment by YuvHayun** [comment]
You should be able to sign it from either the [here](https://cla-assistant.io/demisto/content?pullRequest=32679) or [here](https://forms.gle/XDfxU4E61ZwEESSMA). Let me know if you still have issues.

**Comment by YuvHayun** [comment]
Closing this pr, I'll work to merge it myself on [this](https://github.com/demisto/content/pull/32975) one.

**Pull request closed without merging**
