### PR TITLE
file sample from path add playbooks & tests

### PR DESCRIPTION
**Pull request by erezh31**

### CODE REVIEW

**Comment by erezh31** [comment]
tests:
cb get file path - https://demo2.demisto.com/#/WorkPlan/38515
d2 get file path - https://demo2.demisto.com/#/WorkPlan/38508 - not run on the CI (impossible, port open only from demo2)
generic get file path - https://demo2.demisto.com/#/WorkPlan/38514 (fail due to server bug, will be fixed tonight)

**Comment by erezh31** [comment]
fix https://github.com/demisto/etc/issues/8038

**Comment by erezh31** [comment]
@JonathanMeler please review - we need to merge this (CI pass for this playbook test - other tests failed)

**Comment by erezh31** [comment]
CI passed for my test (failed for proofpoint)
@meirwah can you merge plz?

**Comment by meirwah** [comment]
Let's wait for content build to stable

**Pull request merged**
