### PR TITLE
added hidden key to old integration params

### PR DESCRIPTION
**Pull request by YuvHayun**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
[added hidden key to old integration params](https://github.com/demisto/content/commit/50c92eaf116e90732361e1ffd95b66cc11bb8f6e)

## Does it break backward compatibility?
   - [ ] Yes
   - [X] No

### CODE REVIEW

**Review by ShahafBenYakir — APPROVED** [review]
Nice

**Comment by ShahafBenYakir** [comment]
@YuvHayun Already approved this PR. Fix the status checks and merge.

**Comment by YuvHayun** [comment]
The build is failing because the integration is skipped from nightly [IN140], I need you to force merge this PR

**Comment by YuvHayun** [comment]
The build is failing because the integration is skipped in nightly, I need you to force merge it please.

**Pull request merged**
