### PR TITLE
Update playbook api path

### PR DESCRIPTION
**Pull request by ANT1OFF**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Description
The API path for the execute playbook functionality of the integration is out of date.

## Screenshots
Current API doc from Red Canary:
image

Error when using the function:
image

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No
       - Further details: Fixes already broken external dependency.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by eyalpalo** [comment]
Hi @ANT1OFF! please bump version of this pack and add release notes.

**Comment by ANT1OFF** [comment]
@eyalpalo done.

**Comment by eyalpalo** [comment]
Hi @ANT1OFF lets schedule a demo. A recorded session of the command in action is good as well.

**Comment by ANT1OFF** [comment]
image
Is this sufficient? The instance has the changes proposed in this pr.

**Comment by eyalpalo** [comment]
Hi @ANT1OFF, actually if you choose the recorded video option I would like to see the following:
- The command being executed.
- The command being executed with wrong argument (such as playbook-name).
- The playbook running.

**Review by eyalpalo — APPROVED** [review]

**Pull request merged**
