### PR TITLE
Add tags for result object of agents

### PR DESCRIPTION
**Pull request by nikstuckenbrock**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added a field for the response. The docs for the API are private sadly.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by kgal-pan** [comment]
@munna-metron @saurabh-metron - Can you please review and approve these changes?

**Comment by munna-metron** [comment]
HI @kgal-pan ,
The changes are looking good to me. an we can proceed further. thanks
cc: @saurabh-metron

**Comment by nikstuckenbrock** [comment]
Hey @kgal-pan,

is there something I can do to fix the Review Release Notes step?

**Comment by kgal-pan** [comment]
> Hey @kgal-pan,
> 
> is there something I can do to fix the Review Release Notes step?

@nikstuckenbrock  - Don't worry about it, it's a known issue and the check is not mandatory to pass.

**Comment by nikstuckenbrock** [comment]
Hi @kgal-pan ,

is there something we are waiting for here? :)

**Comment by kgal-pan** [comment]
> Hi @kgal-pan ,
> 
> is there something we are waiting for here? :)

Nothing from my end, waiting for @thefrieddan1's review.

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
