### PR TITLE
send-mail added from arg

### PR DESCRIPTION
**Pull request by ChanochShayner**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/17776

## Description
Added 'from' arg to send-mail command.

### CODE REVIEW

**Comment by ChanochShayner** [comment]
Duplicate of this - https://github.com/demisto/content/pull/16693 (was closed due to conflicts)
@guykeller @yuvalbenshalom Please review the changes.
In addition, this PR needs force merge due to docker update validation and docker update broke the UTs as here - https://github.com/demisto/content/pull/16523#issuecomment-1003897003

**Review by guykeller — APPROVED** [review]
To me, this looks great.
@yuvalbenshalom Unless you have any comments, if you can force merge this please, I'll appreciate it. I'm accountable if anything goes wrong.

**Comment by ChanochShayner** [comment]
@yuvalbenshalom Please don't merge it yet.

**Comment by ChanochShayner** [comment]
@yuvalbenshalom Ready for force merge.

**Review by yuvalbenshalom — APPROVED** [review]

**Pull request merged**
