### PR TITLE
Case management updates dec2022

### PR DESCRIPTION
**Pull request by beauchompers**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
None

## Description
Updates to the Case Management Pack including:
- Added Phase field to the info section on the layout.  
- Replaced Detection URL field with External Link field to match Malware Investigation and Response Layout.
- Added Case Management - Generic - Start SLA Timers, this playbook will start the Time to Assignment or Remediation SLA timers based on whether an Owner is assigned to the Incident.
- Can be used as a sub-playbook to perform the same logic across different playbooks/use cases. (Available from Cortex XSOAR 6.5.0).
- Added the Case Management - Generic - Start SLA Timers sub-playbook to the Case Management v2 playbok, which performs the same logic of starting the appropriate timers based on Owner assignment.

## Screenshots
None, will share video of the changes on the other form. 

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ X] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by ostolero — APPROVED** [review]
Hi @beauchompers the changes look good! I'm adding our security team member @efelmandar to review the playbooks,layout and incident types.

**Comment by efelmandar** [comment]
Hi @beauchompers, thank you for your contribution, all the changes looks great! I've sent you an access request for the video you linked if you could approve it I would love to see it in action, but anyway I think we can continue with the merge - @ostolero

**Comment by efelmandar** [comment]
@beauchompers thank you for the access I watched the video and it looks great, @ostolero I would say we can go forward with the merge

**Comment by ostolero** [comment]
Hi @beauchompers , Everything looks great! watched the demo video and we can merge.
I changes the Case Management - Generic - Start SLA Timers playbook from version to 6.2.0 (it was 6.5.0)
As you explained in the demo video this is the same logic, and as the original playbook is 6.2.0 the sub-playbook can't require a higher version. If this sounds off let me know and we can create a different setup.
Thanks!

**Review by ostolero — APPROVED** [review]

**Pull request merged**
