### PR TITLE
Vectra AI - Detect - Retrospective fetch

### PR DESCRIPTION
**Pull request by Vectra-ODuda**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
.

## Description
A retrospective delay (1 hour) has been added in the fetch_incidents function to ensure all occurred events are properly pulled from Vectra API.
We are doing that to ensure that all events are properly transformed into XSOAR incidents (when necessary) when these events are not published by the API in the same order as they occurred.

No change in documentation as inputs/outputs/config are identical.

_Some linting improvements have been shipped also._

## Must have
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Vectra-ODuda** [comment]
Hi @mmhw , @kgal-pan , 
It's been a while I haven't done a PR for XSOAR. Let me know if it's ok :)

Wish you a nice day

**Comment by Vectra-ODuda** [comment]
Hi @kgal-pan @mmhw , I saw the "review release notes" failed, but seems an issue in your end, as other tests (ci/circle) are not complaining about this release note file.
Thx in advance for your feedback.

**Comment by kgal-pan** [comment]
> Hi @kgal-pan @mmhw , I saw the "review release notes" failed, but seems an issue in your end, as other tests (ci/circle) are not complaining about this release note file. Thx in advance for your feedback.

@Vectra-ODuda - Correct, the release notes check is failing because some issue on our side. It's not mandatory so no need to worry about it.

**Comment by mmhw** [comment]
Hi @Vectra-ODuda ,
Thank you for your contribution!
Looks great work :)

Note that we have a mechanism called "look back" that is designed exactly for your case.
Basically, it allows the user to define in fetch how long to look back and pull events.
The documentation is [here](https://xsoar.pan.dev/docs/integrations/fetch-incidents-lookback).
You can see an example in [O365 Outlook Mail (Using Graph API)](https://github.com/demisto/content/blob/master/Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py) or in [ServiceNow v2](https://github.com/demisto/content/blob/master/Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml).

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by mmhw** [comment]
Hi @Vectra-ODuda, we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

**Review by mmhw — APPROVED** [review]
Nice work

**Pull request merged**
