### PR TITLE
Taxii Feed bug

### PR DESCRIPTION
**Pull request by merit-maita**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43527

## Description
fixed an issue where some indicators types were not parsed as expected.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kobymeir** [comment]
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12136081004)
- **FeedTAXII** pack version was bumped to **1.2.25**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

**Review by thefrieddan1 — APPROVED** [review]

**Comment by merit-maita** [comment]
the TPB is failing in the build for NG machine, since the %%SERVER_HOST%% param is not parsed correctly in NG envs.
more details: https://jira-dc.paloaltonetworks.com/browse/CIAC-11471

**Review by Ni-Knight — APPROVED** [review]
Looks good, did you test it with a dummy TAXII 1 server?

**Comment by kobymeir** [comment]
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12232346213)
- **FeedTAXII** pack version was bumped to **1.2.26**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

**Pull request merged**
