### PR TITLE
[WIP] Contrib/CDS - Added CyCognito Content Pack

### PR DESCRIPTION
**Pull request by crestdatasystems**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [ ] Ready
- [x] In Hold - (We recently discovered that the CyCognito team has changed the APIs, causing some of the commands to fail. As a result, we'd like to put this PR on hold. We will perform regression testing and change the status of the PR once we receive confirmation from CyCognito.)

## Description
Created a content pack for CyCognito which provides an organization's attack surface overview to SOCs.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by crestdatasystems** [comment]
pycountry docker image PR: https://github.com/demisto/dockerfiles/pull/7855

**Comment by AradCarmi** [comment]
Hi @[crestdatasystems](https://github.com/crestdatasystems),
Thank you for contributing!
Apologies for the delay in reviewing your PR, the team will review your code as soon as possible.

Thanks again.

**Review by idovandijk — COMMENTED** [review]
Thank you for your patience.
While @AradCarmi is reviewing your code, I've reviewed the rest of the content.
From my side no changes are required, except that all new content should have a `fromversion: 6.2.0` and not `6.0.0`.
Also since there are no playbooks or anything complex requiring a demo, it would suffice to see a GIF demonstrating the dashboard / incident layout instead - could you attach a GIF/video showing those?

**Comment by crestdatasystems** [comment]
Hello, We have changed the PR status to On Hold because of we recently noticed that the CyCognito team has changed the APIs, and thus some of the commands will not function properly. Hence we would like to put this PR to hold. Once we get confirmation from CyCognito we will do the regression testing and change the status of the PR. We are really sorry for the inconvenience.

**Comment by AradCarmi** [comment]
@[crestdatasystems](https://github.com/crestdatasystems) - Thank you for the update.
Following what you have described, we would prefer to close the PR for now.
Once you’ll get the confirmation from Cycognito and done with the regression tests, please open a new PR with the updated files, so it will be reassigned to a reviewer from our team.
Please don’t hesitate to contact me with any question :)
Thanks again.

**Pull request closed without merging**
