### PR TITLE
made the use case development stage field searchable

### PR DESCRIPTION
**Pull request by joe-cosgrove**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Modified a field so it is searchable and viewable in the dashboard

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by joe-cosgrove** [comment]
@MichaelYochpaz updated release notes. I only updated one custom field use case development stage. that is what is needed for my dashboards and reports to work. im aware of making them all indexable and the performance impacts. this will not cause issues.

**Review by MichaelYochpaz — APPROVED** [review]
Looks good :)
Please just resolve the conflict with pack's version and we'll merge it.

**Review by melamedbn — APPROVED** [review]

**Comment by joe-cosgrove** [comment]
i did bump the version already? Am i missing something.

**Comment by joe-cosgrove** [comment]
@MichaelYochpaz i didn't see your message, i was trying to fix my fork because it appears it was an old version. Updating the release notes with the sdk  wasn't working for me since it was old version. please discard these changes and ill modify the files as you instructed. I overcomplicated it lol

**Pull request merged**
