### PR TITLE
Rsapack

### PR DESCRIPTION
**Pull request by adit-ghildiyal**
nw-database-dump, nw-sdk-summary , nw-sdk-session commands do not use concentrator port and usessl as query parameters

### CODE REVIEW

**Review by anas-yousef — COMMENTED** [review]
@adit-ghildiyal
Thank you so much for your contribution!

Please bump the pack version in the pack_metadata.json file and add notes describing your changes to a new Release Notes file.
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

Once done, we can conduct a small demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available for one over DFIR. 
Feel free also to send me a recording of a demo.

**Comment by anas-yousef** [comment]
Hey @adit-ghildiyal, feel free to send me a message on Slack if you need further assistance.

**Comment by adit-ghildiyal** [comment]
> Hey @adit-ghildiyal, feel free to send me a message on Slack if you need further assistance.

Sure, @anas-yousef . I will do the needful and update this PR , also the demo. I just wanted to know, while setting up the dev environment for xsoar with vscode extension and wsl2, I'm getting some issues. Initially it had worked but now I'm faing some errors again. I have followed https://xsoar.pan.dev/docs/concepts/vscode-extension#local-development-linux-macos-wsl2 , do you have any other document or tutorial for this?

**Comment by anas-yousef** [comment]
@adit-ghildiyal Let us chat via Slack so I can help you with your environment.
Are you in our [DFIR](https://start.paloaltonetworks.com/join-our-slack-community) slack channel?

**Comment by anas-yousef** [comment]
Hey @adit-ghildiyal, let us talk over Slack so we can fix your issue. Hit me up at your earliest convenience :).

**Comment by anas-yousef** [comment]
Hi @adit-ghildiyal, 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

**Pull request closed without merging**
