### PR TITLE
SaaS Security text changes.

### PR DESCRIPTION
**Pull request by zhiwangprisma**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by DeanArbel** [comment]
@zhiwangprisma You seem to have a conflict in the `README.md` please make sure to fix it.

@yaron-libman Please assign someone to review the documents in this PR.

**Comment by zhiwangprisma** [comment]
rebased pr, need to reopen

**Comment by tschanfeld** [comment]
Will this be reopened for doc review?

**Comment by DeanArbel** [comment]
@tschanfeld Doesn't seem so.
@zhiwangprisma why did you close the PR?

**Pull request closed without merging**
