### PR TITLE
Added function read chart data in ArcSight Logger Integration (#3246)

### PR DESCRIPTION
**Pull request by anara123**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
added function to handle chart operation in logger search

## Related PRs
https://github.com/demisto/content/pull/3246

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by anara123** [comment]
@Itay4 this is an external PR. I merged it to internal PR. 
There is no instance to test it, but I think we can merge it.

**Comment by Itay4** [comment]
@kirbles19 please review the changelog

**Comment by kirbles19** [comment]
@Itay4 Done.

**Comment by Itay4** [comment]
@anara123 ?

**Pull request merged**
