### PR TITLE
Armorblox sdk code changes

### PR DESCRIPTION
**Pull request by SamhithaTatipalli**

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
@AradCarmi please review this docker PR together with [this PR ](https://github.com/demisto/dockerfiles/pull/8214)

**Comment by AradCarmi** [comment]
Hi @SamhithaTatipalli,
Thank you for contributing!
Apologies for the delay in reviewing your PR, the team will review your code as soon as possible.

Thanks again.

**Review by ShacharKidor — CHANGES_REQUESTED** [review]
Hi @SamhithaTatipalli, 
Thank you for your contribution! - good job :)

In order to complete your contribution:
1. Please see my comments and suggestions below.
2. Please add a release note file that describes the changes made in this PR, and also bump the pack's version. You can easily do so by running the following SDK command: 
`demisto-sdk update-release-notes -i <path to the armorblox pack>`. For more info please see: [update-release-notes-command](https://xsoar.pan.dev/docs/documentation/release-notes#when-i-run-the-update-release-notes-command-it-does-not-find-any-of-my-changes).

@idovandijk - Please review the changes in the classifier and playbook. 

I'm available for every question, here or via slack. 
Thanks again!

**Comment by ShacharKidor** [comment]
I opened an updated docker PR with the last changes - [8431](https://github.com/demisto/dockerfiles/pull/8431).

**Review by idovandijk — COMMENTED** [review]
Thank you for the contribution and for waiting patiently as we took time to review your content.
You've done a good job. Here are my comments for the playbooks and classifier:
1. Are you sure this condition is correct? It means that whether the incident needs a review or remediates automatically, it will send an email. But it looks like your intention was that only ones that need review will have an email sent. Also, is it possible to have many actions under the `Armorblox.Threat.remediation_actions`? If so the condition should be "in" rather than "equals".
2. Depending on where you want to be managing your incident, You may prefer to use an Ask task to get the response from the admins on whether they remediated the incident or think it's benign. Then you can decide to close your XSOAR incident with the corresponding admin's resolution (malicious/benign) 
3. This is regarding the mapper which is not part of the PR, but I'm curious: are you sure that mapping your Armorblox priority to our XSOAR severity is correct? We have values 0, 0.5, 1, 2,  with the respective meanings of unknown, informational, low, medium, high, critical.
4. I would like to see a demo of an incident that ran through the classifier and sent an email in the playbook, It could also be a short video recording, that would be fine by me.

Thanks again for your hard work!

**Comment by ankita-sharma2019** [comment]
> Thank you for the contribution and for waiting patiently as we took time to review your content. You've done a good job. Here are my comments for the playbooks and classifier:
> 
> 1. Are you sure this condition is correct? It means that whether the incident needs a review or remediates automatically, it will send an email. But it looks like your intention was that only ones that need review will have an email sent. Also, is it possible to have many actions under the `Armorblox.Threat.remediation_actions`? If so the condition should be "in" rather than "equals".
> 
> image
> 
> 2. Depending on where you want to be managing your incident, You may prefer to use an Ask task to get the response from the admins on whether they remediated the incident or think it's benign. Then you can decide to close your XSOAR incident with the corresponding admin's resolution (malicious/benign)
> 3. This is regarding the mapper which is not part of the PR, but I'm curious: are you sure that mapping your Armorblox priority to our XSOAR severity is correct? We have values 0, 0.5, 1, 2,  with the respective meanings of unknown, informational, low, medium, high, critical.
> 4. I would like to see a demo of an incident that ran through the classifier and sent an email in the playbook, It could also be a short video recording, that would be fine by me.
> 
> Thanks again for your hard work!

Hi @idovandijk ,
Please find the response to your comments below - 

1. Yes, the condition is correct. Now, we also want to trigger the email notification if the remediation action is "WILL_AUTO_REMEDIATE". The field remediation_actions will always have one item in the list so, the condition is correct.
2. We are not managing the incident. It is something we have left for our actual customers to add/configure.
3. Yes, We are mapping the severity correctly. We map directly the string values and not integer value - 
image
4. Here is the video - https://drive.google.com/file/d/1dlRrLjNu5G_DFub1ZJx_0jIKUtj3UXmb/view?usp=sharing. Please let me know if you can access it. 

Thank you!

**Review by idovandijk — COMMENTED** [review]
Thank you so much for the demo @SamhithaTatipalli.
I only have 1 suggestion and it is to create a more user friendly incident layout rather than having 1 small section with all the incident details there.
However this is not a necessity to continue and merge.

@ShacharKidor from my side this is approved, feel free to approve once all code changes are done.

**Comment by ankita-sharma2019** [comment]
> Hi @SamhithaTatipalli, Thank you for your contribution! - good job :)
> 
> In order to complete your contribution:
> 
> 1. Please see my comments and suggestions below.
> 2. Please add a release note file that describes the changes made in this PR, and also bump the pack's version. You can easily do so by running the following SDK command:
>    `demisto-sdk update-release-notes -i <path to the armorblox pack>`. For more info please see: [update-release-notes-command](https://xsoar.pan.dev/docs/documentation/release-notes#when-i-run-the-update-release-notes-command-it-does-not-find-any-of-my-changes).
> 
> @idovandijk - Please review the changes in the classifier and playbook.
> 
> I'm available for every question, here or via slack. Thanks again!

Hi @ShacharKidor , 
Trying to update the release notes but getting this message - 
image
Should I do it manually?

**Comment by ShacharKidor** [comment]
Hi @SamhithaTatipalli, 
As we spoke offline - please grant me permission to your branch and I'll update the RN for you - [inviting-collaborators-to-a-personal-repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository),
Or push the RN I sent to you via slack. 

Thanks.

**Comment by SamhithaTatipalli** [comment]
@urajat , @absanjay2022, Please find the PR for Cortex Integration.

**Review by ShacharKidor — APPROVED** [review]

**Pull request merged**
