### PR TITLE
Slack: set max workers for default loop executor

### PR DESCRIPTION
**Pull request by glicht**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22018

## Description
Limit the thread pool used by the main asyncio pool

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation - changelog

### CODE REVIEW

**Comment by liorblob** [comment]
So there is no need to close the threads?

**Comment by glicht** [comment]
No need to close. They will be reused.

**Comment by GalRabin** [comment]
@glicht 
In my solution, I am not limiting the max workers,
I wanted to live it unlimited, I just wanted to close this pool in the end, so it will save its regular cap (I don't think we have a problem with number of threads together) if I am not mistaking?

**Comment by kirbles19** [comment]
@glicht Done.

**Comment by glicht** [comment]
Build failing on timeout of waiting to test to complete even though test completes fine.

**Pull request merged**
