### PR TITLE
Added the vsys param to the register_ip_tag command

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
- [x] Ready

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22176

## Description
Added the vsys param to the following commands:
- register_ip_tag command
- unregister_ip_tag_command
- register_user_tag command
- unregister_user_tag command

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Comment by Shellyber** [comment]
I tested it locally in our env - it seems that the API does recognize the vsys param in this command (it will also throw an error if the vsys is not valid) 
I can't test a change since we only have vsys1
I will send it to the customer to verify

**Comment by Shellyber** [comment]
@ShahafBenYakir / @GuyAfik Ready for review

**Comment by ShahafBenYakir** [comment]
@Shellyber please add a verification for the vsys param inside the unit test.

**Comment by Shellyber** [comment]
@ShahafBenYakir done

**Comment by GuyAfik** [comment]
@Shellyber how will this behave if we run those commands against panorama instance and not a firewall?

**Comment by Shellyber** [comment]
@GuyAfik The behavior is the same behavior, it takes the default vsys, even if it's not passed to the command. 
So empty string or nothing at all its the same.
But I'll update to keep the same behavior.

**Review by GuyAfik — APPROVED** [review]

**Pull request merged**
