### PR TITLE
Kenna v2 - Asset Group enhancement

### PR DESCRIPTION
**Pull request by SergeBakharev**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Implements additional commands to retrieve Asset Group related data from Kenna API:
* kenna-get-asset-group - Gets details of a specific asset group
* kenna-list-asset-groups - Lists all the possible asset groups and summary information
* kenna-get-top-fixes - Shows the most impactful (top) fixes for the specified asset group

## Minimum version of Demisto
- [ ] 5.0.0
- [X] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

### CODE REVIEW

**Comment by SergeBakharev** [comment]
I see CI has picked up a number of issues for me to resolve. Will look at them in the next day or two.

**Comment by Bargenish** [comment]
@SergeBakharev  Please fill the contribution[ registration form](https://docs.google.com/forms/d/e/1FAIpQLSd0V270r75tTy9YbT50irQBUpKK8Wfn1aCUihYNn2rc_LkPpA/viewform)

**Comment by SergeBakharev** [comment]
@Bargenish Contributor form completed. I haven't got a video but if it helps I can record one.

**Review by Bargenish — COMMENTED** [review]
Thanks for your contribution @SergeBakharev. looks great.
Few notes:
- Please go over the `KennaV2.yml` file and verify the types of the command's outputs according to the suggested changes.
- Please add unit tests for the added commands. See [this](https://xsoar.pan.dev/docs/integrations/unit-testing) for more info. 
- Please add the commands youve added to the existing TestPlaybook. See [this](https://xsoar.pan.dev/docs/integrations/test-playbooks) for more info.
- Please add the new commands to the README.md. See [this](https://xsoar.pan.dev/docs/integrations/integration-docs) for more info.
- Add an argument called `limit` to the `kenna-list-asset-groups` (see suggestion)

**Comment by SergeBakharev** [comment]
Thanks for the detailed feedback @Bargenish  I really appreciate it. I will review and implement the suggested changes later this week.

**Comment by bakatzir** [comment]
@SergeBakharev is there anything we can do to speed up the comment fixes? would you want to set a short zoom for further explanation or are all the comments clear?

**Comment by Bargenish** [comment]
Closing since no response here and on slack. @SergeBakharev reopen if relevant.
@bakatzir FYI

**Pull request closed without merging**
