### PR TITLE
Create script-padZeros.yml

### PR DESCRIPTION
**Pull request by omercnet**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/17254

## Description
Transformer to pad a string/number with zeros

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
None

## Additional changes
Describe additional changes done, for example adding a function to common server.

### CODE REVIEW

**Comment by Itay4** [comment]
@omercnet sorry for the very late review
if you can still handle that (else let me know), please do the following:
1. merge from master
2. convert to package format
3. add test
4. convert rn to changelog

**Comment by omercnet** [comment]
did 1) 
could you please do the rest? 🙄

**Comment by Itay4** [comment]
@kirbles19 please review yml

**Comment by kirbles19** [comment]
@Itay4 all done.

**Pull request merged**
