### PR TITLE
Changed default playbook for phishing to Phishing Investigation - Generic v2

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
Related to: https://github.com/demisto/etc/issues/44049 and https://github.com/demisto/content/pull/16533

## Description
Changed the default playbook that runs for Phishing incidents to be `Phishing Investigation - Generic v2` for 2 reasons:
1. It's our main phishing playbook. Currently it's set to run the manual one which is outdated and is... well... manual.
2. We will need this new configuration to be able to test new incidents with that playbook, because once we generate phishing incidents we will need them to be set for the right playbook.

## Minimum version of Cortex XSOAR
5.0

## Does it break backward compatibility?
Technically yes, but it should not cause problems since no one is using the manual playbook, and most customers duplicate and customize their own, and set their Phishing incident type to run it.

@melamedbn @tomer-pan fyi

### CODE REVIEW

**Comment by idovandijk** [comment]
Checked and this shouldn't affect users of v5 since we don't update the incident types there. In 5.5 where we can start detaching, we won't update for those who have changed their default playbook - since they have to detach it to do that.

**Comment by ShirleyDenkberg** [comment]
@michalgold Doc review completed.

**Comment by idovandijk** [comment]
@michalgold we can merge

**Comment by idovandijk** [comment]
In the currently supported XSOAR versions, our default is `Phishing - Generic v3`, so this PR is not relevant anymore.

**Pull request closed without merging**
