### PR TITLE
20.8.2

### PR DESCRIPTION
**Pull request by ebuige**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added api https://<ISEHost>:9060/ers/config/ancendpoint/clear to remove an applied policy from an endpoint. Added api /admin/API/mnt/Session/EndPointIPAddress/{ip}' to return session data from an active endpoint and then extract the mac address from the returned xml and write to context menu. Added http request call for admin/monitoring API calls (no port required) and added header to handle returned xml. 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No - Changes were made to be non invasive to the existing code. No existing code was modified. All code added is independent of existing functionality. 

## Must have
- [ ] Tests
- [x] Documentation - provided to XSOAR Lead Developer (Anar Azadaliyev) and R&D manager Shai Yaakovi. 
[Cisco_ISE.pdf](https://github.com/demisto/content/files/5402703/Cisco_ISE.pdf)

### CODE REVIEW

**Comment by Itay4** [comment]
Hi @ebuige 
This pull request seems a bit off, what are you trying to do ?

**Comment by ebuige** [comment]
I have provided all the details to Anar Azadaliyev and Shai Yaakovi. Please confer with them for a clearer understanding. Thank You.

**Comment by ebuige** [comment]
I wasn't sure exactly how your process worked, I thought they just wanted the code and that's why I sent in PDF format. Here it is in plain text. Hopefully this is what you are looking for.
[Cisco_ISE.py.txt](https://github.com/demisto/content/files/5407999/Cisco_ISE.py.txt)

**Comment by yaakovi** [comment]
@ebuige 
as we discussed on the call, I'm closing this PR.

**Pull request closed without merging**
