### PR TITLE
Social Engineering Domain Analysis

### PR DESCRIPTION
**Pull request by nericksen**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by nericksen** [comment]
I have found a bug where an error is thrown if the domain is not registered and therefore returns no DNS results.  Have added a conditional to check for this and will push the fix.

**Comment by dorschw** [comment]
@nericksen please note that #16131 has been merged, removing the `Condition` tag, and will be available in the marketplace soon. Please make the required changes to the PR (as well as the bug you mentioned), and then we'll be able to move forward and merge this one. Thanks!

**Comment by nericksen** [comment]
okay thanks @dorschw will update once it is available

**Comment by nericksen** [comment]
Updated to the enrichment playbook to use "GetStringDistance", README now uses a white background on the image , added conditional task before rasterizing the domains.

**Review by dorschw — APPROVED** [review]

**Pull request merged**
