### PR TITLE
ProtectWise added token parameter

### PR DESCRIPTION
**Pull request by dmourer**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added support for token authentication as requested by customer

## Minimum version of Demisto
- [ x] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

### CODE REVIEW

**Comment by Itay4** [comment]
@dmourer thanks for the contribution !
can you please comment when this is ready for review ?

**Comment by Itay4** [comment]
@dmourer are you still working on this? do you need any help from our side?

**Comment by dmourer** [comment]
Approved

**Comment by Itay4** [comment]
@dmourer what do you mean by "Approved"?

**Comment by fvigo** [comment]
@itay4 it was tested by them and is ready

**Comment by Itay4** [comment]
@kirbles19 please review the yml and changelog

**Comment by kirbles19** [comment]
@Itay4 Done.

**Pull request merged**
