### PR TITLE
urlscan - file metadata issue fix

### PR DESCRIPTION
**Pull request by derilevi**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
-

## Description
In some cases, when the given URL points to a file, urlscan API does not return all the expected metadata values and the integration fails. This modification fixes the issue.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by heipei** [comment]
No objections from our end getting this merged!

**Comment by derilevi** [comment]
Hi,
Can you give me an update on this PR? Is there any problem which is blocking the merge?
Thank you!
Best Regards,
Levente

**Comment by derilevi** [comment]
Hi,
I made a mistake in my repo, while trying to update it to the latest commit and that's why many people were added to the PR.
Sorry about that.
Best Regards,
Levente

**Review by jbabazadeh — APPROVED** [review]
Hi @derilevi,
Thank you for your contribution!
Good work :)
Sorry for the delay I apologize.

**Pull request merged**
