### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DorisNaaman**
Added README.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by yaakovpraisler** [comment]
@DorisNaaman - Please sign in to the [CLA](https://cla-assistant.io/demisto/content?pullRequest=14068).
And also please fill out the [contribution form](https://forms.gle/XDfxU4E61ZwEESSMA), so I can start review the PR.

**Comment by DorisNaaman** [comment]
Done.

*Dor Doris Naaman*
Security Product
***@***.***

**Review by yaakovpraisler — APPROVED** [review]
Looking good.
Please check the secrets in the failed validation, and ignore them if you want or remove them.

**Comment by DorisNaaman** [comment]
i dont really know how to do it. is it crucial for the PR ?
i can ask our relevant integration person who was involved

*Dor Doris Naaman*
Security Product
***@***.***

**Comment by yaakovpraisler** [comment]
First check if it's a real secret. If you don't know then check with whoever is supposed to know.
if it's a secret then remove it, if not, so you can ignore it by adding this to the secret_ignore file (Packs/Logzio/.secrets-ignore)

**Pull request merged**
