### PR TITLE
Symantec bluecoat malware analysis - Beta

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
~~In Progress~~ READY
~~Still missing integration and command names as will be decided by @Arsenikr~~

## Related Issues
fixes: https://github.com/demisto/etc/issues/12002

## Description
implementing only:
upload-url
upload-file
get-report
and detonation playbooks ***without*** genericpolling

## Required version of Demisto
4.0.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests - no. no instance.
- [x] Documentation - will not be generated for beta.
- [x] Code Review

## Technical writer review
~~will not be reviewed.~~
- [ ] [YAML file](https://github.com/demisto/content/blob/e296dd11d2755127423ca303849ce002e2d7181a/Beta_Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis.yml)
- [ ] [PB Detonate File](https://github.com/demisto/content/blob/e296dd11d2755127423ca303849ce002e2d7181a/Beta_Integrations/playbook-SymantecBlueCoatMalwareAnalysis_DetonateFile.yml)
- [ ] [PB Detonate URL](https://github.com/demisto/content/blob/e296dd11d2755127423ca303849ce002e2d7181a/Beta_Integrations/playbook-SymantecBlueCoatMalwareAnalysis_DetonateURL.yml)

### CODE REVIEW

**Comment by bakatzir** [comment]
@silviudm Hey.
First of all - thanks for the contribution.
I've made changes to the integration code, yml, commands names and playbooks.

Command names might change prior to the release.

Is it possible to ask you to try out the new integration code with the customer to make sure it is working? If there are any issues, I can join to a quick call and fix on the fly.
thanks.

**Comment by silviudm** [comment]
Not problem at all! I can test the integration next week with RWJBH! One qq
- how did you’ve implemented the pooling for scans? Via websocket ?
-- 


Thanks,

Silviu Dascalu

Customer Success Engineer

sdascalu@paloaltonetworks.com

+34-664-607-549

**Comment by Arsenikr** [comment]
> ## Status
> In Progress
> Still missing integration and command names as will be decided by @Arsenikr
> 
> ## Related Issues
> fixes: [demisto/etc#12002](https://github.com/demisto/etc/issues/12002)
> 
> ## Description
> implementing only:
> upload-url
> upload-file
> get-report
> and detonation playbooks _**without**_ genericpolling
> 
> ## Required version of Demisto
> 4.0.0
> 
> ## Does it break backward compatibility?
> * No
> 
> ## Must have
> * [x]  Tests - no. no instance.
> * [x]  Documentation - will not be generated for beta.
> * [ ]  Code Review
> 
> ## Technical writer review
> * will not be reviewed.

Integration name: Symantec Bluecoat Content and Malware Analysis

command names will have the prefix **symantec-cma-**

**Comment by bakatzir** [comment]
@silviudm We did not. I wrote in the description that i'm not using polling.

**Comment by richardbluestone** [comment]
Docs reviewed and updated.

**Pull request merged**
