### PR TITLE
new integration for Deep Instinct (https://github.com/demisto/content…

### PR DESCRIPTION
**Pull request by asiadeepinstinct**
…/pull/6490 was approved and I was asked to create a new PR because of repository cleaning )

Same files as before

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [x] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by asiadeepinstinct** [comment]
@ronykoz new PR as you requested (duplicate of https://github.com/demisto/content/pull/6490 ) that was approved before

**Comment by asiadeepinstinct** [comment]
> @ronykoz new PR as you requested (duplicate of #6490 ) that was approved before

CLA is signed

**Comment by ronykoz** [comment]
@asiadeepinstinct seems that your UTs are failing, can you take a look at that please?

**Comment by asiadeepinstinct** [comment]
> @asiadeepinstinct seems that your UTs are failing, can you take a look at that please?

I had minor import issue that I fixed,
now it says it's failing but in curcleCI I dont the the error in and says
Your job ran 5 tests in unknown with 0 failures

can you explain why it fails?
https://circleci.com/gh/demisto/content/54454?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request closed without merging**
