### PR TITLE
[ASM] EXPANDR-6313 - Update Playbooks to Reference New Alert Objects

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6313

## Description
Updated playbooks to utilize new *asmprotocol* and *asmprovider* fields.

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@ShirleyDenkberg , please review when possible

**Comment by johnnywilkes** [comment]
@BigEasyJ / @capanw , please review when possible

**Review by capanw — APPROVED** [review]

**Comment by ShirleyDenkberg** [comment]
@capanw @aaron1535 @tomer-pan Doc review completed.

**Comment by johnnywilkes** [comment]
@tomer-pan  @aaron1535 , this has been approved by Xpanse, please merge when possible

**Review by aaron1535 — APPROVED** [review]

**Pull request merged**
