### PR TITLE
[* A related enhancement case is ..  01476587 .This integration has v…

### PR DESCRIPTION
**Pull request by sankakongalagePA**
…arious additional options to filter the passwords made available via a password vault and other functional fixes.]

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue A related enhancement case is ..  01476587

## Description
This integration has various additional options to filter the passwords made available via a password vault and other functional fixes.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
hi @sankakongalagePA, thanks for the contribution !
a few comments before we start the review:
1. please sign the CLA
2. please elaborate on what exactly we're adding/fixing here
3. the YML file currently contain many changes that seem to be non related, please go over the diff in that file and remove these

**Comment by Itay4** [comment]
@sankakongalagePA hi
do you wish to continue working on this?
let me know if you need my assistance

**Comment by sankakongalagePA** [comment]
Hey Itay,
Sorry about the late reply. Got super busy with some other projects.
Just Signed the CLA
The changes were made by the PA support team as requested by PG&E. which
they want to include in the main release. I'm trying to get some more
information about the changes. As far as right now All i have is following
"

   - A related enhancement case is ..  01476587
   - This integration has various additional options to filter the
   passwords made available via a password vault and other functional fixes.

"
Have attached the original yml file that i received from the customer.
It's my first time working on an enhancement. Please let me know what would
be the next step. Thanks

**Comment by Itay4** [comment]
@sankakongalagePA currently there are a lot of changes done to both in the YML and the Python file, some are wrong (i.e. modifying the `id` file in the YML file and adding the Python code to the YML file)
i recommend starting at https://xsoar.pan.dev/docs/concepts/getting-started-guide

**Comment by Itay4** [comment]
hi @sankakongalagePA 
closing this due to inactivity, feel free to reopen if you get the time to work on it
thanks !

**Pull request closed without merging**
