### PR TITLE
attackiq documentation

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/19773

## Description
Adding documentation to package

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by glicht** [comment]
@kirbles19 please review

**Comment by yaakovi** [comment]
@orlichter1 please regenerate the docs with the original script (md output)

**Comment by orlichter1** [comment]
@yaakovi as I told @glicht, we no longer have an instance. I tried to find an html to md converter but none that I found could handle the tables generated by the HTML script.

**Comment by kirbles19** [comment]
We'll do this one, but manually creating these tables is not time effective and can't be maintained. We have to figure something else out for legacy HTML docs.

**Comment by glicht** [comment]
@kirbles19 you can leave it as HTML. Just make sure the documentation is according to standard. Once we understand the scale we can build a process for converting to HTML. The docs site will display HTML.

**Comment by kirbles19** [comment]
We already finished the conversion for this one, I believe I opened a PR to add the README to the integration package. We can close this.

**Pull request closed without merging**
