### PR TITLE
Return warning in case of result is empty list (object not found error)

### PR DESCRIPTION
**Pull request by revahh**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: Return warning in case of result is empty list (object not found error)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by ronykoz** [comment]
fixes https://github.com/demisto/content/pull/6413

**Comment by hirshbergshachar** [comment]
@bakatzir who else can review the text? Alex would be back only after the holiday

**Comment by revahh** [comment]
@David-BMS can you please check the status of Panorama Query Logs test since it fails PR

**Comment by ronykoz** [comment]
@hirshbergshachar @bakatzir where are we on this one?

**Comment by bakatzir** [comment]
@hirshbergshachar Should review.

**Comment by hirshbergshachar** [comment]
@ronykoz @bakatzir any special ideas why the build fails?

**Comment by anara123** [comment]
@revahh please pull from origin master and push. The build fails on a bug that we fixed in master

**Comment by hirshbergshachar** [comment]
@anara123 still fails

**Comment by bakatzir** [comment]
@hirshbergshachar on Test PB tasks. 
`Failed	 - palo_alto_firewall_test_pb (Mock Disabled)`
the test playbook needs to pass in order to merge the PR.

**Pull request merged**
