### PR TITLE
Splunkpy readme

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/18664
fixes: https://github.com/demisto/etc/issues/21337
## Description
The README file for Splunk

** A part of this file was already approved in the link above. New commands are 8 and 9**

### CODE REVIEW

**Comment by orlichter1** [comment]
@kirbles19 can you please go over this? thanks :)

**Comment by orlichter1** [comment]
@yaakovi I went over added things from changelog. Now I've also regenerated the docs as you suggested and updated the small additions/changes.

**Comment by kirbles19** [comment]
@orlichter1 Please regenerate the README with the new docs script.

**Comment by orlichter1** [comment]
@kirbles19 I did that 2 weeks ago. Has there been an update to the script since then?

**Comment by orlichter1** [comment]
@kirbles19 Regenerated the Readme :)

**Comment by kirbles19** [comment]
@orlichter1 Done

**Comment by orlichter1** [comment]
@yaakovi can we force merge this? @liorblob said to leave the `minServerVersion` and `certification` empty.

**Pull request merged**
