### PR TITLE
ThreatQ - Custom Status fix

### PR DESCRIPTION
**Pull request by roysagi**
## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/23991

## Description
Indicator status, indicator type, event type and attachment type are all pulled from ThreatQ instead of a predefined dict - in order to deal with custom statuses and types

### CODE REVIEW

**Comment by ronykoz** [comment]
Let's add the option to configure it once we contact ThreatQ

**Comment by roysagi** [comment]
> Let's add the option to configure it once we contact ThreatQ

Sent a mail to our contact there - waiting for a response.

**Comment by roysagi** [comment]
@amshamah419 - If you could please look at the RN.

**Comment by amshamah419** [comment]
Looks good

**Comment by ronykoz** [comment]
@roysagi let's fix the conflicts

**Pull request merged**
