### PR TITLE
Pack adoption process second stage with minor updates

### PR DESCRIPTION
**Pull request by kaushal-sophos**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
- Pack Adoption
- Added support for partner and organization level credentials.
- Added support for base URL caching.
- Reformatted entire code, fixed flake8 issues.
- Added support for the following commands:
    - Isolate endpoint(s) (sophos-central-isolate-endpoint)
    - Deisolate endpoint(s) (sophos-central-deisolate-endpoint)
- Updated the Docker image to: *demisto/python3:3.9.5.21272*.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kaushal-sophos** [comment]
@tallieber, the `Run Validations` stage is failing because of the following reasons:

1. `[IN124] - Parameter: "insecure" can't be hidden. Please remove this field.`: We have hidden the `insecure` parameter as Sophos doesn't want users to communicate with their APIs without SSL certificate verification in any case. But it seems that hiding this parameter is not allowed. As mentioned in the error message above, we also tried removing it but then it gives `[IN129] - You've removed integration parameters, the removed parameters are '{'insecure'}'`. So is it possible to hide/remove this parameter as it's not required in our use case? Before removing/hiding this parameter, we had confirmed this on Demisto DFIR Slack community and the suggestion was that the vendor can hide/remove this parameter if it's not required.
2. `[Errno 2] No such file or directory: 'Packs/SophosCentral/Author.yml'`: We have added the `Author_image.png` under `content/Packs/SophosCentral` directory as suggested in the docs: https://xsoar.pan.dev/docs/packs/packs-format#author_imagepng.

image

But it seems the validation script is looking for `Author.yml`. When we remove the image, it fails with `[IM109] - Partners must provide a non-empty author image under the path Packs/SophosCentral/Author_image.png`.

Could you please help to resolve these two issues? Thanks!

**Comment by tallieber** [comment]
> @tallieber, the `Run Validations` stage is failing because of the following reasons:
> 
> 1. `[IN124] - Parameter: "insecure" can't be hidden. Please remove this field.`: We have hidden the `insecure` parameter as Sophos doesn't want users to communicate with their APIs without SSL certificate verification in any case. But it seems that hiding this parameter is not allowed. As mentioned in the error message above, we also tried removing it but then it gives `[IN129] - You've removed integration parameters, the removed parameters are '{'insecure'}'`. So is it possible to hide/remove this parameter as it's not required in our use case? Before removing/hiding this parameter, we had confirmed this on Demisto DFIR Slack community and the suggestion was that the vendor can hide/remove this parameter if it's not required.
> 2. `[Errno 2] No such file or directory: 'Packs/SophosCentral/Author.yml'`: We have added the `Author_image.png` under `content/Packs/SophosCentral` directory as suggested in the docs: https://xsoar.pan.dev/docs/packs/packs-format#author_imagepng.
> 
> image
> 
> But it seems the validation script is looking for `Author.yml`. When we remove the image, it fails with `[IM109] - Partners must provide a non-empty author image under the path Packs/SophosCentral/Author_image.png`.
> 
> Could you please help to resolve these two issues? Thanks!

Hey, regarding the first issue, Im checking if we can ignore this error. Regarding the second, I will handle it in the internal PR  after we will merge this PR. You did all fine. I send you an email to schedule a demo. The code looks good.

**Comment by kaushal-sophos** [comment]
@tallieber, for your reference, here are a couple of screenshots showing the output of the isolate endpoint and deisolate endpoint commands. As discussed we will record a demo video that shows the same with multiple endpoint IDs and the corresponding context data shortly once we have actual endpoints available.

Screenshot 2021-08-17 at 3 31 22 PM

Screenshot 2021-08-17 at 3 31 35 PM

Also, for your reference, attaching the screenshot showing the confirmation for removing the `insecure` parameter as per the Sophos requirements:

image (1)

**Comment by tallieber** [comment]
> @tallieber, for your reference, here are a couple of screenshots showing the output of the isolate endpoint and deisolate endpoint commands. As discussed we will record a demo video that shows the same with multiple endpoint IDs and the corresponding context data shortly once we have actual endpoints available.
> 
> Screenshot 2021-08-17 at 3 31 22 PM
> 
> Screenshot 2021-08-17 at 3 31 35 PM
> 
> Also, for your reference, attaching the screenshot showing the confirmation for removing the `insecure` parameter as per the Sophos requirements:
> 
> image (1)

So regarding the insecure field, you can remove it and then add the validation code (IN129) to the pack_ignore file.

**Comment by kaushal-sophos** [comment]
@tallieber As requested, we have recorded a video that covers a detailed demo of newly added two commands (isolate/deisolate endpoints) with multiple endpoint IDs as command arguments. We have also covered the content of context data after running each command. Please find the video here: https://drive.google.com/file/d/1VukANloDwwjwHnptWzny4SomYn2LutM0/view?usp=sharing

Also, let me know if you still need any specific information. Thanks!

**Comment by kaushal-sophos** [comment]
@tallieber, I have also added `IN129` into `.pack-ignore` and removed the `insecure` parameter from `SophosCentral.yml`.

**Comment by kaushal-sophos** [comment]
@tallieber Did you get a chance to take a look at the demo? Let me know if there are any suggestions or you require more information. Thanks!

**Comment by nandishdoshi-sophos** [comment]
@tallieber Request you to please share if any more information needed, looking forward to get this PR merged asap

**Comment by mchasepan** [comment]
@tallieber when you're back, plz review demo video.
@ShahafBenYakir FYI

**Review by tallieber — APPROVED** [review]

**Pull request merged**
