### PR TITLE
Update GitHub Integration README

### PR DESCRIPTION
**Pull request by ayman-m**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Update Github README to include more information on how to configure Github authentication

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

### CODE REVIEW

**Comment by eyalpalo** [comment]
Hi @ayman-m, I reviewed your PR, looks good, please note that the build fails due to secretes test.

**Review by eyalpalo — APPROVED** [review]

**Comment by eyalpalo** [comment]
Hi @yaron-libman, please review this PR.

**Comment by julieschwartz18** [comment]
Hi @ayman-m @eyalpalo - can you give me permission to edit the README.md file? Thanks

**Comment by ayman-m** [comment]
> Hi @ayman-m @eyalpalo - can you give me permission to edit the README.md file? Thanks

Hi @julieschwartz18 , I have added you to the repo with write permission

**Comment by julieschwartz18** [comment]
@ayman-m - doc review is complete for the README file. Please note the following:
1. Reworded the introductory information (at the beginning of the file).
2. In a number of places there were minor misspellings in the descriptions (for example, in the updated file lines 993 - archived, line 1632 - workflow, line 1730 - organization)
3. There were minor capitalization and punctuation corrections throughout. 

Is it relevant to go back to the yaml file and make these corrections? Once you confirm these corrections I will click docs-approved. Thanks

**Comment by eyalpalo** [comment]
@ayman-m it is preferred that changes made in description that appear also in the yml will be changed there as well.

**Review by eyalpalo — APPROVED** [review]

**Comment by eyalpalo** [comment]
Hi @julieschwartz18, as I validated @ayman-m changed the yml to match the changes in the README, please add docs-approved label so we can merge.

**Pull request merged**
