### PR TITLE
Add keywords

### PR DESCRIPTION
**Pull request by RotemAmit**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5039)

## Description
Added vendor name to data source packs "keywords".

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by Shellyber — APPROVED** [review]
Looks good to me 
Lets ask @meital-aizen to have a look as well before merging

**Comment by Shellyber** [comment]
@meital-aizen Can you have a look?

**Comment by meital-aizen** [comment]
> @meital-aizen Can you have a look?

@RotemAmit Looks good, we're just missing one pack - G Suite Security Alert Center. Please add "Google" keyword to it and you can merge.

**Comment by RotemAmit** [comment]
@meital-aizen  G Suite Security Alert Center already has the "Google" keyword, this is why i didn't add it.

**Comment by RotemAmit** [comment]
> > @meital-aizen Can you have a look?
> 
> @RotemAmit Looks good, we're just missing one pack - G Suite Security Alert Center. Please add "Google" keyword to it and you can merge.

@meital-aizen G Suite Security Alert Center already has the "Google" keyword, this is why i didn't add it.

**Pull request merged**
