### PR TITLE
Fix cloudtrail contribution

### PR DESCRIPTION
**Pull request by Noy-Maimon**
reoponed contribution PR due to failure
original PR: https://github.com/demisto/content/pull/19717

### CODE REVIEW

**Comment by Noy-Maimon** [comment]
@amkoppad Hi there, I reopened your PR since it had an issue while merging.
I noticed you used a new docker image but i could not find it in our dockerfiles repo. did you open a pr for that? if not, you should open a dockerfiles pr, see more info here: https://github.com/demisto/dockerfiles#demistos-dockerfiles-and-image-build-management

**Comment by amkoppad** [comment]
Hi @Noy-Maimon. I tried to copy the AWS Cloudtrail master and duplicate it and made the changes. But I did have a custom boto3 image that automatically got picked up. Now changing it back to the one that master is using demisto/boto3:2.0.0.24033 is throwing an error at line where I implement the max fetch items.
line 464. (for response in paginator.paginate(**kwargs, PaginationConfig={'MaxItems': fetch_limit}):) says invalid syntax. I will try and figure it out. Meanwhile if you have the info handy please let me know. Thank you.

**Comment by amkoppad** [comment]
Hi @Noy-Maimon demisto/boto3:2.0.0.24033 image that master is using is NOT running python 3.3 or higher as base correct? Because changing the image back to the one that master has I am getting timestamp() error. datetime.datetime object does not have timestamp attribute.

**Comment by Noy-Maimon** [comment]
the contributor will open another PR

**Pull request closed without merging**
