### PR TITLE
Revert "McAfee ATD add credentials option in parameters"

### PR DESCRIPTION
**Pull request by bakatzir**
Reverts demisto/content#1941

### CODE REVIEW

**Comment by bakatzir** [comment]
Note to self: when merging this PR, also merge a new conf.json credentials to match this revert.

**Comment by Spivaka** [comment]
I think you have more changes than you need

**Comment by aviadl** [comment]
@bakatzir did you see the message that @Spivaka has wrote you ?

**Comment by bakatzir** [comment]
@aviadl  @Spivaka 
Yes it looks like the revert i meant to do in ATD.
in the jask file, it's a spare whitespace

**Pull request merged**
