### PR TITLE
Delete context auto option

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/14191

## Description
Added `auto` option to subplaybook arg. 

## Required version of Demisto
4.1.0+

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation (arg description + release notes)
- [ ] Code Review

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](https://github.com/demisto/content/blob/delete-context-auto-option/Scripts/script-DeleteConext.yml#L130) (description of subplaybook arg)
- [ ] [CHANGELOG](https://github.com/demisto/content/blob/delete-context-auto-option/Scripts/script-DeleteConext_CHANGELOG.md)

### CODE REVIEW

**Comment by glicht** [comment]
@yaakovi @ronykoz please check the build. The Configure Test Filter stage is failing:

image

Not sure. Tried adding `DeleteContext-auto-subplaybook-test` to `skipped_tests` but doesn't seem to help. And also getting errors on unrelated test playbooks.

**Comment by yaakovi** [comment]
since you edited the DeleteContext script, it collects and runs every test playbook that uses that script, therefore the large amount of collected tests.

regarding the errors, we have two options:
1) ignoring tests that doesn't appear in `conf.json` (require change in `configure_tests.py`)
2) adding the 3 tests to the test list in `conf.json`

**Comment by glicht** [comment]
@yaakovi see my commit: https://github.com/demisto/content/pull/4682/commits/c6b14f3a9fd1dd3f84d7449f95e42ea17b53c42d . Basically, if the test is in skip the verification doesn't fail.

**Comment by glicht** [comment]
@kirbles19 waiting for review. Only release notes and small arg description.

**Comment by kirbles19** [comment]
@glicht Done.

**Pull request merged**
