### PR TITLE
updated deviceName as optional graph

### PR DESCRIPTION
**Pull request by orhovy**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/20684

## Description
changed useAsKpi to true 

## Minimum version of Demisto
- [x] 5.5.0

## Does it break backward compatibility?
   - [x] Yes

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by orhovy** [comment]
image

**Comment by orhovy** [comment]
image

**Comment by bakatzir** [comment]
@kirbles19 Please review the RN:
https://github.com/demisto/content/blob/e1618f922e3bfe9dd293f35bbbd8d7de9f957f4a/IncidentFields/incidentfield-Device_Name_CHANGELOG.md

**Comment by kirbles19** [comment]
@orhovy Done.

**Pull request merged**
