### PR TITLE
Update DomainTools_Iris.py

### PR DESCRIPTION
**Pull request by bdanjoux**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: Running !domaintools-whois with raw-response=true returns nothing (an empty dict)

## Description
This PR introduces a "contents" in the results of the !domaintools-whois command to bring it inline with the other commands of this integration that return both Human Readable results and Raw results

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by aaron1535** [comment]
Hi @bdanjoux,
Thank you for your contribution.

In order to move forward with your contribution process, I want to understand the use case.
Usually, we use `raw_response` when we make any API call for the requested command, and in `raw_response` we will return the response returned from the endpoint
The use of `outputs` is to return information to the context (for which, of course, we need to arrange the information we want to return in an orderly dictionary)
Please explain what you want to do
Thank you

**Comment by bdanjoux** [comment]
Hi @aaron1535 

I want to make sure that the command `domaintools-whois` returns the raw response of the API, as it currently only returns human readable results.

Indeed, using `raw_response` is all that's needed here, I will modify the PR accordingly.

**Comment by aaron1535** [comment]
@bdanjoux Indeed, this is the right way to do what you asked for.
Please add release notes so we can merge the change
You can find more explanation [here](https://xsoar.pan.dev/docs/documentation/release-notes)

**Comment by aaron1535** [comment]
@bdanjoux. We are waiting for the partner's approval so that we can merge
in the meantime
Please update your Docker image to the latest version `1.0.0.114678`

**Review by aaron1535 — APPROVED** [review]

**Pull request merged**
