### PR TITLE
adding cisco umbrella investigation threatgrid will follow later based…

### PR DESCRIPTION
**Pull request by trorabaugh**
… on requests. This also uses the new arch.

### CODE REVIEW

**Comment by slavikm** [comment]
Nice.
When specifying the outputs - you need to document the leafs and not the object. Also, just returning the entire json to context might be an overkill - you want to expose only the interesting parts. The user already has the `Contents` as the raw response so if he wants something else from it he can get it via `Extend` property.

**Comment by trorabaugh** [comment]
will do

**Comment by meirwah** [comment]
@trorabaugh what's the statues of this?

**Comment by liorkol** [comment]
Being merged in another PR

**Pull request closed without merging**
