### PR TITLE
Virus total rfc1918

### PR DESCRIPTION
**Pull request by Anonymoo53**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold

## Related Issues
fixes: N/A

## Description
Adds an integration parameter that can be used to prevent queries against the VT API for private IP addresses reducing license usage.

## Must have
- [ x ] Tests
- [ x ] Documentation

### CODE REVIEW

**Review by ostolero — COMMENTED** [review]
Hi @Anonymoo53 , Thank you for this contribution!
As this is a partner pack we've reached out to Virus Total to review it.
As far as I checked everything looks good so we'll wait for their response.

**Comment by danipv** [comment]
Hi, thanks for your contribution, all looks good from VirusTotal side.

**Review by danipv — APPROVED** [review]
LGTM

**Comment by ostolero** [comment]
Great @danipv thank you,
@Anonymoo53 I've reached out using Slack to schedule our demo.

**Review by ostolero — APPROVED** [review]
Hi @Anonymoo53 , thanks for a great demo! we can merge

**Pull request merged**
