### PR TITLE
Compliance - Breach Notification - California

### PR DESCRIPTION
**Pull request by altmannyarden**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/23537

## Description
1. Created a new pack name: Breach Notification - US
2. Added 2 playbooks:
- breach notification - PII check
- Breach notification - California

## Screenshots
image
image

## Minimum version of Demisto
- [ ] 4.5.0
- [x] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by altmannyarden** [comment]
@yaron-libman Please look at the new 2 playbooks yml.

**Comment by yaron-libman** [comment]
@altmannyarden Reviewed the yaml files and made changes throughout.

**Comment by altmannyarden** [comment]
Will create a new branch

**Comment by altmannyarden** [comment]
opened a new branch

**Pull request closed without merging**
