### PR TITLE
Cortex Data Lake: rename brand

### PR DESCRIPTION
**Pull request by ilappe**
## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8922

## Description
rename the band from `Cortex Data Lake` to `Strata Logging Service`

based on rename of [Microsoft Defender ATP - rename to Endpoint](https://github.com/demisto/content/pull/10472) 
the only changes are:
- rename the pack name in pack_metadata
- change the display and description of the integration 
- update the readme

### CODE REVIEW

**Review by DeanArbel — APPROVED** [review]

**Comment by DeanArbel** [comment]
@ShirleyDenkberg Any other changes required for the rebranding?

**Comment by ShirleyDenkberg** [comment]
@DeanArbel 
The name and ID will still be Cortex Data Lake?
And what about all these readmes?

- https://xsoar.pan.dev/docs/reference/playbooks/pan-os-to-cortex-data-lake-monitoring---cron-job
- https://xsoar.pan.dev/docs/reference/playbooks/pan-os-logging-to-cortex-data-lake---action-required
- https://xsoar.pan.dev/docs/reference/playbooks/cortex-data-lake---traffic-indicators-hunting
- https://xsoar.pan.dev/docs/reference/playbooks/cortex-data-lake---indicators-hunting
- https://xsoar.pan.dev/docs/reference/playbooks/cortex-data-lake---file-indicators-hunting
- https://xsoar.pan.dev/docs/reference/articles/PaloAltoNetworks_Integrations#cortex-data-lake

**Comment by ilappe** [comment]
@ShirleyDenkberg 
the rebrand should be only for the UI

so the ids will remain as is
the names - we investigating the impact of change the names

i work to update also the mentioned readme files
thanks!

**Comment by ShirleyDenkberg** [comment]
But just remember that it is not supposed to go live until Jan 12

Regards,


Shirley Denkberg |  Senior Technical Writer

Palo Alto Networks  |  Yigal Alon 94  |  Tel Aviv  |  Israel

Mobile: +972 584323365  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>

**Comment by ilappe** [comment]
waiting for https://github.com/demisto/dockerfiles/pull/23498 to be merged

**Pull request merged**
