### PR TITLE
update py dependencies

### PR DESCRIPTION
**Pull request by glicht**
ter the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Update dependencies as we had a few not in sync. Also removed installing builid-dependencies for py2.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by yaakovi — APPROVED** [review]

**Comment by yaakovi** [comment]
@glicht looks like the new demisto-py version broke the build
should we update the `test_integration.py` script or is that a bug in demisto-py?

**Comment by glicht** [comment]
> @glicht looks like the new demisto-py version broke the build
> should we update the `test_integration.py` script or is that a bug in demisto-py?

It looks like a bug in demisto-py.  Will check.

**Comment by glicht** [comment]
@yaakovi please review the changes to test_integration.py. I did some changes to support latest demisto-py.

**Review by yaakovi — APPROVED** [review]
looks good

**Pull request merged**
