### PR TITLE
CrowdStrike Falcon Streaming v2 - improve handling for no resources were discovered

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

fixes https://github.com/demisto/etc/issues/29952

## Description
improved handling of exception raised in stream discovery in which no resource events were returned (probably because there is already a client connected to the stream with the same app id):
```
failed because of stderr output: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<EventStream._discover_refresh_stream() done, defined at <string>:4344> exception=ValueError("Did not get event stream resources - {'resources': [], 'meta': {'query_time': 0.001456147, 'powered_by': 'FalconHose', 'trace_id': 'a8126116-d281-41e6-a760-3c42365a499e'}}")>
Traceback (most recent call last):
  File "<string>", line 4370, in _discover_refresh_stream
ValueError: Did not get event stream resources - {'resources': [], 'meta': {'query_time': 0.001456147, 'powered_by': 'FalconHose', 'trace_id': 'a8126116-d281-41e6-a760-3c42365a499e'}}
```

added a timeout for the discovery event of 10 seconds with sleep and retry, in addition to updating the integration module health with the error

## Does it break backward compatibility?
   - [x] No

### CODE REVIEW

**Review by glicht — APPROVED** [review]

**Comment by kirbles19** [comment]
@Itay4 Done.

**Comment by Itay4** [comment]
@glicht see my last commit - i've added validation for legal app id

**Comment by Itay4** [comment]
@glicht see my last commit 
added handling for stream refresh failure

**Comment by Itay4** [comment]
@glicht @anara123 please see my last commit - added handling for 401 and 429 status codes in stream discovery/refresh

**Pull request merged**
