### PR TITLE
Securonix fetch bug - incident_status not taken into account

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
- [x] In Progress - customer validation

## Related Issues
fixes: https://github.com/demisto/etc/issues/23641
~~fixes: https://github.com/demisto/etc/issues/23642~~

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
can we add unit test for this?

**Comment by bakatzir** [comment]
I'll try soon. i'm validating with the customer first as our instance is lacking.

**Comment by bakatzir** [comment]
@Itay4 no way to test, as this is an open issue on the vendor side. add a limitation in the readme.
@kirbles19 can you have a look?
https://github.com/demisto/content/blob/8e4cdd0803be9905664fcbaa45ead41c46b5feb1/Packs/Securonix/Integrations/Securonix/README.md

**Comment by amshamah419** [comment]
Looks good

**Pull request merged**
