### PR TITLE
Anomali enhancements

### PR DESCRIPTION
**Pull request by anara123**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/18216

## Description
We got this code as a contribution from a customer. I changed it a bit to fit to our standards

  - Added command ***threatstream-approve-import***
  - The ***threatstream-import-indicator-with-approval*** command now receives two new arguments ***tags*** ***trustedcircles***
  - The ***threatstream-create-model*** command now receives two new arguments ***import_sessions*** ***circles***
  - The ***threatstream-update-model*** command now receives two new arguments ***import_sessions*** ***circles***

## Minimum version of Demisto
- [x] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by anara123** [comment]
@IkaDemisto the only thing that is need to be changed here is that the customer implemented threatstream-approve-import not as Generic Polling command but via sleep.

**Comment by Itay4** [comment]
@IkaDemisto are you reviewing this?

**Comment by IkaDemisto** [comment]
@Itay4 as far as I understand it requires more than just review. 
@anara123 do we want to change the implementation of `threatstream-approve-import` command to work using polling? How can we test it? Currently we don't have instance...

**Comment by Itay4** [comment]
Closing this due to changes done in `master` branch.
Please reopen in a new branch.

**Pull request closed without merging**
