### PR TITLE
Update process email + phishing layout

### PR DESCRIPTION
**Pull request by JonathanMeler**
* And `HTML Rendered Image` MD field to phishing layout
* Add Base64 output to the `rasterize-email` command
* Update rasterized image to the Phishing summary page

TODO:
* Remove the HTML field mapping in the relevant integrations

Fixes: https://github.com/demisto/etc/issues/12327

### CODE REVIEW

**Comment by aviadl** [comment]
I tend to agree

**Comment by JonathanMeler** [comment]
The base64 is truncated in the context when opened, so the browser won't get stuck when viewed by user. Also the Image created is around 10k in size, so I don't think it will burden the BE.

How can I had the tag filtering field? I'll give it a chance

@liorkol @trorabaugh what do you guys think?

**Comment by JonathanMeler** [comment]
I meant how can I show those specific entries in the Summary page?

**Comment by slavikm** [comment]
You can add to the layout `Incident Timeline` with filter on the tag - not sure if you can specify any filter but I think you can.

**Pull request merged**
