### PR TITLE
[tufin-3] Playbooks added

### PR DESCRIPTION
**Pull request by jtmoran**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added playbooks for Tufin pack

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [x] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [x] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by prasenshelar** [comment]
@jtmoran and @idovandijk had a meeting last week. John to make the necessary edits here.

**Comment by fvigo** [comment]
@ronykoz @yuvalbenshalom @idovandijk if this is all good please let's make sure it gets merged in the upcoming release!

Thanks!

**Comment by idovandijk** [comment]
I renamed the playbooks and changed spaces with underscores (in the **FILENAMES**, not the actual playbook name). For some reason I can't edit the names of the PNG files. Can you please rename them the same way?

**Comment by fvigo** [comment]
@idovandijk done , added the new images with proper names and put the right pointers in the README. Please check if everything looks good. Thanks!

**Comment by idovandijk** [comment]
Please update branch with content master 
@yuvalbenshalom need to update base branch as well

**Comment by Itay4** [comment]
@idovandijk whats the status here?

**Pull request merged**
