### PR TITLE
[ASM] EXPANDR-8305: SO Bug fix

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/EXPANDR-8305

## Description
Fixed small issue with SO not getting set all the time

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@BigEasyJ , please review

**Review by BigEasyJ — APPROVED** [review]
Look Good.

**Comment by johnnywilkes** [comment]
@merit-maita , this has been approved by Xpanse.  Please merge when possible.

**Comment by johnnywilkes** [comment]
@merit-maita , i believe the validation error is an issue with the build, right?

**Comment by merit-maita** [comment]
> @merit-maita , i believe the validation error is an issue with the build, right?

yes correct, i will look into it.

**Comment by merit-maita** [comment]
@johnnywilkes can you please make sure to fill the contribution form, and for the validation erorr, pull from master and push again to trigger it again

**Comment by johnnywilkes** [comment]
> @johnnywilkes for the validation error, please pull from master and push again to trigger it again

@merit-maita , done

**Review by merit-maita — APPROVED** [review]

**Pull request merged**
