### PR TITLE
Recorded future identity 1.1

### PR DESCRIPTION
**Pull request by rderkachrf**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added new command !recordedfuture-password-lookup that lets you check the password with the Recorded Future Identity Dataset.
The main logic is moved to Recorded Future API to make this client lightweight.
Added additional playbooks to work with the Recorded Future Identity Dataset.

## Screenshots
Password lookup
image

New playbooks
Identity Found Playbook Incident playbook
image

Lookup Identities
image

Subplaybook for Lookup Identities
image

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by efelmandar — COMMENTED** [review]
@rderkachrf Thank you for submitting this PR! I think it looks great overall, however, I would like to suggest a few changes: 

#### Identity - Identity Found (incident) - playbook
I suggest adding a playbook input for auto IR to allow users to configure the playbook to run automated IR, with the default value being `AutomatedIR = False`. Additionally, I suggest adding a `Description` field to the playbook inputs, as well as a check to see if the AD integration is configured and enabled, using the `IsIntegrationEnabled` automation/conditional task.

Please add some descriptions for playbooks and playbook inputs in the other playbook as well as it makes your content easier to use for the users.

**Comment by rderkachrf** [comment]
@efelmandar Thanks for reviewing. We will fix this and update the request.

**Comment by rderkachrf** [comment]
@efelmandar we updated the playbooks according to your comment.

Regarding

> Identity - Identity Found (incident) - playbook
> I suggest adding a playbook input for auto IR to allow users to configure the playbook to run automated IR, with the default value being AutomatedIR = False.

We would like not to do this change because disabling accounts and resetting passwords (We believe) should always be approved by an analyst before the specific actions take place

**Review by efelmandar — APPROVED** [review]
I reviewed the changes, Great work!

**Comment by daryakoval** [comment]
Hi, 
We have holidays until 9.4, therefore the review process may be delayed. 
Thanks for understanding.

**Comment by daryakoval** [comment]
Hi @rderkachrf, please fix the test: `test_call_return_error`.

**Comment by daryakoval** [comment]
Please handle 2 validations errors: 
- [ERROR]: /home/circleci/project/Packs/IdentityRecordedFuture/IncidentTypes/incidenttype-customIncidentTypes-identity.json: [GR100] - Content item 'Recorded Future Identity' can be used in the 'marketplacev2, xpanse, xsoar' marketplaces, however it uses content items: 'Recorded Future Identity - Identity Found (incident)' which are not supported in all of the marketplaces of 'Recorded Future Identity'.
- Validating Packs/IdentityRecordedFuture/ReleaseNotes/1_1_0.md as releasenotes
[ERROR]: Packs/IdentityRecordedFuture/ReleaseNotes/1_1_0.md: [RN111] - The 1_1_0.md release notes file contains incompatible Docker images:
- Recorded Future Identity: Release notes file has dockerimage: demisto/python3:3.10.10.51930 but the YML file has dockerimage: demisto/python3:3.10.10.52956
To fix this please run: 'demisto-sdk update-release-notes -i Packs/IdentityRecordedFuture'

**Comment by daryakoval** [comment]
Please rename the files not to use `(` `)`, and fix the readme files to use the new filenames as well : 

- Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Create_Incident_(sub).png

- Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Identity_Found_(incident).png

- Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Lookup_Identities_(parent).png

**Comment by rderkachrf** [comment]
Hi @daryakoval. All the things should be fixed but it looks like some of the checks have not run.

**Review by daryakoval — APPROVED** [review]

**Pull request merged**
