### PR TITLE
LogPoint

### PR DESCRIPTION
**Pull request by Hruuttila**
## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/7612

## Description
LogPoint Integration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [x ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by Hruuttila** [comment]
@yuvalbenshalom Great! I will start working on these changes.

**Comment by Hruuttila** [comment]
@yuvalbenshalom Hi, I fixed the things you requested. Did not have time to work on the playbooks. I pushed the content.

**Comment by mchasepan** [comment]
I'm working with the Partner who will take this on, hopefully augment a little, and then get thru review. Suggest closing this PR and they will submit another shortly. They will also assume support of the pack.

**Comment by Hruuttila** [comment]
@mchasepan awesome. Will close this.

**Pull request closed without merging**
