### PR TITLE
Trend micro vision one

### PR DESCRIPTION
**Pull request by shaqnawe**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Update to pytmv1 0.8.7 and added OAT action.

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [X] Tests
- [X] Documentation

### CODE REVIEW

**Comment by thefrieddan1** [comment]
@shaqnawe please make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**Comment by shaqnawe** [comment]
@thefrieddan1 The documentation and yml file will have to be updated to include the new pytmv1 image based on the PR here https://github.com/demisto/dockerfiles/pull/29688.

**Comment by thefrieddan1** [comment]
@shaqnawe lets please schedule a demo.

**Comment by shaqnawe** [comment]
> @shaqnawe lets please schedule a demo.

Can you send me a link to schedule a demo. Additionally, I'm waiting for updated docker image with pytmv1:0.8.7 package to test action. Please advise.

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
