### PR TITLE
Limit query time range for better index usage - Find similar incidents search v2

### PR DESCRIPTION
**Pull request by meirwah**
## Status
In Progress

## Description
for better memory usage of incident search

## Does it break backward compatibility?
   - No

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by erezh31** [comment]
@roysagi can you review the RN please?

**Comment by meirwah** [comment]
@roysagi can you review this?

**Comment by meirwah** [comment]
@erezh31 plz fix build as `Playbook dedup_-_generic_-` fails here

**Comment by erezh31** [comment]
@kirbles19 @roysagi plz approve

**Comment by erezh31** [comment]
@meirwah playbook fails on other task in the playbook, I don't think it's related to the change. I will try to fix it anyway

**Comment by kirbles19** [comment]
@meirwah Done.

**Comment by erezh31** [comment]
@meirwah seems like the playbook is failing because of https://github.com/demisto/etc/issues/21350
we can merge this PR

**Pull request merged**
