### PR TITLE
AzureDevOps add auth code flow

### PR DESCRIPTION
**Pull request by ostolero**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3688)

## Description
Support user auth flow for AzureDevOps integration.
In this opportunity removed the beta flag, and require a re-do of README.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ostolero** [comment]
Test playbook is failing due to an expired token. @yucohen will update the token in the next few days :)

**Comment by ostolero** [comment]
Hi @ShirleyDenkberg can you please re-do the pack README?
requested [here](https://jira-hq.paloaltonetworks.local/browse/CIAC-3688) by @bakatzir

**Review by JudahSchwartz — APPROVED** [review]

**Review by yucohen — APPROVED** [review]
Great!

**Comment by ostolero** [comment]
force merge is required as we added a new param `auth_type` with `required: true`, which fails validation but should be presented in this way.
Default is assigned in yml and in the code for bc.

**Pull request merged**
