### PR TITLE
Added IgnoreFields Pack

### PR DESCRIPTION
**Pull request by anilagr**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A transformer to remove selected fields from the JSON object.

## Screenshots
Screenshot 2022-09-12 at 2 14 41 PM

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by JasBeilin** [comment]
Hi @anilagr, thank you for this contribution! It is so helpful, in fact, that we want to make it xsoar supported. This means that in the next few days we will change some of it and enter it to an existing script's pack.
We will appreciate your help in doing so.

**Comment by anilagr** [comment]
Thank you! Happy to help.

**Comment by JasBeilin** [comment]
@anilagr, I have added to this PR a version of your script (in the XSOAR's CommonScripts pack) which includes ability to parse json if it comes from cli or pass a list in addition to comma-separated string.

Could you please try and use it, and make sure it still answers your original needs?
Once you will, I will delete your pack from this PR and move forward with the merge.

**Comment by anilagr** [comment]
This works and is much better 👍🏼

**Comment by ShirleyDenkberg** [comment]
@JasBeilin Doc review completed.

**Review by JasBeilin — APPROVED** [review]

**Pull request merged**
