### PR TITLE
ThreatConnect v1/v2 (Deprecated) - Deprecated. Use the ThreatConnect …

### PR DESCRIPTION
**Pull request by bakatzir**
…v3 integration instead.

## Status
- [x] Ready

relates to: https://jira-hq.paloaltonetworks.local/browse/CIAC-2355

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4841

### CODE REVIEW

**Review by JudahSchwartz — APPROVED** [review]

**Comment by bakatzir** [comment]
@JudahSchwartz due to 
```
[ERROR]: Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml: [IN140] - The integration ThreatConnect v2 is currently in skipped. Please add working tests and unskip. Skip comment: unstable instance
```
this will require a forcemerge, no need to unskip a deprecated integration.

**Review by gal-forer — APPROVED** [review]

**Comment by JudahSchwartz** [comment]
@ostolero notice the above ^. Requiring unskip on a deprecated integration.

**Comment by ShahafBenYakir** [comment]
@JudahSchwartz I see failure in build, please check this might be related to deprecation.

**Comment by ostolero** [comment]
Noted, will open a ticket to avoid test validation for deprecated integration

**Review by anara123 — APPROVED** [review]

**Pull request merged**
