### PR TITLE
ExtraHop release v2.1.0

### PR DESCRIPTION
**Pull request by crestdatasystems**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Added **sec.attack** as the default category if not provided.
- Added support for categories in the *detections list command* for the filter argument and in the *Integration Configuration* for the advanced filter parameter.
- Updated minimum required ExtraHop firmware version to 9.3.0 from 9.1.2.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by thefrieddan1** [comment]
Hi @crestdatasystems in order for me to start reviewing your PR, 
Please be sure to fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

Thanks

**Comment by crestdatasystems** [comment]
Hey, I just filled out the form.

**Comment by thefrieddan1** [comment]
Hi @crestdatasystems  thank you for your contribution we appreciate your effort, I reviewed the content in the PR and would like to schedule a demo.

**Comment by crestdatasystems** [comment]
@thefrieddan1 We are based out of IST. Please share few slots out of your availability to schedule a call.

**Comment by thefrieddan1** [comment]
Hi @crestdatasystems 

I am available today June 6th from 4:00 PM IST to 6:00 PM IST
And tomorrow June 7th from 4:00 PM to 5:30 IST 

Thanks

**Comment by crestdatasystems** [comment]
Okay sending you the invitation for tomorrow.

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
