### PR TITLE
Added additional details the the content pack's README.md as requested.

### PR DESCRIPTION
**Pull request by rhallick**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
Hi @rhallick 
I see you already have an open pull request with these changes https://github.com/demisto/content/pull/12549
Should we close this one?

**Comment by rhallick** [comment]
@Itay4 - Fine to close duplicate pull request.  Thank you.

**Comment by rhallick** [comment]
@Itay4 - how do I get additional changes that I've pushed into the original pull request?  Thank you.

**Comment by Itay4** [comment]
@rhallick not sure i understand the question, can you clarify what you're after please?

**Comment by rhallick** [comment]
So @mchasepan requested that I make some additional changes to the content pack's README.md file.  I made those and pushed the changes.  How does the original pull request now get updated to include the commit with those changes?

**Comment by Itay4** [comment]
the README files in both pull requests are identical, what changes are you referring to?

**Comment by rhallick** [comment]
The changes that are now in https://github.com/rhallick/content/blob/master/Packs/FeedIntel471/README.md

**Comment by Itay4** [comment]
will be handled in https://github.com/demisto/content/pull/12549

**Comment by rhallick** [comment]
OK, so do I need to do anything else at the moment in order to progress #12549?

**Comment by Itay4** [comment]
it will be soon reviewed, better to keep track there than here

**Pull request closed without merging**
