### PR TITLE
Email Enrichment v2.1 - filter empty domains

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/18288

## Description
#17390 will fix only from 5.0. fixing the pb as well.

## Required version of Demisto
4.1.0

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - no change
- [ ] Code Review

### CODE REVIEW

**Comment by yuvalbenshalom** [comment]
@bakatzir please do test that re create the problem and show that it is fixed. even manual.

**Comment by bakatzir** [comment]
@yuvalbenshalom  looks good.
Screen Shot 2019-08-05 at 10 26 09
Screen Shot 2019-08-05 at 10 26 19

**Comment by bakatzir** [comment]
@yuvalbenshalom prior to fix it went to the else path:
Screen Shot 2019-08-05 at 11 00 58

**Comment by idovandijk** [comment]
Can you please provide server for review / show me on your local instance that it solves the bug?
I have 2 concerns:
1. I am not sure whether "Is Not Empty" operator can check all elements of `inputs.Domain`, I think it checks if the object itself is not empty and not whether its children all have data.
However, if I am wrong, and it does work as intended, then the filter should be added to the `playbook inputs` **as well as the** `Is there a domain list input?` task

**Comment by bakatzir** [comment]
Set down with @idovandijk  and changed accordingly, adding more filters to playbook input as well

**Pull request merged**
