### PR TITLE
[CSPi184] Aria packet intelligence update with latest REST API

### PR DESCRIPTION
**Pull request by stang-aria**
## XSOAR [CSPi184] Aria packet intelligence update with latest REST API
In case you are a technological partner:
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This update using the latest REST API of ARIA PacketIntelligence. Update the existing Integration ARIAPacketIntelligence.
Use RCS arguments to select different SIA.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details: minimum SDS version 1.0.9
   - [] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by guyfreund** [comment]
This PR is waiting for a TPA (To be reviewed after a notify has received from @mchasepan)

**Comment by stang-aria** [comment]
@guyfreund I have questions on the erros at ci/circleci:Run Validations. I don't understand what's the error means and how can I fix for it? Pass other checks and wait for your documentation review. Thanks

**Comment by orlichter1** [comment]
@stang-aria Hi, The issue you've experienced in the ` ci/circleci:Run Validations` step was caused by a parsing error of the README.md file. It thought that `<>` is a part of some HTML code so I added escape characters in order to remedy that.
From my understanding, we are [still waiting for a TPA ](https://github.com/demisto/content/pull/9110#issuecomment-700781472). Once that process is done we can review the code

**Comment by stang-aria** [comment]
> @stang-aria Hi, The issue you've experienced in the ` ci/circleci:Run Validations` step was caused by a parsing error of the README.md file. It thought that `<>` is a part of some HTML code so I added escape characters in order to remedy that.
> From my understanding, we are [still waiting for a TPA ](https://github.com/demisto/content/pull/9110#issuecomment-700781472). Once that process is done we can review the code

**Comment by stang-aria** [comment]
> @stang-aria Hi, The issue you've experienced in the ` ci/circleci:Run Validations` step was caused by a parsing error of the README.md file. It thought that `<>` is a part of some HTML code so I added escape characters in order to remedy that.
> From my understanding, we are [still waiting for a TPA ](https://github.com/demisto/content/pull/9110#issuecomment-700781472). Once that process is done we can review the code

Thanks @orlichter1, It passed the validation now

**Comment by orlichter1** [comment]
PR will be reopened once CSPi184 will sign a TPA.

**Pull request closed without merging**
