### PR TITLE
Fix process email generic email attachment logic

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/15277
fixes: https://github.com/demisto/etc/issues/15743

## Description
Fixes DT logic for detecting attached email files

Test playbook has been expanded to check multiple email types and also false positive case.

## Screenshots
image

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - No

## Must have
- [x] Test
- [x] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [x] Phishing Playbooks

### CODE REVIEW

**Comment by idovandijk** [comment]
Guy, do you have a spot instance or something where I can login and test this?

**Comment by glicht** [comment]
@idovandijk No I don't. You can download the content zip from the circle build.

**Comment by idovandijk** [comment]
Looks good. I also threw in some doc/x files of my own (in addition to your test) and it ignores them as expected.

My only question is - is the following Email.From output, expected behavior?
image

**Comment by glicht** [comment]
@idovandijk the email from display is a bug not related to this fix. will file.

**Pull request merged**
