### PR TITLE
[ASM] EXPANDR-3750 - Serviceownership enrichment hotfix

### PR DESCRIPTION
**Pull request by capanw**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3750. Fixing the service ownership playbook missing issue.

## Description
Fixing the service ownership playbook missing issue.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Review by capanw — COMMENTED** [review]
LGTM

**Review by BigEasyJ — APPROVED** [review]
Fixes #25927

Noting that `demisto-sdk format` changed: 
- `script` changed to `scriptName`
- `playbookId` to `playbookName`

Note: Please refer to our [Pull Request Guidelines for XSOAR Contribution and Xpanse Remediation teams](https://confluence.paloaltonetworks.local/display/XPANSE/Pull+Request+Guidelines+for+XSOAR+Contribution+and+Xpanse+Remediation+teams) for merging PRs only related to Packs/CortexAttackSurfaceManagement.

Please merge as soon as possible.

**Comment by BigEasyJ** [comment]
@merit-maita 
Please merge as soon as possible.

**Comment by BigEasyJ** [comment]
@merit-maita also please refer to our Pull Request Guidelines for XSOAR Contribution and Xpanse Remediation teams for merging PRs only related to Packs/CortexAttackSurfaceManagement.

**Review by merit-maita — APPROVED** [review]

**Pull request merged**
