### PR TITLE
MISP: Add new parameter to define benign tag ids

### PR DESCRIPTION
**Pull request by nikstuckenbrock**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added a new parameter to the MISP integration to define tags that should be recognized as benign.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by israelpoli — COMMENTED** [review]
Thank you for your contribution, It looks great 💪 

I see that the unit tests are failing due to an argument mismatch in the `test_get_score` function could you please fix that?

Additionally, if you could update the `Docker` as well.

thanks 🙏

**Comment by nikstuckenbrock** [comment]
There seems to a problem with the mock object for the pymisp package. I'll try to fix it.

**Comment by nikstuckenbrock** [comment]
Hi @israelpoli,

fixed it. Feel free to recheck if you've got time.

**Comment by israelpoli** [comment]
Hi @nikstuckenbrock 
I’m a bit delayed with the review due to a workload
I hope to go over it again later today
I apologize for the delay
Thank you

**Review by israelpoli — APPROVED** [review]
Good job 💪 
I am taking it to the next level hoping to merge to master soon

Thank you

**Pull request merged**
