### PR TITLE
Oletools phishing

### PR DESCRIPTION
**Pull request by tomer-pan**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4301

## Description
- Adding oletools to "Extract Indicators From Files - Generic v2" playbook
- Adding the macro source code to the phishing layout

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by tomer-pan** [comment]
@jrosenpanw Can someone please go over these files?
- The "description" key of this file: `Packs/CommonTypes/IncidentFields/incidentfield-Macro_Source_Code.json`.
- The "description" on line 689 in this file: `Packs/CommonTypes/IncidentFields/incidentfield-Macro_Source_Code.json`.
- RN files.

**Review by idovandijk — COMMENTED** [review]
Looks good, let's go over together next week and decide if we want a new version from 6.5 or to just edit the existing version

**Comment by ShirleyDenkberg** [comment]
@michalgold @idovandijk Doc review completed.

**Review by idovandijk — APPROVED** [review]
nice one prince

**Pull request merged**
