### PR TITLE
OpenLDAP - Added readme file

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
Ready

## Description
Added OpenLDAP readme file.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [x] Documentation (with link to it)
- [x] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [x] TestCommonPython
- [x] DocumentationTest

## Technical writer review
Mention and link to the files that require a technical writer review.
- [x] [README](https://github.com/demisto/content/blob/2e4ed1a508fc3c4199e98eb02e38aab7733b7997/Beta_Integrations/OpenLDAP/README.md)

### CODE REVIEW

**Comment by kirbles19** [comment]
https://support.demisto.com/hc/en-us/articles/360041363893

**Comment by IkaDemisto** [comment]
@ElazarK did you update the readme file https://github.com/demisto/content/blob/291c2d23e5e203f5bd4a319905e26c760fcbebe4/Beta_Integrations/OpenLDAP/README.md also?

**Comment by IkaDemisto** [comment]
Any update here?

**Comment by Itay4** [comment]
@IkaDemisto lets merge this

**Pull request merged**
