### PR TITLE
Test fetch incidents from test_module command - SplunkPy

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/20597

## Does it break backward compatibility?
   - [ ] No

## Must have
- [ ] Tests

### CODE REVIEW

**Comment by Shellyber** [comment]
@kirbles19 Please review the CHANGELOG file

**Comment by ShahafBenYakir** [comment]
@Shellyber Let me know when this is ready for CR

**Comment by Shellyber** [comment]
Ready

On Fri, 24 Jan 2020 at 22:49 Shahaf Ben Yakir <notifications@github.com>
wrote:

> @Shellyber
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Shellyber&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=qVFauV5Znio35RXTvoaxJAqZNAGn-RFNF0elNKU0Aow&m=_y78qAfgRr3MJn2RwO59AJ2xsmWxw7urQlp6-elu0gw&s=bwwSWxCbRiGtvytluQrJ2AgIO4nSEEFL_5-QwgQ44f4&e=>
> Let me know when this is ready for CR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_5525-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAK6J23U2SK23R2X6DJN3ZULQ7NH5HA5CNFSM4KKUAPO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ4BRAY-23issuecomment-2D578295939&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=qVFauV5Znio35RXTvoaxJAqZNAGn-RFNF0elNKU0Aow&m=_y78qAfgRr3MJn2RwO59AJ2xsmWxw7urQlp6-elu0gw&s=5kU8jHc0sUZ1GwbTjDdcwxSiCNt3tVu0d5zdcOOKaJ4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AK6J23V6CWDVOCRKIRAKVITQ7NH5HANCNFSM4KKUAPOQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=qVFauV5Znio35RXTvoaxJAqZNAGn-RFNF0elNKU0Aow&m=_y78qAfgRr3MJn2RwO59AJ2xsmWxw7urQlp6-elu0gw&s=ThaJm284fEVpsuC7n6FGFjtB38Ga0vt8l6P3srirytg&e=>
> .
>
-- 

*Shelly Berman*

Software Engineer, Content Team, Demisto

Email: sberman@paloaltonetworks.com

**Comment by kirbles19** [comment]
@Shellyber Done

**Pull request merged**
