### PR TITLE
VT playbook move 2

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
In the bug https://github.com/demisto/etc/issues/22197 a playbook was saved in playbooks with a spelling mistake. Also the description was wrong.

[YML](https://github.com/demisto/content/edit/moving_vt_playbook2/Playbooks/playbook-Detonate_File-VirusTotal.yml?pr=%2Fdemisto%2Fcontent%2Fpull%2F6229)

### CODE REVIEW

**Comment by orlichter1** [comment]
@kirbles19 could you please go over the [yml](https://github.com/demisto/content/edit/moving_vt_playbook2/Playbooks/playbook-Detonate_File-VirusTotal.yml?pr=%2Fdemisto%2Fcontent%2Fpull%2F6229)? I've copied the description from other detonate playbooks.

**Comment by kirbles19** [comment]
@yaron-libman

**Comment by yaron-libman** [comment]
Reviewed the yaml file.

**Comment by yaakovi** [comment]
@orlichter1  pull from master
if the only failure is `validate` on the id issue - we can force merge it.

**Comment by orlichter1** [comment]
@yaakovi Can we force merge this? This is the only error:
image

**Comment by yaakovi** [comment]
@orlichter1 make sure master build passes (or at least error only on this error as well)

**Comment by orlichter1** [comment]
@yaakovi  
image

**Comment by orlichter1** [comment]
@yaakovi How do I run master after merge?

**Comment by orlichter1** [comment]
Checking here https://github.com/demisto/content/pull/6513

**Comment by orlichter1** [comment]
@yaakovi All good :) Green build

**Pull request merged**
