### PR TITLE
[PAN-OS] fixed contextPath

### PR DESCRIPTION
**Pull request by michal-dagan**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6322)

## Description
- Fixed an issue where the wrong context path was declared in the following commands: **pan-os-create-address**, **pan-os-create-address-group**, **pan-os-list-address-groups**.
from 'Panorama.Addresses.Tag' to 'Panorama.Addresses.Tags'
and from 'Panorama.AddressGroups.Tag' to 'Panorama.AddressGroups.Tags' according to the code.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by bziser — COMMENTED** [review]
Nice
Did you check if there are playbboks/test playbooks that based on these outputs?

**Comment by michal-dagan** [comment]
> Nice Did you check if there are playbboks/test playbooks that based on these outputs?

Yes, it appears that there are no playbooks/test playbooks based on this output.

**Comment by GuyAfik** [comment]
@bziser @michal-dagan doesn't it break BC? will this require a force-merge?

**Comment by michal-dagan** [comment]
> @bziser @michal-dagan doesn't it break BC? will this require a force-merge?
@DeanArbel yes, it requires a force-merge

**Review by bziser — APPROVED** [review]

**Pull request merged**
