### PR TITLE
SplunkPy - correct the usage of fields for hec submit event command

### PR DESCRIPTION
**Pull request by ag3ntsc4rn**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
For Splunk HEC submissions using the submit-event-hec command, fields param used to take in a comma separated string. So when you used the command, in splunk a field by the name "fields" will be created and its value will be the comma separated string. This is not the recommended usage of fields according to Splunk. Fields should actually be a JSON key value pair where you can create new fields (with the name provided in the param and not hardcoded 'fields') and values in Splunk. This PR addresses that issue.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ X] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by guykeller** [comment]
@ag3ntsc4rn 
This seems to me like a backwards compatibility break, and quite a major one since this is a mandatory argument, unless you are actually asking the user for the same syntax - in which case I don't understand the change.

Are you 100% sure the current syntax does not work?

@Shellyber Any input on this? since you wrote the command and this is a major change, thought you should be aware

**Comment by ag3ntsc4rn** [comment]
@guykeller - So the current syntax works. It just does not work the way it is intended to by Splunk. In current syntax, when the logs are sent to Splunk, it creates one field called 'fields' with one or more comma separated values.

What I am suggesting is actually what Splunk recommends. You should pass a json payload to fields argument. The keys in the payload will be the fields in Splunk. Example.
`{"mykey":"myvalue"}`. This will create a field called mykey with a value of myvalue in Splunk and you can search in Splunk using.
`index=foo sourcetype=bar mykey::myvalue` (If mykey is not an indexed extraction)
`index=foo sourcetype=bar mykey=myvalue` (If mykey is an indexed field)

Having said that, I agree this is a big change for users who are not aware of this usage of fields. and code will break in json.fields. Maybe a json parse can be added to the logic. That way, if you send a valid json string, we can use the logic described here, if not a valid json, well continue with what we have. Open to suggestions.

**Comment by guykeller** [comment]
@ag3ntsc4rn 
Thank you for the detailed explanation!
I agree with you - this is quite a big change.
Let's do it as you suggested - if the string isn't a valid json, use the old way. Otherwise, use your suggested way.

**Comment by guykeller** [comment]
@ag3ntsc4rn 
Your current problem is that you don't have any release notes for the change you have introduced here. Let's add those and merge the change

**Comment by ag3ntsc4rn** [comment]
Updated code as discussed via commit `ec6fbfe`
Not sure about how and where to update release notes. Need some guidance as this is my first ever contribution.

**Comment by guykeller** [comment]
@ag3ntsc4rn 
Let's schedule a call so I would help you through it.
Please let me know which platform would you like to schedule on, Slack or email.

**Comment by guykeller** [comment]
@ag3ntsc4rn Regarding the call I suggested - would love to schedule it.
Which platform would suit you best for scheduling it?

**Comment by ag3ntsc4rn** [comment]
Same here. Submitted RN but CLA is unhappy.

**Comment by anara123** [comment]
@ag3ntsc4rn who is `Manish Menon`?
 it seems that you signed

**Comment by ag3ntsc4rn** [comment]
That’s my name actually. Ugh. I might have some time in the past switched to hiding my email for privacy reasons.

**Comment by anara123** [comment]
@ag3ntsc4rn then you are good to go. You can ignore the CLA warning. It seems that you signed it

**Comment by guykeller** [comment]
@ag3ntsc4rn 
As Anar said, we can ignore the CLA but it seems you still have some flake8 errors.
I re-ran your build but they seem straight forward enough to be fixed easily - would you like my help with that?

**Comment by ag3ntsc4rn** [comment]
@guykeller - I may not be able to get to it over the weekend. If you have time, I don't mind you fixing it for me.

**Comment by guykeller** [comment]
@ronykoz Could we do what we discussed here as well please?

**Pull request merged**
