### PR TITLE
19.10.3 - clear release notes

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

### CODE REVIEW

**Comment by yardensade** [comment]
No need to clear RN in this case, it will ignore the content that was
released between 10.2 & 10.3 even tho it was not released. Just need to
merge the urlacan changelog.

**Comment by yardensade** [comment]
can close this or change just "Integrations/UrlScan/URLScan_CHANGELOG.md"

**Comment by yaakovi** [comment]
updated url scan change log in another PR

**Comment by yardensade** [comment]
Because he's the hero Gotham deserves, but not the one it needs right now. So we'll hunt him. Because he can take it. Because he's not our hero. He's a silent guardian. A watchful protector. A Dark Knight.

**Pull request closed without merging**
