### PR TITLE
ExtractDomainFromUrlFormat fix

### PR DESCRIPTION
**Pull request by jochman**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/14241
https://demisto.zendesk.com/agent/tickets/3892

## Description
ExtractIndicators couldn't extract domain if they contained `-`.

## Screenshots
Paste here any images that will help the reviewer
image

## Does it break backward compatibility?
   - Shoukdnt

## Must have
- [X] Tests
- [ ] Code Review

### CODE REVIEW

**Comment by anara123** [comment]
@jochman looks good. please check also the same domain if the script can extract from url and not only email

**Comment by jochman** [comment]
> @jochman looks good. please check also the same domain if the script can extract from url and not only email

image

Done.

**Comment by Itay4** [comment]
@jochman whats the status here?

**Comment by glicht** [comment]
This is being also handled at: https://github.com/demisto/content/pull/3182 . 

I think we can close this.

**Comment by yardensade** [comment]
The regex way is not solving the actual need:
support.google.com -> will yield 'support'.
https://github.com/demisto/content/pull/3182 solves this.

**Pull request closed without merging**
