### PR TITLE
Sanitize unmockable

### PR DESCRIPTION
**Pull request by jochman**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Mostly fixes tests and add issues numbers

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Does it break backward compatibility?

   - No

### CODE REVIEW

**Comment by yaakovi** [comment]
@ShahafBenYakir @jochman 
what is the status here? are you planning on continuing the effort?

**Comment by ShahafBenYakir** [comment]
@jochman Received the branch from me he should've merged it eventually.

**Comment by Itay4** [comment]
@jochman @yaakovi @ShahafBenYakir ??

**Comment by Itay4** [comment]
closing pr and keeping branch alive for now in case needed

**Pull request closed without merging**
