### PR TITLE
Change prevname of incidentfield-namefield.json

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22945

### CODE REVIEW

**Comment by Itay4** [comment]
@anara123 @ronykoz please keep me sane here and verify this makes sense and we're not missing anything here

**Comment by Itay4** [comment]
@jochman please access the build demisto instance and make sure both `name` (the system one) and `namefield` exist as expected

**Comment by anara123** [comment]
looks ok. make sure that the error not happens and as @Itay4 mentioned both fields exists

**Comment by jochman** [comment]
before upgrading
image
after upgrading
image

Seems like we're breaking BC with this one. Looking forward for another solution.

**Comment by jochman** [comment]
It looks like now it's fine.
image
The indicator is installed.
image
Nothing contains `VCStore` In the logs.

**Comment by Itay4** [comment]
@jochman any reason to keep the `name` field?

**Comment by jochman** [comment]
> @jochman any reason to keep the `name` field?
Somehow, someone is maybe using it.

**Comment by jochman** [comment]
according to @sagylell all of those keys should not be in the file:
"vcShouldIgnore"
shouldPublish"
"shouldCommit"
"shouldPush"
"commitMessage"
"modified"
"prevName"
"prevDetails"
"prevKind"
"prevTypeId"
"prevType"

deleting all of those and updating.

**Comment by jochman** [comment]
after removing those keys, the indicator is inside demisto
image

logs:
image
nothing found

**Comment by sagylell** [comment]
Haven't tested manually myself, but it should be ok

**Pull request merged**
