### PR TITLE
CSC Pack Adoption

### PR DESCRIPTION
**Pull request by bob-t-csc**
Updating README file for adoption

### CODE REVIEW

**Comment by edik24** [comment]
Hi @bob-t-csc please sign the [CLA](https://github.com/demisto/content/pull/35792#issuecomment-2274018620) and fill the [registration form](https://github.com/demisto/content/pull/35792#issuecomment-2274022860)

**Comment by israelpoli** [comment]
Hi @bob-t-csc 
I see you signed the `cla` but you haven't filled out the `contribution form` yet
please fill that

thanks 🙏

**Comment by bob-t-csc** [comment]
> Hi @bob-t-csc I see you signed the `cla` but you haven't filled out the `contribution form` yet please fill that
> 
> thanks 🙏

Hi @israelpoli 
Our internal security was blocking docs.google.com. I obtained access and am filling out the form now. For 'Type of contribution' should I select 'New pack' or 'Existing pack'?

Thank you!

**Comment by edik24** [comment]
> > Hi @bob-t-csc I see you signed the `cla` but you haven't filled out the `contribution form` yet please fill that
> > thanks 🙏
> 
> Hi @israelpoli Our internal security was blocking docs.google.com. I obtained access and am filling out the form now. For 'Type of contribution' should I select 'New pack' or 'Existing pack'?
> 
> Thank you!

Existing pack

**Comment by bob-t-csc** [comment]
Hi @israelpoli
I completed the registration form. I will look into joining the Slack DFIR community.

Thanks again!

**Review by israelpoli — APPROVED** [review]

**Pull request merged**
