### PR TITLE
Added the Wait And Complete Task By Status playbook

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
Fixes: https://github.com/demisto/etc/issues/44415
Related to: https://github.com/demisto/etc/issues/44049

## Description
Added a playbook that waits until a task reaches a certain state and then completes it if configured to do so.
Also fixed `inc-test-domain-indicator` test which slept for 2 seconds to let indicator be created. Increased to 25 seconds.

## Screenshots
Wait_And_Complete_Task_By_Status

## Minimum version of Cortex XSOAR
6.0.0

## Does it break backward compatibility?
No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by idovandijk** [comment]
Failed due to unrelated test `inc-test-domain-indicator`.
Added a fix

**Comment by ShirleyDenkberg** [comment]
@michalgold Doc review completed.

**Review by David-BMS — COMMENTED** [review]
Probably should moved to dev pack
But makes much more sense to do it in  a script

**Comment by idovandijk** [comment]
@daryakoval is releasing a script instead

**Pull request closed without merging**
