### PR TITLE
Fix opening threads ewsv2

### PR DESCRIPTION
**Pull request by jochman**
# Status
Ready

## Related Issues
related: https://github.com/demisto/etc/issues/20566

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [X] Documentation (with link to it)
- [X] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
@jochman @IkaDemisto lets make sure this makes it to the release

**Comment by IkaDemisto** [comment]
@glicht @Itay4 we don't gain any improvement in `EWS v2` integration with this change in contrast to `EWS Mail Sender`. Thread numbers remains fixed size with/without this change and there is no impact on memory usage inside docker container. However terminating thread pool will have negative effect and will break all integration's commands that use indirectly `EWSPooledMixIn` class (is using protocol.thread_pool also https://github.com/ecederstrand/exchangelib/blob/10fc6d8f73894f11c4f131da2d7d983947fbfac9/exchangelib/services/common.py). 
error
Probably there is a solution to close/terminate thread pool in less aggressive way without breaking other functionality of `exchagelib` but my suggestion is not to merge this changes.

**Comment by jochman** [comment]
> @glicht @Itay4 we don't gain any improvement in `EWS v2` integration with this change in contrast to `EWS Mail Sender`. Thread numbers remains fixed size with/without this change and there is no impact on memory usage inside docker container. However terminating thread pool will have negative effect and will break all integration's commands that use indirectly `EWSPooledMixIn` class (is using protocol.thread_pool also https://github.com/ecederstrand/exchangelib/blob/10fc6d8f73894f11c4f131da2d7d983947fbfac9/exchangelib/services/common.py).
> error
> Probably there is a solution to close/terminate thread pool in less aggressive way without breaking other functionality of `exchagelib` but my suggestion is not to merge this changes.

I think that @IkaDemisto is right, We've already seen that there's a problem with this change and I'm afraid that the change that we did in EWSMailSender is also problematic, but we need to wait for feedback.

**Comment by jochman** [comment]
@IkaDemisto, Shall I merge?

**Pull request merged**
