### PR TITLE
ParseEmailFiles - payload filtering

### PR DESCRIPTION
**Pull request by teizenman**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29476

## Description
There was a need to filter strings out of the payload data before iterating over it.

## Screenshots
Using the two example files from the issue:
Before change:
image

After:
image

### CODE REVIEW

**Comment by ronykoz** [comment]
@teizenman please add a UT for this

**Comment by anara123** [comment]
@teizenman what is the result of the ParseEmailFiles after your fix? It returns just the attached email name?

**Comment by teizenman** [comment]
> @teizenman please add a UT for this

Was waiting to see if I can get one of the files from the issue, and I can, so Im adding it as UT.

**Comment by teizenman** [comment]
> @teizenman what is the result of the ParseEmailFiles after your fix? It returns just the attached email name?

The outcome is the same as before, but for some files, the `get_payload()` function is returning a list of `email.message.Message` objects, and `\n` strings that should be ignored.

**Review by anara123 — APPROVED** [review]

**Pull request merged**
