### PR TITLE
Moving to the new upload flow

### PR DESCRIPTION
**Pull request by guyfreund**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/26708

## Description
At the end of the testing period we are conducting ATM, we will be moving to use the new upload flow.
- Removed the upload step from `Server 6_0` job.
- Refactored force upload.
- Changed prepare content script to copy from production to build at all times.
- Removed `TESTING_BUCKET` from upload packs & marketplace services.

To be merged on Tuesday 17/11.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by guyfreund** [comment]
@hod-alpert @Itay4 FYI

**Review by ShahafBenYakir — APPROVED** [review]

**Review by hod-alpert — APPROVED** [review]
@guyfreund Can you add a successfull build example?

**Comment by guyfreund** [comment]
> @guyfreund Can you add a successfull build example?

https://app.circleci.com/pipelines/github/demisto/content/44021/workflows/5cfde2f5-8f31-48fa-a178-bbfaaebf5892

this is a dev branch, which is equal to this branch but with some different constants

**Review by hod-alpert — CHANGES_REQUESTED** [review]
1. Move the destroy instances step to the server jobs (It does not destroy anything in the upload step)
2. Upload artifacts in the server jobs (there are logs there that can be usefull when debugging, you can upload only what's in `artifacts/logs` instead of the while artifacts directory)
3. Modify the log name in Tests/Marketplace/configure_and_install_packs.py:26 to match the name of the step you have given it (Upload packs)

**Review by hod-alpert — APPROVED** [review]

**Pull request merged**
