### PR TITLE
update varonis logo

### PR DESCRIPTION
**Pull request by vkorenkov-varonis**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
update varonis logo

## Must have
- [n/a] Tests
- [n/a] Documentation

### CODE REVIEW

**Comment by aaron1535** [comment]
Hi  @vkorenkov-varonis,
Thank you for your contribution.
In order for us to continue the process, please make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

**Comment by vkorenkov-varonis** [comment]
@aaron1535 About partner approvement, how it should be done?

**Comment by aaron1535** [comment]
@vkorenkov-varonis
In order for us to take care of your PR, please make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form
We will not be able to continue without filling out the form
Have a wonderful day

**Comment by vkorenkov-varonis** [comment]
> @vkorenkov-varonis In order for us to take care of your PR, please make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form We will not be able to continue without filling out the form Adding the tag happens automatically after filling out the form (after identifying you as a partner, of course)

done

**Comment by aaron1535** [comment]
@vkorenkov-varonis Indeed, this is the way to do what you asked for.
Please add release notes in the jar so we can merge the change
You can find more explanation [here](https://xsoar.pan.dev/docs/documentation/release-notes)

**Comment by vkorenkov-varonis** [comment]
@aaron1535 
 I do have an error, when trying to generate release notes:
image

**Review by aaron1535 — APPROVED** [review]

**Pull request merged**
