### PR TITLE
Remove pointless "From ServiceNow" prefix for close notes

### PR DESCRIPTION
**Pull request by tlium**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
The "From ServiceNow" prefix for close notes is annoying and should be removed. When close notes are synced in both incoming and outgoing mappers we end up with "From ServiceNow" as a prefix for close notes in both XSOAR and ServiceNow.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Bharathwaj-Murali** [comment]
@bakatzir @Shellyber @darkushin This makes sense. The issue is triggered because XSOAR field closeNotes is updated as a result of incident closure on ServiceNow. XSOAR in turn syncs with ServiceNow since it has a field to be updated and updates the close_notes field in ServiceNow with closeNotes from XSOAR which has 'From ServiceNow: close notes'. 

Easy fix is just to remove the From ServiceNow as suggested.

**Comment by ShacharKidor** [comment]
Hi @tlium, 
Thank you for your contribution! 
Our team will review your code soon. 

Can you please fill out the contribution registration form again? (we had a technical problem with your last submission)
[Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

Thanks again. 

FYI - @gal-forer

**Comment by tlium** [comment]
I assume the use case is pretty well defined for this PR and no video is required?

**Comment by ShacharKidor** [comment]
> I assume the use case is pretty well defined for this PR and no video is required?

@tlium - Sure :) 
I've just found out that this exact change was added in another contribution PR - [23808](https://github.com/demisto/content/pull/23808) and will be merged soon... so I'm closing this PR.

**Thanks again for suggesting that change, we really appreciate that!**

I'm available here or on slack for any questions :)

FYI - @Bharathwaj-Murali

**Pull request closed without merging**
