### PR TITLE
Rubrik release 1 2 2

### PR DESCRIPTION
**Pull request by crestdatasystems**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added a user-configurable parameter for the max file size in rubrik-radar-ioc-scan command.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by RotemAmit — COMMENTED** [review]
Thank you very much for your contribution! Nice work!
I have only 1 comment, please resolve the conflict in the release notes file and bump the pack version accordingly.

**Comment by crestdatasystems** [comment]
> Thank you very much for your contribution! Nice work! I have only 1 comment, please resolve the conflict in the release notes file and bump the pack version accordingly.

@RotemAmit I've resolved the conflict. Please let me know if you need anything else from our side.

**Comment by RotemAmit** [comment]
> > Thank you very much for your contribution! Nice work! I have only 1 comment, please resolve the conflict in the release notes file and bump the pack version accordingly.
> 
> @RotemAmit I've resolved the conflict. Please let me know if you need anything else from our side.

Please change back the base branch to contrib/crestdatasystems_Rubrik-Release-1-2-2 .

**Review by RotemAmit — APPROVED** [review]
Thank you very much for your contribution!

**Pull request merged**
