### PR TITLE
Rasterize - Fix timeout issue

### PR DESCRIPTION
**Pull request by adi88d**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: 
[XSUP-44587](https://jira-dc.paloaltonetworks.com/browse/XSUP-44587)
[XSUP-44856](https://jira-dc.paloaltonetworks.com/browse/XSUP-44856)

## Description
Removed the success_flag when waiting the tab to be ready.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by ilaredo — APPROVED** [review]
approved

**Review by tkatzir — APPROVED** [review]
Great! Approved.

**Comment by ShirleyDenkberg** [comment]
@tkatzir @ilaredo Doc review completed.

**Comment by adi88d** [comment]
the build is failing in xsaor 8 for rasterize test playbook which is a known issue, so the pr will be force merged.

**Pull request merged**
