### PR TITLE
Add output

### PR DESCRIPTION
**Pull request by K35537**
Added output as a Boolean with the contextPath of "in_whitelist"

This gives you a True/False to pivot off of once the whitelist has been checked.

### CODE REVIEW

**Comment by Bars92** [comment]
Hello @K35537! Thanks for the PR!
Im afraid we will have to still return 'yes', 'no' as a result to allow for backward compatibility. But the context is a good idea. I suggest something like this:
```
contextKey = "WhitelistCheck"
contextValue = demisto.get(demisto.context(), contextKey)
contextDic = { demisto.args()['item']: answer }
if contextValue:
    contextValue.update(contextDic)
    demisto.setContext(contextKey, contextValue)
else:
    demisto.setContext(contextKey, contextDic)
```

This will add to `WhitelistCheck` in the context the indicator and the results while keeping old results. Let me know if you find this ok and we can fix this PR.

**Comment by K35537** [comment]
@Bars92 that sounds good to me!

**Comment by Bars92** [comment]
@K35537 thanks for the PR! we will continue it in https://github.com/demisto/content/pull/1412.

**Comment by K35537** [comment]
@Bars92  would you like me to delete this branch?

**Comment by Bars92** [comment]
yes @K35537, thanks you!

**Pull request closed without merging**
