### PR TITLE
Added logic to ensure malicious indicator is found in phishing tests

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Description
- Added tasks that add (and at the end, also remove) a malicious URL to Minemeld miner. This way, Minemeld, which we rely on in the phishing tests, will always find this indicator malicious.

## Screenshots
image

### CODE REVIEW

**Comment by yardensade** [comment]
I don't think it should be removed.
Several test like this running at the same time could in theory cause conflict when the indicator is removed yet another phishing playbook is trying to find it at that time.
Better solution is simply to keep the add task and ignore errors, that way if the miner exists already, you will skip it and move on.
Another less lazy way would be to check first if the indicator exists in that miner, only if it doesn't -> add it. That should be bullet proof.
But in that case the lazy way should do.

**Comment by idovandijk** [comment]
Won't re-adding it all the time just flood Minemeld with duplicates?


> I don't think it should be removed.
> Several test like this running at the same time could in theory cause conflict when the indicator is removed yet another phishing playbook is trying to find it at that time.
> Better solution is simply to keep the add task and ignore errors, that way if the miner exists already, you will skip it and move on.
> Another less lazy way would be to check first if the indicator exists in that miner, only if it doesn't -> add it. That should be bullet proof.
> But in that case the lazy way should do.

**Comment by yardensade** [comment]
Nope.
image
image

**Comment by idovandijk** [comment]
I took your advice. Thanks.

**Comment by idovandijk** [comment]
Green build :)

**Pull request merged**
