### PR TITLE
VT - fix duplicate keys in IP.Address context key

### PR DESCRIPTION
**Pull request by bakatzir**
@GavrielFilippov  FYI 

## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16488

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - no need
- [ ] Code Review

### CODE REVIEW

**Comment by bakatzir** [comment]
i believe not, it's under: IP.Address, all items are as list
https://github.com/demisto/internal-content/tree/master/documentation/context_standards

**Comment by yardensade** [comment]
should be added to tests imo, add something to context, add it again, make sure there is only 1 entry there and not a list or something of the sort.

**Comment by bakatzir** [comment]
@yardensade would you mind have another look in the test playbook before merging?

**Comment by yardensade** [comment]
it seems to me like you repeat the IP command 2 times in the entire playbook, yet you delete the context after the first time you execute this command, and therefore it does not simulate the situation where the context is being updated.

This is by looking at the yml, I did not download the actual file, so correct me if I'm wrong.

**Comment by bakatzir** [comment]
@yardensade  834 tasks playbook can be counter intuitive to look at :)
Screen Shot 2019-04-21 at 20 02 57

**Comment by yardensade** [comment]
True story, that picture is great, looks good to me.

**Comment by bakatzir** [comment]
improve readability and checked for malicious ip as well.

**Pull request merged**
