### PR TITLE
Add Testing Docs to Content repo

### PR DESCRIPTION
**Pull request by amshamah419**
## Status
Ready

## Description
Making our testing process open for public reference.

## Relevant Issue
fixes: demisto/etc#18307

### CODE REVIEW

**Comment by amshamah419** [comment]
Hey @kirbles19 can I get an extra set of eyes on this?

https://github.com/demisto/content/tree/tests-docs/docs/tests and all of the pages under this.

**Comment by amshamah419** [comment]
@Itay4 The doc for test playbook was exactly the same so I'll leave it out.

**Comment by Itay4** [comment]
lets merge only after @kirbles19 review

**Comment by Itay4** [comment]
@kirbles19 @ygerowitz whats our status here?

**Comment by ygerowitz** [comment]
@amshamah419 Updated the readme.md and posted the changes there.

**Pull request merged**
