### PR TITLE
Slack - Better Handling of user invites in mirroring

### PR DESCRIPTION
**Pull request by liorblob**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/20311

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [CHANGELOG](https://github.com/demisto/content/compare/slack-fixes?expand=1#diff-2e92c7b68cd6a9f0e792c765a6ee5bec)

### CODE REVIEW

**Comment by Itay4** [comment]
@liorblob can we enhance the test playbook ?
gonna need to add a relevant user

**Comment by liorblob** [comment]
How can I add a user in this context?

**Comment by Itay4** [comment]
@yaakovi is this a configuration in the ami ?

**Comment by yaakovi** [comment]
@Itay4 @liorblob 
should be possible, ask @nir1212 

what this user should do? do you want to connect to demisto using that user?
this might be problematic

**Comment by kirbles19** [comment]
@liorblob Done.

**Pull request merged**
