### PR TITLE
Rasterize email output unique file name

### PR DESCRIPTION
**Pull request by MosheEichler**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43999

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
@MosheEichler This was tagged as Release Notes only, but there are no Release Notes in the PR.

**Comment by MosheEichler** [comment]
> @MosheEichler This was tagged as Release Notes only, but there are no Release Notes in the PR.

Sorry I forgot to add the RN.
Added now, Can you please review again?
Thanks.

**Comment by ShirleyDenkberg** [comment]
@tkatzir @ilaredo Doc review completed.

**Review by tkatzir — APPROVED** [review]
Good! Approved.

**Review by ilaredo — APPROVED** [review]
Great!
Approved

**Comment by MosheEichler** [comment]
[Need](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/10959317#L1469) a force merge.
[Ticket](https://jira-dc.paloaltonetworks.com/browse/CIAC-11230).

**Pull request merged**
