### PR TITLE
Removed username display in the configuration form and kept API key(password)

### PR DESCRIPTION
**Pull request by devang-metron**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Removed redundant API key/Password field as just one is required.

## Description
Removed redundant API key/Password field as just one is required. No changed made to script section

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by devang-metron** [comment]
Changes in the configuration are as follow:
image

**Comment by devang-metron** [comment]
@jlevypaloalto Also, please let me know if I need to make change to ConfKey [here](https://github.com/demisto/content/blob/9170282959eadafe919104f10dcfc84ad13b85d0/Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py#L410).

**Review by jlevypaloalto — CHANGES_REQUESTED** [review]
Hi @devang-metron,
Thank you for your contribution!

In regards to your question, no change is needed in the code.
Please generate release notes. You can find out how to that [here](https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/generate_docs#generate-docs).

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

**Comment by devang-metron** [comment]
@jlevypaloalto I have updated the ReadMe and release notes.

**Comment by jlevypaloalto** [comment]
Please update the docker image.
You can find out how update the docker [here](https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/format#:~:text=%2Dud%20%2C%2D%2Dupdate%2Ddocker).

**Comment by devang-metron** [comment]
@jlevypaloalto Formatted and updated docker as per your inputs.

**Comment by jlevypaloalto** [comment]
Hi @devang-metron,
I merged the internal PR, and your update is now in the master branch of content repo.
Your update should be available in the marketplace within the next 72 hours.
Again, thank you very much for your contribution!

**Pull request merged**
