### PR TITLE
Create integration-DigitalShadows.yml

### PR DESCRIPTION
**Pull request by shaniacht1**
fixes https://github.com/demisto/server/issues/9231

Some commands are still missing context

### CODE REVIEW

**Comment by dorsha** [comment]
deletedBy_role and requestedBy_role are deifned twice and cause UI errors:

image

image

image

**Comment by dorsha** [comment]
Also, command names are too long:
image

**Comment by shaniacht1** [comment]
@dorsha 
What do you suggest to do with the command names? We used to add the shortened name of the integration but then we stopped. And I'm afraid if I shorten the actual name of the command it will make the usage of the command unclear. 
Ideas?

**Comment by dorsha** [comment]
@NeelRust please suggest what do you want to do here.

**Comment by rishibhargava** [comment]
My recommendation is to shorten the name of brand but have the description start with digital shadows for each command so that search works great in war room. Can we complete this by Sunday. We have an event on Tuesday with digital shadows.

Regards,
Rishi

________________________________

**Comment by dorsha** [comment]
Commands names should start with: `ds-`

**Pull request merged**
