### PR TITLE
Microsoft Graph Mail - Added readme file

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
Ready

## Related Issues
related to: https://github.com/demisto/content/pull/4904

## Description
Added readme file.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [x] Documentation (with link to it)
- [x] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [x] TestCommonPython
- [x] DocumentationTest

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [README](https://github.com/demisto/content/blob/8f2803818f9ce3a3963479b26fd46a7df8355c6b/Integrations/MicrosoftGraphMail/README.md)

### CODE REVIEW

**Comment by IkaDemisto** [comment]
@ElazarK Any changes in readme file required here?

**Comment by bakatzir** [comment]
@kirbles19 @ElazarK 
No changes have made to the readme, can you please review?

**Comment by IkaDemisto** [comment]
Any update here?

**Comment by Itay4** [comment]
@IkaDemisto lets merge this

**Comment by IkaDemisto** [comment]
@Itay4 I will merge it but the readme are not updated

**Comment by Itay4** [comment]
@IkaDemisto so lets update and merge

**Comment by IkaDemisto** [comment]
@ElazarK did you have a chance to update the readme?

**Comment by jochman** [comment]
@IkaDemisto what is the status here?

**Comment by IkaDemisto** [comment]
@jochman ask @ElazarK

**Comment by jochman** [comment]
@ElazarK what is the status here?

**Comment by ElazarK** [comment]
@jochman @IkaDemisto according to @kirbles19 we're not supposed to be working on this anymore. any questions should be directed to him

**Pull request closed without merging**
