### PR TITLE
Hackathon SSL thingy

### PR DESCRIPTION
**Pull request by Hruuttila**
## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
Harri Ruuttila SA Palo Alto Networks 

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Automation script to:
1. Get certificate details from a site
2. Report the issuer and the expiration date
3. Use this info to create a playbook to monitor that none of your certificates expire.

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Comment by barchen1** [comment]
@Hruuttila I cant understand what this pack is for, its an empty pack. 
It has only the pack_metadata.json file.

**Comment by Hruuttila** [comment]
@barchen1 haha, forgot to add the script itself :D my bad. adding it now

**Comment by Hruuttila** [comment]
Added the actual script file.

**Comment by anara123** [comment]
@Hruuttila is this pack participates in XSOAR Hackathon?

**Comment by Hruuttila** [comment]
@anara123 Yes

**Comment by barchen1** [comment]
@Hruuttila Please add a video demoing your script.

**Comment by Hruuttila** [comment]
@barchen1 its added to the hackathon submission page as requested in the hackathon submission.

**Review by guykeller — CHANGES_REQUESTED** [review]
Suggested a few changes, the only critical one being the separation of the YML to YML and Python file.
The rest of the comments, though highly recommended, aren't mandatory - so feel free to let me know when you'd like me to review the changes.

**Comment by guykeller** [comment]
Closing is per my discussion with Harri, a new PR will be opened

**Pull request closed without merging**
