### PR TITLE
guid change by by readable format

### PR DESCRIPTION
**Pull request by GalRabin**
## Status
Ready
Merge must be forced in order to pass validate YAML in the build process.

## Related Issues
fixes - https://github.com/demisto/etc/issues/19289
fixes - https://github.com/demisto/etc/issues/19720

## Description
Changing scripts id which is not in a readable format to a readable format.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Code Review

### CODE REVIEW

**Comment by GalRabinDemisto** [comment]
@glicht 
I added `CHANGELOG` to relevant files

**Comment by GalRabinDemisto** [comment]
@glicht 
I did the following test:
    1. I created an [instance with demisto-5.0](https://ec2-13-52-188-76.us-west-1.compute.amazonaws.com):
        - user: admin
        - pass: 0522703456Gal
    2. I chose 2 scripts which has name != id (yaml format) and performed the following:
               a. [DisplayHtml](https://github.com/demisto/content/blob/master/Scripts/script-DisplayHTML.yml)
        b. [IPToHost](https://github.com/demisto/content/blob/2d4f5b8c17934638164ba381f420151e4630e559/Scripts/script-IPToHost.yml)
    3. I searched for 2 playbooks that contains each one of the scripts:
        a. [Vulnerability Handling - Qualys](https://github.com/demisto/content/blob/2d4f5b8c17934638164ba381f420151e4630e559/Playbooks/playbook-Vulnerability_Handling_-_Qualys.yml) - displayhtml
        b. [IP Enrichment - External - Generic v2](https://github.com/demisto/content/blob/master/Playbooks/playbook-IP_Enrichment_-_External_-_Generic_v2.yml) - ChangeRemediationSLAOnSevChange.
    4. I validated that the tasks which use the scripts from section 2 don't show the discussed error `Automation is missing`.
    5. I updated the [instance with demisto-5.0](https://ec2-13-52-188-76.us-west-1.compute.amazonaws.com) content to [guid build content](https://circleci.com/gh/demisto/content/32119) by uploading its `content_new.zip` from artifacts.
    6. I validated that the error isn't influenced by the playbook task and I wasn't able to recreate it (Please check out the images after uploading the changed content).

Screen Shot 2019-10-30 at 12 24 06
Screen Shot 2019-10-30 at 12 25 27

**Comment by GalRabinDemisto** [comment]
@yaakovi 
You need to do force merge

Thanks

**Comment by yaakovi** [comment]
not converting to packages / not adding tests

**Pull request merged**
