### PR TITLE
[MSDE] Commands for queries

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/42391

## Description
- Added *time_range* argument to **microsoft-atp-advanced-hunting** command.
- Added new command **microsoft-atp-advanced-hunting-lateral-movement-evidence**.
- Added new command **microsoft-atp-advanced-hunting-persistence-evidence**.
- Added new command **microsoft-atp-advanced-hunting-file-origin**.
- Added new command **microsoft-atp-advanced-hunting-process-details**.
- Added new command **microsoft-atp-advanced-hunting-network-connections**.
- Added new command **microsoft-atp-advanced-hunting-privilege-escalation**.
- Added new command **microsoft-atp-advanced-hunting-tampering**.
- Added new command **microsoft-atp-advanced-hunting-cover-up**.

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by DeanArbel** [comment]
@jrosenpanw The pull request is ready for a technical writer review.
Please review the `.yml` changes, the `readme` changes, and the `release notes` changes.

**Comment by julieschwartz18** [comment]
Doc review complete for the MicrosoftDefenderAdvancedThreatProtection.yml file. @DeanArbel - please confirm the following:
- spelling, capitalization, and minor wording updates in the descriptions - the README file should be regenerated.
- line 1016, 1980, 4892 - the description for MicrosoftATP.Alert.LastUpdateTime is "The first event time that triggered the alert on that machine." - is this correct?
- line 1086 - the description for MicrosoftATP.AlertUser.User.NetworkUser is "True if domain admin, False otherwise." - is this correct?
- line 1132 - the type for MicrosoftATP.AlertFile.Files.IsValidCertificate is defined as Number. Should it be Boolean?
- line 1864 - is it ok that the machine risk score is a string (score is string in other places as well)
- line 2558 - the type defined for MicrosoftATP.Indicators.severity is string, but the description is "An integer representing the severity of the malicious behavior
        identified by the data within the indicator. Possible values: "Informational", "Low", "MediumLow", "MediumHigh", and "High", where High is the most severe
        and Informational is not severe at all." - so is it an integer or a string (same for other severity parameters)
- line 2594, 2831, 3910, 3232 - the description for File.SHA256 is "The SHA1 hash of the file"
- line 3196 - the type for MicrosoftATP.Indicators.severity is Number, but the description is "An integer representing the severity of the malicious behavior
        identified by the data within the indicator. Possible values: "Informational", "Low", "MediumLow", "MediumHigh", and "High", where High is the most severe
        and Informational is not severe at all. - is severity string or number (integer)? And on line 3323, severity seems to be string
- in the description for this PR, the first bullet says "Added time_range argument to microsoft-atp-advanced-hunting command." For the microsoft-atp-advanced-hunting command, there is no time_range argument (all the others have though, for example microsoft-atp-advanced-hunting-lateral-movement-evidence) - is this ok?

**Comment by DeanArbel** [comment]
@julieschwartz18 I answered below:

> * spelling, capitalization, and minor wording updates in the descriptions - the README file should be regenerated.

Ok, will be done once we're done with the other points.

> * line 1016, 1980, 4892 - the description for MicrosoftATP.Alert.LastUpdateTime is "The first event time that triggered the alert on that machine." - is this correct?

I haven't worked on this command - It's obviously not right... it should be something like `UTC time of the last update`.

> * line 1086 - the description for MicrosoftATP.AlertUser.User.NetworkUser is "True if domain admin, False otherwise." - is this correct?

I haven't worked on this command. @barchen1 any idea?

> * line 1132 - the type for MicrosoftATP.AlertFile.Files.IsValidCertificate is defined as Number. Should it be Boolean?

Seems so.

> * line 1864 - is it ok that the machine risk score is a string (score is string in other places as well)

Yeah.

> * line 2558 - the type defined for MicrosoftATP.Indicators.severity is string, but the description is "An integer representing the severity of the malicious behavior
>   identified by the data within the indicator. Possible values: "Informational", "Low", "MediumLow", "MediumHigh", and "High", where High is the most severe
>   and Informational is not severe at all." - so is it an integer or a string (same for other severity parameters)

It's ok.

> * line 2594, 2831, 3910, 3232 - the description for File.SHA256 is "The SHA1 hash of the file"

This should be fixed.

> * line 3196 - the type for MicrosoftATP.Indicators.severity is Number, but the description is "An integer representing the severity of the malicious behavior
>   identified by the data within the indicator. Possible values: "Informational", "Low", "MediumLow", "MediumHigh", and "High", where High is the most severe
>   and Informational is not severe at all. - is severity string or number (integer)? And on line 3323, severity seems to be string

It can stay a string.

> * in the description for this PR, the first bullet says "Added time_range argument to microsoft-atp-advanced-hunting command." For the microsoft-atp-advanced-hunting command, there is no time_range argument (all the others have though, for example microsoft-atp-advanced-hunting-lateral-movement-evidence) - is this ok?

This was missed. I'm addressing this :)

**Comment by barchen1** [comment]
> > * line 1086 - the description for MicrosoftATP.AlertUser.User.NetworkUser is "True if domain admin, False otherwise." - is this correct?
> 
> I haven't worked on this command. @barchen1 any idea?
> 

No. It should be the description for `isOnlyNetworkUser` field. 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alert-related-user-info?view=o365-worldwide

**Review by yuvalbenshalom — APPROVED** [review]
great work.

**Pull request merged**
