### PR TITLE
Fixed: It doesn't work with all=yes and subplaybook=yes/auto in subplaybooks

### PR DESCRIPTION
**Pull request by spearmin10**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
ContextData under the subplaybook aren't deleted with all=yes and subplaybook=yes or auto.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by DeanArbel — CHANGES_REQUESTED** [review]
Nice fix!
* Please add revision version release notes - see [this guide](https://xsoar.pan.dev/docs/integrations/release-notes) for reference.

**Comment by spearmin10** [comment]
Please review the release note for DeleteContext as I've updated it.

**Review by DeanArbel — APPROVED** [review]
Good job, I'm approving the PR, but please note the pack metadata will need to be updated, and the release notes for that version should only contain **the changes in your pull request** - i.e. the change to `DeleteContext`. 
You don't need to worry about this, since we can handle this internally, so you can leave the pull request as it is.

@kirbles19 @ShirleyDenkberg please review `Packs/CommonScripts/ReleaseNotes/1_2_80.md` - keep in mind you should only review the text part for `##### DeleteContext`

**Comment by kirbles19** [comment]
@DeanArbel Done

**Pull request merged**
