### PR TITLE
adding readme and video demo to AlienVaultOTXFeed

### PR DESCRIPTION
**Pull request by roysagi**
## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
adding readme and video demo to AlienVaultOTXFeed

### CODE REVIEW

**Comment by kirbles19** [comment]
@ElazarK Please work with @roysagi to fill in the missing parameter descriptions.
Also, give the command a good human-readable name, and review for overall English/consistency.

**Comment by roysagi** [comment]
@kirbles19 @ElazarK - seems the missing params are simply standard feed integration params as can be seen here: https://xsoar.pan.dev/docs/reference/integrations/auto-focus-feed
I can add them if you haven't already.

**Comment by kirbles19** [comment]
@roysagi Done, ready to publish.

**Comment by roysagi** [comment]
@ronykoz - circle fails because on unrelated integrations - can we merge this?

**Pull request merged**
