### PR TITLE
Azure compute v2

### PR DESCRIPTION
**Pull request by liorblob**
## Status
In Progress

## Related Issues
https://github.com/demisto/etc/issues/19201

## Description
Add v2 to support new auth flow, deprecate the old one

## Does it break backward compatibility?
   - Yes
       - New auth flow

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](https://github.com/demisto/content/compare/azure-compute?expand=1#diff-db05801d5dd21ba1547e1806f48c218b) - ONLY subscription related params/args
- [ ] [CHANGELOG](https://github.com/demisto/content/compare/azure-compute?expand=1#diff-0a0d451bc57c28566871e1ed6bf7393d)

### CODE REVIEW

**Comment by liorblob** [comment]
@kirbles19 any progress on this?

**Comment by Itay4** [comment]
@richardbluestone please review

**Comment by richardbluestone** [comment]
I've reviewed and updated the md file.

**Comment by liorblob** [comment]
@richardbluestone Could you review the yaml file as well? Just the `subscription` parameters and arguments.

**Pull request merged**
