### PR TITLE
Slack v2 - Add docs

### PR DESCRIPTION
**Pull request by liorblob**
## Status
Ready

Slack v2 - Changes since recent update:
1. Added `blocks` argument to `send-notification` command
2. Added a paragraph to `Additional Information` (Blocks and interactions)
3. Added a limitation (unsecure)

### CODE REVIEW

**Comment by richardbluestone** [comment]
Hi why was the html generated before we reviewed the yml file? Do you want me to review the html or make the changes direct in ZenDesk?

**Comment by liorblob** [comment]
The yml file was already reviewed, just need to review these updates and apply them to Zendesk.

**Comment by richardbluestone** [comment]
Hi, I've updated the documentation for Slack V2 integration: https://support.demisto.com/hc/en-us/articles/360034639693

For Slack Ask, is this a new article?

**Comment by liorblob** [comment]
@richardbluestone Indeed it is.

**Comment by richardbluestone** [comment]
Hi - I've added/updated the following:

- Slack V2: https://support.demisto.com/hc/en-us/articles/360034639693-Slack-V2

-  Slack Ask: https://support.demisto.com/hc/en-us/articles/360036396974
Please approve/comment the Slack Ask documentation.

**Comment by liorblob** [comment]
@richardbluestone I'm getting a permission error when I navigate to the SlackAsk page, also I can't find it on zendesk

**Comment by richardbluestone** [comment]
> @richardbluestone I'm getting a permission error when I navigate to the SlackAsk page, also I can't find it on zendesk

Try now: https://support.demisto.com/hc/en-us/articles/360036396974-Slack-Ask

**Comment by liorblob** [comment]
@richardbluestone will it be problematic to sync between the `README.md` files in the PR with the zendesk content?

**Comment by richardbluestone** [comment]
> @richardbluestone will it be problematic to sync between the `README.md` files in the PR with the zendesk content?

Not really, unless we have to generate all of the content from the md files and use it in Zendesk.

**Comment by liorblob** [comment]
@richardbluestone I just want that the README files will identical to the contents currently in zendesk.

**Comment by richardbluestone** [comment]
> @richardbluestone I just want that the README files will identical to the contents currently in zendesk.

Yes they are almost identical - I took the html from the file you generated. The only differences are some of the headings (we give them a human readable form) and I kept a section, called "Generate Authentication Parameters" https://support.demisto.com/hc/en-us/articles/360034639693-Slack-V2

**Comment by liorblob** [comment]
@Itay4 can you approve?

**Pull request merged**
