### PR TITLE
CIAC 7515 - prisma cloud - fix Nonetype in scan images command

### PR DESCRIPTION
**Pull request by yucohen**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7515

## Description
1. The API returns a null values, so changed the `image_scan.get("instances", [{}])[0].get("image")` to `(image_scan.get("instances") or [{}])[0].get("image")`
2. Ruff changes

### CODE REVIEW

**Review by bziser — APPROVED** [review]
great

@GuyAfik please take a look too

**Comment by bziser** [comment]
@yucohen 
please also check why pre-commit failing and try to solve :)

**Comment by yucohen** [comment]
@bziser It makes *a lot* of changes in the fetch command so I didn't want to change it

**Review by GuyAfik — APPROVED** [review]
LGTM, nicely done

**Pull request merged**
