### PR TITLE
Update sane doc reports automation

### PR DESCRIPTION
**Pull request by agamm**
## Status
Ready

## Related Issues
None, just a failing build in `dockerfiles`:
https://github.com/demisto/dockerfiles/pull/1085
https://github.com/demisto/dockerfiles/pull/1130

## Description
Updating the `sane-doc-reports` tag - which should fix docker build problems.

## Required version of Demisto
5.0.0

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [x] Documentation (with link to it)
- [X] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](Scripts/SaneDocReport/CHANGELOG.md)

### CODE REVIEW

**Comment by ronykoz** [comment]
@roysagi can you take a look at the RN please?

**Comment by roysagi** [comment]
I reverted the CHANGELOG as the earlier descriptions were better:
- Fixed an issue where the line chart x-axis was not readable.
- Fixed an issue with the graphs width.

**Comment by ronykoz** [comment]
where are the RN?
@agamm if you want to merge this ping me i'll force merge

**Comment by agamm** [comment]
> where are the RN?
> @agamm if you want to merge this ping me i'll force merge

We had an internal CircleCI docker build failure - this updates fixes it, I don't know if we need RN for this.

**Comment by ronykoz** [comment]
@agamm OK, merging then.

**Pull request merged**
