### PR TITLE
update arguments descriptions

### PR DESCRIPTION
**Pull request by noaco**
## Status
Ready

## Additional changes
Documentation is going through an update as well

### CODE REVIEW

**Comment by noaco** [comment]
@anara123 [documentation](https://github.com/demisto/etc/issues/16201)

**Comment by noaco** [comment]
@kirbles19 can you please approve

**Comment by kirbles19** [comment]
Need time to review all of that.

**Comment by Itay4** [comment]
@kirbles19 did you get to review this?

**Comment by kirbles19** [comment]
@noaco @anara123 @Itay4 Can someone please attach the YML.

**Comment by noaco** [comment]
@kirbles19 sent you over slack

**Comment by yardensade** [comment]
What is the status here?

**Comment by yardensade** [comment]
This is stale for 4 months without any comment, can we close this? @anara123 @noaco @Itay4

**Comment by Itay4** [comment]
@kirbles19 ?

**Comment by Itay4** [comment]
@kirbles19  ?

**Comment by kirbles19** [comment]
I'm in the middle of review, plan to have it finished before code review for this release. We can then publish fresh docs.

**Comment by Itay4** [comment]
@kirbles19  ??

**Comment by noaco** [comment]
@kirbles19 should I close this? is this still relevant?

**Pull request closed without merging**
