### PR TITLE
Upload index fix

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
- [x] Ready

## Description
Fixing the following issue https://app.circleci.com/pipelines/github/demisto/content/93386/workflows/6aba0d5c-3fcf-40b4-954e-af5b7903e084/jobs/383404#queue-placeholder/containers/0

Skipping upload if files not found.

### CODE REVIEW

**Review by guyfreund — CHANGES_REQUESTED** [review]
- Please use `-f` https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html.
- Please also check for all other copied files from artifacts to gcs.

**Review by guyfreund — COMMENTED** [review]
Please check that your fixes are ok when the upload is empty.

**Comment by Shellyber** [comment]
Regular upload, works like a charm: https://app.circleci.com/pipelines/github/demisto/content/93509/workflows/50b8f557-3389-479a-b67e-92a5a3c96edc/jobs/383662

https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/upload-index-fix/50b8f557-3389-479a-b67e-92a5a3c96edc/content?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Empty upload: https://app.circleci.com/pipelines/github/demisto/content/93519/workflows/b8f10658-73fa-4b40-9922-e73a9a29e71d/jobs/383688

image

**Review by guyfreund — APPROVED** [review]
Nice. just remove the sys.exit before merging 👏

**Pull request merged**
