### PR TITLE
EclecticIQ v3 integration

### PR DESCRIPTION
**Pull request by mikhva-eiq**
commit repeats state of PR before git changes

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
New version of integration with EclecticIQ Intelligence Center. New commands and functionality.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by mikhva-eiq** [comment]
@ilappe I believe I made some mistakes while tried to resolve git issues and that PR is on the same state as it was before that change.

**Comment by edik24** [comment]
Previous PR is https://github.com/demisto/content/pull/30508

**Review by ilappe — COMMENTED** [review]
Hi @mikhva-eiq
thanks!
i fixed most of the lint and pre-commit issues
please:
- see my comment regarding`Packs/EclecticIQ/Author_image.png` 
- validate the Unit test passed and increase the coverage rate to be at least 70%
thanks again!

**Review by melamedbn — APPROVED** [review]

**Comment by ilappe** [comment]
> @ilappe How test coverage calculated in Demisto-sdk/circleci here? I’m asking because I made a few commits with different tests and see that coverage vary from 0 to 14% but don’t get clear logic.

the calculation are (number of tested code lines /total line number)
for example, if `EclecticIQIntelligenceCenterv3.py` have ~2780 lines, and in the test only 278 lines are was executed, the rate will be ~10 %
BTW, there is no test now after the last commit

**Comment by mikhva-eiq** [comment]
@ilappe I committed some test and I dont see errors in CircleCI output anymore, does it mean that all is ok now?

**Comment by mikhva-eiq** [comment]
@ilappe I finished with unittests and other technical issues, what are we doing next? Is it only doc and release notes review left?

**Comment by ilappe** [comment]
Hi @mikhva-eiq
thanks for your effort!!
it's look like the Contribution Form not filled 
[Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA)
in addition, what are your available time for a demo ?

**Review by ilappe — APPROVED** [review]

**Comment by ilappe** [comment]
Hi @mikhva-eiq
any updates regarding this https://github.com/demisto/content/pull/32417#issuecomment-1938478958?

**Comment by mikhva-eiq** [comment]
@ilappe apologise for delay, are you located in Israel? I mean what do you think about demo at 25th Feb Sunday? for me at this week it's the best option

**Comment by ilappe** [comment]
@mikhva-eiq 
25th Feb Sunday is good for me
what are your available time and time zone ?

**Comment by mikhva-eiq** [comment]
@ilappe Im in CET, available between 11:00 and 17:00. Would you like I share with you our zoom or we need to use yours meeting?

**Comment by ilappe** [comment]
Status: Waiting for a demo video

**Comment by mikhva-eiq** [comment]
@ilappe I sent you demo recording a couple of days ago, is all clear with that? what are our next steps?

**Comment by ilappe** [comment]
Hi @mikhva-eiq 
Great demo !
i will continue with our process to merge it
thanks for your great effort!

**Comment by mikhva-eiq** [comment]
@ilappe done

**Pull request merged**
