### PR TITLE
Fixed an issue that it doesn't decode the content with charset

### PR DESCRIPTION
**Pull request by spearmin10**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fixed an issue that it doesn't decode the content payload with its charset.

## Screenshots
The email is displayed like below with the current version. RAW encoded text is shown as a body text.
image

The fixed one decodes body texts with its charset like below.
image

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by adi88d** [comment]
@spearmin10 Please fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**Comment by spearmin10** [comment]
@adi88d I've filled out it.

**Review by adi88d — APPROVED** [review]
Thanks for your contribution @spearmin10!

**Comment by adi88d** [comment]
@DinaMeylakh please fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**Comment by kirbles19** [comment]
@spearmin10 Done.

**Pull request merged**
