### PR TITLE
Encourage migrating to GenericSQL

### PR DESCRIPTION
**Pull request by omercnet**
This change marks *query* command as depracated and adds *pgsql-query*
so it's seamless to switch over to GenericSQL integration,
and encourages switching to *sql-command*.

Signed-off-by: Omer Cohen <git@omer.io>

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/27036

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

### CODE REVIEW

**Comment by ohaim1008** [comment]
@glicht would like your opinion.
If we are having a different command for postgre maybe it shouldn't be referenced to the general one.
Also, `query` command used to ease the changes from other SQL integrations so maybe we should keep it.

**Comment by ohaim1008** [comment]
The error in 5.0 happened before (the one with Microsoft_SQL_instance_using_encrypted_connection_test) we are not sure why, we checked it locally and in self-service and it's ok, so you can ignore it.

**Comment by glicht** [comment]
@kirbles19 please review

**Comment by kirbles19** [comment]
@omercnet Done.

**Comment by omercnet** [comment]
much appreciated @kartikb007 

@ohaim1008 @glicht who has the power to force merge this with 5_0 failing on the integration instance test?

**Pull request merged**
