### PR TITLE
Combine existing OpenAI integrations and add support for Azure OAI

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Follow-up to: https://github.com/demisto/content/pull/31235 

## Description
This PR would combine the two existing, community-supported OpenAI integrations into one to simplify the user experience, and make the integrations easier to update and maintain going forward.

It would also add support for Azure OpenAI, using the work of Tim Roberts.

I am of the opinion that we should combine standard OpenAI and Azure OpenAI into a single integration, to simplify future updates and help ensure we are keeping both services in sync. Per Microsoft:
"Azure OpenAI co-develops the APIs with OpenAI, ensuring compatibility and a smooth transition from one to the other."
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/faq#how-do-the-capabilities-of-azure-openai-compare-to-openai-

## Must have
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by MLainer1** [comment]
Hi @ali-sawyer, is this PR ready for merge?

**Comment by ali-sawyer** [comment]
@MLainer1 sorry I missed your comment – yes this is ready for review. This is basically a continuation of https://github.com/demisto/content/pull/31235, so as long as it looks good to you, it is ready for merge.

**Comment by MLainer1** [comment]
Hi @ali-sawyer, looks like there are minor validation errors and flake8 issues. If you could fix them, I'll go ahead and merge the PR :)

**Comment by MLainer1** [comment]
Closing the issue, feel free to open it when you are ready to continue working on it.

**Pull request closed without merging**
