### PR TITLE
Acti indicator query playbook

### PR DESCRIPTION
**Pull request by satyakidroid**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR is created to continue working on (https://github.com/demisto/content/pull/18725)

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by satyakidroid** [comment]
@kgal-pan  I think this should work

**Comment by kgal-pan** [comment]
@satyakidroid - Looks good. Please merge from `master` to fix validation:

```bash
/Utils/git_pull_master_into_fork.sh
```

**Comment by satyakidroid** [comment]
@kgal-pan , I think the current state is good.

**Comment by kgal-pan** [comment]
@yaakovi - This PR was already reviewed by @tomer-pan and approved in https://github.com/demisto/content/pull/18401 regarding Playbooks.

The only difference is that in includes some fixes for UTs that were sending out HTTP requests to Accenture APIs instead of mocking them, see [here](https://github.com/demisto/content/pull/18725#issuecomment-1108445976).

Therefore, not sure that we need @idovandijk to review this PR.

**Review by yaakovi — APPROVED** [review]

**Pull request merged**
