### PR TITLE
chore: Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by ShacharKidor** [comment]
Hi @naveensrinivasan, 
Thank you for contributing!

Correct me if I'm wrong but I think that if we restrict the GITHUB_TOKEN permissions at the repo level as described in section 4 [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions), it automatically defines the ‘contents: read’ key in all of the repository's workflows.
D0300368-39D2-464B-A3ED-C746390B8411
Please correct me if I missed anything. 

I'm available here or via slack :) 
Thanks again.

**Comment by naveensrinivasan** [comment]
> Hi @naveensrinivasan, Thank you for contributing!
> 
> Correct me if I'm wrong but I think that if we restrict the GITHUB_TOKEN permissions at the repo level as described in section 4 [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions), it automatically defines the ‘contents: read’ key in all of the repository's workflows. D0300368-39D2-464B-A3ED-C746390B8411 Please correct me if I missed anything.
> 
> I'm available here or via slack :) Thanks again.

Yes, you are right. It will restrict it. 

But there are

> Hi @naveensrinivasan, Thank you for contributing!
> 
> Correct me if I'm wrong but I think that if we restrict the GITHUB_TOKEN permissions at the repo level as described in section 4 [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions), it automatically defines the ‘contents: read’ key in all of the repository's workflows. D0300368-39D2-464B-A3ED-C746390B8411 Please correct me if I missed anything.
> 
> I'm available here or via slack :) Thanks again.

Yes, you are right! :)

**Comment by ShacharKidor** [comment]
@naveensrinivasan - Thank you for the quick reply. 
So in that case,  restricting the GITHUB_TOKEN permissions at the repo level should be sufficient, which makes the suggested changes in this PR unnecessary... right?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan - Thank you for the quick reply.
> So in that case, restricting the GITHUB_TOKEN permissions at the repo level should be sufficient, which makes the suggested changes in this PR unnecessary... right?

Yes. If you enable that.

**Comment by ShacharKidor** [comment]
@naveensrinivasan - After consulting with @glicht we decided to accept your contribution as a best practice. 

Please fill in the following form so I could merge your PR: 

> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @ShacharKidor will know he can start review the proposed changes.

Thank you again!

**Comment by naveensrinivasan** [comment]
> > @naveensrinivasan - After consulting with @glicht we decided to accept your contribution as a best practice.
> > In order to complete this contribution:
> > 
> > 1. Please fill in the following form so I could merge your PR:
> > 
> > > Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @ShacharKidor will know he can start review the proposed changes.
> > 
> > 
> > 
> > 2. Please merge master.
> > 
> > Thank you again!
> 
> Hi @naveensrinivasan - haven't heard from you for a while. Can you please do the above two requests so we could merge your PR? Thanks in advance.

I have done that. I apologize for the delay. Thanks for the reminder.

**Review by ShacharKidor — APPROVED** [review]

**Comment by ShacharKidor** [comment]
@naveensrinivasan - Thank you :) merging your PR now.

**Pull request merged**
