### PR TITLE
normalizing all feed integration common parameter names and order

### PR DESCRIPTION
**Pull request by roysagi**
## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/22198

## Description
normalizing all feed integration common parameter names and order

### CODE REVIEW

**Comment by roysagi** [comment]
no docs - adding docs approved

**Comment by roysagi** [comment]
note validation fails because of this issue:
image
in all yml files.

It is a known issue and will be fixed in the next SDK version @bakatzir

**Comment by avidan-H** [comment]
Results on this branch:

 parameter name            | parameter display                                                         | count   
-------------------------- | ------------------------------------------------------------------------- | -------
 api_key                   | The AutoFocus API key                                                     |       1 
 api_token                 | API token                                                                 |       1 
 auth_code                 | Authorization Code                                                        |       1 
 credentials               | Username                                                                  |       2 
 custom_feed_urls          | The URL for the custom feed to fetch                                      |       1 
 delimiter                 | Delimiter                                                                 |       1 
 doublequote               | Double quote                                                              |       1 
 escapechar                | Escape character                                                          |       1 
 feed                      | Fetch indicators                                                          |      21 
 feed_source               | Feed Source                                                               |       1 
 feedBypassExclusionList   | Bypass exclusion list                                                     |      21 
 feedExpirationInterval    | ""                                                                        |      21 
 feedExpirationPolicy      | ""                                                                        |      20 
 feedExpirationPolicy      |                                                                           |       1 
 feedFetchInterval         | Feed Fetch Interval                                                       |      21 
 feedReliability           | Source Reliability                                                        |      20 
 feedReliability           | Source reliability                                                        |       1 
 feedReputation            | Indicator Reputation                                                      |      21 
 fetch_time                | First fetch time range (<number> <time unit>, e.g., 1 hour, 30 minutes)   |       1 
 fieldnames                | Field Names                                                               |       1 
 fusion_file_path          | Fusion File Path                                                          |       1 
 ignore_regex              | Ignore Regex                                                              |       1 
 indicator_feeds           | Indicator feed                                                            |       1 
 indicator_type            | Indicator type                                                            |       1 
 indicator_type            | Indicator Type                                                            |       2 
 insecure                  | Trust any certificate (not secure)                                        |      21 
 polling_timeout           | Request Timeout                                                           |       8 
 proxy                     | Use system proxy settings                                                 |      21 
 quotechar                 | Quote Character                                                           |       1 
 regions                   | Regions                                                                   |       3 
 risk_rule                 | Risk Rule                                                                 |       1 
 services                  | Services                                                                  |       2 
 skipinitialspace          | Skip Initial Space                                                        |       1 
 sub_feeds                 | Sub Feeds                                                                 |       1 
 sub_feeds                 | Sub-Feeds                                                                 |       1 
 subfeeds                  | Sub-Feeds                                                                 |       1 
 threat_type               | The threat type for which to fetch indicators                             |       1 
 threshold                 | Malicious Threshold                                                       |       1 
 url                       | Sub-Feeds                                                                 |       4 
 url                       | URL                                                                       |       1

**Comment by ronykoz** [comment]
@roysagi please fix the remaining ones

**Comment by roysagi** [comment]
@ronykoz @avidan-H - Done found the last ones

**Comment by avidan-H** [comment]
Results after the latest commits:


 parameter name            | parameter display                                                         | count   
-------------------------- | ------------------------------------------------------------------------- | -------
 api_key                   | The AutoFocus API key                                                     |       1 
 api_token                 | API token                                                                 |       1 
 auth_code                 | Authorization Code                                                        |       1 
 credentials               | Username                                                                  |       2 
 custom_feed_urls          | The URL for the custom feed to fetch                                      |       1 
 delimiter                 | Delimiter                                                                 |       1 
 doublequote               | Double quote                                                              |       1 
 escapechar                | Escape character                                                          |       1 
 feed                      | Fetch indicators                                                          |      21 
 feed_source               | Feed Source                                                               |       1 
 feedBypassExclusionList   | Bypass exclusion list                                                     |      21 
 feedExpirationInterval    | ""                                                                        |      21 
 feedExpirationPolicy      | ""                                                                        |      21 
 feedFetchInterval         | Feed Fetch Interval                                                       |      21 
 feedReliability           | Source Reliability                                                        |      21 
 feedReputation            | Indicator Reputation                                                      |      21 
 fetch_time                | First fetch time range (<number> <time unit>, e.g., 1 hour, 30 minutes)   |       1 
 fieldnames                | Field Names                                                               |       1 
 fusion_file_path          | Fusion File Path                                                          |       1 
 ignore_regex              | Ignore Regex                                                              |       1 
 indicator_feeds           | Indicator Feed                                                            |       1 
 indicator_type            | Indicator Type                                                            |       3 
 insecure                  | Trust any certificate (not secure)                                        |      21 
 polling_timeout           | Request Timeout                                                           |       8 
 proxy                     | Use system proxy settings                                                 |      21 
 quotechar                 | Quote Character                                                           |       1 
 regions                   | Regions                                                                   |       3 
 risk_rule                 | Risk Rule                                                                 |       1 
 services                  | Services                                                                  |       2 
 skipinitialspace          | Skip Initial Space                                                        |       1 
 sub_feeds                 | Sub-Feeds                                                                 |       2 
 subfeeds                  | Sub-Feeds                                                                 |       1 
 threat_type               | The threat type for which to fetch indicators                             |       1 
 threshold                 | Malicious Threshold                                                       |       1 
 url                       | Sub-Feeds                                                                 |       4 
 url                       | URL                                                                       |       1

**Comment by ronykoz** [comment]
Force merging due to SDK problems

**Pull request merged**
