### PR TITLE
Added scanner name to qualys-pc-scan-launch & qualys-vm-scan-launch

### PR DESCRIPTION
**Pull request by EdenOhana**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16791

## Description
Added scanner name argument to qualys-pc-scan-launch & qualys-vm-scan-launch.
This allows the user to specify a scanner to be able to scan internal network IP.

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by Itay4** [comment]
@kirbles19 please review the yml

**Comment by Itay4** [comment]
@EdenOhana please convert release notes and changelog format and lets merge

**Comment by Itay4** [comment]
@EdenOhana can we finish this one ?

**Comment by ronykoz** [comment]
@EdenOhana @Itay4 what's the status here?

**Pull request merged**
