### PR TITLE
Ews compliance

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/17410

## Description
We passed the password for EWS as plain text inside a docker container. Now the pass is not written explicitly in docker at all.
Will create another PR to fix same issue in "integration-Exchange2016_Compliance"

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by orlichter1** [comment]
@kirbles19 Could you please go over the [release notes](https://github.com/demisto/content/edit/EWS-compliance/Integrations/EWSv2/CHANGELOG.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F3938)? .yml . wasn't changed

**Comment by richardbluestone** [comment]
Hi, I've reviewed the mk file. Thanks

**Comment by yaakovi** [comment]
@orlichter1 test is failing on EWS

**Comment by orlichter1** [comment]
@yaakovi Ika said that pyEWS_test failed this morning in the regular build. He's looking into it. When he's done I'll rerun CircleCI see if it was fixed.

**Pull request merged**
