### PR TITLE
fixes cloudwatch attribute assignment

### PR DESCRIPTION
**Pull request by zatarra**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR fixes a bad reference to the logStreamName.  Currently, it is pointing to the wrong attribute (`creationTime`) which makes it impossible to retrieve the `logStreamName` whenever we call the describe_log_streams() function.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jbabazadeh** [comment]
Hi @zatarra you need sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=33405) before we can accept your contribution.
please let me know if you have any question.

**Review by jbabazadeh — APPROVED** [review]
Hi @zatarra 
Great work! 
please sign the CLA

**Comment by zatarra** [comment]
> Hi @zatarra Great work! please sign the CLA

Hi @jbabazadeh  It seems that I messed up the PR because the author is wrong (branch new computer and I forgot to set the user.email correctly.  How can I update the author for the commits on this PR? Can I amend them?

**Comment by jbabazadeh** [comment]
Hi @zatarra 
you need to add release note to the PR.
If you are using our demisto-sdk you can run this command:
Please run `demisto-sdk update-release-notes -i Packs/AWS-CloudWatchLogs -u (major|minor|revision|documentation)` to generate release notes according to the new standard. You can refer to the documentation found here: https://xsoar.pan.dev/docs/integrations/changelog for more information.

**Comment by jbabazadeh** [comment]
Hi @zatarra , 
Thank you for your contribution. 
I have not received a response from you in a while, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again

**Pull request closed without merging**
