### PR TITLE
Making the documents look better

### PR DESCRIPTION
**Pull request by mtraceable**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Documentation changes so that it looks nice on the website and in the xsoar UI.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by mtraceable** [comment]
Output of the failing steps from my local environment:
```
% demisto-sdk doc-review --release-notes --use-git --use-packs-known-words --known-words ./Tests/known_words.txt --console-log-threshold INFO
[INFO] Log file location: /Users/mayuresh/Documents/tmpworkspace/xsoar/content/demisto_sdk_debug.log
[INFO] You are using demisto-sdk 1.20.8.

[INFO] ================= Starting Doc Review =================
[INFO] Running only on release notes
[INFO] Gathering all changed files from git

Checking file Packs/Traceable/ReleaseNotes/1_1_1.md

[INFO] No [known_words] section was found within: Packs/Traceable/.pack-ignore

[INFO] Using known words file found within pack: Packs/Traceable/.pack-ignore
[INFO]  - Release notes Packs/Traceable/ReleaseNotes/1_1_1.md match a known template.
[INFO]  - No misspelled words found in Packs/Traceable/ReleaseNotes/1_1_1.md

[INFO] ================= Files Without Misspells =================
[INFO] Packs/Traceable/ReleaseNotes/1_1_1.md
```

**Review by ilappe — CHANGES_REQUESTED** [review]
Thanks @mtraceable  for making it better!
please replace all the `<br>` with `<br/>`
thanks!

**Comment by mtraceable** [comment]
> Thanks @mtraceable for making it better! please replace all the `<br>` with `<br/>` thanks!

Done

**Comment by mtraceable** [comment]
```
% demisto-sdk doc-review --release-notes --use-git --use-packs-known-words --known-words ./Tests/known_words.txt --console-log-threshold INFO
[INFO] Log file location: /Users/mayuresh/Documents/tmpworkspace/xsoar/content/demisto_sdk_debug.log
[INFO] You are using demisto-sdk 1.20.8.

[INFO] ================= Starting Doc Review =================
[INFO] Running only on release notes
[INFO] Gathering all changed files from git

Checking file Packs/Traceable/ReleaseNotes/1_1_1.md

[INFO] No [known_words] section was found within: Packs/Traceable/.pack-ignore

[INFO] Using known words file found within pack: Packs/Traceable/.pack-ignore
[INFO]  - Release notes Packs/Traceable/ReleaseNotes/1_1_1.md match a known template.
[INFO]  - No misspelled words found in Packs/Traceable/ReleaseNotes/1_1_1.md

[INFO] ================= Files Without Misspells =================
[INFO] Packs/Traceable/ReleaseNotes/1_1_1.md
```

**Review by ilappe — APPROVED** [review]
Good job!

**Pull request merged**
