### PR TITLE
Added "Stringify" argument

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/20859

## Description
The `Stringify` argument will allow saving numerical values as strings too, which previously would always be saved as integers.

## Does it break backward compatibility?
   - No

## Technical writer review
Mention and link to the files that require a technical writer review.
- [x] [YAML file](https://github.com/demisto/content/blob/8f664878f2e9c03b173878c32ef09d796a578a58/Scripts/script-Set.yml) - line 63 only
- [x] [CHANGELOG](https://github.com/demisto/content/blob/8f664878f2e9c03b173878c32ef09d796a578a58/Scripts/script-Set_CHANGELOG.md)

@michalgold FYI required for Offboarding playbook (due to deep nesting in context and the need to save in another key, as string)

### CODE REVIEW

**Comment by kirbles19** [comment]
@idovandijk Done.

**Comment by idovandijk** [comment]
@glicht can this be force merged?

**Comment by glicht** [comment]
Please review the build. I see failures.

**Comment by idovandijk** [comment]
Taking care of phishing failure here:
https://github.com/demisto/content/pull/5242
https://github.com/demisto/content/pull/5240

@David-BMS please check your tests that failed here which are:
- `Test Convert file hash to corresponding hashes`
- `PANW - Hunting and threat detection by indicator type Test`

**Comment by David-BMS** [comment]
Handled here
https://github.com/demisto/content/pull/5247/files#diff-53aee29b4b4742656a54600ffaa808c9

**Comment by anara123** [comment]
@idovandijk pull from master

**Comment by idovandijk** [comment]
@David-BMS Currently I'm getting error for missing releasenotes for `playbook-PANW_-_Hunting_and_threat_detection_by_indicator_type.yml`
please update me when merged to master so i rebuild with it

**Comment by idovandijk** [comment]
@anara123 Added test playbook for both scenarios

**Comment by idovandijk** [comment]
@anara123 provided test, build seems OK other than the fact that it's red (only 1 test fails and unrelated to this change. Pretty good for a 5 hour build)

**Comment by anara123** [comment]
`The test 'Set - Test' does not exist in the conf.json file, please re-check your code`
@idovandijk please add the test in conf.json

**Pull request merged**
