### PR TITLE
Context path for reputation values - new context paths, cleanup, test script + test playbook

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/14953

## Description
This change should fix problems resulting from indicator types not being put into context.
The following indicator types should now be put into context as part of the **auto-extract** process, **regardless of available integrations / calculated reputations.**

- Added context path for reputation values for:
MD5 hash
SHA1 hash
SHA256 hash (from referenced PR, and now removed a deprecated script from it too)
IP
Escaped IP
Domain

- Removed deprecated enhancementScriptNames from all of the above

- Replaced old `reputationScriptName` with the new `reputationCommand` (e.g., "IPReputation" will not be used. "!ip" will).

- Added test script + test playbook for:
Email addresses
MD5 hash
SHA1 hash
SHA256 hash
Domains from URL
Domain from email address
URLs
Escaped URLs
IPs
Escaped IPs

## Related PRs
Related to: https://github.com/demisto/content/pull/2886 (completes the process)

## Does it break backward compatibility?
   - No

## Additional changes
Did not make changes to pre-3.0.1 values.

### CODE REVIEW

**Comment by idovandijk** [comment]
> can you add a test?

I am working on a test for ´Entity Enrichment - Generic´ which we could use here when it's ready

**Comment by anara123** [comment]
ok

**Comment by idovandijk** [comment]
Found bugs while working on this:
Reputation command" window never closes again if not closed explicitly [Visual Bug]
https://github.com/demisto/etc/issues/15320

RegPathReputationBasicLists returns wrong score
https://github.com/demisto/etc/issues/15326

**Comment by idovandijk** [comment]
This branch is completely dead, I tried fixing the conflicts, reverting, rebasing, everything..
The new branch is this: https://github.com/demisto/content/pull/2931

**Pull request closed without merging**
