### PR TITLE
DemistoUploadFileToIncident, DemistoUploadFile - add body argument

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/15704

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - scripts - no docs
- [ ] Code Review

### CODE REVIEW

**Comment by anara123** [comment]
@bakatzir what is the difference between those two scripts? and why they are not in the Demisto integration?

**Comment by bakatzir** [comment]
I believe they can both be deprecated and can added as a command to the integration.

**Comment by anara123** [comment]
@bakatzir what is the difference between those two scripts?

**Comment by bakatzir** [comment]
@anara123 don't see any difference.

**Comment by anara123** [comment]
there is some difference. The url is different , please check what is the exact difference, so we could update the description of the script

'entry/upload/' + args.incidentID

"incident/upload/{}".format(incident_id)

**Comment by bakatzir** [comment]
u5
u6



u7
u9

**Comment by anara123** [comment]
@dorsha what is the difference between those two routes?
`entry/upload/:id` and `incident/upload/:id`

@Itay4 I see that you created the `DemistoUploadFileToIncident` what was the reason? why not to use DemistoUploadFile

**Comment by dorsha** [comment]
Will answer in a private message.

**Comment by Itay4** [comment]
@anara123 don't really remember

**Comment by yuvalbenshalom** [comment]
@anara123 how do you wish we will go forward with this?

**Comment by bakatzir** [comment]
Added meaningful description consulting with @kirbles, and test playbooks.

**Comment by yardensade** [comment]
can we close this branch?

**Pull request merged**
