### PR TITLE
Added command to get direct reports for Microsoft Graph User

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/24090

## Description
Added the command `msgraph-direct-reports` to Microsoft Graph User. It's a bit chaotic, I had to use code that was added to a very old version of the integration apparently (did it go through a rewrite?) and incorporate it into the new integration code. The YML needs fixing as well as the code (noticed you added a new class...)

## Does it break backward compatibility?
No

Docs:
- [YML](https://github.com/demisto/content/blob/64ff7e8dcecab5f97b6afbf50989735c21c9ad38/Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml)
Descriptions in lines 398-441

- [Changelog](https://github.com/demisto/content/blob/64ff7e8dcecab5f97b6afbf50989735c21c9ad38/Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/CHANGELOG.md)

### CODE REVIEW

**Comment by idovandijk** [comment]
@michalgold needs review

**Comment by idovandijk** [comment]
@Bargenish can you please tell me if I should update the docker image as stated in the build error message? Right now the one in the yml is `dockerimage: demisto/crypto:1.0.0.303`

**Comment by Bargenish** [comment]
@idovandijk you should. change the docker image field inside the yml file to:
` dockerimage: demisto/crypto:1.0.0.7634`

**Comment by kirbles19** [comment]
@idovandijk Done. Updated the changelog, YML looked fine.

**Pull request merged**
