### PR TITLE
Added Dragos WorldView integration

### PR DESCRIPTION
**Pull request by jpbruckler**
## Status
Ready

## Related Issues
fixes: none

## Description
Adds in integration for the Dragos WorldView API. The integration exposes the following commands:

  - file
  - ip
  - domain

This integration will retrieve information about an indicator (file/ip/domain) from Dragos' WorldView API and return that information to Demisto. A DBot score is calculated based on the confidence for the indicator as returned by the Dragos API.

## Required version of Demisto
4.1.0

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

### CODE REVIEW

**Comment by jpbruckler** [comment]
THe "Hard-Coded Secrets" security issue is flagging on the Base64 image in the yml - should that be removed?

**Comment by Itay4** [comment]
fixes https://github.com/demisto/etc/issues/17519

**Comment by yaakovi** [comment]
Hi @jpbruckler ,

can we schedule a session where you will demo the integration?
i'm currently reviewing the code but we don't have access to the product so it cannot be tested.

**Comment by jpbruckler** [comment]
@yaakovi that's absolutely doable. I'm offsite the remainder of this week, but available starting 7/1.

**Comment by yaakovi** [comment]
@jpbruckler 
please schedule a session for us when you are free.
contact me at: syaakovi@paloaltonetworks.com

**Comment by jpbruckler** [comment]
Closing pull request. Dragos has requested changes to the frequency of polling.

**Pull request closed without merging**
