### PR TITLE
Added Compatibility with new Allowed Indicator Module in CTIX 3.6

### PR DESCRIPTION
**Pull request by coreybodendein-cyware**
I also ran all of the pre-commit hooks and resolved all of those issues.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
The main goal of this PR is to make the `ctix-allowed-iocs` and `ctix-get-allowed-iocs` compatible with CTIX 3.6 as the endpoint used by those two commands changed in that version. For both commands, we'll make a call to the new endpoint first, and if that returns a 404 (which it will if the user has CTIX < 3.6), make a call to the previous endpoint.

The rest of the changes are all done by running the pre-commit hooks.

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by coreybodendein-cyware** [comment]
@jbabazadeh, is anything needed from me to move this forward?

Thanks.

**Review by jbabazadeh — APPROVED** [review]
Hi @coreybodendein-cyware , the code looks good!

We're ready for a demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available for one over DFIR.

**Comment by coreybodendein-cyware** [comment]
@jbabazadeh, can you email me at corey.bodendein@cyware.com so we can find times to align on demoing this. I'm currently in UTC−06:00. Thanks!

**Comment by edik24** [comment]
Hey @coreybodendein-cyware,
When you fill in the contribution form, since the pack is partner supported and you're from the partner - you need to select the "Technical Partner" and not "individual developer".
You'll also need to enter your partner-id.

for this PR it's not relevant anymore, but make sure to follow those guidelines in future PR's

**Comment by coreybodendein-cyware** [comment]
Thanks @edik24, I'll keep that in mind for next time.

I rebased the branch as requested by @jbabazadeh via email.

**Comment by jbabazadeh** [comment]
Hi @coreybodendein-cyware ,
I merged the internal PR, and your update is now in the master branch of content repo.
Your update should be available in the marketplace within the next 72 hours.
Again, thank you very much for your contribution!

**Pull request merged**
