### PR TITLE
fixed none type error

### PR DESCRIPTION
**Pull request by IkaDemisto**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related to: https://github.com/demisto/etc/issues/20719#issuecomment-58550929

### CODE REVIEW

**Comment by IkaDemisto** [comment]
Should fix this error:
Screen Shot 2020-02-13 at 15 18 14

**Comment by anara123** [comment]
@IkaDemisto but what is this field `integrationScript` inside of `configuration`? I don't see that any integration have it

**Comment by IkaDemisto** [comment]
@anara123 it is returned from the rest api when creating integration instance using `demisto-py`:
`
        res = demisto_client.generic_request_func(self=client, method='PUT',
                                                  path='/settings/integration',
                                                  body=module_instance)
`

**Comment by yaakovi** [comment]
@anara123 this is the `script` dict in integrations, the key is taken from the server representation of integrations: https://github.com/demisto/server/blob/master/domain/module.go#L336

**Pull request merged**
