### PR TITLE
Added Support for predicting in different languages (2)

### PR DESCRIPTION
**Pull request by lperryp**
## Description
Added Support for predicting in different languages. Continuation of former PR https://github.com/demisto/content/pull/6962

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by lperryp** [comment]
marking as "docs-approved" as it was checked here: https://github.com/demisto/content/pull/6962

**Comment by Itay4** [comment]
@lperryp whats the status here?

**Comment by lperryp** [comment]
> @lperryp whats the status here?

@Itay4 had some problems with the new release notes format, will complete this, thanks

**Comment by Itay4** [comment]
@erezh31 @lperryp whats the status here?

**Comment by lperryp** [comment]
> @erezh31 @lperryp whats the status here?

Not sure why it keeps failing on Marketplace version (although it's a super small change), will try to complete this ASAP

**Comment by Itay4** [comment]
@lperryp what is the status here?

**Comment by Itay4** [comment]
build fails on non relevant docker image validation
merging

**Pull request merged**
