### PR TITLE
Add Authorization Screenshot

### PR DESCRIPTION
**Pull request by ShirleyDenkberg**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/29857

## Description
Add screenshot of CDL authorization process.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by neela-j — APPROVED** [review]

**Review by neela-j — APPROVED** [review]
Approved.

**Review by neela-j — APPROVED** [review]

**Review by neela-j — APPROVED** [review]

**Review by IBrecher — APPROVED** [review]

**Review by IBrecher — APPROVED** [review]
1

**Comment by ShirleyDenkberg** [comment]
@neela-j @IBrecher This PR still needs a an approval by a reviewer with write access.  Please make this happen.

**Review by neela-j — APPROVED** [review]
Approved.

**Review by IBrecher — APPROVED** [review]

**Comment by altmannyarden** [comment]
If the image will be used in pan.dev, please 
1. close this PR
2. create other PR and add the image the following path:
`content-docs/tree/master/docs/doc_imgs/integrations`

**Comment by ShirleyDenkberg** [comment]
Closing this PR and opening a new one.

**Pull request closed without merging**
