### PR TITLE
Update SplunkPy README Configuration/Commands Sections

### PR DESCRIPTION
**Pull request by kgal-pan**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9307

## Description
As part of working on https://github.com/demisto/demisto-sdk/pull/3820 I tested out the README update and noticed that the SplunkPy integration README was missing 2 tagging parameters added for mirroring in https://github.com/demisto/content/issues/28198. 

The two added parameters overwrite a comment under the configuration options table that referred to two parameters that were removed in https://github.com/demisto/content/pull/14365 and no longer exist in the integrations.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kgal-pan** [comment]
@ShahafBenYakir @ilappe - I also noticed that some command sections are descriptions while others have the actual command name (as it's generated by the SDK).

For example, we have a command section titled [Get Mapping Fields](https://xsoar.pan.dev/docs/reference/integrations/splunk-py#get-mapping-fields) and another command section is in the form of the command name such as [`splunk-kv-store-collection-create`](https://xsoar.pan.dev/docs/reference/integrations/splunk-py#splunk-kv-store-collection-create). Should I standardize these command section to conform to command name or leave as is?

**Comment by ShahafBenYakir** [comment]
@kgal-pan regarding the command naming convention, when you generate the README fo this command what is the format it is created? `A B` or `a-b`?

**Comment by kgal-pan** [comment]
> @kgal-pan regarding the command naming convention, when you generate the README for this command what is the format it is created? `A B` or `a-b`?

`a-b`

**Comment by kgal-pan** [comment]
Rebase to resolve https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/3996720#L812.

**Comment by ShahafBenYakir** [comment]
@kgal-pan go by the convention created by the command.

**Review by ilappe — APPROVED** [review]
great catch!

**Comment by kgal-pan** [comment]
[Splunk UTs are failing](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/717767):

image

Looking into it.

**Comment by kgal-pan** [comment]
In `artifacts/xsoar/logs/Run_Tests.log`, found that SplunkPy Test Playbook is failing because it exceeded 100MB memory threshold:

```
[2023-12-27 10:09:43] - [Thread-1 (execute_tests)] - [ERROR] - Failed docker resource test. Docker container demistoserver_pyexec-578a8fd1-3a17-45c7-8cfb-0e29fddf7ceb-demistosplunksdk-py31.0.0.83421--13 exceeded the memory threshold, configured: 100 MiB and actual memory usage is 135.2 MiB.
Fix container memory usage or add `memory_threshold` key to failed test in conf.json with value th
at is greater than 135.2

[2023-12-27 10:09:43] - [Thread-1 (execute_tests)] - [ERROR] - Test failed: playbook: "SplunkPy parse-raw - Test" with integration(s): ["SplunkPy"]
```

**Pull request merged**
