### PR TITLE
[greynoise-266] Update Pack ReadMe on GreyNoise Pack

### PR DESCRIPTION
**Pull request by bradchiappetta**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

We've been requested to submit an update to our pack README file in the Pack Root directory.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by bradchiappetta** [comment]
@mchasepan : FYI

**Comment by marcellarichmond** [comment]
@mchasepan FYI

**Comment by sangsoojun88** [comment]
Everything looks good on my end

**Comment by moishce** [comment]
Hi @bradchiappetta 
Thank you for this
Just need to resolve the conflict that exists.
Or give me writing permissions and I'll fix it.

**Comment by bradchiappetta** [comment]
@moishce : should be all set now, thanks.

**Review by moishce — APPROVED** [review]

**Pull request merged**
