### PR TITLE
Generic objects upload

### PR DESCRIPTION
**Pull request by iyeshaya**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/39291

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0
- [ ] 
## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Review by guyfreund — COMMENTED** [review]
Looking good 💅
Please attach the following successful upload runs:
1. A pack with all of the mentioned generic objects
2. A pack with multiple generic objects of the same type
3. A pack, with two new RNs (simulating that it was released twice), and in the RN have changes in all of the generic objects in the pack (for verifying the aggregation).

**Comment by iyeshaya** [comment]
> Looking good 💅
> Please attach the following successful upload runs:
> 
> 1. A pack with all of the mentioned generic objects
> 2. A pack with multiple generic objects of the same type
> 3. A pack, with two new RNs (simulating that it was released twice), and in the RN have changes in all of the generic objects in the pack (for verifying the aggregation).

1. https://app.circleci.com/pipelines/github/demisto/content/108160/workflows/964e3810-ebf9-4195-a594-d43b835c6919
2. https://app.circleci.com/pipelines/github/demisto/content/108169/workflows/ec14a11d-38a3-4d83-a1ea-963bb52aed1b
3. https://app.circleci.com/pipelines/github/demisto/content/108246/workflows/3e7a800f-7ca5-4954-89bd-1cf435800d54

**Comment by guyfreund** [comment]
@iyeshaya regarding 1 & 2:

GenericFields & GenericTypes are missing

**Comment by iyeshaya** [comment]
> @iyeshaya regarding 1 & 2:
> 
> GenericFields & GenericTypes are missing

Fixed

1. https://app.circleci.com/pipelines/github/demisto/content/108533/workflows/1baeaaaa-8475-4f9c-a945-7880de96a91f
2. https://app.circleci.com/pipelines/github/demisto/content/108584/workflows/89fe69a7-4852-4662-8d33-77da9913e1f0
3. https://app.circleci.com/pipelines/github/demisto/content/108613/workflows/6c400b08-e7f8-4897-9da8-28fb42e846d4

**Review by guyfreund — APPROVED** [review]

**Pull request merged**
