### PR TITLE
Shodan - Added handling 404 response

### PR DESCRIPTION
**Pull request by saharsabban**
fixed 404 response and improved human readable for ip command

fixes issue #11791

### CODE REVIEW

**Comment by gshriki** [comment]
@NeelRust - Does Shodan give any indication on maliciousness?

**Comment by meirwah** [comment]
@gshriki can you add test?

**Comment by saharsabban** [comment]
Test playbook added for Shodan integration.

**Comment by Itay4** [comment]
@saharsabban Please resolve conflicts and merge.

**Comment by Itay4** [comment]
@saharsabban What is the status of this?

**Pull request merged**
