### PR TITLE
[PAN-OS] add the pan-os-list-templates command

### PR DESCRIPTION
**Pull request by GuyAfik**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-1535

## Description
Added the **pan-os-list-templates** command

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by JudahSchwartz** [comment]
@GuyAfik is this heading to master or your branch? Can we update the pr so its clear whats new?

**Review by JudahSchwartz — APPROVED** [review]

**Comment by JudahSchwartz** [comment]
Nice work! Lets have a doc review on this 1

**Comment by SarahFleising** [comment]
Doc review completed. Let me know if you have any questions.

**Comment by ShirleyDenkberg** [comment]
@JudahSchwartz Doc review completed.

**Pull request merged**
