### PR TITLE
Added 2 new functions: file and file_command to handle global file co…

### PR DESCRIPTION
**Pull request by aburt-demisto**
…mmand in the Demisto platform.

## Status
Ready/In Progress/In Hold(Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - Yes
       - Further details:
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by Itay4** [comment]
@aburt-demisto this change breaks backward compatibility.
lets add a new command to implement the functionality you added

**Comment by aburt-demisto** [comment]
@Itay4 Sorry it breaks backward compatibility. Are there some versions of VMRay that don't have the hash lookup function? Happy to add a dedicated lookup function. Would you like me to write, or are you happy to adapt the existing code?

**Comment by Itay4** [comment]
Would appreciate if you could add a hash lookup command to this integration

**Comment by aburt-demisto** [comment]
I plan to write them next week. Am PTO this week. Can it wait until then?

**Comment by anara123** [comment]
@aburt-demisto sure

**Pull request closed without merging**
