### PR TITLE
Update hooks to python3

### PR DESCRIPTION
**Pull request by ronykoz**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16482

## Description
Updating python scripts to python3 format

### CODE REVIEW

**Comment by glicht** [comment]
Unit tests are running with python2. Need to run them with `python3 -m pytest ...`

**Comment by glicht** [comment]
The convert process added blindly to `print` statements brackets even if not needed. So there is a bunch of stuff of the form: `print((...))`. Try to see if there is an easy way to clean this up.

**Comment by glicht** [comment]
Status?

**Comment by ronykoz** [comment]
@bakatzir will do the same in a new PR, with the current code.

**Pull request closed without merging**
