### PR TITLE
[Pack: Recorded Future Intelligence][v1.3.0] Restructure and extend the integration. Add new classifier, mapper, incident types, playbooks. 

### PR DESCRIPTION
**Pull request by recordedfuture-dev**
## Contributing to Cortex XSOAR Content

This pull request is the continuation of the original pull request: https://github.com/demisto/content/pull/20933

## Status
- [x] Ready

## Description
- Renamed Pack name from *RecordedFuture v2* to *Recorded Future Intelligence*
- Added *recordedfuture-malware-search* command
- Added support for Malware to *recordedfuture-intelligence* command
- Added *fetch_analyst_notes* for *recordedfuture-intelligence* command
- Added the *fetch_statuses* integration parameter to allow users to specify which Recorded Future alert statuses to include in the fetch (default is 'no-action')
- Added the *update_status* integration parameter to allow users to specify whether a Recorded Future alert should have it's status updated once fetched by the integration (default is True)
- Fixed an issue where the integration would repeatedly fetch the same alerts due to incorrectly setting the last fetch time in last run dict
- Restructured integration, moved the logic from integration to the API side.
- Added 5 new playbooks:
	-   Recorded Future Entity Enrichment
	-   Recorded Future Hatching Sandbox
	-   Recorded Future Leaked Credential Alert Handling
	-   Recorded Future Typosquat Alert Handling
	-   Recorded Future Vulnerability Alert Handling
- Renamed layout from *Recorded Future Layout* to *Recorded Future Incident*
- Renamed incident type *Recorded Future Alert* to *Recorded Future Unclassified*
- Added 3 new incident types
	- Leaked Credential Monitoring
	- New Critical or Pre NVD Vulnerabilities
	- Potential Typosquat
- Added new Classifier named *Recorded Future - Classifier*
- Added new Incoming Mapper named *Recorded Future - Incoming Mapper*
- Updated docker image version 

## Minimum version of Cortex XSOAR
- [x] 6.5.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by YuvHayun** [comment]
Changes looks good!
I triggered instance tests, once this is done we can schedule a demo for next week.
@recordedfuture-dev

**Comment by YuvHayun** [comment]
@recordedfuture-dev Please fill the contribution form at the mean time.

**Comment by recordedfuture-dev** [comment]
> @recordedfuture-dev Please fill the contribution form at the mean time.

Done

**Comment by recordedfuture-dev** [comment]
> Changes looks good!
> I triggered instance tests, once this is done we can schedule a demo for next week.
> @recordedfuture-dev

Good to know!
Thanks!

**Comment by YuvHayun** [comment]
@recordedfuture-dev sorry for the delay, there seem to be some issues with the build.. Hope we'll be able to get it fixed by the end of this week.

**Comment by recordedfuture-dev** [comment]
> @recordedfuture-dev sorry for the delay, there seem to be some issues with the build.. Hope we'll be able to get it fixed by the end of this week.

Got it. Thanks for the update!

**Comment by YuvHayun** [comment]
Hey @recordedfuture-dev.
After consluting @esharf, we decided to try the following workaround: please try to change your repo name to content.
We hope this should fix it for now and in the meantime, we're also working on a better solution for the problem.

**Comment by recordedfuture-dev** [comment]
> Hey @recordedfuture-dev.
> After consluting @esharf, we decided to try the following workaround: please try to change your repo name to content.
> We hope this should fix it for now and in the meantime, we're also working on a better solution for the problem.

Hi there @YuvHayun 

I've renamed the repo to "content"

**Comment by YuvHayun** [comment]
> > Hey @recordedfuture-dev.
> > After consluting @esharf, we decided to try the following workaround: please try to change your repo name to content.
> > We hope this should fix it for now and in the meantime, we're also working on a better solution for the problem.
> 
> Hi there @YuvHayun
> 
> I've renamed the repo to "content"

Great, please pull from master and push.

**Comment by recordedfuture-dev** [comment]
> Great, please pull from master and push.

Done

**Comment by YuvHayun** [comment]
Hey @recordedfuture-dev, thx for your patience, and sorry for all the delay.
unfortunately, we couldn't bypass the instance tests issues so we'll move straight to the demo.
Since we couldn't bypass the instance tests issues, I'll need you to show me that all the playbooks you added in this pr are working fine.
Also, please notice that you have one error that causes the Run Validations step to fail, please make sure to fix it before the demo.
@edik24 will contact you via email to schedule a demo.

**Comment by YuvHayun** [comment]
@recordedfuture-dev Following our demo, please let me know how big will be the effort to retrieve the TPB.

**Comment by recordedfuture-dev** [comment]
I see that the validation failed due to data in test playbook. Not sure how should I solve this?

**Comment by YuvHayun** [comment]
> I see that the validation failed due to data in test playbook. Not sure how should I solve this?

I ran format command and it fixed the errors.
pushing fixed version.

**Review by YuvHayun — APPROVED** [review]

**Comment by YuvHayun** [comment]
@recordedfuture-dev need you to fix the license step and we're ready to merge.

**Comment by recordedfuture-dev** [comment]
> @recordedfuture-dev need you to fix the license step and we're ready to merge.

The problem with licenses - is with the authors of some commits from demisto MASTER branch, that I pulled into my branch.

I've rebased my branch onto latest master, so those commits with bad license authors are no longer present as commits in my branch/mr.

So now the issue should be solved.

Feel free to merge, when you are ready.

**Comment by YuvHayun** [comment]
@recordedfuture-dev merging this pr, thank you very much for your contribution!

**Comment by recordedfuture-dev** [comment]
The changes were merged into https://github.com/demisto/content/tree/contrib/recordedfuture-dev_recorded_future_xsoar_improvement-1 branch

when they will be merged into master?

**Comment by recordedfuture-dev** [comment]
> Working to make it happen today.
> You should be able to see it on the MP tomorrow.
> I'll let you know if any delays commes up.

Thanks!

**Pull request merged**
