### PR TITLE
Add file upload command to Intezer

### PR DESCRIPTION
**Pull request by Nitzperetz**
By @shaytidhar

### CODE REVIEW

**Comment by anara123** [comment]
@Nitzperetz don't merge yet.
@JonathanMeler let us know if you need anything from this integration

**Comment by michalgold** [comment]
@Nitzperetz please change the category from “Data Enrichment & Threat Intelligence” to “Forensics & Malware Analysis ”.

**Comment by Nitzperetz** [comment]
@michalgold updated

**Comment by Nitzperetz** [comment]
@michalgold , @anara123 , What is the status of this PR?

**Comment by anara123** [comment]
@JonathanMeler ?
@Nitzperetz the build must be green. 
@michalgold I think we fixed the docs right?

**Pull request merged**
