### PR TITLE
Fixed a bug where the playbook would confuse MSG / EML files with doc/x.

### PR DESCRIPTION
**Pull request by idovandijk**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/16137

## Description
- Fixed a bug where the playbook would confuse MSG / EML files with doc/x.
- Added downloading an EML file to the test. If the EML file is parsed then the test will fail. If the EML file was parsed and did not fail the test, then we also look for a URL from the file, and if we find it - we will intentionally fail the test.

## Required version of Demisto
4.1.0 and up.

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [ ] Code Review

### CODE REVIEW

**Comment by glicht** [comment]
@idovandijk  build is failing

**Comment by idovandijk** [comment]
> @idovandijk build is failing

OK, Re-ran it to see why it failed. Might be unrelated to the fix.

**Comment by idovandijk** [comment]
Can't access the server. It dies instantly. What's going on?

**Comment by idovandijk** [comment]
Contacted @yaakovi to take a look at why the instance keeps dying so I can see why the test failed.

**Comment by idovandijk** [comment]
Was blocked by this: https://github.com/demisto/etc/issues/16336.
Found the problem and resolved here https://github.com/demisto/content/pull/3292.
Now getting this error but should be resolved within ~30min (devops)
image

Should then pass, at least on latest GA.

**Comment by glicht** [comment]
@idovandijk can you add to the test playbook (or a new test playbook) a verification that the bug is fixed. Meaning add an msg/eml file and make sure it is not being extracted as a word doc.

**Comment by idovandijk** [comment]
> @idovandijk can you add to the test playbook (or a new test playbook) a verification that the bug is fixed. Meaning add an msg/eml file and make sure it is not being extracted as a word doc.

Sure

**Comment by idovandijk** [comment]
Green build :)

**Pull request merged**
