### PR TITLE
[ASM] - Expander - 3856

### PR DESCRIPTION
**Pull request by johnnywilkes**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3856

## Description
Adding improvements of GridFieldSetup automation (https://github.com/demisto/content/pull/26634) to update a new field (ASM - Playbook Stage) to keep track of stages of playbook and when they are complete.  This data can be displayed in layout or report.

## Screenshots
image

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@thefrieddan1 , i have seen this error come up for "Alert" as well: https://app.circleci.com/pipelines/github/demisto/content/262079/workflows/f30418de-0add-4c9b-957f-778368644f8b/jobs/702032?invite=true#step-119-189

This seems to be something new, can we bypass?

**Comment by johnnywilkes** [comment]
@BigEasyJ @capanw , if either of you can look into this.  Known build errror: https://app.circleci.com/pipelines/github/demisto/content/262079/workflows/f30418de-0add-4c9b-957f-778368644f8b/jobs/702032?invite=true#step-119-189

**Comment by thefrieddan1** [comment]
@johnnywilkes Please see my ignore addition to the playbook in name

**Comment by johnnywilkes** [comment]
@thefrieddan1 , please allow approval from my team
@capanw / @BigEasyJ , Dan has fixed the naming error.  Can you please look over and approve so he can merge?

**Review by BigEasyJ — APPROVED** [review]
Review playbooks in alerts.

- Fields are lowercased.
- Set `asmplaybookstage` as last step of stage

Looks good to me.

**Review by capanw — APPROVED** [review]

**Comment by johnnywilkes** [comment]
@thefrieddan1 this is good to merge now

**Review by thefrieddan1 — APPROVED** [review]

**Pull request merged**
