### PR TITLE
Moving premium packs validation to after the upload

### PR DESCRIPTION
**Pull request by hod-alpert**
## Related Issues
https://github.com/demisto/content/pull/9992

## Description
Bucket validations should be executed right after uploading to the bucket

### CODE REVIEW

**Comment by DinaMeylakh** [comment]
Couldn't find a working pipeline with this flow on your branch. Looks good otherwise.

**Review by DinaMeylakh — CHANGES_REQUESTED** [review]
Couldn't find a working pipeline with this flow on your branch. Looks good otherwise.

**Comment by guyfreund** [comment]
@hod-alpert this should be part of the nightly, not the upload flow

**Comment by Itay4** [comment]
lets trigger upload to verify this works as expected

**Comment by hod-alpert** [comment]
Build example - https://app.circleci.com/pipelines/github/demisto/content/53766/workflows/2811b7b4-4da4-4dde-a21d-286d7403a4c9

**Review by DinaMeylakh — APPROVED** [review]

**Review by guyfreund — APPROVED** [review]

**Pull request merged**
