### PR TITLE
Microsoft ATP - new commands

### PR DESCRIPTION
**Pull request by DeanArbel**
## Status
In Progress

## Related Issues
implements: https://github.com/demisto/etc/issues/14623
implements: https://github.com/demisto/etc/issues/15642
implements: https://github.com/demisto/etc/issues/15749

## Description
Added 3 new commands: 
1. microsoft-atp-advanced-hunting - Run advanced queries like you would using ATP portal.
2. microsoft-atp-create-alert - Create a new alert entity using event data, as obtained from the Advanced Hunting.
3. microsoft-atp-get-alert-related-user - Retrieves the user associated to a specific alert."

## Screenshots
image

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Additional changes
Improved error messages in case of error.

### CODE REVIEW

**Comment by DeanArbel** [comment]
## microsoft-atp-advanced-hunting
image

## microsoft-atp-get-alert-related-user:
image

## microsoft-atp-create-alert
image

**Comment by DeanArbel** [comment]
Update: I was able to successfully test all the commands, except for: microsoft-atp-get-alert-related-user, as the microsoft representative I talked to didn't know how to associate an alert to a user.

**Comment by Itay4** [comment]
how are you planning to run the test?

**Comment by DeanArbel** [comment]
> how are you planning to run the test?

I'm adding an instance to test-conf

**Comment by Itay4** [comment]
if someone will generate a new token it will break the test..

**Comment by DeanArbel** [comment]
> if someone will generate a new token it will break the test..

Perhaps, but this is a dev instance, so if that'll happen it will be someone from the dev team, and in that case we can just update the conf.json

**Comment by Itay4** [comment]
that assumption is wrong.. SEs and SAs can also use it
lets discuss this

**Comment by DeanArbel** [comment]
@anara123 @yuvalbenshalom This integration is ready for master. I have disconnected the test playbook from the integration since currently it's unable to run the tests (since dbot server isn't functioning).

Following merging this branch, @avidan-H will adjust it to the new dbot server.
Following the dbot server fix and after the implementation of the new authentication, I will create a new PR so the test playbook can be integrated back to the tests that are ran in the content build.

image

**Comment by anara123** [comment]
seems like the ATP test is failing
```
Configuring instance for Windows Defender Advanced Threat Protection
Test integration failed.
 Failure message: Error in authentication with the application. Please check the credentials. (85)
Failed to create instance
```

**Comment by DeanArbel** [comment]
> seems like the ATP test is failing
> 
> ```
> Configuring instance for Windows Defender Advanced Threat Protection
> Test integration failed.
>  Failure message: Error in authentication with the application. Please check the credentials. (85)
> Failed to create instance
> ```

@anara123 yes, it's failing because the dbot server is unavailable... however I moved the test to skipped so it'll not fail the content build until we can run the test properly on circeci

**Comment by DeanArbel** [comment]
Development continued in https://github.com/demisto/content/pull/3659

**Comment by yardensade** [comment]
Can we delete this?

**Comment by DeanArbel** [comment]
Not yet. @avidan-H is still working on it

**Pull request closed without merging**
