### PR TITLE
Cohesity Update pack README and pack_metadata.json

### PR DESCRIPTION
**Pull request by PankajKCohesity**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Only app store meta-data changes: Pack README.md and pack_metadata.json (and related files).

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PankajKCohesity** [comment]
@ilaner Just checking if there is anything else needed for your review? We are waiting for response on this PR.  Thank you.

**Comment by PankajKCohesity** [comment]
@kgal-pan @ilaner checking again to see if there is any update? The files changed section shows only the readme related changes and is a minor PR.  Please let me know if you need me to do something.  Thank you.

**Comment by ilaner** [comment]
> @kgal-pan @ilaner checking again to see if there is any update? The files changed section shows only the readme related changes and is a minor PR. Please let me know if you need me to do something. Thank you.

@tschanfeld will make a documentation review for this.

**Review by ilaner — APPROVED** [review]
No need to wait for a doc review, approved.

**Pull request merged**
