### PR TITLE
nightly-fix

### PR DESCRIPTION
**Pull request by guyfreund**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: nightly

## Description
running nightly with all packs and not empty string

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

### CODE REVIEW

**Review by Itay4 — CHANGES_REQUESTED** [review]
run nightly against this and remove line 85

**Review by hod-alpert — COMMENTED** [review]
`OVERRIDE_ALL_PACKS=true` and  `PACKS_LIST="all"` are declared in one of the cases below too.

Also can you document what the flags and the cases while you're at it?

**Comment by guyfreund** [comment]
> run nightly against this and remove line 85

Can't remove line 85, different use-case. I've improved commenting for these configurations.

image

**Comment by guyfreund** [comment]
nightly run: https://app.circleci.com/pipelines/github/demisto/content/42752/workflows/bf45a840-13c1-4f28-8497-3441bddd0d44

**Review by hod-alpert — CHANGES_REQUESTED** [review]
Add the  << pipeline.parameters.nightly >> to line 1258

**Review by hod-alpert — CHANGES_REQUESTED** [review]
Also remove the comments in lines 92-94

**Review by Itay4 — APPROVED** [review]

**Comment by Itay4** [comment]
@guyfreund @hod-alpert whats our status here? need to merge this asap

**Comment by guyfreund** [comment]
> @guyfreund @hod-alpert whats our status here? need to merge this asap

@Itay4 waiting for nightly run to finish, approx 30-40min

**Review by hod-alpert — APPROVED** [review]

**Comment by ShahafBenYakir** [comment]
>@Itay4 waiting for nightly run to finish, approx 30-40min

You canceled it since you pushed to your branch you need to re-run

**Pull request merged**
