### PR TITLE
Transformer convert counrty code name

### PR DESCRIPTION
**Pull request by OmriItzhak**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added transformer to convert between country code to country name.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Review by ostolero — APPROVED** [review]
Hi @OmriItzhak , the code looks good! let's have a mini demo tomorrow and see it on the server together. Then we can merge :)

**Comment by ostolero** [comment]
validations fails due to bug in the new rn validation. passes validate locally, need to force merge

**Comment by altmannyarden** [comment]
@ostolero Is there an issue about the bug? Is it already fixed? Going to be fixed in the next version?

**Comment by ostolero** [comment]
there is a fix already but it's an SDK issue so will require a release, contacted you in private to see how to proceed.

**Pull request merged**
