### PR TITLE
Penfield AI Pull Request 1

### PR DESCRIPTION
**Pull request by penfield-chan**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by guykeller** [comment]
Hi there!
Due to a sequence of holidays in recent weeks, your review was delayed. We apologize for the inconvenience and will try to do our best to complete your review as quickly and efficiently as possible, please bear with us.
Thanks for your understanding, and for your contribution.

**Comment by guykeller** [comment]
Hi there!
Due to a sequence of holidays in recent weeks, your review was delayed. We apologize for the inconvenience and will try to do our best to complete your review as quickly and efficiently as possible, please bear with us.
Thanks for your understanding, and for your contribution.

**Comment by daryakoval** [comment]
Hi, Please register your contribution by filling the [Contribution Registration form](https://forms.gle/XDfxU4E61ZwEESSMA).

**Review by daryakoval — CHANGES_REQUESTED** [review]

**Comment by daryakoval** [comment]
@penfield-chan  Hi, Please register your contribution by filling the [Contribution Registration form](https://forms.gle/XDfxU4E61ZwEESSMA).

**Comment by ShahafBenYakir** [comment]
FYI @edik24

**Comment by edik24** [comment]
New PR was opened
https://github.com/demisto/content/pull/15523

this one is closed

**Pull request closed without merging**
