### PR TITLE
GMail - Fixed an issue where getting an email without labels with fail

### PR DESCRIPTION
**Pull request by omercnet**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/19457

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------

## Required version of Demisto
x.x.x

## Does it break backward compatibility?
   - Yes
       - Further details:
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [ ] Dependency 1
- [ ] Dependency 2
- [ ] Dependency 3

## Additional changes
Describe additional changes done, for example adding a function to common server.

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [CHANGELOG](https://github.com/demisto/content/blob/fix/gmail_labelids/Integrations/Gmail/CHANGELOG.md)

### CODE REVIEW

**Comment by Itay4** [comment]
can we add a unit test which reproduces the bug this pr handles ?

**Comment by omercnet** [comment]
> can we add a unit test which reproduces the bug this pr handles ?

this happened when I tried moving the first email that you get when you open a gmail account, might be an edge case but should be easy to test as all mailboxes have such

**Comment by Itay4** [comment]
should be easy to test with some mocks

**Comment by roysagi** [comment]
> please add the unit test as itay suggested.

on it.

**Pull request closed without merging**
