### PR TITLE
README for ShowLocationOnMap

### PR DESCRIPTION
**Pull request by richardbluestone**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by ali-sawyer — APPROVED** [review]
Looks good! No changes.

**Comment by richardbluestone** [comment]
@ali-sawyer You also need to Review and approve the changes in the Files Changed tab here:
image

**Review by ali-sawyer — APPROVED** [review]
I thought I did approve the Files Changed.. Hopefully this goes through this time.

**Review by ali-sawyer — APPROVED** [review]
Trying once more. Perhaps a different reviewer is required? The GitHub conversation shows that I approved the changes, but then it still says review required.

**Comment by richardbluestone** [comment]
@altmannyarden Can you approve this PR as Ali doesn't have the required approvals for it to be merged? Thanks

**Review by altmannyarden — APPROVED** [review]

**Pull request merged**
