### PR TITLE
Removed 4.5 from config.yml

### PR DESCRIPTION
**Pull request by ShahafBenYakir**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28993

## Description
Removed 4_5 from config

### CODE REVIEW

**Review by yaakovi — COMMENTED** [review]
do we also want to update references in the `collect test` script?

**Review by yaakovi — APPROVED** [review]

**Review by hod-alpert — APPROVED** [review]
LGTM

Let's remove those instances from `content-test-conf/awsinstancetool/instancesconfig.json` - under `Content-Env`

**Comment by ShahafBenYakir** [comment]
@hod-alpert Are we sure we want to remove this? It is not being used anymore it is just a config. 4.1 is also there

**Comment by yaakovi** [comment]
@ShahafBenYakir @hod-alpert 
the aws_instance_tool.py is a mess.
I wouldn't remove it from the Content-Env for now (no actual meaning) until we reorganize the code there.

**Comment by ShahafBenYakir** [comment]
@yaakovi See this[ 6.0 build](https://app.circleci.com/pipelines/github/demisto/content/34358/workflows/73734218-fdea-4517-a6d0-ecf2daeba93e/jobs/149878)

**Pull request merged**
