### PR TITLE
adding README.md file to Teams

### PR DESCRIPTION
**Pull request by roysagi**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
A new Readme file for MS Teams.
Used the generate-docs with the following commands doc: 
[ms teams commands.txt](https://github.com/demisto/content/files/4398484/ms.teams.commands.txt)

Also put in the info found in the existing docs - https://support.demisto.com/hc/en-us/articles/360034095994-Microsoft-Teams#h_51a52394-6431-4fbc-8679-455be9a0b413

Though I wasn't able to attach the pictures found in the documentation nor the ZIP file at its end.

### CODE REVIEW

**Comment by ronykoz** [comment]
lets add the file of the commands to the PR too

**Comment by roysagi** [comment]
> lets add the file of the commands to the PR too

it is attached in the description above

**Comment by ronykoz** [comment]
@Itay4 do you have those pictures @roysagi is talking about?

**Comment by Itay4** [comment]
hmmm why cant we download them from zendesk and add them here?

**Comment by roysagi** [comment]
@Itay4 @ronykoz - I couldn't find a way to simply embed the files at least no without saving them on the repo - do we want to do that? what about the attached zip - that as well?

**Comment by Itay4** [comment]
@glicht where should the images and the zip should be stored?

**Comment by hod-alpert** [comment]
This file will be removed from the PR soon

**Comment by glicht** [comment]
@roysagi let's also mention the option to route via the Demisto server with a link to the following documentation: https://xsoar.pan.dev/docs/integrations/long-running#invoking-http-integrations-via-cortex-xsoar-servers-route-handling

**Comment by glicht** [comment]
@roysagi all links to images and downloads should be absolute and raw. For example: https://raw.githubusercontent.com/demisto/content/b222375925eb13feaaa28cd8b1c814b4d212f2e4/Integrations/MicrosoftTeams/doc_files/MSTeams-BotID.png otherwise they will break when deploying to the dev hub.

**Comment by roysagi** [comment]
closing as this go corrupted - will open a new PR

**Pull request closed without merging**
