### PR TITLE
changed to the new docker image

### PR DESCRIPTION
**Pull request by teizenman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

### CODE REVIEW

**Comment by teizenman** [comment]
First, I want to make sure that the docker fits it

**Comment by Itay4** [comment]
note you changed from py2 to py3 here

**Comment by teizenman** [comment]
@Itay4 I know, and I saw that pyminizip is updated to python3 so I preferred to upgrade if possible

**Comment by teizenman** [comment]
Needs a force merge due to the `dockerimage` change

**Pull request merged**
