### PR TITLE
Move SendEmailToManager and StaticAnalyze

### PR DESCRIPTION
**Pull request by liorblob**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

Moved SendEmailToManager to AD pack and changed the `AdSearch` command to `ad-search`.
Moved `StaticAnalyze` to D2 pack as it uses `D2PEdump`.

### CODE REVIEW

**Comment by liorblob** [comment]
@yuvalbenshalom nothing depends on this script

**Comment by yuvalbenshalom** [comment]
@anara123 @michalgold  WDYT?
should we open a separate pack for this or put it on AD pack?

**Comment by anara123** [comment]
Move to AD pack

**Comment by IkaDemisto** [comment]
`AdSearch` deprecated script of deprecated pack is used in this script.

**Comment by liorblob** [comment]
@IkaDemisto is that a problem?

**Comment by IkaDemisto** [comment]
Yes, that is why I moved this script temporary to `Legacy` pack.

**Comment by liorblob** [comment]
Until when?

**Comment by IkaDemisto** [comment]
Until it won't depend on script from `DeprecatedContent` pack. It's dependencies are ignored and new packs should not depend on this pack.

**Comment by liorblob** [comment]
it's an old pack though, should we change the dependency?

**Comment by IkaDemisto** [comment]
Yes, I think so.

**Comment by liorblob** [comment]
@IkaDemisto done

**Pull request merged**
