### PR TITLE
Modify sane doc reports script docker image

### PR DESCRIPTION
**Pull request by agamm**
## Status
Ready

## Description
Updates to the snae-doc-reports script docker image.

### CODE REVIEW

**Comment by anara123** [comment]
you are missing releaseNotes @agamm

**Comment by agamm** [comment]
> you are missing releaseNotes @agamm

https://github.com/demisto/content/pull/3802/files#diff-f2ecf958dc343067f3e44a2b5be41e74R27 ?

**Comment by anara123** [comment]
@agamm we have a new way to add release notes.
You have to create a file under Releases/LatestRelease/SaneDocReport.md and insert your release notes there

**Comment by agamm** [comment]
Is it ok now? (I changed the docker image version like we talked)

**Pull request merged**
