### PR TITLE
carbon black integration netconn local ip remote ip fix

### PR DESCRIPTION
**Pull request by ennozdd**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[netconn_complete response](https://developer.carbonblack.com/reference/enterprise-response/6.3/rest-api/#netconn_complete)

## Description
There are two different formats for netconn_complete. The v1 API returns an array of pipe delimited strings:

"2013-09-16 07:11:59.000000|-1979811809|80|6|dl.javafx.com|true"

    field 0: event time
    field 1: remote IP address as a 32-bit signed long (host byte order)
    field 2: remote port
    field 3: protocol: 6 is TCP, 17 is UDP
    field 4: domain name associated with the IP address, from the client’s perspective at the time of the network connection
    field 5: boolean “true” if the connection was outbound; “false” if the connection was inbound

The v2 API and newer return an array of JSON objects:

[{"domain": "login.live.com",
  "proto": 6,
  "local_port": 49240,
  "timestamp": "2017-01-11T16:20:04.892Z",
  "local_ip": 167772448,
  "direction": "true",
  "remote_port": 80,
  "remote_ip": -2080555708},
  ...
]

Since the request is made to v3 there is no parser implemented for netconn_complete. The caveat to this however is that IPs are in integer format. With this commit IPs now look the way they are supposed to

## Screenshots
After the change
image
the screenshot is clipped as it contains sensitive information

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by MLainer1** [comment]
@ennozdd Hi, please make sure to update the version in the pack metadata, and add a release note

**Comment by ennozdd** [comment]
@MLainer1 

I made another pull request 
https://github.com/demisto/content/pull/18909

**Comment by MLainer1** [comment]
> 

So can I close this pr?

**Comment by MLainer1** [comment]
Closing this PR due to the comment above.

**Pull request closed without merging**
