### PR TITLE
handle proofpoint v3

### PR DESCRIPTION
**Pull request by avidan-H**
## Status
Done

## Related Issues
fixes: https://github.com/demisto/etc/issues/18545

## Description
Add support for proofpoint v3 urls to the `UnEscapeURLs` script.

## Required version of Demisto
any

## Does it break backward compatibility?
   - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
Mention the dependencies of the entity you changed as given from the precommit hooks in checkboxes, and tick after tested them.
- [x] UnEscapeURL-Test

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [CHANGELOG](https://github.com/demisto/content/edit/update-unescapeurls/Scripts/script-UnEscapeURLs_CHANGELOG.md?pr=%2Fdemisto%2Fcontent%2Fpull%2F4639)

### CODE REVIEW

**Comment by avidan-H** [comment]
@kirbles19 Please review the changelog linked above in the issue-description. The yml file is not relevant since no descriptions there have changed.

**Comment by kirbles19** [comment]
@avidan-H Done.

**Comment by rgleza** [comment]
Hi, I just tested this new feature and it looks like it's adding an extra `/`
*Not sure if this is the place to put this info @avidan-H @Itay4 

image

**Comment by Itay4** [comment]
@rgleza it is not, lets discuss in the issue

**Pull request merged**
