### PR TITLE
Fixed "error_message undefined" issue. 

### PR DESCRIPTION
**Pull request by BenJoParadise**
The raise should only occur in the "except" block.
This resolves the issue experienced by slack user (customer) @mohan1704

### CODE REVIEW

**Comment by anara123** [comment]
ok. But still add test playbook.
Do you see the entry email sent confirmation?

**Comment by BenJoParadise** [comment]
Pending merge of https://github.com/demisto/content-test-conf/pull/93

**Comment by BenJoParadise** [comment]
@anara123 I see it in my setup, i'm thinking i'll send him a debug integration to see why the entry is not returning.

**Comment by BenJoParadise** [comment]
@anara123 He sees the message now after he restarted the Demisto service.
I've added the test, please review.

**Pull request merged**
