### PR TITLE
EWS separate process

### PR DESCRIPTION
**Pull request by glicht**
## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/20654

## Description
Add option to run ews in separate process.

Based off: https://github.com/demisto/content/pull/5140

## Does it break backward compatibility?
  - No

## Must have
- [ ] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by glicht** [comment]
@jochman waiting for you to add the param to control. Default will be not to run in separate process.

**Comment by glicht** [comment]
@jochman you committed unnecessary files

**Comment by kirbles19** [comment]
@glicht Done. I changed the language to "Run as a separate process". If this is not technically accurate, you can revert to "Run on a separate process".

**Comment by glicht** [comment]
@kirbles19 see my commit. I changed to use  `protect` which is clearer to me: https://github.com/demisto/content/pull/5237/commits/8a8ac8d7a9ce90ee7e0d8fef159261e389700814

**Pull request merged**
