### PR TITLE
PhishMe reputation changes

### PR DESCRIPTION
**Pull request by Itay4**
Fixes https://github.com/demisto/server/issues/9790

### CODE REVIEW

**Comment by Itay4** [comment]
## Overview:
Human-vetted, Phishing-specific Threat Intelligence from PhishMe.
Used through Demisto to check reputation of queries. 

## To set up ICEBRG to work with Demisto:
How to obtain API token (on PhishMe):
	1. Go to ‘Settings > API TOKEN
	2. Click ‘Add a new api token’.
	3. Enter description.	
	4. Click ‘Add’
	5. Record this token to use in the next steps.

## To set up the integration on Demisto:
1.	Go to ‘Settings > Integrations > Servers & Services’
2.	Locate ‘Phishme’ by searching for it using the search box on the top of the page.
3.	Click ‘Add instance’ to create and configure a new integration. You should configure the following settings: Name: A textual name for the integration instance. Server URL for the API: The URL appliance. API username: PhishMe API token. Password: PhishMe API password. Test: Checks correctness of URLs and token.

## Top Use-cases:
1. Get reputation for queries, such as URL and IP.
2. Check if file or email is malicious.

## Commands:
### 1.	Command name: url
#### Inputs:
	a. url (mandatory) -  URL to check for reputation.

#### Context output:

  | Path | Description
-- | -- | --
1 | URL.Data | Bad URLs found
2 | URL.Malicious.Vendor | For malicious URLs, the vendor that made the decision
3 | URL.Malicious.Description | For malicious URLs, the reason for the vendor to make the decision
4 | DBotScore.Indicator | The indicator we tested
5 | DBotScore.Type | The type of the indicator
6 | DBotScore.Vendor | Vendor used to calculate the score
7 | DBotScore.Score | The actual score

#### Raw output:

	         {
                        "blockType": "URL",
                        "data": "http://heckwassleftran2.ru/cgi-bin/180515/post.cgi",
                        "data_1": {
                            "domain": "heckwassleftran2.ru",
                            "host": "heckwassleftran2.ru",
                            "path": "/cgi-bin/180515/post.cgi",
                            "protocol": "http",
                            "url": "http://heckwassleftran2.ru/cgi-bin/180515/post.cgi"
                        },
                        "impact": "Major",
                        "infrastructureTypeSubclass": {
                            "description": "Update or Standard C2"
                        },
                        "malwareFamily": {
                            "description": "Unnamed malware variety",
                            "familyName": "Unnamed"
                        },
                        "role": "C2",
                        "roleDescription": "Command and control location used by malware"
              }

### 2.		Command name: file
#### Inputs:
a. file (mandatory) -  Hash of the file to query. Supports MD5, SHA1 and SHA256. Notice that you can pass comma-separated multiple values to efficiently retrieve multiple responses.
#### Context output:

  | Path | Description
-- | -- | --
1 | File.MD5 | File MD5
2 | File.Malicious.Vendor | For malicious files, the vendor that made the decision
3 | File.Malicious.Description | For malicious URLs, the reason for the vendor to make the decision
4 | DBotScore.Indicator | The indicator we tested
5 | DBotScore.Type | The type of the indicator
6 | DBotScore.Vendor | Vendor used to calculate the score
7 | DBotScore.Score | The actual score

Raw output:

                    {
                        "dateEntered": 1433791056918,
                        "executableSubtype": {
                            "description": "Persistence module or file"
                        },
                        "fileName": "21807.bat",
                        "fileNameExtension": "bat",
                        "malwareFamily": {
                            "description": "Microsoft Office documents with macro scripting for malware 			      
                                                   delivery",
                            "familyName": "OfficeMacro"
                        },
                        "md5Hex": "77d736dc280968d0af8c3f46e673f821",
                        "severityLevel": "Major",
                        "type": "Drop",
                        "vendorDetections": []
                    }

### 3.	Command name: ip
#### Inputs:
a. file (mandatory) -  IP to check for reputation.			

#### Context output:

  | Path | Description
-- | -- | --
1 | IP.Address | Bad IP Address found
2 | IP.Malicious.Vendor | For malicious IPs, the vendor that made the decision
3 | IP.Malicious.Description | For malicious IPs, the reason for the vendor to make the decision
4 | DBotScore.Indicator | The indicator we tested
5 | DBotScore.Type | The type of the indicator
6 | DBotScore.Vendor | Vendor used to calculate the score
7 | DBotScore.Score | The actual score

#### Raw output:

                  {
                        "blockType": "IPv4 Address",
                        "data": "35.165.118.153",
                        "data_1": "35.165.118.153",
                        "impact": "Minor",
                        "ipDetail": {
                            "asn": 16509,
                            "asnOrganization": "Amazon.com, Inc.",
                            "continentCode": "NA",
                            "continentName": "North America",
                            "countryIsoCode": "US",
                            "countryName": "United States",
                            "ip": "35.165.118.153",
                            "isp": "Amazon Technologies",
                            "latitude": 45.8696,
                            "longitude": -119.688,
                            "lookupOn": 1501611947628,
                            "metroCode": 810,
                            "organization": "Amazon.com",
                            "postalCode": "97818",
                            "subdivisionIsoCode": "OR",
                            "subdivisionName": "Oregon",
                            "timeZone": "America/Los_Angeles"
                        },
                        "malwareFamily": {
                            "description": "Banking trojan",
                            "familyName": "Banload"
                        },
                        "role": "C2",
                        "roleDescription": "Command and control location used by malware"
                    }

### 4.	Command name: phishme-search
#### Inputs:
	a. str (mandatory) - String to search.
	b. limit - Limit of strings to search, default is 10.
		
#### Context output:

  | Path | Description
-- | -- | --
1 | PhishMe.NumOfThreats | Number of threats
2 | PhishMe.String | String to search

### 5.	Command name: email
#### Inputs:
	a. email (mandatory) - Sender address to check if malicious.
		
#### Context output:

  | Path | Description
-- | -- | --
1 | Email.From | Sender address to check
4 | DBotScore.Indicator | The indicator we tested
5 | DBotScore.Type | The type of the indicator
6 | DBotScore.Vendor | Vendor used to calculate the score
7 | DBotScore.Score | The actual score

#### Raw output:

	         {
                        "malwareFamily": {
                            "familyName": "Keylogger",
                            "description": "Malware capable of collecting victim keystrokes for 					         exfiltration"
                        },
                        "impact": "Major",
                        "blockType": "Email",
                        "roleDescription": "Command and control location used by malware",
                        "role": "C2",
                        "infrastructureTypeSubclass": {
                            "description": "Command and control host to which victim information 					is shared by the malware"
                        },
                        "data": "forme@kanhseai.com",
                        "data_1": "forme@kanhseai.com"
            }

### Troubleshooting
This integration was integrated and tested with version 1 of PhishMe API.

**Comment by dorsha** [comment]
@mayairv pay attention that you have here documentation..

**Comment by mayairv** [comment]
Added **Integration: PhishMe** article as a draft. 
@NeelRust should review and publish

**Comment by NeelRust** [comment]
@mayairv @michalgold  Need an actual command invocation example for the search command. Also specify what kind of values can be given in search. string to search. Lets follow that pattern for all query examples where the results can be free form.

image

**Pull request merged**
