### PR TITLE
Added type ticket (normal, standard, emergency) to the create and upd…

### PR DESCRIPTION
**Pull request by dem-evgeny**
Added type ticket (normal, standard, emergency) to the create and update commands.

fixes https://github.com/demisto/server/issues/9951
fixes https://github.com/demisto/server/issues/9956
fixes https://github.com/demisto/server/issues/9816
fixes https://github.com/demisto/server/issues/9763

### CODE REVIEW

**Comment by dorsha** [comment]
@dem-evgeny you should reference with fixes to the original issue. `fixes <url to the issue>`

**Comment by dorsha** [comment]
Yes it should be added to the MD result of other commands.

**Comment by dem-evgeny** [comment]
@dorsha What do you mean?

**Comment by dorsha** [comment]
@dem-evgeny what is the status of this PR?
I think you should merge from master.
As we decided, PRs that will be opened more than 14 days will be closed.

**Pull request merged**
