### PR TITLE
Azure compute update

### PR DESCRIPTION
**Pull request by ayman-m**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added three new commands and update the README file.

## Minimum version of Cortex XSOAR
- [ x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [x ] Documentation

### CODE REVIEW

**Comment by ayman-m** [comment]
@bziser the new PR

**Comment by bziser** [comment]
@ayman-m Looks great! Could you add unit-tests to your new commands?

**Comment by ayman-m** [comment]
> @ayman-m Looks great! Could you add unit-tests to your new commands?

Sure I will do that next week as I am OOO this week

**Comment by bziser** [comment]
@ayman-m Reminding you to add unit-tests :)

**Comment by ayman-m** [comment]
@bziser I really apologize for the delay , I had two unplanned engagements this week, will definitely allocate some time next week to close this PR

**Comment by ayman-m** [comment]
closing this PR, will open a new one when I have time to allocate to it creating those test functions

**Pull request closed without merging**
