### PR TITLE
MarketplaceV2: Added the `Aliases` field with the relevant inc fields to the main in…

### PR DESCRIPTION
**Pull request by Bargenish**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
relates:  https://github.com/demisto/etc/issues/45421
relates:  https://github.com/demisto/etc/issues/43979#issuecomment-1000807051

## Description
Added the Aliases field with the relevant inc fields to the main incident field
### IMPORTANT:
WAIT FOR THE NEXT DEMISTO_SDK RELEASE TO MERGE THIS ONE (should be tomorrow - 13.01.22)

### CODE REVIEW

**Comment by Bargenish** [comment]
How does it affect the `associatedTypes` field?
should we set `associatedToAll` to true?

**Comment by David-BMS** [comment]
The list of aliases [here ](demisto/etc#43979 (comment)) is very partial and was just as an example
We will have a very extensive list of aliases

**Comment by David-BMS** [comment]
@MI

> How does it affect the `associatedTypes` field? should we set `associatedToAll` to true?

@michalgold Is this what we intend to do for the x2 fields?
ToAll true and no types

**Comment by reutshal** [comment]
@David-BMS Who should provide the list of all aliases? 
@michalgold Any answer regarding @David-BMS question?

**Comment by David-BMS** [comment]
@reutshal 
1. My team Its in the works now

**Comment by michalgold** [comment]
> @mi
> 
> > How does it affect the `associatedTypes` field? should we set `associatedToAll` to true?
> 
> @michalgold Is this what we intend to do for the x2 fields? ToAll true and no types

Is there field association in XSIAM? @asafshen

**Review by yaakovi — COMMENTED** [review]
looks good

**Review by yaakovi — APPROVED** [review]
looks good

**Pull request merged**
