### PR TITLE
Lastline - add File.Type outputs for file, lastline-get-report commands

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
Ready

## Related Issues
reference: https://github.com/demisto/etc/issues/17949

## Description
@DeanArbel  please see raw-reponse in private to check if I missed anything.

## Does it break backward compatibility?
   - No

## Must have
- [x] Tests
- [x] Documentation - after CR
- [x] Code Review

### CODE REVIEW

**Comment by bakatzir** [comment]
@kirbles19  can you review the RN and added output:
https://github.com/demisto/content/blob/d2b35fc428777dd734e564b123036b3749fba6d5/Integrations/integration-Lastline.yml
https://github.com/demisto/content/blob/d2b35fc428777dd734e564b123036b3749fba6d5/Integrations/integration-Lastline_CHANGELOG.md

**Comment by kirbles19** [comment]
I didn't review the yml

**Comment by bakatzir** [comment]
@kirbles19 added an output according to context standard (File.Type).
do you wish to review the whole integration?

**Comment by kirbles19** [comment]
Yes.

**Comment by bakatzir** [comment]
@kirbles19 so i'll open a new issue regarding that.

**Pull request merged**
