### PR TITLE
Symantec DLP v2 update outputs

### PR DESCRIPTION
**Pull request by barchen1**
## Status
- [x] In Progress
- [ ] Ready

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/48055)

## Description
Added more outputs to `symantec-dlp-get-incident-details`

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by barchen1** [comment]
@meital-aizen sent the updated integration to the client, waiting for an update.

**Review by DeanArbel — APPROVED** [review]

**Comment by DeanArbel** [comment]
@jrosenpanw Please assign someone to review this PR.

**Comment by tschanfeld** [comment]
@DeanArbel I submitted changes for the yml file. Can you check over and then regenerate md files? Thanks.

**Comment by tschanfeld** [comment]
@barchen1 Submitted edits to readme and a few more minor edits for yml. Release notes md file looks fine.

**Pull request merged**
