### PR TITLE
Add closed by DBot widget

### PR DESCRIPTION
**Pull request by Nitzperetz**
Using output script for widget.
Merge in version 4.0.0

### CODE REVIEW

**Comment by Nitzperetz** [comment]
Showing the percentage?
How would you do it?

**Comment by Nitzperetz** [comment]
@gshriki , please add description.

**Comment by Nitzperetz** [comment]
@gshriki , please add description.

**Comment by gshriki** [comment]
Showing percentage of incidents handled and closed by DBot, without qn owner being assigned to, across all incidents in the provided period.

@kirbles19 - wdyt?

**Comment by kirbles19** [comment]
@Nitzperetz @gshriki I need to see it in context. maybe you can show me this morning.

**Comment by Nitzperetz** [comment]
@kirbles19 , we reviewed it together a while ago.
The widget is of type script, which is a new feature for this version.
The description provided by @gshriki is for the widget itself.
Ping me if you want more details.

**Pull request merged**
