### PR TITLE
Cortex xdr 5.0

### PR DESCRIPTION
**Pull request by anara123**
## Status
In progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/16792

## Description
Incident type & fields & classifier & playbook the whole package for Palo Alto networks Cortex XDR integration

### CODE REVIEW

**Comment by anara123** [comment]
@kirbles19 please review
playbook - https://github.com/demisto/content/blob/cortex-xdr-5.0/Playbooks/playbook-PaloAltoNetworks_Cortex_XDR_Blueprint.yml

This whole PR will be available only from 5.0

**Comment by anara123** [comment]
@kirbles19

**Comment by kirbles19** [comment]
@anara123 All done. Please review my edits for technical accuracy and clarity.

**Comment by anara123** [comment]
@kirbles19 
Please review and fix 
https://github.com/demisto/content/blob/cortex-xdr-5.0/Classifiers/classifier-PaloAltoNetworks_CortexXDR_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Alert_Count_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Alerts_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Assigned_User_Email_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Assigned_User_Pretty_Name_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Description_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Detection_Time_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_File_Artifacts_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_High_Severity_Alert_Count_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Incident_ID_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Low_Severity_Alert_Count_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Medium_Severity_Alert_Count_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Network_Artifacts_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Notes_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Resolve_Comment_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_Status_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_URL_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentFields/incidentfield-XDR_User_Count_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/IncidentTypes/incidenttype-Cortex_XDR_Incident_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/Layouts/layout-details-Cortex_XDR_Incident_CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/Playbooks/playbook-PaloAltoNetworks_Cortex_XDR_Incident_Sync.yml
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/EntryWidgetNumberHostsXDR/EntryWidgetNumberHostsXDR.yml
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/EntryWidgetNumberUsersXDR/CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/EntryWidgetNumberUsersXDR/EntryWidgetNumberUsersXDR.yml
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/EntryWidgetPieAlertsXDR/CHANGELOG.md
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/EntryWidgetPieAlertsXDR/EntryWidgetPieAlertsXDR.yml
https://github.com/demisto/content/blob/cortex-xdr-5.0/Scripts/XDRSyncScript/CHANGELOG.md

**Pull request merged**
