### PR TITLE
[RecordedFuture] threat actor playbook update V2.5.1

### PR DESCRIPTION
**Pull request by nestoor22**
## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by nestoor22** [comment]
Hi @MichaelYochpaz 
We found small issues in the playbook for threat actor search.
The goal of this PR is to fix it
Let me know if you have any questions

**Review by MichaelYochpaz — APPROVED** [review]
Hey, thank you for the contribution.
Looks good from my side, just waiting for @melamedbn's approval.

**Comment by melamedbn** [comment]
Hi @nestoor22,

Everything looks great! I would just change the RN you wrote for the error handling change, shorten it so that it explains exactly what we did and not why we did it.

Best regards,
Ben

**Comment by nestoor22** [comment]
> Hi @nestoor22,
> 
> Everything looks great! I would just change the RN you wrote for the error handling change, shorten it so that it explains exactly what we did and not why we did it.
> 
> Best regards, Ben

Updated

**Review by melamedbn — APPROVED** [review]

**Pull request merged**
