### PR TITLE
New transformer RegexExtractAll

### PR DESCRIPTION
**Pull request by tundisto**
New transformer RegexExtractAll

## Status
Ready

## Related Issues
N/A

## Description
Extraction of all matches from a specified regular expression pattern from a provided string.  Returns an array of results.  This differs from RegexGroups in several ways:

* It returns all matches of the specified pattern, not just specific groups.  This is useful for extracting things using a pattern where the content of the source string is indeterminate, such as extracting all email addresses.
* Some convenience arguments have been added to enhance usability: multi-line, ignore_case, period_matches_newline
* A new argument has been added, "error_if_no_match".  The script will not ordinarily throw an error if a match is not found but if not using as a transformer within a playbook, it may, in certain limited circumstances, be desirable to throw an error if the expression doesn't match.
* It uses the 'regex'  library, which supports more some more advanced regex functionality than the standard 're' library.  For more info, see https://pypi.org/project/regex/.

## Screenshots
Paste here any images that will help the reviewer

## Related PRs
N/A

## Required version of Demisto
4.x,5.x

## Does it break backward compatibility?
   - No

## Must have
- [X] Tests
- [ ] Documentation (with link to it)
- [ ] Code Review

## Dependencies
N/A

## Additional changes
N/A

## Technical writer review
Mention and link to the files that require a technical writer review.
- [ ] [YAML file](link)
- [ ] [CHANGELOG](link)

### CODE REVIEW

**Comment by anara123** [comment]
Hello @tundisto , thank you for the contribution.
For some reason I don't see our circle ci build running, nor the CLI agreement. 
Please merge from our master branch, and do a small commit (it could be just adding space or comment - sometimes this will trigger the build)

**Comment by anara123** [comment]
@tundisto please take a look at the build. The build fails.
You need to whitelist a url `https://somedomain ` for that go to https://github.com/demisto/content/blob/master/Tests/secrets_white_list.json and add `somedomain ` under `'urls'` list

**Comment by anara123** [comment]
@kirbles19 please review the PR
https://github.com/tundisto/content/blob/RegexExtractAll/Scripts/RegexExtractAll/RegexExtractAll.yml

**Comment by kirbles19** [comment]
@anara123 Done.

**Comment by anara123** [comment]
@tundisto there is no much left to do. Can you fix the build?

**Comment by tundisto** [comment]
@anara123 sorry for the long delay -- should be all good now

**Pull request merged**
