### PR TITLE
remove flake8 dependency

### PR DESCRIPTION
**Pull request by dorschw**
- remove `flake8` dependency
- remove `boto3-stubs`  (see [CIAC-10508](https://jira-dc.paloaltonetworks.com/browse/CIAC-10508) comment)
- remove `boto3` dependency
- remove the unused `native` pyproject category

fixes:  https://jira-dc.paloaltonetworks.com/browse/CIAC-10510

### CODE REVIEW

**Comment by dorschw** [comment]
test nightly https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1007206

**Comment by dorschw** [comment]
test nightly (after removing `native` group) https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1007290

**Comment by dorschw** [comment]
test nightly (after updating `boto3`)
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1007319

**Comment by dorschw** [comment]
test nightly (after removing `boto3`, updating `boto3-stubs`)
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1007377

**Review by kobymeir — APPROVED** [review]

**Comment by dorschw** [comment]
@yuvalbenshalom please force-merge, only failed installing on XSIAM, unrelated to the PR.

**Pull request merged**
